Repository Alfresco/alfresco-ng2-components, pull requests merged in 2018-02, with the labels that each got.

#2924 [ADF-2289] Login with oauth2 provider
  docs/login.component.md
  lib/core/app-config/schema.json
  lib/core/services/alfresco-api.service.ts
  lib/core/services/authentication.service.ts
Labels: change requested

#2917 [ADF-2262] Updated theming docs
  docs/docassets/images/ThemeSwatches.png
  docs/theming.md
Labels: do not merge

#2921 [ADF-2212] Task List - Improve the pagination using the interface
  demo-shell/src/app/components/process-service/process-service.component.html
  demo-shell/src/app/components/process-service/process-service.component.ts
  docs/task-list.component.md
  lib/process-services/task-list/components/task-list.component.ts
Labels: needs rebase

#2963 [ADF-2305] Process app tiles on process workspace landing page show "…" in Firefox
  lib/core/styles/_mixins.scss
  lib/process-services/app-list/apps-list.component.scss
  lib/process-services/styles/_index.scss
Labels: change requested

#2920 [ADF-2261] Missing documentation to render json in a form component
  docs/form.component.md
Labels: do not merge
