Repository Alfresco/alfresco-ng2-components, pull requests merged in 2018-03, with the labels that each got.

#3033 [ADF-2320] Complete button is visible on an involved task
  lib/process-services/task-list/components/task-details.component.html
  lib/process-services/task-list/components/task-details.component.spec.ts
  lib/process-services/task-list/components/task-details.component.ts
Labels: change requested

#3058 [ADF-2368] Version manager update
  demo-shell/src/app/components/file-view/file-view.component.html
  demo-shell/src/app/components/file-view/file-view.component.ts
  demo-shell/src/app/components/files/version-manager-dialog-adapter.component.html
  demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
  demo-shell/src/app/material.module.ts
  docs/upload-button.component.md
  lib/content-services/i18n/en.json
  lib/content-services/upload/components/upload-button.component.ts
  lib/content-services/upload/components/upload-version-button.component.ts
  lib/content-services/upload/public-api.ts
  lib/content-services/upload/upload.module.ts
  lib/content-services/version-manager/version-upload.component.html
  lib/core/models/file.model.ts
  lib/core/services/upload.service.spec.ts
  lib/core/services/upload.service.ts
Labels: needs js-api to be merged first

#3089 [ADF-2504] Add read-only mode for the content meta-data component
  docs/content-services/content-metadata.component.md
  lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.html
  lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.spec.ts
  lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.ts
  lib/content-services/content-metadata/components/content-metadata/content-metadata.component.html
  lib/content-services/content-metadata/components/content-metadata/content-metadata.component.ts
Labels: change requested

#3106 [ADF-2432] Creating component to display node permission
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/app.routes.ts
  demo-shell/src/app/components/datatable/datatable.component.ts
  demo-shell/src/app/components/files/files.component.html
  demo-shell/src/app/components/files/files.component.ts
  demo-shell/src/app/components/permissions/demo-permissions.component.html
  demo-shell/src/app/components/permissions/demo-permissions.component.scss
  demo-shell/src/app/components/permissions/demo-permissions.component.ts
  docs/content-services/permission-list.component.md
  docs/docassets/images/adf-permission-list.png
  lib/content-services/content.module.ts
  lib/content-services/document-list/services/document-list.service.ts
  lib/content-services/i18n/en.json
  lib/content-services/index.ts
  lib/content-services/mock/permission-list.component.mock.ts
  lib/content-services/permission-manager/components/permission-display/permission-list.component.html
  lib/content-services/permission-manager/components/permission-display/permission-list.component.scss
  lib/content-services/permission-manager/components/permission-display/permission-list.component.spec.ts
  lib/content-services/permission-manager/components/permission-display/permission-list.component.ts
  lib/content-services/permission-manager/index.ts
  lib/content-services/permission-manager/models/permission.model.ts
  lib/content-services/permission-manager/permission-manager.module.ts
  lib/content-services/permission-manager/public-api.ts
  lib/content-services/styles/_index.scss
  lib/core/services/nodes-api.service.ts
Labels: change requested

#3108 [ADF-2451] Reviewed component docs
  docs/README.md
  docs/content-services/README.md
  docs/content-services/node-share.directive.md
  docs/core/README.md
  docs/core/form.component.md
  docs/core/node-delete.directive.md
  docs/core/sites.service.md
  docs/core/thumbnail.service.md
  docs/process-services/README.md
  docs/process-services/process-attachment-list.component.md
  docs/process-services/process-filter.service.md
  docs/process-services/process-filters.component.md
  docs/process-services/process-list.component.md
  docs/process-services/task-filter.service.md
  docs/process-services/task-header.component.md
  lib/core/services/sites.service.ts
  lib/process-services/process-list/components/process-list.component.ts
  lib/process-services/process-list/services/process-filter.service.ts
  lib/process-services/task-list/services/task-filter.service.ts
Labels: change requested

#3104 [ADF-711] Drag and drop doesn't have the acceptedFilesType property
  docs/content-services/upload-drag-area.component.md
  lib/content-services/upload/components/base-upload/upload-base.ts
  lib/content-services/upload/components/upload-button.component.ts
  lib/content-services/upload/components/upload-drag-area.component.spec.ts
  lib/content-services/upload/components/upload-drag-area.component.ts
  lib/content-services/upload/public-api.ts
Labels: change requested, needs rebase
