Repository Alfresco/alfresco-ng2-components, pull requests merged in 2018-06, with the labels that each got.

#3404 [ADF-3039] Task List - Enanchement
  demo-shell/src/app/components/process-service/process-service.component.ts
  docs/core/datatable.component.md
  docs/process-services/task-list.component.md
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/core/datatable/data/data-table.schema.ts
  lib/core/datatable/public-api.ts
  lib/process-services/mock/public-api.ts
  lib/process-services/mock/task/task-list.mock.ts
  lib/process-services/task-list/components/task-list.component.html
  lib/process-services/task-list/components/task-list.component.spec.ts
  lib/process-services/task-list/components/task-list.component.ts
Labels: needs rebase

#3407 [ADF-2438] fixed thumbnails height
  lib/core/viewer/components/pdfViewer-thumb.component.html
  lib/core/viewer/components/pdfViewer-thumb.component.spec.ts
  lib/core/viewer/components/pdfViewer-thumb.component.ts
  lib/core/viewer/components/pdfViewer-thumbnails.component.scss
  lib/core/viewer/components/pdfViewer-thumbnails.component.spec.ts
  lib/core/viewer/components/pdfViewer-thumbnails.component.ts
Labels: waiting for review

#3414 [ADF-2754] People component tests fixed and style improvement
  lib/core/form/components/widgets/people/people.widget.html
  lib/core/form/components/widgets/people/people.widget.scss
Labels: change requested

#3332 [ADF-2795] SSO implicitflow
  demo-shell/resources/i18n/en.json
  demo-shell/src/app.config.json
  demo-shell/src/app/app.component.ts
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/app.routes.ts
  demo-shell/src/app/components/app-layout/app-layout.component.html
  demo-shell/src/app/components/app-layout/app-layout.component.ts
  demo-shell/src/app/components/files/files.component.ts
  demo-shell/src/app/components/home/home.component.html
  demo-shell/src/app/components/login/login.component.html
  demo-shell/src/app/components/login/login.component.ts
  demo-shell/src/app/components/logout/logout.component.html
  demo-shell/src/app/components/logout/logout.component.scss
  demo-shell/src/app/components/logout/logout.component.ts
  demo-shell/src/app/components/settings/settings.component.html
  demo-shell/src/app/components/settings/settings.component.ts
  docs/core/logout.directive.md
  docs/core/menu-button.model.md
  lib/content-services/dialogs/folder.dialog.ts
  lib/content-services/document-list/services/document-actions.service.spec.ts
  lib/content-services/document-list/services/document-list.service.spec.ts
  lib/content-services/document-list/services/folder-actions.service.spec.ts
  lib/content-services/social/services/rating.service.spec.ts
  lib/content-services/tag/services/tag.service.spec.ts
  lib/core/about/about.component.ts
  lib/core/app-config/schema.json
  lib/core/core.module.ts
  lib/core/directives/logout.directive.spec.ts
  lib/core/directives/logout.directive.ts
  lib/core/directives/node-favorite.directive.spec.ts
  lib/core/i18n/en.json
  lib/core/login/components/login.component.html
  lib/core/login/components/login.component.spec.ts
  lib/core/login/components/login.component.ts
  lib/core/mock/alfresco-api.service.mock.ts
  lib/core/models/oauth-config.model.ts
  lib/core/services/alfresco-api.service.ts
  lib/core/services/auth-guard-bpm.service.spec.ts
  lib/core/services/auth-guard-ecm.service.ts
  lib/core/services/auth-guard.service.spec.ts
  lib/core/services/auth-guard.service.ts
  lib/core/services/authentication.service.spec.ts
  lib/core/services/authentication.service.ts
  lib/core/services/page-title.service.spec.ts
  lib/core/services/upload.service.spec.ts
  lib/core/services/user-preferences.service.spec.ts
  lib/core/services/user-preferences.service.ts
  lib/core/settings/host-settings.component.html
  lib/core/settings/host-settings.component.scss
  lib/core/settings/host-settings.component.spec.ts
  lib/core/settings/host-settings.component.ts
  lib/core/testing/setupTestBed.ts
  lib/process-services/process-list/services/process-filter.service.spec.ts
  lib/process-services/process-list/services/process.service.spec.ts
  lib/process-services/task-list/services/task-filter.service.spec.ts
  lib/process-services/task-list/services/tasklist.service.spec.ts
  package-lock.json
Labels: do not merge, needs rebase

#3495 [ADF-3912] Setting Component - Return as default BASIC authType
  lib/core/services/alfresco-api.service.ts
  lib/core/settings/host-settings.component.ts
Labels: change requested

#3494 [ADF-3190] Fix rerendering issue with content-meta-data
  lib/content-services/content-metadata/components/content-metadata/content-metadata.component.spec.ts
  lib/content-services/content-metadata/components/content-metadata/content-metadata.component.ts
Labels: change requested

#3481 [ADF-3199] Datatable layout fix
  lib/core/datatable/components/datatable/datatable.component.scss
Labels: next version

#3489 [ADF-2962] Login Hide/Show icon is not reachable
  lib/core/login/components/login.component.html
Labels: next version
