Repository Alfresco/alfresco-ng2-components, pull requests merged in 2018-05, with the labels that each got.

#3251 [ADF-2846] new facets
  .vscode/settings.json
  demo-shell/src/app.config.json
  demo-shell/src/app/components/search/search-result.component.ts
  docs/content-services/search-filter.component.md
  docs/docassets/images/search-check-list.png
  docs/docassets/images/search-date-range.png
  docs/docassets/images/search-facet-fields.png
  docs/docassets/images/search-facet-queries.png
  docs/docassets/images/search-number-range.png
  docs/docassets/images/search-radio.png
  docs/docassets/images/search-slider.png
  docs/docassets/images/search-text.png
  lib/content-services/document-list/components/document-list.component.ts
  lib/content-services/i18n/en.json
  lib/content-services/search/components/search-check-list/search-check-list.component.html
  lib/content-services/search/components/search-check-list/search-check-list.component.scss
  lib/content-services/search/components/search-check-list/search-check-list.component.spec.ts
  lib/content-services/search/components/search-check-list/search-check-list.component.ts
  lib/content-services/search/components/search-date-range/search-date-range.component.html
  lib/content-services/search/components/search-date-range/search-date-range.component.scss
  lib/content-services/search/components/search-date-range/search-date-range.component.spec.ts
  lib/content-services/search/components/search-date-range/search-date-range.component.ts
  lib/content-services/search/components/search-filter/search-filter.component.html
  lib/content-services/search/components/search-filter/search-filter.component.spec.ts
  lib/content-services/search/components/search-filter/search-filter.component.ts
  lib/content-services/search/components/search-filter/search-filter.service.ts
  lib/content-services/search/components/search-number-range/search-number-range.component.html
  lib/content-services/search/facet-field.interface.ts
  lib/content-services/search/response-facet-field.interface.ts
  lib/content-services/search/search-configuration.interface.ts
  lib/content-services/search/search-query-builder.service.spec.ts
  lib/content-services/search/search-query-builder.service.ts
  lib/content-services/search/search.module.ts
  lib/core/app-config/schema.json
Labels: change requested

#3271 [ADF-2905] Updated JSDocs for core
  docs/core/app-config.service.md
  docs/core/bpm-user.service.md
  docs/core/card-view.component.md
  docs/core/comment-content.service.md
  docs/core/content.service.md
  docs/core/context-menu.directive.md
  docs/core/favorites-api.service.md
  docs/core/form-rendering.service.md
  docs/core/form.service.md
  lib/core/app-config/app-config.service.ts
  lib/core/card-view/components/card-view/card-view.component.ts
  lib/core/context-menu/context-menu.directive.ts
  lib/core/form/services/form.service.ts
  lib/core/services/comment-content.service.ts
  lib/core/services/content.service.ts
  lib/core/services/dynamic-component-mapper.service.ts
  lib/core/services/favorites-api.service.ts
  lib/core/userinfo/services/bpm-user.service.ts
Labels: needs rebase

#3295 Added the working-with-nodes-api-service tutorial.
  docs/docassets/images/nodesapiservices_createnode.png
  docs/docassets/images/nodesapiservices_createnode_proof.png
  docs/docassets/images/nodesapiservices_deletefolder.png
  docs/docassets/images/nodesapiservices_myonnodedoubleclick.png
  docs/docassets/images/nodesapiservices_nodelist.png
  docs/docassets/images/nodesapiservices_properties.png
  docs/tutorials/README.md
  docs/tutorials/working-with-nodes-api-service.md
  docs/user-guide/summary.json
Labels: documentation

#3297 [ADF-2843] added tooltips for all the buttons in toolbar
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/components/files/files.component.html
Labels: change requested

#3310 Added the tutorial 'Creating your JavaScript application using alfresco-js-api'.
  docs/docassets/images/javascript_app_launch.png
  docs/tutorials/README.md
  docs/tutorials/creating-javascript-app-using-alfresco-js-api.md
  docs/user-guide/summary.json
Labels: documentation

#3319 Added the tutorial 'Working with the Nodes API Service'.
  docs/docassets/images/alfrescocorerestapi_children.png
  docs/docassets/images/alfrescocorerestapi_nodesdata.png
  docs/tutorials/README.md
  docs/tutorials/working-with-nodes-js-api.md
  docs/user-guide/summary.json
Labels: documentation

#3326 [ADF-2995] Permissions - Consumer should be able to upload a new version for his file on a private site
  lib/content-services/upload/components/upload-button.component.spec.ts
  lib/content-services/upload/components/upload-button.component.ts
  lib/content-services/upload/components/upload-version-button.component.ts
Labels: change requested

#3334 [ADF-2131] Search sorting
  demo-shell/src/app.config.json
  demo-shell/src/app/components/files/files.component.html
  demo-shell/src/app/components/files/files.component.ts
  demo-shell/src/app/components/search/search-result.component.html
  demo-shell/src/app/components/search/search-result.component.scss
  demo-shell/src/app/components/search/search-result.component.ts
  docs/content-services/document-list.component.md
  docs/content-services/search-filter.component.md
  docs/content-services/search-sorting-picker.component.md
  docs/core/sorting-picker.component.md
  docs/docassets/images/sorting-picker.png
  lib/content-services/document-list/components/document-list.component.ts
  lib/content-services/document-list/data/share-datatable-adapter.spec.ts
  lib/content-services/document-list/data/share-datatable-adapter.ts
  lib/content-services/search/components/search-sorting-picker/search-sorting-picker.component.html
  lib/content-services/search/components/search-sorting-picker/search-sorting-picker.component.spec.ts
  lib/content-services/search/components/search-sorting-picker/search-sorting-picker.component.ts
  lib/content-services/search/public-api.ts
  lib/content-services/search/search-configuration.interface.ts
  lib/content-services/search/search-query-builder.service.spec.ts
  lib/content-services/search/search-query-builder.service.ts
  lib/content-services/search/search-sorting-definition.interface.ts
  lib/content-services/search/search.module.ts
  lib/core/app-config/schema.json
  lib/core/components/sorting-picker/sorting-picker.component.html
  lib/core/components/sorting-picker/sorting-picker.component.spec.ts
  lib/core/components/sorting-picker/sorting-picker.component.ts
  lib/core/core.module.ts
  lib/core/index.ts
Labels: change requested

#3329 [ADF-2884] Task List - Custom apps display all tasks
  demo-shell/src/app/components/process-service/process-service.component.html
  demo-shell/src/app/components/process-service/process-service.component.ts
  docs/process-services/process-filters.component.md
  docs/process-services/task-filters.component.md
  lib/process-services/task-list/components/task-filters.component.spec.ts
  lib/process-services/task-list/components/task-filters.component.ts
Labels: change requested

#3357 Broken links and missing images for two tutorials.
  docs/docassets/images/login_header.png
  docs/docassets/images/yeoman_creation.png
  docs/docassets/images/yeoman_start.png
  docs/tutorials/creating-javascript-app-using-alfresco-js-api.md
  docs/tutorials/creating-the-app-using-yeoman.md
  docs/tutorials/working-with-nodes-api-service.md
Labels: documentation

#3294 [ADF-2832] Demo-shell, Fix Task filter dropdown menu alignment
  lib/process-services/process-list/components/process-filters.component.html
  lib/process-services/process-list/components/process-filters.component.scss
  lib/process-services/task-list/components/task-filters.component.html
  lib/process-services/task-list/components/task-filters.component.scss
Labels: change requested, do not merge

#3378 Added the tutorial 'Basic theming'.
  docs/docassets/images/theming_palette.png
  docs/tutorials/README.md
  docs/tutorials/basic-theming.md
  docs/user-guide/summary.json
Labels: documentation

#3386 Added the 'Content metadata component' tutorial.
  docs/docassets/images/content_metadata_preset.png
  docs/tutorials/README.md
  docs/tutorials/content-metadata-component.md
  docs/user-guide/summary.json
Labels: documentation

#3373 [ADF-2977] made language change persistent
  lib/core/services/user-preferences.service.ts
Labels: needs rebase

#3345 [ADF-3041] TaskList Component - Empty State issue.
  docs/process-services/task-list.component.md
  lib/core/datatable/datatable.module.ts
  lib/core/datatable/directives/empty-custom-content.directive.ts
  lib/core/datatable/public-api.ts
  lib/process-services/task-list/components/task-list.component.html
  lib/process-services/task-list/components/task-list.component.spec.ts
  lib/process-services/task-list/components/task-list.component.ts
  lib/process-services/task-list/task-list.module.ts
Labels: needs rebase

#3364 [ADF-2753] Error Component throwing default error fixed
  docs/core/error-content.component.md
  lib/core/core.module.ts
  lib/core/i18n/en.json
  lib/core/templates/error-content/error-content.component.html
  lib/core/templates/error-content/error-content.component.scss
  lib/core/templates/error-content/error-content.component.spec.ts
  lib/core/templates/error-content/error-content.component.ts
  lib/core/templates/template.module.ts
Labels: change requested, do not merge

#3409 [ADF-2593] z-index fix for search bar
  lib/process-services/app-list/apps-list.component.scss
Labels: change requested
