Repository Alfresco/alfresco-ng2-components, pull requests merged in 2018-08, with the labels that each got.

#3644 [ADF-3400] fix buckets update on search filter
  lib/content-services/search/components/search-filter/search-filter.component.html
  lib/content-services/search/components/search-filter/search-filter.component.spec.ts
  lib/content-services/search/components/search-filter/search-filter.component.ts
Labels: Missing test

#3609 [ADF-3380] lazy loading fixes
  demo-shell/src/app/adf.module.ts
  demo-shell/src/app/app.component.spec.ts
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/app.routes.ts
  demo-shell/src/app/components/blob-preview/blob-preview.module.ts
  demo-shell/src/app/components/file-view/file-view.module.ts
  demo-shell/src/main.ts
  lib/content-services/breadcrumb/breadcrumb.module.ts
  lib/content-services/content-metadata/content-metadata.module.ts
  lib/content-services/content-node-selector/content-node-selector.module.ts
  lib/content-services/content.module.ts
  lib/content-services/dialogs/dialog.module.ts
  lib/content-services/document-list/document-list.module.ts
  lib/content-services/permission-manager/permission-manager.module.ts
  lib/content-services/search/search.module.ts
  lib/content-services/site-dropdown/sites-dropdown.module.ts
  lib/content-services/tag/tag.module.ts
  lib/content-services/testing/content.testing.module.ts
  lib/content-services/upload/upload.module.ts
  lib/content-services/version-manager/version-manager.module.ts
  lib/content-services/webscript/webscript.module.ts
  lib/core/about/about.module.ts
  lib/core/app-config/app-config.module.ts
  lib/core/buttons-menu/buttons-menu.module.ts
  lib/core/card-view/card-view.module.ts
  lib/core/collapsable/collapsable.module.ts
  lib/core/comments/comments.module.ts
  lib/core/context-menu/context-menu-holder.component.spec.ts
  lib/core/context-menu/context-menu.module.ts
  lib/core/core.module.ts
  lib/core/datatable/datatable.module.ts
  lib/core/form/form.module.ts
  lib/core/login/login.module.ts
  lib/core/package.json
  lib/core/pagination/pagination.module.ts
  lib/core/settings/host-settings.module.ts
  lib/core/sorting-picker/sorting-picker.module.ts
  lib/core/templates/template.module.ts
  lib/core/userinfo/userinfo.module.ts
  lib/core/viewer/viewer.module.ts
  lib/insights/analytics-process/analytics-process.module.ts
  lib/insights/diagram/diagram.module.ts
  lib/insights/insights.module.ts
  lib/insights/testing/insights.testing.module.ts
  lib/process-services/app-list/apps-list.module.ts
  lib/process-services/attachment/attachment.module.ts
  lib/process-services/content-widget/attach-file-widget.components.spec.ts
  lib/process-services/content-widget/content-widget.module.ts
  lib/process-services/people/people.module.ts
  lib/process-services/process-comments/process-comments.module.ts
  lib/process-services/process-list/process-list.module.ts
  lib/process-services/process.module.ts
  lib/process-services/task-list/task-list.module.ts
  lib/process-services/testing/process.testing.module.ts
  package.json
Labels: needs rebase

#3686 viewer fixes for demo shell
  demo-shell/src/app/components/process-service/process-service.component.ts
  git
  lib/core/form/components/start-form.component.ts
  lib/core/form/components/widgets/upload/upload.widget.ts
Labels: approved
