Repository Alfresco/alfresco-ng2-components, pull requests merged in 2018-04, with the labels that each got.

#3156 upgrade ng-packagr
  demo-shell/package.json
  lib/content-services/ng-package.json
  lib/core/ng-package.json
  lib/insights/ng-package.json
  lib/package.json
  lib/process-services/ng-package.json
Labels: do not merge

#3165 [ADF-2607] Task Form - Number Widget placeholder no longer displayed
  lib/core/form/components/widgets/amount/amount.widget.scss
  lib/core/form/components/widgets/container/container.widget.scss
  lib/core/form/components/widgets/text/text.widget.spec.ts
  lib/core/form/components/widgets/text/text.widget.ts
Labels: change requested

#3198 [ADF-2695] DocumentList content action documentation
  docs/content-services/content-action.component.md
Labels: documentation

#3197 [ADF- 2670] Checked and updated docs for 2.3
  docs/README.md
  docs/content-services/README.md
  docs/content-services/content-metadata.component.md
  docs/content-services/content-node-selector-panel.component.md
  docs/content-services/document-list.component.md
  docs/content-services/document-list.service.md
  docs/content-services/search-filter.component.md
  docs/content-services/search-query-builder.service.md
  docs/content-services/search.component.md
  docs/content-services/upload-drag-area.component.md
  docs/content-services/version-manager.component.md
  docs/core/README.md
  docs/core/alfresco-api.service.md
  docs/core/content.service.md
  docs/core/datatable.component.md
  docs/core/pagination.component.md
  docs/core/user-preferences.service.md
  docs/process-services/process-list.component.md
  docs/process-services/task-details.component.md
  docs/process-services/task-list.component.md
  docs/versionIndex.md
Labels: documentation

#3207 bump 2.3.0 package.json
  demo-shell/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/insights/package.json
  lib/package.json
  lib/process-services/package.json
Labels: do not merge

#3179 [APM-7] Feature enhancement for the create and edit folder directive
  docs/content-services/folder-create.directive.md
  docs/content-services/folder-edit.directive.md
  docs/core/sidenav-layout.component.md
  lib/content-services/dialogs/folder.dialog.html
  lib/content-services/dialogs/folder.dialog.spec.ts
  lib/content-services/dialogs/folder.dialog.ts
  lib/content-services/folder-directive/folder-create.directive.spec.ts
  lib/content-services/folder-directive/folder-create.directive.ts
  lib/content-services/folder-directive/folder-edit.directive.spec.ts
  lib/content-services/folder-directive/folder-edit.directive.ts
  lib/core/sidenav-layout/components/sidenav-layout/sidenav-layout.component.spec.ts
  lib/core/sidenav-layout/components/sidenav-layout/sidenav-layout.component.ts
Labels: next version

#3177 [ADF-2601] added permission check to info editing button
  lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.html
  lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.spec.ts
  lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.ts
  lib/core/viewer/components/viewer.component.ts
Labels: next version

#3192 [ADF-2703] Info Drawer - Header does not navigate to name of default tab
  lib/core/viewer/components/viewer.component.html
  lib/core/viewer/components/viewer.component.ts
Labels: do not merge

#3187 [ADF-2709] Replace the ADF accordion with material accordion
  lib/core/collapsable/accordion-group.component.html
  lib/core/collapsable/accordion-group.component.scss
  lib/core/collapsable/accordion-group.component.spec.ts
  lib/core/collapsable/accordion-group.component.ts
  lib/core/collapsable/accordion.component.spec.ts
  lib/core/collapsable/accordion.component.ts
  lib/core/material.module.ts
Labels: next version

#3215 [ADF-2650] Error with rootDir at insights folder fixed
  docs/docassets/images/adf-buttons-menu-desktop.png
  docs/docassets/images/adf-buttons-menu-mobile.png
  docs/insights/buttons-menu.component.md
  lib/core/buttons-menu/buttons-menu.component.html
  lib/core/buttons-menu/buttons-menu.component.spec.ts
  lib/core/buttons-menu/buttons-menu.component.ts
  lib/core/buttons-menu/buttons-menu.module.ts
  lib/core/buttons-menu/index.ts
  lib/core/buttons-menu/menu-button.model.ts
  lib/core/buttons-menu/public-api.ts
  lib/core/core.module.ts
  lib/core/index.ts
  lib/core/styles/prebuilt/_all-theme.scss
  lib/insights/analytics-process/analytics-process.module.ts
  lib/insights/analytics-process/components/analytics-report-list.component.scss
  lib/insights/analytics-process/components/analytics-report-parameters.component.html
  lib/insights/analytics-process/components/analytics-report-parameters.component.scss
  lib/insights/analytics-process/components/analytics-report-parameters.component.spec.ts
  lib/insights/analytics-process/components/analytics-report-parameters.component.ts
  lib/insights/material.module.ts
  lib/insights/styles/_index.scss
Labels: change requested, do not merge, needs rebase

#3235 [ADF-2563] Upload new version information dialog
  demo-shell/src/app/components/file-view/file-view.component.html
  demo-shell/src/app/components/file-view/file-view.component.scss
  demo-shell/src/app/components/file-view/file-view.component.ts
  demo-shell/src/app/components/files/files.component.html
  demo-shell/src/app/components/files/files.component.scss
  docs/content-services/upload-button.component.md
  docs/content-services/upload-drag-area.component.md
  docs/content-services/version-list.component.md
  docs/core/viewer.component.md
  lib/content-services/content-metadata/components/content-metadata/content-metadata.component.ts
  lib/content-services/i18n/en.json
  lib/content-services/upload/components/base-upload/upload-base.spec.ts
  lib/content-services/upload/components/base-upload/upload-base.ts
  lib/content-services/upload/components/upload-button.component.ts
  lib/content-services/upload/components/upload-drag-area.component.ts
  lib/content-services/upload/components/upload-version-button.component.ts
  lib/content-services/version-manager/version-list.component.html
  lib/content-services/version-manager/version-list.component.scss
  lib/content-services/version-manager/version-list.component.spec.ts
  lib/content-services/version-manager/version-list.component.ts
  lib/content-services/version-manager/version-manager.component.html
  lib/content-services/version-manager/version-manager.component.scss
  lib/content-services/version-manager/version-manager.component.spec.ts
  lib/content-services/version-manager/version-manager.component.ts
  lib/content-services/version-manager/version-manager.module.ts
  lib/content-services/version-manager/version-upload.component.html
  lib/content-services/version-manager/version-upload.component.scss
  lib/content-services/version-manager/version-upload.component.ts
  lib/core/collapsable/accordion-group.component.scss
  lib/core/models/file.model.ts
  lib/core/services/upload.service.spec.ts
  lib/core/services/upload.service.ts
  lib/core/utils/file-utils.ts
  lib/core/viewer/components/viewer.component.scss
  lib/core/viewer/components/viewer.component.ts
  lib/package-lock.json
  lib/package.json
Labels: needs rebase

#3245 [ADF-2739] Long names in breadcrumb fixed
  lib/content-services/breadcrumb/breadcrumb.component.scss
  lib/core/datatable/components/datatable/datatable.component.scss
Labels: do not merge

#3249 [ADF-2771] Sidebar action menu component - UX review
  lib/core/sidebar/sidebar-action-menu.component.scss
Labels: change requested
