Repository Alfresco/alfresco-ng2-components, pull requests merged in 2018-07, with the labels that each got.

#3525 [ADF-2599] Share button disabled after clicking it fixed
  demo-shell/src/app/components/files/files.component.html
  lib/content-services/directives/node-share.directive.ts
Labels: change requested

#3563 [ADF_NOISSUE] Header image fix
  lib/core/assets/images/logo.png
  lib/core/layout/components/header/header.component.ts
  lib/core/styles/_index.scss
Labels: change requested

#3577 [ADF-3193, ADF-3275] CardView e2e tests
  e2e/card-view-component.e2e.ts
  e2e/pages/adf/cardViewPageComponent.js
  e2e/pages/adf/navigationBarPage.js
Labels: change requested

#3572 [ADF-3018] Create automated test for replacing an app
  e2e/actions/APS/apps.actions.ts
  e2e/actions/APS/models.actions.ts
  e2e/apps-section.e2e.ts
  e2e/pages/adf/process_services/processServicesPage.js
  e2e/util/constants.js
Labels: Failing tests, change requested

#3576 [ADF-3339] added test component for header
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/app.routes.ts
  demo-shell/src/app/components/app-layout/app-layout.component.html
  demo-shell/src/app/components/app-layout/app-layout.component.ts
  demo-shell/src/app/components/form/demo-form.ts
  demo-shell/src/app/components/header-data/header-data.component.html
  demo-shell/src/app/components/header-data/header-data.component.scss
  demo-shell/src/app/components/header-data/header-data.component.ts
  demo-shell/src/app/components/header-data/header-data.service.ts
  lib/core/layout/components/header/header.component.scss
  lib/core/layout/components/header/header.component.spec.ts
  lib/core/layout/components/header/header.component.ts
Labels: change requested

#3616 Fix update-content tag documentation
  docs/core/empty-content.component.md
Labels: do not merge

#3617 Typo convention
  CONTRIBUTING.md
Labels: do not merge

#3624 [ADF-3377] Create automated tests for comments-Tasks
  e2e/pages/adf/commentsPage.ts
  e2e/process-services/comment_component_processes.e2e.ts
  e2e/process-services/comment_component_tasks.e2e.ts
Labels: change requested

#3630 [ADF-3388] E2e tests for notification component added
  demo-shell/src/app/components/notifications/notifications.component.html
  demo-shell/src/app/components/notifications/notifications.component.ts
  e2e/content-services/notifications_component.e2e.ts
  e2e/pages/adf/notificationPage.js
Labels: Failing tests, do not merge
