Repository Alfresco/alfresco-ng2-components, pull requests merged in 2019-02, with the labels that each got.

#4237 [ADF-3745] Updated doc comments
  docs/process-services-cloud/edit-process-filter-cloud.component.md
  lib/core/services/login-dialog.service.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
Labels: documentation

#4222 [ADF-3959] Fixing trashcan-pagination tests
  e2e/content-services/trashcan-pagination.e2e.ts
  e2e/content-services/upload/excluded-file.e2e.ts
  e2e/content-services/upload/uploader-component.e2e.ts
  e2e/content-services/upload/user-permission.e2e.ts
  e2e/pages/adf/dialog/uploadDialog.ts
  e2e/pages/adf/material/formControllersPage.ts
Labels: e2e

#4192 [ADF-3929] - Use created user in move/copy
  lib/content-services/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/content-node-selector/content-node-selector.component.html
Labels: Investigation, change requested, waiting for review

#4210 [ADF-3829] Add multiple select checkbox to tasks and process cloud APS2
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/components/app-layout/cloud/cloud-breadcrumb-component.html
  demo-shell/src/app/components/app-layout/cloud/cloud-layout.component.html
  demo-shell/src/app/components/app-layout/cloud/cloud-layout.component.scss
  demo-shell/src/app/components/app-layout/cloud/cloud-layout.component.ts
  demo-shell/src/app/components/app-layout/cloud/cloud-settings.component.html
  demo-shell/src/app/components/app-layout/cloud/cloud-settings.component.scss
  demo-shell/src/app/components/app-layout/cloud/cloud-settings.component.ts
  demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.html
  demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.ts
  demo-shell/src/app/components/app-layout/cloud/services/cloud-layout.service.ts
  demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.html
  demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.html
Labels: do not merge

#4263 [ADF-4013] Fixed anchor generation in ToC doc tool
  tools/doc/doctool.config.json
  tools/doc/tools/toc.js
Labels: documentation

#4239 [ADF-3745] Updated code samples for empty content component
  docs/core/empty-content.component.md
Labels: documentation, needs rebase

#4221 [ADF-3828] - e2e add assignee tests
  e2e/core/icons-component.e2e.ts
  e2e/core/login/login-sso/login-sso.e2e.ts
  e2e/core/user-info-component-cloud.e2e.ts
  e2e/pages/adf/dataTablePage.ts
  e2e/pages/adf/process-cloud/editTaskFilterCloudComponent.ts
  e2e/pages/adf/process-cloud/startTasksCloudComponent.ts
  e2e/pages/adf/settingsPage.ts
  e2e/process-services-cloud/apps-section-cloud.e2e.ts
  e2e/process-services-cloud/edit-task-filters-component.e2e.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/process-filters-cloud.e2e.ts
  e2e/process-services-cloud/start-process-cloud.e2e.ts
  e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts
  e2e/process-services-cloud/task-details-cloud.e2e.ts
  e2e/process-services-cloud/task-filters-cloud.e2e.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
Labels: e2e

#4274 [ADF-4016] Added page with version compatibility table
  docs/README.md
  docs/abn-tree.yml
  docs/compatibility.md
  docs/versionIndex.md
Labels: documentation

#4278 [ADF-3745] Added styling to *where* property for clarity
  docs/content-services/content-node-selector-panel.component.md
  docs/content-services/content-node-selector.component.md
  docs/content-services/document-list.component.md
  lib/content-services/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/document-list/components/document-list.component.ts
Labels: documentation

#4277 [ADF-3745] Added docs for remaining classes
  docs/README.md
  docs/core/login.component.md
  docs/extensions/dynamic-tab.component.md
  docs/process-services-cloud/README.md
  docs/process-services-cloud/group-cloud.service.md
  docs/process-services-cloud/process-list-cloud.service.md
  docs/process-services-cloud/task-list-cloud.service.md
  docs/versionIndex.md
  lib/process-services-cloud/src/lib/group/services/group-cloud.service.ts
  lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
  lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
  tools/doc/doctool.config.json
Labels: documentation

#4287 [ADF-3745] Performed doc checks with tools
  docs/README.md
  docs/content-services/confirm.dialog.md
  docs/content-services/content-node-share.directive.md
  docs/content-services/document-actions.service.md
  docs/content-services/node-permission.service.md
  docs/content-services/search-query-builder.service.md
  docs/core/authentication.service.md
  docs/core/bpm-user.model.md
  docs/core/content.widget.md
  docs/core/download-zip.service.md
  docs/core/icon.component.md
  docs/core/node-delete.directive.md
  docs/core/node-download.directive.md
  docs/core/node-favorite.directive.md
  docs/core/translation.service.md
  docs/core/viewer.component.md
  docs/extensions/README.md
  docs/process-services/process-filters.component.md
  docs/process-services/process.service.md
  docs/process-services/start-task.component.md
  docs/user-guide/app-extensions.md
  docs/versionIndex.md
  tools/doc/doctool.config.json
  tools/doc/tools/sourceLinker.js
  tools/doc/tools/sourceLinker.ts
Labels: documentation

#4291 [ADF-3745] Updates for doc review
  docs/README.md
  docs/content-services/README.md
  docs/content-services/content-node-selector-panel.component.md
  docs/content-services/content-node-selector.component.md
  docs/content-services/document-list.component.md
  docs/content-services/image-resolver.model.md
  docs/content-services/row-filter.model.md
  docs/content-services/search-query-builder.service.md
  docs/core/icon.component.md
  docs/core/identity-user.service.md
  docs/core/infinite-pagination.component.md
  docs/core/login-dialog.service.md
  docs/core/translation.service.md
  docs/process-services/task-list.component.md
  docs/versionIndex.md
  lib/content-services/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/document-list/components/document-list.component.ts
  lib/content-services/search/search-query-builder.service.ts
  lib/core/icon/icon.component.ts
  lib/core/services/login-dialog.service.ts
  lib/core/userinfo/services/identity-user.service.ts
  lib/process-services/task-list/components/task-list.component.ts
  tools/doc/tools/sourceLinker.js
  tools/doc/tools/sourceLinker.ts
Labels: documentation

#4292 [ADF-4055] ProcessAttachmentListComponent- add opt parameter on process-instances api call
  lib/core/form/services/process-content.service.spec.ts
  lib/core/form/services/process-content.service.ts
  lib/process-services/attachment/process-attachment-list.component.spec.ts
  lib/process-services/attachment/process-attachment-list.component.ts
Labels: Failing tests

#4302 [ADF-4069] Added updated license list tool
  docs/abn-tree.yml
  docs/license-info/license-info-v3.0.0.md
  package.json
  tools/doc/licenseList.js
  tools/doc/templates/licensePage.ejs
Labels: documentation

#4311 [ADF-3745] Reviewed 3.0.0 release notes
  docs/release-notes/RelNote300.md
Labels: documentation

#4315 [ADF-4080] Updated compatibility page plus other minor fixes
  docs/README.md
  docs/compatibility.md
  docs/license-info/license-info-v3.0.0.md
Labels: documentation

#4147 [ADF-3861] Document List - aria-label on checkbox and actions menu
  lib/core/datatable/components/datatable/datatable.component.html
Labels: Accessibility

#4320 [ADF-3745] Reviewed breaking changes page
  docs/README.md
  docs/breaking-changes/breaking-change-2.6.0-3.0.0.md
Labels: documentation

#4231 [ADF-3981] - Should be possible to login with valid credentials
  e2e/core/login/login-component.e2e.ts
Labels: e2e

#4325 [ADF-4095] Test Inherit Permission
  e2e/content-services/permissions-component.e2e.ts
  e2e/pages/adf/permissionsPage.ts
Labels: e2e

#4180 [ADF-NO-ISSUE] Changing locators using arial-label
  e2e/pages/adf/lockFilePage.ts
  e2e/pages/adf/paginationPage.ts
  e2e/pages/adf/process-services/widgets/dynamicTableWidget.ts
  lib/content-services/dialogs/node-lock.dialog.html
  lib/core/pagination/pagination.component.html
Labels: Failing tests

#4323 [ADF-4012] Should be able to set default columns in adf-process-list-cloud
  e2e/pages/adf/configEditorPage.ts
  e2e/pages/adf/dataTablePage.ts
  e2e/process-services-cloud/processList-cloud-component.e2e.ts
  e2e/process-services-cloud/processListCloud.config.ts
Labels: change requested, e2e

#4299 [ADF-4067] Process Service Cloud change applicationName input
  demo-shell/src/app/app.routes.ts
  demo-shell/src/app/components/app-layout/cloud/cloud-breadcrumb-component.html
  demo-shell/src/app/components/app-layout/cloud/cloud-breadcrumb-component.ts
  demo-shell/src/app/components/app-layout/cloud/cloud-layout.component.html
  demo-shell/src/app/components/app-layout/cloud/cloud-layout.component.ts
  demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.html
  demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.ts
  demo-shell/src/app/components/app-layout/cloud/start-process-cloud-demo.component.html
  demo-shell/src/app/components/app-layout/cloud/start-process-cloud-demo.component.ts
  demo-shell/src/app/components/app-layout/cloud/start-task-cloud-demo.component.html
  demo-shell/src/app/components/app-layout/cloud/start-task-cloud-demo.component.ts
  demo-shell/src/app/components/app-layout/cloud/task-details-cloud-demo.component.html
  demo-shell/src/app/components/app-layout/cloud/task-details-cloud-demo.component.ts
  demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.html
  demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.ts
  docs/process-services-cloud/edit-process-filter-cloud.component.md
  docs/process-services-cloud/edit-task-filter-cloud.component.md
  docs/process-services-cloud/process-list-cloud.component.md
  docs/process-services-cloud/task-header-cloud.component.md
  docs/process-services-cloud/task-list-cloud.component.md
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
Labels: needs rebase

#4341 [ADF-4068] StartTaskComponent - add description empty space validator
  lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.ts
Labels: waiting for review

#4331 [ADF-4100] Automate Permission Role dropdown for User
  e2e/content-services/permissions-component.e2e.ts
  e2e/pages/adf/dataTablePage.ts
  e2e/pages/adf/permissionsPage.ts
Labels: change requested, e2e

#4339 [ADF-3995] EditProcessFilterCloud - fix processInstanceId filter pr…
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
Labels: waiting for review

#4334 [ADF-4066] Should create a task unassigned when assignee field is empty …
  demo-shell/src/app/components/app-layout/cloud/task-details-cloud-demo.component.html
  e2e/pages/adf/demo-shell/process-services/taskDetailsPage.ts
  e2e/pages/adf/process-cloud/taskListCloudComponent.ts
  e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts
Labels: change requested, e2e

#4342 [ADF-4143] EditTaskFilterComponent - change date format
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/task-filters-cloud.module.ts
Labels: waiting for review

#4347 [ADF-4066] Start task form with no assignee is saved as unassigned task
  demo-shell/src/app/components/app-layout/cloud/task-details-cloud-demo.component.html
  e2e/pages/adf/demo-shell/process-services/taskDetailsPage.ts
  e2e/pages/adf/process-cloud/taskListCloudComponent.ts
  e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts
Labels: e2e

#4348 [ADF-4103] Remove User or Group from the Permission list
  e2e/content-services/permissions-component.e2e.ts
  e2e/pages/adf/permissionsPage.ts
  lib/content-services/permission-manager/components/permission-list/permission-list.component.html
Labels: e2e

#4356 [ADF-4105] Role Site Dropdown is Displayed
  e2e/content-services/permissions-component.e2e.ts
  e2e/pages/adf/contentServicesPage.ts
  e2e/pages/adf/dialog/contentListPage.ts
  e2e/pages/adf/permissionsPage.ts
Labels: change requested, e2e
