Repository Alfresco/alfresco-ng2-components, pull requests merged in 2019-11, with the labels that each got.

#5206 [ADF-2990] Datatable - access header row via keyboard
  lib/core/datatable/components/datatable/datatable-row.component.spec.ts
  lib/core/datatable/components/datatable/datatable-row.component.ts
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.scss
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.ts
Labels: Accessibility, PR: reviewed-approved, PR: unreviewed

#5212 Remove discovery
  e2e/core/login/login-sso/login-sso-error.e2e.ts
  e2e/core/login/login-sso/login-sso.e2e.ts
  e2e/protractor/save-remote.js
  lib/core/login/components/login.component.spec.ts
  lib/core/login/components/login.component.ts
  lib/core/services/authentication.service.ts
  package-lock.json
  package.json
  protractor.conf.ts
Labels: PR: merged

#5208 [ADF-4979] Add onChanges detection for Task Header Cloud component
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/app.routes.ts
  demo-shell/src/app/components/app-layout/app-layout.component.ts
  demo-shell/src/app/components/cloud/task-details-cloud-demo.component.html
  demo-shell/src/app/components/cloud/task-details-cloud-demo.component.ts
  demo-shell/src/app/components/cloud/task-header-cloud-demo.component.html
  demo-shell/src/app/components/cloud/task-header-cloud-demo.component.scss
  demo-shell/src/app/components/cloud/task-header-cloud-demo.component.ts
  docs/process-services-cloud/components/task-header-cloud.component.md
  lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-header/services/process-header-cloud.service.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
  lib/process-services-cloud/src/lib/services/user-preference-cloud.service.ts
  lib/process-services-cloud/src/lib/task/directives/claim-task.directive.ts
  lib/process-services-cloud/src/lib/task/directives/complete-task.directive.ts
  lib/process-services-cloud/src/lib/task/directives/unclaim-task.directive.ts
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
Labels: PR: reviewed-approved

#5216 Should not redirect if is SilentLogin on
  lib/core/services/auth-guard-base.ts
  lib/core/services/auth-guard-bpm.service.spec.ts
  lib/core/services/auth-guard-ecm.service.spec.ts
  lib/core/services/auth-guard.service.spec.ts
Labels: PR: reviewed-approved

#5218 [ADF-4979] TaskHeader - Fix loop
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
Labels: PR: unreviewed

#5219 [ADF-4973] CLONE - Header - sidenav menu button expanded/collapsed state not exposed via ARIA
  demo-shell/src/app/components/app-layout/app-layout.component.html
Labels: PR: reviewed-approved

#5220 Modified candidateuserprocess to have candidate users and removed adm…
  e2e/resources/activiti7/candidatebaseapp.zip
Labels: PR: unreviewed

#5221 enable mergify
  .mergify.yml
Labels: PR: reviewed-approved

#5225 make error message more clear
  lib/testing/src/lib/core/utils/browser-actions.ts
Labels: PR: reviewed-approved

#5224 Refactor e2e PS-CLOUD
  e2e/process-services-cloud/apps-section-cloud.e2e.ts
  e2e/process-services-cloud/edit-process-filters-component.e2e.ts
  e2e/process-services-cloud/edit-task-filters-component.e2e.ts
  e2e/process-services-cloud/form-field/date-widget.e2e.ts
  e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts
  e2e/process-services-cloud/form-field/visibility-condition-tabs.e2e.ts
  e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
  e2e/process-services-cloud/people-group-cloud-component.e2e.ts
  e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/process-filter-results.e2e.ts
  e2e/process-services-cloud/process-filters-cloud.e2e.ts
  e2e/process-services-cloud/process-header-cloud.e2e.ts
  e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts
  e2e/process-services-cloud/process-list-cloud-component.e2e.ts
  e2e/process-services-cloud/process-list-selection-cloud.e2e.ts
  e2e/process-services-cloud/start-process-cloud.e2e.ts
  e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts
  e2e/process-services-cloud/start-task/start-task-group-cloud.e2e.ts
  e2e/process-services-cloud/task-filters-cloud.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  e2e/process-services-cloud/task-header-cloud.e2e.ts
  e2e/process-services-cloud/task-list-cloud-action-menu.e2e.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/process-services-cloud/task-list-selection.e2e.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
  e2e/test.config.js
  lib/testing/src/lib/core/pages/login-sso.page.ts
  scripts/app-config-replace.js
  scripts/travis/e2e/process-services-cloud-e2e.sh
Labels: PR: reviewed-approved

#5227 add missing typing information
  lib/process-services/src/lib/attachment/process-attachment-list.component.ts
  lib/process-services/src/lib/attachment/task-attachment-list.component.ts
  lib/process-services/src/lib/people/components/people-list/people-list.component.ts
  lib/process-services/src/lib/people/components/people-search-field/people-search-field.component.ts
  lib/process-services/src/lib/people/components/people-search/people-search.component.ts
  lib/process-services/src/lib/people/components/people/people.component.ts
  lib/process-services/src/lib/task-list/models/user-event.model.ts
  lib/process-services/src/lib/task-list/models/user-group.model.ts
  lib/process-services/src/lib/task-list/services/tasklist.service.ts
  lib/process-services/src/lib/task-list/validators/task-description.validator.ts
  lib/testing/src/lib/core/actions/identity/group-identity.service.ts
  lib/testing/src/lib/core/actions/identity/identity.service.ts
  lib/testing/src/lib/core/actions/identity/tasks.service.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  lib/testing/src/lib/core/pages/form/formFields.ts
  lib/testing/src/lib/core/utils/logger.ts
  lib/testing/src/lib/process-services-cloud/actions/message-events.service.ts
  lib/testing/src/lib/process-services-cloud/actions/process-definitions.service.ts
  lib/testing/src/lib/process-services-cloud/pages/dialog/edit-process-filter-dialog.page.ts
  lib/testing/src/lib/process-services-cloud/pages/dialog/edit-task-filter-dialog.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/start-tasks-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
  lib/testing/src/lib/process-services/pages/form-fields.page.ts
Labels: PR: reviewed-approved

#5226 [ADF-4986] Move or copy - Empty cells should not receive focus
  lib/core/datatable/components/datatable/datatable.component.html
Labels: PR: reviewed-approved

#5205 [AAE-485] Fix card view int item validator when value is empty
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/validators/card-view-item-float.validator.ts
  lib/core/card-view/validators/card-view-item-int.validator.ts
Labels: PR: unreviewed

#5229 allow indexed access for DataRow objects
  lib/core/datatable/data/data-row.model.ts
Labels: PR: reviewed-approved

#5217 [ADF-4984] Focus indicator is not clearly visible- mat-expansion-panel
  lib/core/styles/_index.scss
  lib/core/styles/_mixins.scss
Labels: Accessibility, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#5230 Fix e2e test visibility
  e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
Labels: PR: reviewed-approved

#5211 [ADF-4982] Refactor CLI script and add new S3 scripts
  lib/cli/README.md
  lib/cli/bin/adf-cli
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/cli/scripts/artifact-from-s3.ts
  lib/cli/scripts/artifact-to-s3.ts
  lib/cli/scripts/docker-publish.ts
  lib/cli/scripts/exec.ts
  lib/cli/scripts/init-aae-env.ts
  lib/cli/scripts/kubectl-delete.ts
  lib/cli/scripts/kubectl-image.ts
  lib/cli/scripts/logger.ts
  lib/cli/scripts/npm-publish.ts
  lib/cli/scripts/update-commit-sha.ts
  lib/cli/scripts/update-version.ts
  package-lock.json
  package.json
  scripts/check-env/check-ps-env.js
Labels: PR: reviewed-approved

#5237 AAE-702 - update simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#5239 updated the simpleapp with fix for Processwithvariables and messageevents tests
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#5236 [ADF-4979] TaskHeaderCloudComponent Add error emit when appName or taskId is not provided
  demo-shell/src/app/components/cloud/task-header-cloud-demo.component.html
  demo-shell/src/app/components/cloud/task-header-cloud-demo.component.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
Labels: PR: unreviewed

#5234 [ADF-4988] CLONE - Toolbar Actions and Navigation - Dialog is closed focus is not returned to trigger
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.ts
Labels: PR: unreviewed

#5238 added the method to retrieve the processInstanceId based on the processname
  lib/testing/src/lib/core/actions/identity/query.service.ts
Labels: PR: unreviewed

#5213 [AAE-534] Search - extract search text input from SearchControlComponent
  docs/core/components/search-cloud.component.md
  docs/core/components/search-text-input.component.md
  docs/docassets/images/search-text-input.png
  lib/content-services/src/lib/search/components/search-control.component.html
  lib/content-services/src/lib/search/components/search-control.component.scss
  lib/content-services/src/lib/search/components/search-control.component.spec.ts
  lib/content-services/src/lib/search/components/search-control.component.ts
  lib/content-services/src/lib/search/components/search.component.ts
  lib/content-services/src/lib/search/public-api.ts
  lib/content-services/src/lib/search/search.module.ts
  lib/core/core.module.ts
  lib/core/index.ts
  lib/core/interface/search-configuration.interface.ts
  lib/core/models/public-api.ts
  lib/core/models/search-text-input.model.ts
  lib/core/search-cloud/components/search-text-cloud/search-text-cloud.component.html
  lib/core/search-cloud/components/search-text-cloud/search-text-cloud.component.spec.ts
  lib/core/search-cloud/components/search-text-cloud/search-text-cloud.component.ts
  lib/core/search-cloud/search-cloud.component.scss
  lib/core/search-cloud/search-cloud.component.spec.ts
  lib/core/search-cloud/search-cloud.component.ts
  lib/core/search-text/animations.ts
  lib/core/search-text/index.ts
  lib/core/search-text/public-api.ts
  lib/core/search-text/search-text-input.component.html
  lib/core/search-text/search-text-input.component.scss
  lib/core/search-text/search-text-input.component.spec.ts
  lib/core/search-text/search-text-input.component.ts
  lib/core/search-text/search-text-input.module.ts
  lib/core/search-text/search-trigger.directive.ts
  lib/core/services/search-cloud.service.ts
  lib/core/styles/_index.scss
Labels: PR: reviewed-approved

#5200 [AAE-463] - change dueDate render component
  e2e/process-services-cloud/task-header-cloud.e2e.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-header/mocks/task-details-cloud.mock.ts
Labels: PR: reviewed-approved

#5244 [ADF-4979] Remove unnecessary demo shell required validation
  demo-shell/src/app/components/cloud/task-header-cloud-demo.component.html
  demo-shell/src/app/components/cloud/task-header-cloud-demo.component.ts
Labels: PR: unreviewed

#5241 [ADF-4992] [TaskListCloudComponent] Use standalone property in the task query api
  demo-shell/src/app/components/cloud/tasks-cloud-demo.component.html
  docs/process-services-cloud/components/edit-task-filter-cloud.component.md
  docs/process-services-cloud/components/task-list-cloud.component.md
  e2e/process-services-cloud/config/task-list-cloud.config.ts
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/start-task/models/task-details-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/mocks/fake-task-details-response.mock.ts
  lib/process-services-cloud/src/lib/task/task-header/mocks/task-details-cloud.mock.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/mock/fakeTaskResponseMock.ts
  lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
Labels: PR: reviewed-approved

#5242 upgrade node-sass to support node 12
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#5240 [AAE-485] - empty value for CardView Int Item e2e test
  e2e/core/card-view/card-view-component.e2e.ts
  e2e/pages/adf/cardViewComponentPage.ts
Labels: PR: reviewed-approved

#5247 [AAE-811] Add getStatusByName in task list page
  lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
Labels: PR: reviewed-approved

#5245 [AAE-849] improve search component
  docs/core/components/search-text-input.component.md
  lib/core/search-text/search-text-input.component.ts
Labels: PR: reviewed-approved

#5250 Fixed start-visibility-form and start-task-visibility-form processes
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: reviewed-approved

#5251 updated the simpleapp with multiinstance processes
  e2e/resources/activiti7/simpleapp.zip
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: unreviewed

#5248 [DW-1486] form versioning and cloud service enhancements
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/resources/forms/checkbox-visibility-condition.ts
  e2e/resources/forms/custom-date-form.ts
  e2e/resources/forms/tab-visibility-conditions.ts
  lib/content-services/src/lib/content-metadata/services/config/content-metadata-config.factory.spec.ts
  lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.spec.ts
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.spec.ts
  lib/content-services/src/lib/content-node-share/content-node-share.directive.spec.ts
  lib/content-services/src/lib/directives/node-lock.directive.spec.ts
  lib/content-services/src/lib/permission-manager/services/node-permission-dialog.service.spec.ts
  lib/core/mock/form/widget-visibility-cloud.service.mock.ts
  lib/core/mock/form/widget-visibility.service.mock.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/components/form-definition-selector-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/models/form-definition-selector-cloud.model.ts
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
  lib/process-services-cloud/src/lib/form/services/form-definition-selector-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/form/services/form-definition-selector-cloud.service.ts
  lib/process-services-cloud/src/lib/process-services-cloud.module.ts
  lib/process-services-cloud/src/lib/process/process-header/services/process-header-cloud.service.ts
  lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
  lib/process-services-cloud/src/lib/services/base-cloud.service.ts
  lib/process-services-cloud/src/lib/services/user-preference-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/services/user-preference-cloud.service.ts
  lib/process-services-cloud/src/lib/task/services/start-task-cloud.service.ts
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
  lib/process-services-cloud/src/lib/task/start-task/models/task-details-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-header/mocks/task-details-cloud.mock.ts
  lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
  lib/process-services/src/lib/form/form.component.ts
  lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
Labels: PR: unreviewed

#5252 fix 'standalone' spelling
  e2e/process-services-cloud/task-list-properties.e2e.ts
Labels: PR: reviewed-approved

#5253 [ADF-4995] Metadata - edit mode cannot be access via keyboard
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
Labels: Accessibility, PR: reviewed-approved, PR: unreviewed

#5254 [ADF-4994] Move realmRole functions inside JwtHelperService.
  lib/core/services/auth-guard-sso-role.service.spec.ts
  lib/core/services/auth-guard-sso-role.service.ts
  lib/core/services/jwt-helper.service.spec.ts
  lib/core/services/jwt-helper.service.ts
Labels: PR: reviewed-approved

#5255 [ADF-4787] Invalid value of number field is parsed and fields with visibility conditions based on the number field are visible
  lib/core/form/services/widget-visibility-cloud.service.spec.ts
  lib/core/form/services/widget-visibility.service.spec.ts
  lib/core/form/services/widget-visibility.service.ts
Labels: PR: reviewed-approved

#5261 REVERT [ADF-4988] CLONE - Toolbar Actions and Navigation - Dialog is closed focus is not returned to trigger
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.ts
Labels: PR: reviewed-approved

#5267 [ADF-5008] Add an health checks on the services:
  lib/cli/scripts/init-aae-env.ts
Labels: PR: reviewed-approved

#5273 [AAE-880] Fix updater script in the cli
  lib/cli/scripts/update-version.ts
Labels: PR: reviewed-approved

#5268 [ADF-5002] Datatable - fix focus selection for grid list
  lib/core/datatable/components/datatable/datatable.component.ts
Labels: PR: reviewed-approved

#5269 [DW-1563] Complete button is not present for empty forms
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
Labels: PR: reviewed-approved

#5265 [AAE-898] Fix Datetime card view model custom format
  e2e/core/card-view/card-view-component.e2e.ts
  lib/core/card-view/models/card-view-datetimeitem.model.ts
Labels: PR: reviewed-approved

#5262 Fix ps e2e
  cspell.json
  e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts
  e2e/process-services-cloud/config/start-process-cloud.config.ts
  e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
  e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
  e2e/process-services-cloud/process-header-cloud.e2e.ts
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component-tab.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  e2e/process-services-cloud/task-header-cloud.e2e.ts
  e2e/process-services-cloud/task-list-properties-sort.e2e.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/protractor/save-remote.js
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  lib/testing/src/lib/core/pages/form/widgets/attachFileWidgetCloud.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
  protractor.conf.ts
  scripts/app-config-replace.js
  scripts/travis/e2e/process-services-cloud-e2e.sh
Labels: PR: reviewed-approved

#5260 [AAE-207] support aps 1.x for upload reset
  demo-shell/src/app/components/files/files.component.ts
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/upload/components/upload-button.component.spec.ts
  lib/content-services/src/lib/upload/components/upload-button.component.ts
  lib/core/form/components/widgets/upload/upload.widget.spec.ts
  lib/core/form/components/widgets/upload/upload.widget.ts
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#5270 [ADF-5004] [CardViewTextItemComponent] Provide a way to have an icon for the clickable items
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.scss
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
  lib/process-services-cloud/src/lib/task/start-task/models/task-details-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-header/mocks/task-details-cloud.mock.ts
Labels: PR: unreviewed

#5275 [ADF-5013] Dropdown does not display the default value
  lib/process-services-cloud/src/lib/form/components/dropdown-cloud/dropdown-cloud.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/dropdown-cloud/dropdown-cloud.widget.ts
Labels: PR: unreviewed

#5280 [DOCS-5508] Add more info for kerberos
  docs/core/components/login.component.md
  docs/core/directives/logout.directive.md
  docs/user-guide/README.md
  docs/user-guide/kerberos.md
Labels: PR: reviewed-approved

#5279 Revert "[ADF-4861] Fix memory leak in Date widgets and Form Cloud Model"
  lib/core/form/components/widgets/core/form-field.model.ts
  lib/core/form/components/widgets/date-time/date-time.widget.spec.ts
  lib/core/form/components/widgets/date-time/date-time.widget.ts
  lib/core/form/components/widgets/date/date.widget.spec.ts
  lib/core/form/components/widgets/date/date.widget.ts
  lib/process-services-cloud/src/lib/form/components/date-cloud/date-cloud.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/date-cloud/date-cloud.widget.ts
Labels: PR: reviewed-approved

#5272 [ADF-4945] Draft of the release note for 3.6.0.
  docs/compatibility.md
  docs/release-notes/README.md
  docs/release-notes/RelNote360.md
Labels: PR: reviewed-approved, documentation

#5274 [ADF-4943] Update dependencies
  e2e/content-services/metadata/metadata-smoke-tests.e2e.ts
  e2e/process-services/process-instance-details.e2e.ts
  e2e/process-services/start-process-component.e2e.ts
  e2e/process-services/task-details.e2e.ts
  package-lock.json
  package.json
Labels: PR: unreviewed

#5277 [AAE-459] ProcessCloud - set process definition pre-filled value for one result only
  e2e/process-services-cloud/start-process-cloud.e2e.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
  lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
Labels: PR: reviewed-approved

#5283 bump 3.6.0
  demo-shell/package.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package.json
Labels: PR: unreviewed

#5278 [ADF-5015] DocumentList - favorites properties
  lib/content-services/src/lib/document-list/services/custom-resources.service.spec.ts
  lib/content-services/src/lib/document-list/services/custom-resources.service.ts
Labels: PR: reviewed-approved

#5069 [ADF-4823] [e2e] Displaying a file in a form does not work
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  lib/testing/src/lib/core/pages/form/widgets/attachFileWidgetCloud.ts
Labels: PR: reviewed-approved, e2e

#5288 Improve scripts after release
  .travis.yml
  lib/cli/scripts/npm-publish.ts
  scripts/travis/update/update-project.sh
Labels: PR: reviewed-approved

#5290 updated multiinstance-completion process definition
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#5285 [ADF-5027] Fix APS rendition
  lib/process-services/src/lib/attachment/process-attachment-list.component.ts
  lib/process-services/src/lib/attachment/task-attachment-list.component.spec.ts
  lib/process-services/src/lib/attachment/task-attachment-list.component.ts
Labels: PR: unreviewed

#5297 [ADF-5033] Improve publish script
  lib/cli/scripts/exec.ts
  lib/cli/scripts/npm-publish.ts
  lib/cli/scripts/update-commit-sha.ts
  scripts/travis/deploy/deploy.sh
  scripts/travis/deploy/pr-publish.sh
Labels: PR: reviewed-approved

#5298 updated the candidatebaseapp
  e2e/resources/activiti7/candidatebaseapp.zip
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: unreviewed
