Repository Alfresco/alfresco-ng2-components, pull requests merged in 2019-03, with the labels that each got.

#4337 [ADF-4015] Implementing edit task filter automated tests
  demo-shell/src/app/components/app-layout/cloud/cloud-settings.component.html
  e2e/actions/APS-cloud/tasks.ts
  e2e/pages/adf/configEditorPage.ts
  e2e/pages/adf/contentServicesPage.ts
  e2e/pages/adf/dataTablePage.ts
  e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts
  e2e/pages/adf/process-cloud/editTaskFilterCloudComponent.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/process-services-cloud/task-list-selection.e2e.ts
  e2e/process-services-cloud/taskListCloud.config.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
Labels: e2e

#4338 [ADF-4126] add roles filtering to people cloud component
  demo-shell/src/app/components/app-layout/cloud/people-groups-cloud-demo.component.html
  e2e/actions/APS-cloud/groupIdentity.ts
  e2e/actions/APS-cloud/identity.ts
  e2e/actions/APS-cloud/roles.ts
  e2e/core/user-info-component-cloud.e2e.ts
  e2e/pages/adf/demo-shell/process-services/peopleGroupCloudComponentPage.ts
  e2e/pages/adf/navigationBarPage.ts
  e2e/pages/adf/process-cloud/groupCloudComponent.ts
  e2e/pages/adf/process-cloud/peopleCloudComponent.ts
  e2e/pages/adf/process-cloud/startTasksCloudComponent.ts
  e2e/process-services-cloud/people-group-cloud-component.e2e.ts
  e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts
  e2e/util/constants.js
Labels: e2e

#4118 [ADF-3873] Implement automated tests for edit process filter cloud
  e2e/pages/adf/dataTablePage.ts
  e2e/pages/adf/process-cloud/editProcessFilterCloudComponent.ts
  e2e/process-services-cloud/edit-process-filters-component.e2e.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
Labels: Failing tests, e2e

#4379 [ADF-3497] - Facet intervals on search filter-expand-collapse
  e2e/pages/adf/searchFiltersPage.ts
  e2e/search/search-filters.e2e.ts
Labels: e2e

#4249 [ADF-3401] Search filters - fix facet update
  demo-shell/src/app.config.json
  demo-shell/src/app/components/search/search-result.component.html
  docs/content-services/search-chip-list.component.md
  docs/content-services/search-filter.component.md
  lib/content-services/i18n/en.json
  lib/content-services/search/components/search-chip-list/search-chip-list.component.html
  lib/content-services/search/components/search-chip-list/search-chip-list.component.ts
  lib/content-services/search/components/search-filter/models/search-filter-list.model.ts
  lib/content-services/search/components/search-filter/search-filter.component.html
  lib/content-services/search/components/search-filter/search-filter.component.spec.ts
  lib/content-services/search/components/search-filter/search-filter.component.ts
  lib/content-services/search/components/search-radio/search-radio.component.ts
  lib/content-services/search/search-configuration.interface.ts
  lib/core/app-config/schema.json
Labels: Investigation, waiting for review

#4286 [ADF-4048] PeopleCloudComponent - improve preselect input functionality
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/components/app-layout/cloud/people-groups-cloud-demo.component.html
  demo-shell/src/app/components/app-layout/cloud/people-groups-cloud-demo.component.ts
  docs/core/identity-user.service.md
  docs/process-services-cloud/people-cloud.component.md
  lib/core/userinfo/services/identity-user.service.ts
  lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
Labels: waiting for review

#4405 [ADF-4189] Improved document list prop description
  docs/content-services/document-list.component.md
  lib/content-services/document-list/components/document-list.component.ts
Labels: documentation

#4413 [ADF-4190] Fixed bad auto-generated URLs
  lib/tsconfig.json
  package.json
  tools/doc/doctool.config.json
  tools/doc/tools/typeLinker.js
  tools/doc/tools/typeLinker.ts
  tools/doc/yamlTemplates/template.ejs
Labels: documentation

#4395 [ADF-3989] appname duplicated after switching between saved filters
  e2e/pages/adf/process-cloud/editProcessFilterCloudComponent.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/processListCloud.config.ts
Labels: do not merge, e2e

#4408 [ADF-4192]Remove wait for spinner from editTaskFilterCloudComponent test
  e2e/pages/adf/process-cloud/editTaskFilterCloudComponent.ts
  e2e/process-services-cloud/edit-task-filters-component.e2e.ts
Labels: e2e

#4390 [ADF-4083] Parse 'escaped' empty spaced labels inside facetFields
  e2e/pages/adf/searchFiltersPage.ts
  e2e/search/search-filters.e2e.ts
Labels: e2e

#4425 [ADF-3401] Filter facets are not reseted when updating the search query
  .travis.yml
  e2e/pages/adf/searchFiltersPage.ts
  e2e/search/search-filters.e2e.ts
  scripts/affected-folder.sh
  scripts/affected-libs.sh
  scripts/smart-build.sh
Labels: e2e

#4412 [ADF-4197] Automation test for redirection after page reload
  demo-shell/src/app/components/logout/logout.component.html
  e2e/core/login/redirection.e2e.ts
  e2e/pages/adf/demo-shell/logoutPage.ts
Labels: e2e

#4250 [ADF-3977] EditProcessComponent - Be able to change the sort and actions
  demo-shell/src/app.config.json
  demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.html
  demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.ts
  docs/process-services-cloud/edit-process-filter-cloud.component.md
  e2e/pages/adf/process-cloud/editProcessFilterCloudComponent.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
Labels: Failing tests

#4433 [ADF-3735] SSO Login Error for login component
  e2e/core/login/login-component.e2e.ts
  e2e/core/login/login-sso/login-sso.e2e.ts
  lib/testing/src/lib/process-services-cloud/pages/login-sso.page.ts
Labels: e2e

#4432 [ADF-4228] Started basic doc for RTL support
  docs/roadmap.md
  docs/user-guide/README.md
  docs/user-guide/rtl-support.md
Labels: documentation

#4434 [ADF-4239] Updated and moved ADF introduction page
  INTRODUCTION.md
  docs/user-guide/adf-introduction.md
Labels: documentation

#4445 [ADF-4160] Fixed default props description for cont metadata card docs
  docs/README.md
  docs/content-services/components/content-metadata-card.component.md
  docs/content-services/components/content-metadata.component.md
  docs/versionIndex.md
Labels: documentation

#4448 [ADF-4249] Started doc review for 3.1
  docs/extensions/components/preview-extension.component.md
  docs/process-services-cloud/components/process-header-cloud.component.md
  docs/process-services-cloud/services/process-header-cloud.service.md
  lib/extensions/src/lib/components/viewer/preview-extension.component.ts
Labels: documentation

#4447 [ADF-588] Explicitly added task/process list model classes to docs
  docs/process-services/components/process-list.component.md
  docs/process-services/components/task-list.component.md
Labels: documentation

#4426 [AD-4222] e2e compilation fixes
  demo-shell/package.json
  e2e/actions/APS-cloud/apiservice.ts
  e2e/actions/APS-cloud/groupIdentity.ts
  e2e/actions/APS-cloud/identity.ts
  e2e/actions/APS-cloud/roles.ts
  e2e/actions/drop.actions.ts
  e2e/content-services/document-list/document-list-pagination.e2e.ts
  e2e/content-services/permissions-component.e2e.ts
  e2e/content-services/trashcan-pagination.e2e.ts
  e2e/content-services/upload/upload-dialog.ts
  e2e/content-services/upload/user-permission.e2e.ts
  e2e/models/ACS/fileModel.ts
  e2e/pages/adf/dataTableComponentPage.ts
  e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts
  e2e/pages/adf/dialog/editProcessFilterDialog.ts
  e2e/pages/adf/dialog/editTaskFilterDialog.ts
  e2e/pages/adf/dialog/shareDialog.ts
  e2e/pages/adf/dialog/uploadDialog.ts
  e2e/pages/adf/filePreviewPage.ts
  e2e/pages/adf/process-cloud/editProcessFilterCloudComponent.ts
  e2e/pages/adf/process-services/formFields.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/task-details-cloud.e2e.ts
  e2e/process-services/custom-tasks-filters.e2e.ts
  e2e/process-services/start-process-component.e2e.ts
  e2e/process-services/task-filters-component.e2e.ts
  e2e/process-services/task-filters-sorting.e2e.ts
  e2e/tsconfig.e2e.json
  e2e/util/util.ts
  lib/content-services/package.json
  lib/content-services/permission-manager/services/node-permission.service.ts
  lib/core/package.json
  lib/core/viewer/components/pdfViewerHost.component.scss
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/package.json
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
  lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
  lib/process-services/package.json
  lib/process-services/process-list/services/process.service.ts
  lib/process-services/task-list/services/tasklist.service.ts
  lib/testing/index.ts
  lib/testing/package.json
  package-lock.json
  package.json
  protractor.conf.js
  scripts/test-e2e-lib.sh
  tsconfig.json
Labels: e2e

#4389 fix responsiveness issues for empty screen
  demo-shell/src/app/components/trashcan/trashcan.component.html
  e2e/pages/adf/process-cloud/processListCloudComponent.ts
  e2e/pages/adf/process-cloud/taskListCloudComponent.ts
  e2e/pages/adf/process-services/processFiltersPage.ts
  e2e/pages/adf/process-services/processListPage.ts
  e2e/pages/adf/process-services/tasksListPage.ts
  lib/core/templates/empty-content/empty-content.component.html
  lib/core/templates/empty-content/empty-content.component.scss
Labels: needs rebase

#4449 [ADF-4106] Permissions Component automated
  e2e/content-services/permissions-component.e2e.ts
  e2e/content-services/permissions/permissions-component.e2e.ts
  e2e/content-services/permissions/site-permissions.e2e.ts
  e2e/pages/adf/content-services/documentListPage.ts
  e2e/pages/adf/metadataViewPage.ts
  e2e/pages/adf/permissionsPage.ts
  e2e/pages/adf/versionManagerPage.ts
  e2e/pages/adf/viewerPage.ts
Labels: e2e

#4358 [ADF-3677] Add highlight configuration to SearchQueryBuilder
  demo-shell/src/app.config.json
  demo-shell/src/app/components/files/files.component.html
  demo-shell/src/app/components/files/files.component.ts
  demo-shell/src/app/components/search/search-result.component.html
  docs/content-services/components/search-filter.component.md
  e2e/actions/ACS/node.actions.ts
  e2e/pages/adf/contentServicesPage.ts
  e2e/pages/adf/dataTableComponentPage.ts
  e2e/pages/adf/searchResultsPage.ts
  e2e/search/components/search-date-range.e2e.ts
  e2e/search/components/search-number-range.e2e.ts
  e2e/search/components/search-slider.e2e.ts
  e2e/search/components/search-sorting-picker.e2e.ts
  e2e/search/search-page-component.e2e.ts
  lib/content-services/search/search-configuration.interface.ts
  lib/content-services/search/search-query-builder.service.spec.ts
  lib/content-services/search/search-query-builder.service.ts
  lib/core/app-config/schema.json
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
Labels: Failing tests

#4407 [ADF-4149] - Moved the StartTasksCloudComponent/TaskDetailsCloudComponent pages
  e2e/pages/adf/demo-shell/process-services/taskDetailsPage.ts
  e2e/pages/adf/process-services/taskDetailsPage.ts
  e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts
  e2e/process-services-cloud/task-details-cloud.e2e.ts
  lib/testing/src/lib/process-services-cloud/pages/public-api.ts
  lib/testing/src/lib/process-services-cloud/pages/start-tasks-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-header-cloud-component.page.ts
Labels: e2e

#4420 [ADF-4124] DemoShell - Show task-list inside process-cloud-details
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/components/app-layout/cloud/process-details-cloud-demo.component.html
  demo-shell/src/app/components/app-layout/cloud/process-details-cloud-demo.component.scss
  demo-shell/src/app/components/app-layout/cloud/process-details-cloud-demo.component.ts
Labels: waiting for review

#4435 ADF-4201 About Component - added input params
  demo-shell/src/app/components/about/about.component.html
  demo-shell/src/app/components/about/about.component.ts
  docs/core/components/about.component.md
  lib/core/about/about.component.html
  lib/core/about/about.component.ts
Labels: change requested

#4400 [ADF-4045]Add Delete folder when infinite scrolling is enabled test.
  e2e/core/infinite-scrolling.e2e.ts
Labels: e2e

#4410 [ADF-4195] Automation tests for SSO login with implicitFlow false
  e2e/core/login/login-sso/login-sso.e2e.ts
  e2e/test.config.js
  lib/core/login/components/login.component.ts
  lib/testing/src/lib/process-services-cloud/pages/login-sso.page.ts
  protractor.conf.js
Labels: E2E Waiting For Dev Fix, Failing tests, e2e

#4421 [ADF-4099]Implement tests for The metadata group is always showed even though the properties are not there
  e2e/content-services/upload/uploader-component.e2e.ts
  e2e/content-services/upload/user-permission.e2e.ts
  e2e/core/card-view/aspect-oriented-config.e2e.ts
  e2e/core/user-info-component-cloud.e2e.ts
  e2e/pages/adf/dialog/uploadToggles.ts
Labels: e2e, waiting for review

#4461 [ADF-4252] Added doc link fixing tool
  docs/release-notes/RelNote161.md
  docs/release-notes/RelNote170.md
  docs/release-notes/RelNote180.md
  docs/release-notes/RelNote190.md
  docs/release-notes/RelNote200.md
  docs/release-notes/RelNote210.md
  docs/release-notes/RelNote220.md
  docs/release-notes/RelNote230.md
  docs/release-notes/RelNote240.md
  docs/release-notes/RelNote250.md
  docs/release-notes/RelNote260.md
  docs/release-notes/RelNote300.md
  tools/doc/doctool.config.json
  tools/doc/mqDefs.js
  tools/doc/mqDefs.ts
  tools/doc/tools/gqIndex.js
  tools/doc/tools/gqIndex.ts
  tools/doc/tools/linkFixer.js
  tools/doc/tools/linkFixer.ts
  tools/doc/tsconfig.json
Labels: documentation

#4470 [ADF-4249] Updates for doc review
  docs/README.md
  docs/content-services/components/content-node-selector-panel.component.md
  docs/content-services/components/document-list.component.md
  docs/content-services/components/search-filter.component.md
  docs/core/components/datatable.component.md
  docs/core/components/infinite-pagination.component.md
  docs/core/components/login.component.md
  docs/core/directives/logout.directive.md
  docs/core/services/thumbnail.service.md
  docs/process-services-cloud/components/edit-process-filter-cloud.component.md
  docs/process-services-cloud/components/edit-task-filter-cloud.component.md
  docs/process-services-cloud/components/group-cloud.component.md
  docs/process-services-cloud/components/people-cloud.component.md
  docs/process-services-cloud/components/process-list-cloud.component.md
  docs/process-services-cloud/components/start-process-cloud.component.md
  docs/process-services-cloud/components/start-task-cloud.component.md
  docs/process-services-cloud/components/task-header-cloud.component.md
  docs/process-services-cloud/components/task-list-cloud.component.md
  docs/process-services-cloud/services/task-header-cloud.service.md
  docs/process-services/components/people-search.component.md
  docs/process-services/components/people.component.md
  docs/process-services/services/process.service.md
  docs/release-notes/RelNote210.md
  docs/release-notes/RelNote230.md
  docs/release-notes/RelNote300.md
  docs/tutorials/README.md
  docs/tutorials/content-metadata-component.md
  docs/versionIndex.md
  tools/doc/reviewChecker.js
  tools/doc/reviewChecker.ts
Labels: documentation

#4428 [ADF-4226]Adding tests for infinite pagination.
  e2e/core/infinite-scrolling.e2e.ts
  e2e/pages/adf/configEditorPage.ts
  e2e/pages/adf/contentServicesPage.ts
  e2e/pages/adf/core/infinitePaginationPage.ts
Labels: e2e

#4466 [ADF-4265] Automation test for search highlight
  e2e/pages/adf/searchResultsPage.ts
  e2e/search/search-component.e2e.ts
  e2e/search/search.config.ts
Labels: e2e

#4481 [ADF-4146] Added 2.6 -> 3.0 upgrade guide
  docs/README.md
  docs/abn-tree.yml
  docs/upgrade-guide/upgrade26-30.md
Labels: documentation

#4492 [ADF-4249] Fixed issues with ToC and auto-linking tools
  docs/content-services/components/content-node-selector-panel.component.md
  docs/content-services/components/document-list.component.md
  docs/process-services-cloud/edit-process-filter-cloud.component.md
  tools/doc/SourceInfoClasses.js
  tools/doc/SourceInfoClasses.ts
  tools/doc/buildYamlSourceInfo.js
  tools/doc/tools/toc.js
  tools/doc/tools/tsInfo.js
  tools/doc/tools/tsInfo.ts
  tools/doc/yamlTemplates/template.ejs
  tools/doc/yamlTemplates/type.ejs
Labels: documentation

#4503 [ADF-4300] Clarified info about sort properties for Edit task/proc cl…
  docs/process-services-cloud/components/edit-process-filter-cloud.component.md
  docs/process-services-cloud/components/edit-task-filter-cloud.component.md
Labels: documentation

#4508 [ADF-4300] Updated sort properties lists with the non-filter properties
  docs/process-services-cloud/components/edit-process-filter-cloud.component.md
  docs/process-services-cloud/components/edit-task-filter-cloud.component.md
Labels: documentation

#4477 [ADF-4272] DocumentList - add copy content tooltip directive
  .travis.yml
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/components/datatable/datatable.component.html
  docs/core/directives/copy-clipboard.directive.md
  docs/license-info/README.md
  docs/license-info/license-info-v3.1.0.md
  docs/process-services-cloud/components/edit-process-filter-cloud.component.md
  docs/process-services-cloud/components/edit-task-filter-cloud.component.md
  e2e/pages/adf/navigationBarPage.ts
  e2e/pages/adf/process-cloud/editProcessFilterCloudComponent.ts
  e2e/process-services-cloud/edit-process-filters-component.e2e.ts
  e2e/process-services-cloud/edit-task-filters-component.e2e.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
  e2e/resources/aps2/candidateuserapp .zip
  e2e/resources/aps2/simple_app.zip
  e2e/test.config.js
  lib/core/data-column/data-column.component.ts
  lib/core/datatable/components/datatable/datatable-cell.component.ts
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.scss
  lib/core/datatable/data/data-column.model.ts
  lib/core/datatable/datatable.module.ts
  lib/core/datatable/directives/copy-clipboard.directive.spec.ts
  lib/core/datatable/directives/copy-clipboard.directive.ts
  lib/core/datatable/public-api.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/directives/claim-task.directive.spec.ts
  tools/doc/licenseList.js
Labels: change requested

#4519 Release notes review
  docs/release-notes/RelNote310.md
Labels: documentation

#4505 Release note and compatibility matrix for ADF 3.1
  docs/compatibility.md
  docs/release-notes/README.md
  docs/release-notes/RelNote310.md
  docs/versionIndex.md
Labels: documentation

#4524 [ADF-4249] Doc review updates
  docs/README.md
  docs/core/services/nodes-api.service.md
  docs/process-services-cloud/services/task-cloud.service.md
  docs/release-notes/RelNote300.md
  docs/release-notes/RelNote310.md
Labels: documentation

#4476 [ADF-4274] - Fix users filtering on single selection mode
  lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
Labels: waiting for review
