Repository Alfresco/alfresco-ng2-components, pull requests merged in 2019-10, with the labels that each got.

#5121 [ADF-4831] Document list - generic filetype text
  lib/core/i18n/en.json
Labels: Accessibility

#5130 [ADF-4939] Viewer - mime type icon alt text
  lib/core/viewer/components/viewer.component.html
Labels: Accessibility

#5127 [ADF-4938] Viewer - focus on trigger on close
  lib/core/viewer/components/viewer.component.html
  lib/core/viewer/viewer.module.ts
Labels: Accessibility

#5124 [ADF-4862] Upload - refocus dialog on files added
  lib/content-services/upload/components/file-uploading-dialog.component.spec.ts
  lib/content-services/upload/components/file-uploading-dialog.component.ts
Labels: Accessibility

#5120 [ADF-4934] Viewer - sidebar expanded/collapsed state exposed via ARIA
  lib/core/viewer/components/viewer.component.html
Labels: Accessibility

#5138 [ADF-4940] Viewer - actions aria labels
  lib/core/i18n/en.json
  lib/core/viewer/components/pdfViewer.component.html
  lib/core/viewer/components/viewer.component.html
Labels: Accessibility

#5126 [ADF-4937] Viewer - Drag and Drop is not operable with keyboard alone
  lib/core/viewer/components/imgViewer.component.html
  lib/core/viewer/components/imgViewer.component.scss
  lib/core/viewer/components/imgViewer.component.spec.ts
  lib/core/viewer/components/imgViewer.component.ts
Labels: Accessibility

#5147 [ADF-4952] Breadcrumb - focus style issues
  lib/content-services/breadcrumb/breadcrumb.component.scss
Labels: Accessibility

#5148 [ADF-4953] Uploader - confirmation dialog actions should return focus to the upload dialog
  lib/content-services/upload/components/file-uploading-dialog.component.html
  lib/content-services/upload/components/file-uploading-dialog.component.spec.ts
  lib/content-services/upload/components/file-uploading-dialog.component.ts
  lib/content-services/upload/upload.module.ts
Labels: Accessibility

#5155 [ADF-4955] Info Drawer - Visual heading text is not marked as a heading
  lib/content-services/content-metadata/components/content-metadata/content-metadata.component.html
  lib/core/comments/comments.component.html
  lib/core/info-drawer/info-drawer.component.html
Labels: Accessibility

#5162 [ADF-4963] Info Drawer - Focus indicator is not clearly visible
  lib/content-services/content-metadata/components/content-metadata/content-metadata.component.html
  lib/content-services/content-metadata/components/content-metadata/content-metadata.component.scss
Labels: Accessibility

#5161 [ADF-4958] [ADF-4959] Info Drawer - Buttons don't have role and accessible by keyboard alone
  e2e/core/card-view/card-view-component.e2e.ts
  e2e/pages/adf/cardViewComponentPage.ts
  e2e/pages/adf/metadataViewPage.ts
  e2e/pages/adf/process-services/taskDetailsPage.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.scss
Labels: Accessibility

#5143 [ADF-4948] Move the resources config in the process cloud lib - Part 2
  e2e/process-services-cloud/apps-section-cloud.e2e.ts
  e2e/process-services-cloud/edit-process-filters-component.e2e.ts
  e2e/process-services-cloud/edit-task-filters-component.e2e.ts
  e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts
  e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/process-filter-results.e2e.ts
  e2e/process-services-cloud/process-filters-cloud.e2e.ts
  e2e/process-services-cloud/process-header-cloud.e2e.ts
  e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts
  e2e/process-services-cloud/process-list-cloud-component.e2e.ts
  e2e/process-services-cloud/process-list-selection-cloud.e2e.ts
  e2e/process-services-cloud/start-process-cloud.e2e.ts
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts
  e2e/process-services-cloud/start-task/start-task-group-cloud.e2e.ts
  e2e/process-services-cloud/task-filters-cloud.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  e2e/process-services-cloud/task-header-cloud.e2e.ts
  e2e/process-services-cloud/task-list-cloud-action-menu.e2e.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/process-services-cloud/task-list-selection.e2e.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
  e2e/resources/activiti7/simpleapp.zip
  e2e/util/resources.js
  lib/cli/scripts/init-aae-env.ts
  lib/cli/tsconfig.json
  lib/process-services-cloud/src/public-api.ts
  lib/testing/src/lib/core/models/user.model.ts
  lib/testing/src/lib/core/utils/browser-visibility.ts
  lib/testing/src/lib/core/utils/file-browser.util.ts
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
  protractor.conf.ts
  scripts/check-env/check-activiti-env.js
  scripts/check-env/delete-all-apps.js
  scripts/test-e2e-lib.sh
  scripts/travis/e2e/process-services-cloud-e2e.sh
Labels: do not merge

#5150 [ADF-4949] Add SUSPENDED state to the edit task filter
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
Labels: change requested

#5158 [ADF-4956] Header - Focus indicator is not clearly visible
  lib/core/layout/components/header/header.component.scss
Labels: Accessibility, Missing CLA

#5167 [ADF-4964] Add enter and escape events for updating card view properties
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
Labels: PR: reviewed-approved

#5176 [DW-1491] Process instance start date incorrectly displayed
  lib/process-services/src/lib/process-list/components/process-list.component.ts
  lib/process-services/src/lib/task-list/components/task-list.component.ts
Labels: PR: reviewed-approved

#5173 Added isChecked method to verify the status of checkbox widget
  lib/testing/src/lib/core/pages/form/widgets/checkboxWidget.ts
Labels: PR: reviewed-approved

#5177 Adding new process, forms and decision tables for e2e tests on decisiontable mappings
  e2e/resources/activiti7/simpleapp.zip
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: reviewed-approved

#5182 [AAE-174] Show radio box in text box when read only
  lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.html
  lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.spec.ts
Labels: PR: reviewed-approved

#5186 [ADF-4975] Info Drawer - Main Edit button should have an aria-label
  lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.html
Labels: Accessibility, PR: reviewed-approved, PR: unreviewed

#5178 [ADF-4972] CLONE - Header - sidenav menu button aria-label not translatable
  lib/core/i18n/en.json
  lib/core/layout/components/header/header.component.html
Labels: PR: unreviewed

#5179 [ADF-4973] CLONE - Header - sidenav menu button expanded/collapsed state not exposed via ARIA
  demo-shell/src/app/components/app-layout/app-layout.component.html
  lib/core/layout/components/header/header.component.html
  lib/core/layout/components/header/header.component.spec.ts
  lib/core/layout/components/header/header.component.ts
Labels: PR: reviewed-approved

#5190 [ADF-4893] added test for the visible flag
  e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts
  e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts
  e2e/process-services-cloud/task-list-cloud-action-menu.e2e.ts
  lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
Labels: PR: reviewed-approved

#5188 Added the process and form required to test terminate end event
  e2e/resources/activiti7/simpleapp.zip
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: reviewed-approved

#5184 [AAE-520] order apps by name when retrieve from the server
  lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts
  lib/testing/src/lib/core/actions/identity/applications.service.ts
Labels: PR: unreviewed

#5170 [ADF-4966] Keep table headers - visually hidden when showHeader false
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/i18n/en.json
  lib/core/datatable/components/datatable/datatable.component.html
  lib/testing/src/lib/core/pages/data-table-component.page.ts
Labels: Accessibility, PR: reviewed-approved

#5195 [ADF-4976] Fix cloud ps e2e errors
  e2e/pages/adf/process-services/processListPage.ts
  e2e/pages/adf/process-services/processServiceTabBarPage.ts
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  e2e/process-services/empty-process-list-component.e2e.ts
  lib/testing/src/lib/core/utils/browser-actions.ts
  lib/testing/src/lib/form-cloud/actions/form-cloud.service.ts
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: reviewed-approved

#5160 [ADF-4957] Use Replace JS instead of sed to run e2e
  package.json
  scripts/app-config-replace.js
  scripts/test-e2e-lib.sh
  scripts/travis/e2e/insights-e2e.sh
  scripts/travis/e2e/process-services-cloud-e2e.sh
  scripts/travis/e2e/process-services-e2e.sh
  scripts/travis/e2e/search-e2e.sh
Labels: PR: reviewed-approved

#5196 added methods to view file, assert on File title in the viewer and cl…
  e2e/content-services/comments/comment-component.e2e.ts
  e2e/content-services/document-list/document-list-component.e2e.ts
  e2e/content-services/metadata/aspect-oriented-config.e2e.ts
  e2e/content-services/metadata/metadata-permissions.e2e.ts
  e2e/content-services/metadata/metadata-properties.e2e.ts
  e2e/content-services/metadata/metadata-smoke-tests.e2e.ts
  e2e/content-services/permissions/permissions-component.e2e.ts
  e2e/content-services/permissions/site-permissions.e2e.ts
  e2e/content-services/share-file/share-file.e2e.ts
  e2e/content-services/sso/sso-download-directive-component.e2e.ts
  e2e/core/pagination-empty-current-page.e2e.ts
  e2e/core/viewer/file-extensions/viewer-archive.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-excel.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-image.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-powerpoint.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-text.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-word.component.e2e.ts
  e2e/core/viewer/info-drawer.component.e2e.ts
  e2e/core/viewer/viewer-content-services-component.e2e.ts
  e2e/core/viewer/viewer-custom-toolbar-info-drawer.e2e.ts
  e2e/core/viewer/viewer-extension.e2e.ts
  e2e/core/viewer/viewer-properties.e2e.ts
  e2e/core/viewer/viewer-share-content.ts
  e2e/process-services/attach-file-widget.e2e.ts
  e2e/process-services/process-attachmentList-actionMenu.e2e.ts
  e2e/process-services/task-attachmentList-actionMenu.e2e.ts
  e2e/search/search-component.e2e.ts
  lib/testing/src/lib/core/pages/form/widgets/attachFileWidgetCloud.ts
  lib/testing/src/lib/core/pages/public-api.ts
  lib/testing/src/lib/core/pages/viewerPage.ts
Labels: PR: reviewed-approved

#5191 [ADF-4968 ] [TaskHeaderCloudComponent] Allow Assignee property to be clickable if the task in CREATED, ASSIGNED, SUSPENDED states
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
Labels: PR: reviewed-approved

#5092 [ADF-4936] Auth guard redirect fix
  demo-shell/src/app/app.routes.ts
  docs/core/services/auth-guard-ecm.service.md
  lib/core/services/auth-guard-base.ts
  lib/core/services/auth-guard-bpm.service.spec.ts
  lib/core/services/auth-guard-bpm.service.ts
  lib/core/services/auth-guard-ecm.service.spec.ts
  lib/core/services/auth-guard-ecm.service.ts
  lib/core/services/auth-guard.service.spec.ts
  lib/core/services/auth-guard.service.ts
Labels: PR: reviewed-approved

#5198 [ADF-2990] Datatable - row navigation
  e2e/pages/adf/demo-shell/dataTablePage.ts
  e2e/pages/adf/process-services/processFiltersPage.ts
  e2e/pages/adf/process-services/taskDetailsPage.ts
  e2e/pages/adf/process-services/tasksPage.ts
  e2e/pages/adf/trashcanPage.ts
  lib/content-services/src/lib/directives/node-lock.directive.spec.ts
  lib/content-services/src/lib/directives/node-lock.directive.ts
  lib/core/datatable/components/datatable/datatable-row.component.spec.ts
  lib/core/datatable/components/datatable/datatable-row.component.ts
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.scss
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/core/datatable/components/datatable/filesize-cell.component.ts
  lib/core/datatable/datatable.module.ts
  lib/core/datatable/public-api.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
Labels: Accessibility, PR: reviewed-approved, PR: unreviewed

#5193 [AAE-534] Core - add search cloud component
  docs/core/components/search-cloud.component.md
  lib/core/core.module.ts
  lib/core/index.ts
  lib/core/models/search-cloud.model.ts
  lib/core/search-cloud/components/search-text-cloud/search-text-cloud.component.html
  lib/core/search-cloud/components/search-text-cloud/search-text-cloud.component.spec.ts
  lib/core/search-cloud/components/search-text-cloud/search-text-cloud.component.ts
  lib/core/search-cloud/index.ts
  lib/core/search-cloud/public-api.ts
  lib/core/search-cloud/search-cloud.component.scss
  lib/core/search-cloud/search-cloud.component.spec.ts
  lib/core/search-cloud/search-cloud.component.ts
  lib/core/search-cloud/search-cloud.module.ts
  lib/core/services/search-cloud.service.ts
Labels: PR: reviewed-approved

#5043 [ADF-4849] [APM-1226] - Automate boolean and number visibility conditions
  e2e/pages/adf/demo-shell/process-services/processCloudDemoPage.ts
  e2e/pages/adf/process-services/startProcessPage.ts
  e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
  lib/testing/src/lib/core/pages/form/formFields.ts
  lib/testing/src/lib/process-services-cloud/pages/start-tasks-cloud-component.page.ts
Labels: PR: reviewed-approved

#5204 [no-issue] fix log when config is not set
  lib/testing/src/lib/core/utils/logger.ts
Labels: PR: reviewed-approved

#5175 [DW-1560] switch to ACTIVITI roles
  e2e/process-services-cloud/apps-section-cloud.e2e.ts
  e2e/process-services-cloud/edit-process-filters-component.e2e.ts
  e2e/process-services-cloud/edit-task-filters-component.e2e.ts
  e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts
  e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
  e2e/process-services-cloud/people-group-cloud-component.e2e.ts
  e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/process-filter-results.e2e.ts
  e2e/process-services-cloud/process-filters-cloud.e2e.ts
  e2e/process-services-cloud/process-header-cloud.e2e.ts
  e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts
  e2e/process-services-cloud/process-list-cloud-component.e2e.ts
  e2e/process-services-cloud/process-list-selection-cloud.e2e.ts
  e2e/process-services-cloud/start-process-cloud.e2e.ts
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts
  e2e/process-services-cloud/start-task/start-task-group-cloud.e2e.ts
  e2e/process-services-cloud/task-filters-cloud.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  e2e/process-services-cloud/task-header-cloud.e2e.ts
  e2e/process-services-cloud/task-list-cloud-action-menu.e2e.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/process-services-cloud/task-list-selection.e2e.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
  lib/testing/src/lib/core/actions/identity/identity.service.ts
  lib/testing/src/lib/core/actions/identity/roles.service.ts
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: reviewed-approved

#5203 [AAE-726] Add new return await rule
  e2e/actions/APS/apps.actions.ts
  e2e/actions/APS/appsRuntime.actions.ts
  e2e/actions/APS/models.actions.ts
  e2e/actions/drop.actions.ts
  e2e/pages/adf/content-services/treeViewPage.ts
  e2e/pages/adf/contentServicesPage.ts
  e2e/pages/adf/demo-shell/dataTablePage.ts
  e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts
  e2e/pages/adf/dialog/createLibraryDialog.ts
  e2e/pages/adf/dialog/folderDialog.ts
  e2e/pages/adf/dialog/searchDialog.ts
  e2e/pages/adf/dialog/shareDialog.ts
  e2e/pages/adf/dialog/uploadDialog.ts
  e2e/pages/adf/iconsPage.ts
  e2e/pages/adf/metadataViewPage.ts
  e2e/pages/adf/permissionsPage.ts
  e2e/pages/adf/process-services/filtersPage.ts
  e2e/pages/adf/process-services/processFiltersPage.ts
  e2e/pages/adf/process-services/taskDetailsPage.ts
  e2e/pages/adf/process-services/tasksPage.ts
  e2e/pages/adf/searchFiltersPage.ts
  e2e/pages/adf/searchResultsPage.ts
  e2e/pages/adf/tagPage.ts
  e2e/pages/adf/trashcanPage.ts
  e2e/pages/adf/versionManagerPage.ts
  lib/core/services/log.service.spec.ts
  lib/core/viewer/services/view-util.service.ts
  lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
  lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
  lib/testing/src/lib/content-services/pages/document-list.page.ts
  lib/testing/src/lib/content-services/pages/search/date-range-filter.page.ts
  lib/testing/src/lib/content-services/pages/search/number-range-filter.page.ts
  lib/testing/src/lib/content-services/pages/search/search-slider.page.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  lib/testing/src/lib/core/pages/form/widgets/amountWidget.ts
  lib/testing/src/lib/core/pages/login.page.ts
  lib/testing/src/lib/core/pages/settings.page.ts
  lib/testing/src/lib/core/pages/viewerPage.ts
  lib/testing/src/lib/core/utils/browser-actions.ts
  lib/testing/src/lib/material/pages/date-picker.page.ts
  lib/testing/src/lib/process-services-cloud/app/app-list-cloud.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
  lib/testing/src/lib/process-services/pages/form-fields.page.ts
  package.json
  tslint.json
Labels: PR: reviewed-approved
