Repository Alfresco/alfresco-ng2-components, pull requests merged in 2019-08, with the labels that each got.

#4963 [ADF-4776] Release note in draft
  docs/.DS_Store
  docs/compatibility.md
  docs/release-notes/README.md
  docs/release-notes/RelNote340.md
Labels: documentation

#4986 [ADF-4497] ARIA role must be appropriate for the Breadcrumb element
  lib/content-services/breadcrumb/breadcrumb.component.html
  lib/content-services/i18n/en.json
Labels: Accessibility

#4988 [ADF-4802] Login accessibility
  lib/core/i18n/en.json
  lib/core/login/components/login.component.html
  lib/core/login/components/login.component.spec.ts
  lib/core/login/components/login.component.ts
  lib/testing/src/lib/core/pages/login.page.ts
Labels: Accessibility

#4997 [ADF-4830] DocumentList - sort state is not being announced
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/i18n/en.json
Labels: Accessibility

#4993 [ADF-4799][ADF-4801] Automation tests for CardView clear date field and selectbox None option
  e2e/core/card-view/card-view-component.e2e.ts
  e2e/pages/adf/cardViewComponentPage.ts
Labels: e2e

#4999 [ADF-4832] DocumentList - Selected state is not being conveyed to screen reader user
  lib/core/datatable/components/datatable/datatable.component.html
Labels: Accessibility

#5001 [ADF-4809] Automation for non-editable task details when completed
  e2e/pages/adf/process-services/taskDetailsPage.ts
  e2e/process-services/task-details.e2e.ts
Labels: e2e

#5011 [ADF-4839] Document List - column name link accessibility
  lib/content-services/document-list/components/library-name-column/library-name-column.component.ts
  lib/content-services/document-list/components/name-column/name-column.component.ts
  lib/content-services/i18n/en.json
Labels: Accessibility

#4835 [ADF-4544] Automation for form button refresh after action
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  lib/testing/src/lib/process-services-cloud/pages/task-form-cloud-component.page.ts
Labels: e2e

#5015 [ADF-4845] Uploader - Expanded/collapsed state not exposed
  lib/content-services/upload/components/file-uploading-dialog.component.html
Labels: Accessibility

#5014 [ADF-4843] - Automate more manual test cases for visibility chaining …
  e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
  e2e/resources/forms/checkbox-visibility-condition.ts
  e2e/resources/forms/multiple-visibility-conditions.ts
Labels: e2e

#5013 [ADF-4840] Fixing failing tests on process-services-cloud
  e2e/process-services-cloud/edit-process-filters-component.e2e.ts
  e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts
  e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts
  e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts
  e2e/process-services-cloud/start-task/start-task-group-cloud.e2e.ts
Labels: e2e
