Repository Alfresco/alfresco-ng2-components, pull requests merged in 2019-09, with the labels that each got.

#5040 [ADF-4855] Upload dialog - Buttons must have discernible text
  lib/content-services/i18n/en.json
  lib/content-services/upload/components/file-uploading-dialog.component.html
Labels: Accessibility

#5045 [ADF-4862] Upload dialog - reading order
  lib/content-services/i18n/en.json
  lib/content-services/upload/components/file-uploading-dialog.component.html
  lib/content-services/upload/components/file-uploading-dialog.component.spec.ts
  lib/content-services/upload/components/file-uploading-dialog.component.ts
Labels: Accessibility

#5051 [ADF-4865] Upload Dialog - row actions not accessible by keyboard alone
  cspell.json
  docs/README.md
  docs/content-services/directives/toggle-icon.directive.md
  docs/versionIndex.md
  e2e/content-services/upload/cancel-upload.e2e.ts
  e2e/content-services/version/version-actions.e2e.ts
  lib/content-services/i18n/en.json
  lib/content-services/upload/components/file-uploading-dialog.component.html
  lib/content-services/upload/components/file-uploading-list-row.component.html
  lib/content-services/upload/components/file-uploading-list-row.component.scss
  lib/content-services/upload/directives/toggle-icon.directive.spec.ts
  lib/content-services/upload/directives/toggle-icon.directive.ts
  lib/content-services/upload/public-api.ts
  lib/content-services/upload/upload.module.ts
Labels: Accessibility

#4998 [ADF-4831] DocumentList - filetype alternative text is not meaningful
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/i18n/en.json
  lib/testing/src/lib/core/pages/data-table-component.page.ts
Labels: Accessibility

#5053 [ADF-4863] Use npx instead of absolute adf-cli path
  scripts/release/release.sh
  scripts/travis/build/build.sh
  scripts/travis/release/release.sh
Labels: change requested

#5079 [ADF-4892] DocumentList - set appropriate column aria-sort state
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/core/i18n/en.json
Labels: Accessibility

#5105 [ADF-4831] Document list - generic filetype text
  lib/core/i18n/en.json
Labels: Accessibility

#5093 [ADF-4873] Release note in draft.
  docs/compatibility.md
  docs/release-notes/README.md
  docs/release-notes/RelNote350.md
Labels: documentation
