Repository Alfresco/alfresco-ng2-components, pull requests merged in 2019-01, with the labels that each got.

#4134 [ADF-3745] Updated properties and doc comments
  docs/README.md
  docs/content-services/document-actions.service.md
  docs/content-services/search-query-builder.service.md
  docs/core/content.widget.md
  docs/core/icon.component.md
  docs/core/translation.service.md
  docs/process-services/process.service.md
  docs/process-services/start-task.component.md
  lib/content-services/document-list/services/custom-resources.service.ts
  lib/content-services/document-list/services/document-actions.service.ts
  lib/content-services/search/search-query-builder.service.ts
  lib/core/form/components/widgets/content/content.widget.ts
  lib/core/icon/icon.component.ts
  lib/core/services/translation.service.ts
  lib/process-services/process-list/services/process.service.ts
  lib/process-services/task-list/components/start-task.component.ts
  package.json
  tools/doc/doctool.config.json
Labels: documentation

#4141 [ADF-3745] Fixed broken links in docs
  docs/core/form-field.component.md
  docs/core/form-rendering.service.md
  docs/core/form.component.md
  docs/insights/README.md
  docs/insights/widget.component.md
  docs/release-notes/RelNote161.md
  docs/release-notes/RelNote170.md
  docs/release-notes/RelNote180.md
  docs/release-notes/RelNote190.md
  docs/release-notes/RelNote200.md
  docs/release-notes/RelNote210.md
  docs/release-notes/RelNote220.md
  docs/release-notes/RelNote240.md
  docs/release-notes/RelNote250.md
  docs/release-notes/RelNote260.md
  docs/user-guide/app-extensions.md
  docs/user-guide/transclusion.md
Labels: documentation

#4131 [ADF-3898] Fixed incorrect code sample
  docs/process-services/apps-list.component.md
Labels: documentation, needs rebase

#4111 [ADF-3780]Implement task list cloud component tests
  e2e/actions/APS-cloud/tasks.ts
  e2e/pages/adf/dataTablePage.ts
  e2e/pages/adf/demo-shell/processCloudDemoPage.ts
  e2e/pages/adf/demo-shell/tasksCloudDemoPage.ts
  e2e/pages/adf/process-cloud/editTaskFilterCloudComponent.ts
  e2e/pages/adf/process-cloud/taskListCloudComponent.ts
  e2e/process-services-cloud/process-filters-cloud.e2e.ts
  e2e/process-services-cloud/task-filters-cloud.e2e.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
Labels: e2e

#4160 [ADF-3745] Reviewed new Group cloud component docs
  docs/process-services-cloud/group-cloud.component.md
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
Labels: documentation

#4165 [ADF-3745] Doc review updates
  docs/content-services/rating.component.md
  docs/process-services/apps-list.component.md
  docs/process-services/create-process-attachment.component.md
  docs/process-services/create-task-attachment.component.md
  docs/process-services/people-list.component.md
  docs/process-services/process-attachment-list.component.md
  docs/process-services/process-audit.directive.md
  docs/process-services/process-instance-header.component.md
  docs/process-services/select-apps-dialog.component.md
  docs/process-services/start-process.component.md
  docs/process-services/start-task.component.md
  docs/process-services/task-attachment-list.component.md
  docs/process-services/task-audit.directive.md
  docs/process-services/task-header.component.md
Labels: documentation

#4149 [ADF-3900] Implement tests for Universal Icons component
  e2e/core/icons-component.e2e.ts
  e2e/pages/adf/iconsPage.ts
  e2e/pages/adf/navigationBarPage.ts
Labels: Failing tests, e2e

#4081 [ ADF-3821] Start standalone task e2e tests
  e2e/pages/adf/demo-shell/tasksCloudDemoPage.ts
  e2e/pages/adf/process-cloud/startTasksCloudComponent.ts
  e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts
Labels: e2e

#4040 [ADF-3430] E2E for using fields to filter Process List
  demo-shell/src/app/components/process-list-demo/process-list-demo.component.html
  docs/core/format-space.pipe.md
  e2e/actions/APS/apps.actions.ts
  e2e/actions/APS/appsRuntime.actions.ts
  e2e/core/user-info-component.e2e.ts
  e2e/insights/analytics-component.e2e.ts
  e2e/models/APS/FormDefinitionModel.js
  e2e/pages/adf/demo-shell/process-services/processCloudDemoPage.ts
  e2e/pages/adf/demo-shell/process-services/processListDemoPage.ts
  e2e/pages/adf/demo-shell/process-services/taskFiltersDemoPage.ts
  e2e/pages/adf/demo-shell/process-services/taskListDemoPage.ts
  e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts
  e2e/pages/adf/dialog/userInfoDialog.ts
  e2e/pages/adf/navigationBarPage.ts
  e2e/pages/adf/process-services/analyticsPage.ts
  e2e/pages/adf/settingsPage.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services/custom-tasks-filters.e2e.ts
  e2e/process-services/processList-component.e2e.ts
  lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.scss
Labels: Failing tests, e2e

#4090 [ADF-3823] Add tests for create site dialog
  demo-shell/src/app/components/files/files.component.html
  e2e/content-services/directives/create-library-directive.e2e.ts
  e2e/pages/adf/contentServicesPage.ts
  e2e/pages/adf/demo-shell/customSourcesPage.ts
  e2e/pages/adf/dialog/contentListPage.ts
  e2e/pages/adf/dialog/createLibraryDialog.ts
  e2e/pages/adf/navigationBarPage.ts
  lib/content-services/dialogs/library/library.dialog.html
Labels: e2e

#4155 [ADF-3860] - Document List - change datatable to be recognized as a table
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.spec.ts
Labels: Accessibility, change requested, waiting for review

#4166 [ADF-3913] Added roadmap page
  docs/README.md
  docs/abn-tree.yml
  docs/roadmap.md
Labels: documentation

#4115 [ADF-3808] Add automated tests for TaskFilters cloud - default filter
  e2e/pages/adf/demo-shell/process-services/processCloudDemoPage.ts
  e2e/pages/adf/demo-shell/process-services/taskFiltersDemoPage.ts
  e2e/pages/adf/demo-shell/process-services/taskListDemoPage.ts
  e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/process-filters-cloud.e2e.ts
  e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts
  e2e/process-services-cloud/task-filters-cloud.e2e.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
Labels: Failing tests, e2e

#4170 [ADF-3921] Reviewed docs where deprecated content was removed
  docs/content-services/content-node-selector.component.md
  docs/content-services/document-list.component.md
  docs/content-services/document-list.service.md
  docs/content-services/file-uploading-dialog.component.md
  docs/content-services/search-control.component.md
  docs/content-services/search-filter.component.md
  docs/content-services/search-filter.service.md
  docs/content-services/search-widget.interface.md
  docs/content-services/search.component.md
  docs/content-services/upload-button.component.md
  docs/content-services/upload-drag-area.component.md
  docs/content-services/version-list.component.md
  tools/doc/yamlTemplates/template.ejs
Labels: documentation

#4172 [ADF-3921] Reviewed docs where deprecated stuff was removed
  docs/core/form.component.md
  docs/core/host-settings.component.md
  docs/core/infinite-pagination.component.md
  docs/core/login.component.md
  docs/core/node-restore.directive.md
  docs/core/upload.service.md
  docs/core/user-preferences.service.md
  docs/core/viewer.component.md
  docs/process-services/process-list.component.md
Labels: change requested, documentation

#4176 [ADF-3909] Updated references to JS-API in docs
  docs/README.md
  docs/content-services/README.md
  docs/content-services/add-permission.component.md
  docs/content-services/breadcrumb.component.md
  docs/content-services/content-action.component.md
  docs/content-services/content-metadata-card.component.md
  docs/content-services/content-metadata.component.md
  docs/content-services/content-node-dialog.service.md
  docs/content-services/content-node-selector-panel.component.md
  docs/content-services/content-node-selector.component.md
  docs/content-services/document-library.model.md
  docs/content-services/document-list.component.md
  docs/content-services/document-list.service.md
  docs/content-services/dropdown-breadcrumb.component.md
  docs/content-services/folder-create.directive.md
  docs/content-services/folder-edit.directive.md
  docs/content-services/inherited-button.directive.md
  docs/content-services/node-lock.directive.md
  docs/content-services/node-permission-dialog.service.md
  docs/content-services/node-permission.service.md
  docs/content-services/upload-version-button.component.md
  docs/content-services/version-manager.component.md
  docs/core/README.md
  docs/core/alfresco-api.service.md
  docs/core/deleted-nodes-api.service.md
  docs/core/node-permission.directive.md
  docs/core/nodes-api.service.md
  docs/core/process-content.service.md
  docs/core/search-configuration.interface.md
  docs/process-services/README.md
  docs/process-services/start-process.component.md
  docs/process-services/tasklist.service.md
  docs/tutorials/working-with-nodes-api-service.md
  tools/doc/doctool.config.json
Labels: documentation

#4178 [ADF-3745] Added docs for the new pipes
  docs/README.md
  docs/content-services/README.md
  docs/content-services/file-upload-error.pipe.md
  docs/content-services/file-uploading-dialog.component.md
  docs/content-services/upload-button.component.md
  docs/content-services/upload-drag-area.component.md
  docs/process-services-cloud/README.md
  docs/process-services-cloud/group-initial.pipe.md
  tools/doc/doctool.config.json
Labels: documentation

#4183 [ADF-3745] Added docs for proc cloud services
  docs/README.md
  docs/process-services-cloud/README.md
  docs/process-services-cloud/apps-process-cloud.service.md
  docs/process-services-cloud/people-cloud.component.md
  docs/process-services-cloud/task-header-cloud.component.md
  docs/process-services-cloud/task-header-cloud.service.md
  lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts
  lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-header/services/task-header-cloud.service.ts
  tools/doc/doctool.config.json
Labels: documentation

#4184 [ADF-3745] Built initial version index for 3.0
  docs/versionIndex.md
Labels: documentation

#4171 [ADF-3862] - Document List - Add accesibility tags for images and doc…
  lib/core/viewer/components/imgViewer.component.html
  lib/core/viewer/components/pdfViewer.component.html
Labels: Accessibility

#4193 [ADF-3745] Added Confirm dialog docs
  docs/README.md
  docs/content-services/README.md
  docs/content-services/confirm.dialog.md
  docs/docassets/images/ConfirmDialog.png
  tools/doc/doctool.config.json
Labels: documentation

#4133 [ADF-3884] Added start process e2e tests
  e2e/pages/adf/demo-shell/process-services/processCloudDemoPage.ts
  e2e/pages/adf/process-services/startProcessPage.ts
  e2e/process-services-cloud/start-process-cloud.e2e.ts
Labels: e2e

#4201 [ADF-3940] Fix Parent Name property in Task Header Cloud component
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
Labels: Tests passing

#4190 [ADF-3938] support for XMLHttpRequest.withCredentials flag
  demo-shell/src/app.config.json
  docs/core/app-config.service.md
  lib/core/app-config/app-config.service.ts
  lib/core/app-config/schema.json
  lib/core/services/alfresco-api.service.ts
  lib/core/viewer/components/pdfViewer.component.ts
Labels: Failing tests

#4207 [ADF-3905] - Upload counter displays "Uploading 0 / 1"
  e2e/content-services/upload/uploader-component.e2e.ts
Labels: e2e

#4194 [ADF-3943] Remove non-working filters from Edit Task Filter Cloud
  demo-shell/resources/i18n/en.json
  demo-shell/src/app.config.json
  demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.html
  demo-shell/src/app/components/config-editor/config-editor.component.html
  demo-shell/src/app/components/config-editor/config-editor.component.ts
  docs/process-services-cloud/edit-task-filter-cloud.component.md
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
Labels: Tests passing

#4206 [ADF-3951] Added automated tests for failed uploading tooltips
  e2e/content-services/upload/uploader-component.e2e.ts
  e2e/content-services/upload/user-permission.e2e.ts
  e2e/pages/adf/contentServicesPage.ts
  e2e/pages/adf/dialog/uploadDialog.ts
Labels: waiting for review

#4227 [ADF-3967] Automate Settings Component
  e2e/core/settings-component.e2e.ts
  e2e/pages/adf/loginPage.ts
  e2e/pages/adf/navigationBarPage.ts
  e2e/pages/adf/settingsPage.ts
Labels: e2e

#4199 [ADF-3810] Should rearrange toolbar actions in Viewer
  e2e/core/viewer/viewer-content-services-component.e2e.ts
  e2e/pages/adf/viewerPage.ts
Labels: e2e, needs rebase
