Repository Alfresco/alfresco-ng2-components, pull requests merged in 2019-05, with the labels that each got.

#4682 [ADF-4429] Process List Cloud - Remove the pagination parameters.
  docs/process-services-cloud/components/process-list-cloud.component.md
Labels: documentation

#4679 Compatibility matrix for ADF 3.2.
  docs/compatibility.md
  docs/versionIndex.md
Labels: documentation

#4617 Release Note for ADF 3.2 (initial version)
  docs/release-notes/README.md
  docs/release-notes/RelNote320.md
Labels: documentation

#4681 Activiti 7 and ADF tutorial review.
  docs/tutorials/activiti-7-and-adf.md
Labels: documentation

#4718 Better descriptions into the release notes
  docs/release-notes/RelNote320.md
Labels: documentation

#4717 Minor changes to documentation for ADF 3.2.1.
  docs/compatibility.md
  docs/versionIndex.md
Labels: documentation

#4739 [ADF-4578] DemoShell - language menu shows 2 Arabic entries
  demo-shell/src/app.config.json
Labels: bug

#4784 [ADF-4609]Logging the response in case of error.
  e2e/process-services-cloud/process-filters-cloud.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  e2e/process-services-cloud/task-header-cloud.e2e.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
  lib/testing/src/lib/core/actions/identity/identity.service.ts
  lib/testing/src/lib/core/actions/identity/tasks.service.ts
Labels: e2e

#4694 [ADF-4477]Add a new check related to endDate
  e2e/process-services-cloud/edit-task-filters-component.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  e2e/process-services-cloud/task-header-cloud.e2e.ts
Labels: e2e

#4789 Update of upgrade paths.
  docs/upgrade-guide/upgrade26-30.md
  docs/upgrade-guide/upgrade30-31.md
  docs/upgrade-guide/upgrade31-32.md
Labels: documentation

#4776 [ADF-4461] FormCloud - fix date validations
  lib/core/form/components/form-base.component.ts
  lib/core/form/components/widgets/date/date.widget.spec.ts
  lib/core/form/components/widgets/date/date.widget.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
Labels: change requested

#4793 [ADF-4613] Fixing tag-component.e2e.ts
  e2e/content-services/tag-component.e2e.ts
  e2e/pages/adf/tagPage.ts
Labels: e2e
