Repository Alfresco/alfresco-ng2-components, pull requests merged in 2019-12, with the labels that each got.

#5300 Implement smart runner in ADF
  .travis.yml
  e2e/protractor/fail-fast.js
  package-lock.json
  package.json
  protractor.conf.ts
  protractor.excludes.json
Labels: PR: reviewed-approved

#5303 Updated Simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: reviewed-approved

#5304 Update .travis.yml
  .travis.yml
Labels: PR: reviewed-approved

#5305 [AAE-1080]Remove datatable tests related to demo-shell only.
  e2e/core/datatable/data-table-component.e2e.ts
Labels: PR: reviewed-approved

#5302 [ADF-5022] added automation for Display Value Widget
  e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
  e2e/resources/forms/displayValue-visibilityConditions.ts
  lib/testing/src/lib/core/pages/form/widgets/displayValueWidget.ts
Labels: PR: reviewed-approved

#5264 [ADF-5006] Datatable - custom cell template focus not working
  demo-shell/src/app/components/files/files.component.html
  docs/core/components/data-column.component.md
  docs/core/interfaces/datatable-adapter.interface.md
  lib/core/data-column/data-column.component.ts
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/core/datatable/data/data-column.model.ts
  lib/core/datatable/data/object-datacolumn.model.ts
Labels: Accessibility, PR: reviewed-approved, PR: unreviewed

#5307 update the resources file to have the connectors
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: unreviewed

#5266 [ADF-5007] Comments - textarea Escape event cannot be canceled
  lib/core/comments/comments.component.html
  lib/core/comments/comments.component.spec.ts
  lib/core/comments/comments.component.ts
Labels: Failing tests, PR: reviewed-approved, PR: unreviewed

#5308 [AAE-991] ADF - Add CI build failure notification #801
  .travis.yml
Labels: PR: unreviewed

#5306 [ADF-5034] [GroupCloudComponent] Provide a way to make pre-selected groups read-only.
  docs/process-services-cloud/components/group-cloud.component.md
  lib/core/mock/identity-group.service.mock.ts
  lib/core/mock/identity-user.service.mock.ts
  lib/core/models/identity-group.model.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/group/pipe/group-initial.pipe.spec.ts
Labels: PR: reviewed-approved, do not merge, enhancement

#5310 [AAE-840]Add methods for form outcome buttons and info for simpleapp process a…
  lib/testing/src/lib/process-services-cloud/pages/task-form-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: unreviewed

#5311 Ability to clean the env passing apps name
  lib/cli/scripts/init-aae-env.ts
  lib/cli/scripts/kubectl-clean-app.ts
Labels: PR: reviewed-approved

#5313 Fix angular configuration demo shell
  angular.json
Labels: PR: reviewed-approved

#5289 [ADF-5031][PeopleCloudComponent] [PeopleCloudComponent] Provide a way to make selected items read-only (not remove)
  docs/process-services-cloud/components/people-cloud.component.md
  lib/core/models/identity-user.model.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.html
  lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts
Labels: PR: reviewed-approved

#5315 [AAE-840]Add method to start a process knowing the name and the processDefinition
  lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
Labels: PR: reviewed-approved

#5318 [AAE-1169] Use default ecmHost in case of startFormEvent
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
Labels: PR: reviewed-approved

#5321 [AAE-840]Fixed the process definition name
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: unreviewed

#5322 [AAE-1152] Making sure the people and group widget is working fine as part of form
  lib/core/form/components/widgets/core/form-field.model.ts
  lib/core/services/identity-group.service.spec.ts
  lib/core/services/identity-group.service.ts
  lib/core/services/identity-user.service.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.ts
  lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
Labels: PR: unreviewed

#5324 Fix readonly Fix add remove
  lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.ts
  lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
Labels: PR: unreviewed

#5325 Making sure the people does not change the original obj reference
  lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.ts
  lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
Labels: PR: reviewed-approved

#5327 updated simpleapp - calledprocess - usertask with a due date
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#5328 AAE - Fix the attach content from alfresco and local
  demo-shell/src/app/components/cloud/start-process-cloud-demo.component.html
  demo-shell/src/app/components/cloud/start-process-cloud-demo.component.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
Labels: PR: reviewed-approved

#5330 skip temporary the code
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
Labels: PR: unreviewed

#5334 [AAE-1180]Fix datatable tests
  lib/testing/src/lib/core/pages/notification-history.page.ts
  protractor.excludes.json
Labels: PR: reviewed-approved

#5335 [AAE-1178] ADF - deleted un-necessary steps
  e2e/pages/adf/cardViewComponentPage.ts
  e2e/pages/adf/demo-shell/process-services/peopleGroupCloudComponentPage.ts
  e2e/pages/adf/demo-shell/process-services/processListDemoPage.ts
  e2e/pages/adf/demo-shell/process-services/taskListDemoPage.ts
  e2e/pages/adf/dialog/folderDialog.ts
  e2e/pages/adf/dialog/shareDialog.ts
  e2e/pages/adf/dialog/uploadToggles.ts
  e2e/pages/adf/metadataViewPage.ts
  e2e/pages/adf/notificationPage.ts
  e2e/pages/adf/process-services/analyticsPage.ts
  e2e/pages/adf/process-services/attachFormPage.ts
  e2e/pages/adf/process-services/dialog/createChecklistDialog.ts
  e2e/pages/adf/process-services/startProcessPage.ts
  e2e/pages/adf/tagPage.ts
  lib/testing/src/lib/content-services/pages/search/date-range-filter.page.ts
  lib/testing/src/lib/core/pages/form/widgets/dropdownWidget.ts
  lib/testing/src/lib/core/pages/settings.page.ts
  lib/testing/src/lib/core/pages/viewerPage.ts
  lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/start-tasks-cloud-component.page.ts
Labels: PR: reviewed-approved

#5233 [AAE-641]Add tests for assignee not able to release process task
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  e2e/resources/activiti7/candidatebaseapp.zip
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: reviewed-approved

#5332 [AAE-1200] AAE - FE - Provide a way to define icon on CardViewArrayItemComponent
  demo-shell/src/app/components/card-view/card-view.component.ts
  docs/core/components/card-view.component.md
  lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.html
  lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.scss
  lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.spec.ts
  lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.ts
  lib/core/card-view/models/card-view-arrayitem.model.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
Labels: PR: reviewed-approved

#5337 [ADF-4996] Update working-with-nodes-api-service.md
  docs/tutorials/working-with-nodes-api-service.md
Labels: PR: unreviewed

#5336 [AAE-1237] remove excluded test
  e2e/protractor.excludes.json
  protractor.conf.ts
  protractor.excludes.json
Labels: PR: reviewed-approved, do not merge

#5339 [AAE-1238] Re-enable appVersion check
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
Labels: PR: reviewed-approved

#5296 [AAE-1022] Fix components to work on Community environments
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/components/cloud/community/community-cloud.component.ts
  demo-shell/src/app/components/cloud/community/community-filters.component.html
  demo-shell/src/app/components/cloud/community/community-filters.component.ts
  demo-shell/src/app/components/cloud/community/community-process-details-cloud.component.html
  demo-shell/src/app/components/cloud/community/community-process-details-cloud.component.ts
  demo-shell/src/app/components/cloud/community/community-processes-cloud.component.html
  demo-shell/src/app/components/cloud/community/community-processes-cloud.component.ts
  demo-shell/src/app/components/cloud/community/community-start-process-cloud.component.html
  demo-shell/src/app/components/cloud/community/community-start-task-cloud.component.html
  demo-shell/src/app/components/cloud/community/community-task-cloud.component.html
  demo-shell/src/app/components/cloud/community/community-task-details-cloud.component.html
  demo-shell/src/app/components/cloud/community/community-task-details-cloud.component.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/components/form-definition-selector-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-header/services/process-header-cloud.service.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
  lib/process-services-cloud/src/lib/task/directives/claim-task.directive.ts
  lib/process-services-cloud/src/lib/task/directives/complete-task.directive.ts
  lib/process-services-cloud/src/lib/task/directives/unclaim-task.directive.ts
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
  lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.html
  lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
Labels: PR: reviewed-approved

#5342 [ADF-5001] Process Audit File Log APS1 section wrong instruction for complete processes
  demo-shell/src/app/components/process-service/process-attachments.component.html
  demo-shell/src/app/components/process-service/task-attachments.component.html
Labels: PR: reviewed-approved

#5343 fix userinfo e2e
  e2e/core/user-info-component.e2e.ts
  lib/testing/src/lib/core/pages/user-info.page.ts
Labels: PR: unreviewed

#5341 [AAE-1260] Add changes detection for ProcessHeaderCloud when a process gets cancelled
  docs/process-services-cloud/services/process-cloud.service.md
  lib/process-services-cloud/src/lib/process/directives/delete-process.directive.spec.ts
  lib/process-services-cloud/src/lib/process/directives/delete-process.directive.ts
  lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-header/process-header-cloud.module.ts
  lib/process-services-cloud/src/lib/process/process-header/public-api.ts
  lib/process-services-cloud/src/lib/process/process-header/services/process-header-cloud.service.ts
  lib/process-services-cloud/src/lib/process/services/process-cloud.service.ts
Labels: PR: reviewed-approved

#5338 [ADF-4980] Fix app prefix
  docs/core/services/storage.service.md
  e2e/core/login/login-component.e2e.ts
  lib/core/services/alfresco-api.service.ts
  lib/core/services/auth-guard.service.ts
  lib/core/services/authentication.service.ts
  lib/core/services/jwt-helper.service.ts
  lib/process-services/src/lib/task-list/components/no-task-detail-template.directive.spec.ts
Labels: PR: reviewed-approved

#5344 [ADF-5055] update pdfjs
  lib/core/viewer/components/pdfViewer.component.scss
  lib/core/viewer/components/pdfViewer.component.spec.ts
  lib/core/viewer/components/pdfViewer.component.ts
  lib/core/viewer/components/pdfViewerHost.component.scss
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#5347 [ADF-5043] Default adf-cloud-task-list and adf-cloud-process-list doe…
  lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-preset.model.ts
  lib/process-services-cloud/src/lib/task/task-list/models/task-preset-cloud.model.ts
Labels: PR: reviewed-approved
