Repository Alfresco/alfresco-ng2-components, pull requests merged in 2020-01, with the labels that each got.

#5346 Update package.json dependency pdfjs version
  lib/core/package.json
Labels: PR: reviewed-approved

#5312 [ADF-5009] close all the dialogs after false canActivate event
  lib/core/services/auth-guard-base.ts
  lib/core/services/auth-guard-bpm.service.spec.ts
  lib/core/services/auth-guard-bpm.service.ts
  lib/core/services/auth-guard-ecm.service.spec.ts
  lib/core/services/auth-guard-ecm.service.ts
  lib/core/services/auth-guard-sso-role.service.spec.ts
  lib/core/services/auth-guard-sso-role.service.ts
  lib/core/services/auth-guard.service.ts
Labels: PR: reviewed-approved

#5350 [AAE-1344] [FE] - Removed all pre-selected users on removing of single pre-selected user.
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
Labels: PR: reviewed-approved

#5353 [AAE-1351] [GroupCloudComponent] Validate pre-selected groups
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.html
  demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
Labels: PR: reviewed-approved

#5356 Update ADF packages version 3.7.0-beta6
  package.json
Labels: PR: unreviewed

#5358 Fix for LOC-186 - mistranslation in French
  lib/core/i18n/fr.json
Labels: PR: reviewed-approved

#5357 [ADF-5025] add mp3 support mediatype viewer/thumbnail blob
  lib/core/services/thumbnail.service.ts
  lib/core/viewer/components/viewer.component.ts
Labels: PR: reviewed-approved

#5361 [ADF-5009] close dialog in the redirect
  lib/core/services/auth-guard-base.ts
Labels: PR: reviewed-approved

#5362 new js-api should be deployed if build is ok
  .travis.yml
Labels: PR: reviewed-approved

#5354 [AAE-1336] add version on completeTaskForm
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
Labels: PR: reviewed-approved

#5359 [AAE-1361]Add complete task of a process method
  lib/testing/src/lib/core/actions/identity/tasks.service.ts
  lib/testing/src/lib/core/pages/card-view/card-view-text-item.page.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
Labels: PR: reviewed-approved

#5345 [AAE-1174] select first user info when open the first time
  e2e/core/user-info-component.e2e.ts
  lib/core/userinfo/components/user-info.component.html
  lib/core/userinfo/components/user-info.component.ts
  lib/testing/src/lib/core/pages/user-info.page.ts
Labels: PR: reviewed-approved

#5367 unify rancher update strategy
  .travis.yml
  scripts/rancher-update.sh
  scripts/travis/deploy/deploy-pr.sh
  scripts/travis/deploy/deploy.sh
  scripts/travis/deploy/get-docker-image-tag-name.sh
  scripts/travis/deploy/move-dist-folder.js
  scripts/travis/deploy/pr-publish.sh
  scripts/travis/deploy/rancher-pr-deploy.js
  scripts/travis/release/release-npm.sh
Labels: PR: reviewed-approved

#5365 [ADF-5060] fix readonly attach file scenarios
  lib/core/i18n/en.json
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/upload-cloud.widget.html
Labels: PR: reviewed-approved

#5368 [ADF-5062] Content Node Selector - show inputs based on configuration
  docs/content-services/components/content-node-selector.component.md
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
Labels: PR: reviewed-approved

#5370 [AAE-838]Add a method to wait until datatable contains less then a specific nr…
  lib/testing/src/lib/core/pages/pagination.page.ts
Labels: PR: reviewed-approved

#5366 Adding amount row editor for dynamic table
  lib/core/form/components/widgets/dynamic-table/editors/amount/amount.editor.html
  lib/core/form/components/widgets/dynamic-table/editors/amount/amount.editor.scss
  lib/core/form/components/widgets/dynamic-table/editors/amount/amount.editor.spec.ts
  lib/core/form/components/widgets/dynamic-table/editors/amount/amount.editor.ts
  lib/core/form/components/widgets/dynamic-table/editors/row.editor.html
  lib/core/form/components/widgets/index.ts
Labels: PR: reviewed-approved

#5340 [AAE-1235] - fix task completion with datetime form widget
  lib/core/form/components/widgets/core/form-field.model.ts
Labels: PR: reviewed-approved

#5376 JWT error fix
  lib/core/services/auth-guard.service.ts
Labels: PR: reviewed-approved

#5355 [AAE-1372] Refactor People/Group cloud component
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.html
  demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.ts
  docs/process-services-cloud/components/group-cloud.component.md
  docs/process-services-cloud/components/people-cloud.component.md
  e2e/process-services-cloud/people-group-cloud-component.e2e.ts
  e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts
  e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.scss
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
  lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
Labels: PR: unreviewed

#5372 [AAE-1152] added e2e tests for People and Group of people - CloudWidgets
  e2e/process-services-cloud/form-field/date-widget.e2e.ts
  e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts
  e2e/process-services-cloud/form-field/people-group-of-people.e2e.ts
  e2e/process-services-cloud/form-field/visibility-condition-tabs.e2e.ts
  e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component-tab.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  e2e/resources/forms/people-group-formwidget-json.ts
  lib/testing/src/lib/core/pages/form/formPage.ts
  lib/testing/src/lib/process-services-cloud/pages/form/public-api.ts
  lib/testing/src/lib/process-services-cloud/pages/form/widget/process-cloud-widget.page.ts
  lib/testing/src/lib/process-services-cloud/pages/form/widget/public-api.ts
  lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/public-api.ts
Labels: PR: reviewed-approved

#5380 [AAE-1501] EditProcessCloud/EditTaskCloud - Ability to fetch applications by role
  lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
Labels: PR: reviewed-approved

#5385 [AAE-1152] fixed tests using single mode displayed as a tag too
  e2e/process-services-cloud/form-field/people-group-of-people.e2e.ts
Labels: PR: reviewed-approved

#5388 [ACA-2609] removes calendar popup on focus
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
Labels: PR: reviewed-approved

#5389 [AAE-936] injecting external settings for amount widget
  lib/core/form/components/widgets/amount/amount.widget.spec.ts
  lib/core/form/components/widgets/amount/amount.widget.ts
Labels: PR: reviewed-approved

#5383 remove update PR env
  .travis.yml
Labels: PR: reviewed-approved

#5393 Fix wrong import
  lib/content-services/src/lib/document-list/data/share-datatable-adapter.ts
Labels: PR: reviewed-approved

#5392 GERMAN: Fix for https://github.com/Alfresco/alfresco-ng2-components/i…
  lib/content-services/src/lib/i18n/de.json
Labels: PR: reviewed-approved

#5394 Adding process variables to an existent process definition
  e2e/resources/activiti7/candidatebaseapp.zip
Labels: PR: reviewed-approved

#5386 [ACA-2475] keyboard trap
  lib/core/form/components/widgets/date-time/date-time.widget.html
  lib/core/form/components/widgets/date/date.widget.html
Labels: PR: reviewed-approved

#5395 Remove flaky test
  e2e/content-services/tag-component.e2e.ts
Labels: PR: reviewed-approved

#5400 Fix deploy pipeline development
  scripts/travis/deploy/deploy.sh
  scripts/travis/deploy/rancher-update.sh
Labels: PR: unreviewed

#5401 fix flaky share test
  e2e/content-services/share-file/share-file.e2e.ts
  lib/content-services/src/lib/search/components/search-control.component.ts
Labels: PR: unreviewed

#5363 [ACA-2755] [SSO] Unable to access a private url after a public url was loaded in the same browser tab
  lib/core/login/components/login.component.spec.ts
  lib/core/services/auth-guard-ecm.service.spec.ts
  lib/core/services/auth-guard-ecm.service.ts
  lib/core/services/authentication.service.ts
Labels: PR: reviewed-approved

#5397 [ACA-2605] - fix: add aria-label to toggle button
  lib/core/i18n/en.json
  lib/core/sorting-picker/sorting-picker.component.html
Labels: PR: reviewed-approved

#5387 [ACA-2474] adding instructions to the calendar for use
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.html
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.scss
  lib/core/i18n/en.json
Labels: PR: reviewed-approved

#5402 [ACA-2567] - sortable
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/core/i18n/en.json
Labels: PR: unreviewed

#5403 [ACA-2561] Datatable- Hiding Decorative Icons in table
  lib/core/datatable/components/datatable/datatable.component.html
Labels: PR: unreviewed

#5405 [ADF-5064] Info Drawer - More and Less Information buttons are reversed
  e2e/content-services/metadata/metadata-smoke-tests.e2e.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.html
  lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.spec.ts
Labels: PR: reviewed-approved, bug

#5406 [ADF-5048] Review UI strings
  demo-shell/resources/i18n/en.json
  lib/core/i18n/en.json
  lib/process-services-cloud/src/lib/i18n/en.json
Labels: PR: reviewed-approved

#5404 fix release project cli and dependency
  lib/cli/package.json
  lib/cli/scripts/init-aae-env.ts
Labels: PR: reviewed-approved

#5408 [AAE-1564][DW-1654] improved datatable schema
  lib/core/datatable/components/datatable/datatable.component.ts
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#5413 [AAE-1602][AAE-1594] Fix duplicated users issue when validation enabl…
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
Labels: PR: unreviewed

#5414 [AAE-1562] Fix should not be able to search already selected user
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
Labels: PR: reviewed-approved

#5409 vulnerability and license doc
  docs/license-info/README.md
  docs/license-info/license-info-3.0.0.md
  docs/license-info/license-info-3.1.0.md
  docs/license-info/license-info-3.2.0.md
  docs/license-info/license-info-3.3.0.md
  docs/license-info/license-info-3.4.0.md
  docs/license-info/license-info-3.5.0.md
  docs/license-info/license-info-3.6.0.md
  docs/license-info/license-info-3.7.0.md
  docs/vulnerability/audit-info-3.7.0.md
Labels: PR: unreviewed

#5412 Draft of ADF 3.7 release note
  docs/release-notes/RelNote370.md
Labels: PR: reviewed-approved

#5407 Review documentation 3.7.0
  docs/README.md
  docs/content-services/components/content-node-selector-panel.component.md
  docs/core/components/data-column.component.md
  docs/core/components/login.component.md
  docs/core/dialogs/edit-json.dialog.md
  docs/core/directives/logout.directive.md
  docs/core/interfaces/card-view-item.interface.md
  docs/core/services/authentication.service.md
  docs/core/services/identity-group.service.md
  docs/core/services/identity-user.service.md
  docs/core/services/jwt-helper.service.md
  docs/core/services/page-title.service.md
  docs/core/services/storage.service.md
  docs/process-services-cloud/components/edit-process-filter-cloud.component.md
  docs/process-services-cloud/components/edit-task-filter-cloud.component.md
  docs/process-services-cloud/components/form-cloud.component.md
  docs/process-services-cloud/components/form-definition-selector-cloud.component.md
  docs/process-services-cloud/components/group-cloud.component.md
  docs/process-services-cloud/components/people-cloud.component.md
  docs/process-services-cloud/components/process-filters-cloud.component.md
  docs/process-services-cloud/components/process-header-cloud.component.md
  docs/process-services-cloud/components/process-list-cloud.component.md
  docs/process-services-cloud/components/start-process-cloud.component.md
  docs/process-services-cloud/components/start-task-cloud.component.md
  docs/process-services-cloud/components/task-filters-cloud.component.md
  docs/process-services-cloud/components/task-header-cloud.component.md
  docs/process-services-cloud/directives/claim-task.directive.md
  docs/process-services-cloud/directives/complete-task.directive.md
  docs/process-services-cloud/directives/unclaim-task.directive.md
  docs/process-services-cloud/services/apps-process-cloud.service.md
  docs/process-services-cloud/services/process-cloud.service.md
  docs/process-services/components/select-apps-dialog.component.md
  docs/versionIndex.md
  lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
Labels: PR: unreviewed

#5415 [AAE-1591] fix destroy worker and internalize css pdfjs
  .stylelintignore
  lib/core/viewer/components/pdfViewer.component.ts
  lib/core/viewer/components/pdfViewerHost.component.scss
Labels: PR: reviewed-approved

#5418 [AAE-1532] Fix typing fast in search with roles gives wrong results i…
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
Labels: PR: reviewed-approved

#5417 [AAE-1594] Fix partial group name of a valid group should not be vali…
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
Labels: PR: reviewed-approved

#5421 [AAE-1558] Update apps to use new structure
  e2e/resources/activiti7/candidatebaseapp.zip
  e2e/resources/activiti7/simpleapp.zip
  e2e/resources/activiti7/subprocessapp.zip
Labels: PR: unreviewed

#5422 change user for cloud test
  scripts/travis/e2e/process-services-cloud-e2e.sh
Labels: PR: unreviewed

#5420 [AAE-1615] fix preselect user check
  lib/content-services/src/lib/site-dropdown/sites-dropdown.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
Labels: PR: reviewed-approved

#5427 trigger child build after merge like JS-API
  .travis.yml
  scripts/travis/update/trigger-travis-children.sh
Labels: PR: reviewed-approved

#5431 [ADF-5067] extra unit tests for breadcrumb
  lib/content-services/src/lib/breadcrumb/breadcrumb.component.spec.ts
Labels: PR: reviewed-approved

#5436 allow admins to view cloud demos
  demo-shell/src/app/app.routes.ts
Labels: PR: reviewed-approved

#5437 Revert "allow admins to view cloud demos"
  demo-shell/src/app/app.routes.ts
Labels: PR: unreviewed
