Repository Alfresco/alfresco-ng2-components, pull requests merged in 2020-08, with the labels that each got.

#5939 [AAE-3177] Fix tests that are using attach file widget
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  e2e/protractor.excludes.json
  e2e/resources/activiti7/candidatebaseapp.zip
  lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
  lib/testing/src/lib/process-services-cloud/pages/form/widget/attach-file-widget-cloud.page.ts
Labels: PR: unreviewed

#5943 [AAE-3208] Remove local file widget param for attach-file-cloud-widget
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
Labels: PR: partially-approved

#5938 [ACA-3727] - Process Filters add possibility to hide process filter name
  docs/process-services-cloud/components/edit-process-filter-cloud.component.md
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
Labels: PR: unreviewed

#5932 [ACA-3542] - added sorting for filters
  demo-shell/src/app.config.json
  demo-shell/src/app/components/files/files.component.html
  demo-shell/src/app/components/files/files.component.ts
  demo-shell/src/app/components/files/filtered-search.component.html
  demo-shell/src/app/components/files/filtered-search.component.ts
  e2e/core/pages/dialog/folder-dialog.page.ts
  e2e/core/viewer/file-extensions/viewer-archive.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-excel.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-image.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-powerpoint.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-text.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-word.component.e2e.ts
  e2e/tsconfig.e2e.json
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/document-list/components/document-list.component.html
  lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/content-services/src/lib/search/base-query-builder.service.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
  lib/content-services/src/lib/search/search-header-query-builder.service.ts
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/testing/src/lib/process-services-cloud/pages/task-filters-cloud-component.page.ts
Labels: PR: unreviewed

#5940 [ACA-3728] Remove the filter name from the custom filter header
  docs/process-services-cloud/components/edit-task-filter-cloud.component.md
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
Labels: PR: partially-approved

#5945 [ADF-5210] Order by folder on default
  lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
Labels: PR: partially-approved

#5947 [AAE-3203] Add tooltip to Form Cloud Widgets
  lib/core/form/components/widgets/amount/amount.widget.html
  lib/core/form/components/widgets/checkbox/checkbox.widget.html
  lib/core/form/components/widgets/core/form-field.model.ts
  lib/core/form/components/widgets/date-time/date-time.widget.html
  lib/core/form/components/widgets/display-text/display-text.widget.html
  lib/core/form/components/widgets/hyperlink/hyperlink.widget.html
  lib/core/form/components/widgets/multiline-text/multiline-text.widget.html
  lib/core/form/components/widgets/number/number.widget.html
  lib/core/form/components/widgets/people/people.widget.html
  lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.html
  lib/core/form/components/widgets/text/text.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/upload-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
Labels: PR: partially-approved

#5946 [AAE-3200] Attach button of content node selector becomes enabled when selecting a folder
  e2e/protractor.excludes.json
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
Labels: PR: partially-approved

#5928 [ACA-3678] Disable Save and Delete Button for Default Filters
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
Labels: PR: partially-approved

#5944 [AAE-3209]Fix e2e about attach file from local
  e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  e2e/protractor.excludes.json
  lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
  lib/testing/src/lib/core/pages/info-drawer.page.ts
  lib/testing/src/lib/process-services-cloud/pages/form/widget/attach-file-widget-cloud.page.ts
Labels: PR: partially-approved

#5949 Not sortable id and lock in demo shell
  demo-shell/src/app/components/files/files.component.html
Labels: PR: unreviewed

#5937 [ACA-3804] Add All option in process definition name filter dropdown
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
Labels: PR: partially-approved

#5951 [#5950] Fix branch name.
  CONTRIBUTING.md
Labels: PR: partially-approved

#5948 [AAE-3214]Improve process-task-attach-content-file-cloud.e2e.ts
  e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
  e2e/protractor.excludes.json
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: reviewed-approved

#5936 [ACA-3762] Task/Process filters not working with updatePagination
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
Labels: PR: partially-approved

#5957 [#5956] Property enclose in []
  docs/process-services/components/process-instance-details.component.md
Labels: PR: partially-approved

#5955 [AAE-3219] Start process button is disabled when page is first displayed
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
Labels: PR: partially-approved

#5954 [AAE-2718] List available roles for a group
  lib/core/mock/identity-group.service.mock.ts
  lib/core/services/identity-group.service.spec.ts
  lib/core/services/identity-group.service.ts
  lib/core/services/identity-user.service.ts
  lib/core/services/oauth2.service.ts
Labels: PR: unreviewed

#5959 excluded C286516
  e2e/protractor.excludes.json
Labels: PR: partially-approved

#5952 Modify candidatebaseapp - input and output forms that are using attac…
  e2e/protractor.excludes.json
  e2e/resources/activiti7/candidatebaseapp.zip
Labels: PR: partially-approved

#5960 Readded column key as key parameter
  demo-shell/src/app/components/files/filtered-search.component.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.ts
Labels: PR: unreviewed

#5963 Fix process-task-attach-content-file-cloud.e2e.ts afterAll
  e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
Labels: PR: partially-approved

#5961 [ADF-5213] Metadata - select list filter
  demo-shell/src/app.config.json
  lib/core/app-config/schema.json
  lib/core/card-view/card-view.module.scss
  lib/core/card-view/card-view.module.ts
  lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.html
  lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.spec.ts
  lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.ts
  lib/core/card-view/components/card-view-selectitem/select-filter-input/select-filter-input.component.html
  lib/core/card-view/components/card-view-selectitem/select-filter-input/select-filter-input.component.scss
  lib/core/card-view/components/card-view-selectitem/select-filter-input/select-filter-input.component.spec.ts
  lib/core/card-view/components/card-view-selectitem/select-filter-input/select-filter-input.component.ts
  lib/core/card-view/components/card-view.components.ts
  lib/core/card-view/models/card-view-selectitem.model.ts
  lib/core/card-view/public-api.ts
  lib/core/i18n/en.json
Labels: PR: partially-approved

#5964 [AAE-296] Remove excluded test
  e2e/protractor.excludes.json
Labels: PR: unreviewed

#5903 [AAE-3084] Add retrieve metadata option in upload widget
  lib/core/form/components/widgets/core/form-field-metadata.ts
  lib/core/form/services/form.service.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
  lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
  lib/process-services-cloud/src/lib/i18n/en.json
Labels: PR: unreviewed

#5967 [ACA-3551] - Change icon for the view option
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
Labels: PR: partially-approved

#5965 [ADF-5213] Metadata - select list filter documentation
  docs/content-services/components/content-metadata-card.component.md
  docs/docassets/images/adf-search-select.png
Labels: PR: partially-approved

#5966 [ACA-3742] - update i18n error strings
  lib/core/i18n/en.json
Labels: PR: partially-approved

#5972 Update protractor.excludes.json
  e2e/protractor.excludes.json
Labels: PR: unreviewed

#5971 update datepicker
  license-info-4.0.0.md
  package-lock.json
  package.json
Labels: PR: partially-approved

#5974 [ADF-5159] fix visibility condition for label radio box
  lib/core/form/components/widgets/core/form-field.model.ts
  lib/core/form/services/widget-visibility-cloud.service.spec.ts
  lib/core/form/services/widget-visibility.service.spec.ts
  lib/core/form/services/widget-visibility.service.ts
Labels: PR: unreviewed

#5975 Fixed parent changing for search header
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
Labels: PR: partially-approved

#5978 Modify simpleapp and candidatesbaseapp
  e2e/resources/activiti7/candidatebaseapp.zip
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: partially-approved

#5888 use people api and new js api where possible
  lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
  lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
  lib/content-services/src/lib/document-list/services/custom-resources.service.spec.ts
  lib/content-services/src/lib/document-list/services/custom-resources.service.ts
  lib/core/services/ecm-user.service.spec.ts
  lib/core/services/ecm-user.service.ts
  lib/testing/src/lib/core/actions/identity/identity.service.ts
Labels: PR: unreviewed

#5962 [AAE-3204] 'Invalid destination folder path' displayed when clicking on attach file widget of type alfresco & local when destination folder is empty.
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
  lib/process-services-cloud/src/lib/form/models/form-cloud-representation.model.ts
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
Labels: PR: partially-approved

#5981 [ADF-5198] process header loaded event
  lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.ts
Labels: PR: partially-approved

#5982 [AAE-3258] Update simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#5979 [ADF-5165] [Regression] Fix Checkbok widget in completed tasks
  lib/core/form/components/widgets/core/form-field.model.spec.ts
  lib/core/form/components/widgets/core/form-field.model.ts
Labels: PR: partially-approved

#5976 [AAE-2984] fix save not modified Form with dropdown
  lib/core/form/components/widgets/core/form-field.model.ts
  lib/core/mock/form/form.component.mock.ts
  lib/core/pagination/pagination.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
  lib/process-services/src/lib/form/form.component.spec.ts
Labels: PR: unreviewed

#5984 [AAE-3204] Fix destinationFolder breadcrumb restriction not working
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
Labels: PR: unreviewed

#5985 [ADF-5165] - added involved user for task
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.ts
Labels: PR: unreviewed

#5987 update doc node selector and interface
  docs/content-services/components/content-node-selector.component.md
  lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
Labels: PR: partially-approved

#5865 [ACA-3603] Destination picker is not opening on My Files when clicking on Attach file widget
  lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
  lib/content-services/src/lib/site-dropdown/sites-dropdown.component.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog-component.interface.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.html
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.spec.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.ts
  lib/process-services/src/lib/content-widget/attach-file-widget.component.spec.ts
  lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
Labels: PR: partially-approved

#5990 [AAE-2378] Add tooltip to People and Group Cloud Widgets
  lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html
Labels: PR: partially-approved

#5988 allow styling cloud header from the outside
  lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.scss
  lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.ts
Labels: PR: unreviewed

#5991 [ACA-3839] Document List - clear filter called multiple times
  lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
Labels: PR: partially-approved

#5993 [ACA-3506] - Fixed refresh for filters on ADF
  lib/content-services/src/lib/search/components/search-widget-container/search-widget-container.component.ts
Labels: PR: partially-approved

#5992 Draft of the release note for ADF 4.0.0.
  docs/compatibility.md
  docs/release-notes/RelNote380.md
  docs/release-notes/RelNote390.md
  docs/release-notes/RelNote400.md
Labels: 4.0.0, PR: unreviewed, documentation

#6005 [ADF-5165][Form] Save button is not displayed for Involved task
  lib/process-services/src/lib/mock/task/task-details.mock.ts
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.html
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.spec.ts
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.ts
Labels: PR: partially-approved

#5999 [ADF-5218] Fix custom stencil usage on Start Process Form
  demo-shell/src/app/components/files/files.component.ts
  demo-shell/src/app/components/process-service/process-service.component.ts
  docs/user-guide/stencils.md
  lib/process-services/src/lib/form/start-form.component.ts
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.ts
Labels: PR: unreviewed

#6007 [ACA-3853] fix use of more recent pdf viewer versions
  lib/core/viewer/components/pdf-viewer-thumb.component.spec.ts
  lib/core/viewer/components/pdf-viewer-thumb.component.ts
  lib/core/viewer/components/pdf-viewer-thumbnails.component.spec.ts
  lib/core/viewer/components/pdf-viewer-thumbnails.component.ts
  package-lock.json
  package.json
Labels: PR: unreviewed

#6008 [ADF-5211] fix commonjs warnings
  angular.json
Labels: PR: unreviewed

#6009 [ACA-3854] fix error in preview
  lib/core/viewer/services/view-util.service.ts
Labels: PR: reviewed-approved

#5989 Execute test when change exclude file
  e2e/content-services/version/version-permissions.e2e.ts
  e2e/protractor.excludes.json
  lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  nx.json
Labels: PR: partially-approved

#6018 [ACA-3542] Fix Filter sorting initialization
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/components/files/files.component.ts
  demo-shell/src/app/components/files/filtered-search.component.ts
Labels: PR: partially-approved

#6020 Select box can use numbers as value in the card view
  lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.spec.ts
  lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.ts
  lib/core/card-view/interfaces/card-view-selectitem-properties.interface.ts
Labels: PR: reviewed-approved

#6019 drag and drop improvements (copy effect)
  lib/core/datatable/directives/drop-zone.directive.ts
  lib/core/directives/upload.directive.spec.ts
  lib/core/directives/upload.directive.ts
Labels: PR: unreviewed

#6025 less talkative caching
  scripts/ci/utils/artifact-to-s3.sh
Labels: PR: partially-approved

#6032 [ACA-3863] Add query-service call for E2E tests
  lib/testing/src/lib/core/actions/identity/query.service.ts
Labels: PR: partially-approved

#5983 New Service create - AuditService
  docs/content-services/services/audit.service.md
  lib/content-services/src/lib/audit/audit.service.spec.ts
  lib/content-services/src/lib/audit/audit.service.ts
Labels: PR: partially-approved

#6049 Revert "Bump scss-bundle from 2.3.2 to 3.1.2"
  package-lock.json
  package.json
Labels: PR: unreviewed

#6040 fix flex-layout version
  lib/content-services/package.json
  lib/process-services-cloud/package.json
Labels: PR: partially-approved

#6048 [ACA-3800]Add method to datatable PO for selecting row with CMD
  lib/testing/src/lib/core/pages/data-table/data-table-item.ts
Labels: PR: partially-approved

#6057 add missing group role APIs
  lib/core/services/identity-group.service.ts
Labels: PR: unreviewed

#6058 [ACA-3737] Process cloud properties review labels
  lib/process-services-cloud/src/lib/i18n/en.json
Labels: PR: partially-approved

#6024 [AAE-3273] Manage empty option in retrieve content metadata dropdowns
  lib/core/form/components/widgets/core/form.model.spec.ts
  lib/core/form/components/widgets/core/form.model.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
Labels: PR: partially-approved

#6065 Update upgrade39-40.md
  docs/upgrade-guide/upgrade39-40.md
Labels: PR: partially-approved

#6066 fix http method regression
  lib/core/services/oauth2.service.ts
Labels: PR: partially-approved

#6067 publish improvements
  lib/cli/scripts/npm-publish.ts
  package-lock.json
  package.json
  scripts/travis/build/build.sh
Labels: PR: partially-approved

#6075 fix production builds
  .travis.yml
  e2e/search/components/search-text.e2e.ts
  lib/core/form/components/widgets/text/text.widget.spec.ts
  lib/process-services/src/lib/people/components/people-search-field/people-search-field.component.spec.ts
  lib/testing/src/lib/content-services/pages/search/search-text.page.ts
  package-lock.json
  package.json
  scripts/build/build-content-services.sh
  scripts/build/build-core.sh
  scripts/build/build-extensions.sh
  scripts/build/build-insights.sh
  scripts/build/build-process-services-cloud.sh
  scripts/build/build-process-services.sh
  scripts/build/build-testing.sh
Labels: PR: unreviewed
