Repository Alfresco/alfresco-ng2-components, pull requests merged in 2020-10, with the labels that each got.

#6134 [AAE-3199] - Add support for searchable content model properties (new search filters panel in the attach file widget)
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.service.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.module.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.service.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.service.ts
  lib/content-services/src/lib/content-node-selector/public-api.ts
  lib/content-services/src/lib/search/base-query-builder.service.ts
  lib/content-services/src/lib/search/components/search-filter/search-filter.component.html
  lib/content-services/src/lib/search/components/search-filter/search-filter.component.ts
  lib/content-services/src/lib/search/components/search-panel/search-panel.component.html
  lib/content-services/src/lib/search/components/search-panel/search-panel.component.spec.ts
  lib/content-services/src/lib/search/components/search-panel/search-panel.component.ts
  lib/content-services/src/lib/search/public-api.ts
  lib/content-services/src/lib/search/search-query-builder.service.ts
  lib/content-services/src/lib/search/search.module.ts
  lib/core/services/search.service.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
Labels: PR: unreviewed

#6192 [ACA-3010] - Process/Task Cloud fix wrong date range
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/protractor.excludes.json
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.spec.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.ts
  lib/process-services-cloud/src/lib/models/date-cloud-filter.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
Labels: PR: partially-approved

#6186 [ACA-3627] - Add completedBy filter again
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/mock/task-filters-cloud.mock.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
Labels: PR: unreviewed

#6200 add support for toolbar title i18n
  lib/core/toolbar/toolbar.component.html
  lib/core/toolbar/toolbar.module.ts
Labels: PR: partially-approved

#6201 [ADF-5262] Fix query execution in BaseQueryBuilderService
  lib/content-services/src/lib/search/base-query-builder.service.ts
Labels: PR: partially-approved

#6202 [ADF-5259] - addded unit test for custom widget
  lib/core/form/components/form-renderer.component.spec.ts
  lib/core/form/components/mock/form-renderer.component.mock.ts
Labels: PR: partially-approved

#6209 [ADF-5263] Empty page displayed all the time when load content fix
  e2e/content-services/directives/create-library-directive.e2e.ts
  e2e/content-services/directives/favorite-directive.e2e.ts
  e2e/content-services/document-list/document-list-pagination.e2e.ts
  e2e/content-services/document-list/document-list-properties.e2e.ts
  e2e/core/pages/dialog/create-library-dialog.page.ts
  e2e/core/pages/navigation-bar.page.ts
  e2e/process-services-cloud/pages/tasks-cloud-demo.page.ts
  e2e/process-services/info-drawer.e2e.ts
  e2e/process-services/pages/task-details.page.ts
  e2e/process-services/widgets/hyperlink-widget.e2e.ts
  e2e/protractor.conf.js
  lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/content-services/src/lib/document-list/services/document-list.service.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
  lib/process-services/src/lib/app-list/apps-list.component.spec.ts
  lib/testing/src/lib/core/pages/card-view/card-view-text-item.page.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  lib/testing/src/lib/core/pages/viewer.page.ts
  package-lock.json
  scripts/travis/e2e/content-services-e2e.sh
  scripts/travis/e2e/core-e2e.sh
  scripts/travis/e2e/insights-e2e.sh
  scripts/travis/e2e/process-services-cloud-e2e.sh
  scripts/travis/e2e/process-services-e2e.sh
  scripts/travis/e2e/search-e2e.sh
Labels: PR: unreviewed

#6210 add missing interface property
  lib/extensions/src/lib/config/document-list.extensions.ts
  lib/extensions/src/lib/config/navbar.extensions.ts
Labels: PR: partially-approved

#6212 [ADF-5261] Fix excluded flaky tests C297689, C297690
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/protractor.excludes.json
Labels: PR: partially-approved

#6193 [AAE-3637] Attach file - Upload button is not disabled when the user is in search mode
  docs/content-services/components/search-filter.component.md
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
  lib/content-services/src/lib/i18n/en.json
Labels: PR: unreviewed

#6221 [AAE-3764]Fix typo for CLAIM button on form - process services
  lib/process-services/src/lib/i18n/en.json
Labels: PR: partially-approved

#6227 [AAE-3790] - Fix search panel scroll in content node selector
  lib/content-services/src/lib/search/components/search-panel/search-panel.component.html
  lib/content-services/src/lib/search/components/search-panel/search-panel.component.scss
  lib/content-services/src/lib/search/components/search-panel/search-panel.component.ts
Labels: PR: partially-approved

#6229 Fix Redirect URL
  e2e/protractor.conf.js
  lib/core/services/auth-guard-base.ts
  lib/core/services/auth-guard-bpm.service.ts
  lib/core/services/auth-guard-ecm.service.ts
  lib/core/services/auth-guard.service.spec.ts
  lib/core/services/auth-guard.service.ts
Labels: PR: unreviewed

#6228 Release note for 4.1.0 in draft.
  docs/compatibility.md
  docs/release-notes/README.md
  docs/release-notes/RelNote410.md
  docs/versionIndex.md
Labels: PR: unreviewed, documentation

#6234 Fix of the release note menu.
  docs/abn-tree.yml
  docs/release-notes/README.md
Labels: PR: partially-approved, documentation

#6236 [ADF-5270] Fix delete cookie in path
  lib/core/services/cookie.service.ts
Labels: PR: partially-approved

#6235 additional unit tests for the upload
  lib/content-services/src/lib/upload/components/file-uploading-dialog.component.html
  lib/content-services/src/lib/upload/components/file-uploading-list-row.component.html
  lib/content-services/src/lib/upload/components/file-uploading-list-row.component.spec.ts
Labels: PR: partially-approved

#6232 [ADF-5269] - fix datatable date filter
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.html
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.spec.ts
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.ts
Labels: PR: partially-approved

#6220 [AAE-3410] Restrict breadcrumb if upload widget type set to Alfresco Content
  docs/content-services/components/content-node-selector-panel.component.md
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
Labels: PR: partially-approved

#6225 [AAE-3742] fix wrong behavior when editing properties on card view
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
Labels: PR: partially-approved

#6226 [ADF-5268] Fix card view losing focus when typing
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
Labels: PR: unreviewed

#6238 [ACA-4041] Filter not emitting the latest value
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.spec.ts
  lib/content-services/src/lib/search/search-header-query-builder.service.ts
Labels: PR: partially-approved

#6239 Override the redirectTo with the loginFragment
  lib/core/services/auth-guard-base.ts
Labels: PR: partially-approved

#6240 [ACA-4013] - fixed sorting for document list - size
  lib/content-services/src/lib/document-list/components/document-list.component.ts
Labels: PR: partially-approved

#6242 Fix user model default email domain
  lib/testing/src/lib/core/models/user.model.ts
  scripts/test-e2e-lib.sh
Labels: PR: partially-approved

#6243 Return the createUrlTree to see the redirect
  lib/core/services/auth-guard-base.ts
Labels: PR: partially-approved

#6246 Menu for ABN in regard of upgrade guides, vulnerability and licence info.
  docs/abn-tree.yml
  docs/upgrade-guide/README.md
Labels: PR: partially-approved, documentation

#6252 adf-cli - Fix typo on namespace
  lib/cli/scripts/kubectl-image.ts
Labels: PR: partially-approved

#6249 [ACA-4052] - Add today option back
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
Labels: PR: partially-approved

#6251 [ACA-3662] Add setCompleteDateFilterDropDown() method
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
Labels: PR: partially-approved

#6250 Try new travis Graviton
  .travis.yml
Labels: PR: partially-approved

#6259 fix error message for CSRF
  lib/core/i18n/ar.json
  lib/core/i18n/cs.json
  lib/core/i18n/da.json
  lib/core/i18n/de.json
  lib/core/i18n/en.json
  lib/core/i18n/es.json
  lib/core/i18n/fi.json
  lib/core/i18n/fr.json
  lib/core/i18n/it.json
  lib/core/i18n/ja.json
  lib/core/i18n/nb.json
  lib/core/i18n/nl.json
  lib/core/i18n/pl.json
  lib/core/i18n/pt-BR.json
  lib/core/i18n/ru.json
  lib/core/i18n/sv.json
  lib/core/i18n/zh-CN.json
Labels: PR: partially-approved

#6260 Default login with admin if not to create user e2e
  lib/testing/src/lib/core/actions/users.actions.ts
Labels: PR: partially-approved

#6151 [AAE-3587] Use grid to allow using rowspan
  lib/core/form/components/form-renderer.component.spec.ts
  lib/core/form/components/widgets/container/container.widget.html
  lib/core/form/components/widgets/container/container.widget.scss
  lib/core/form/components/widgets/container/container.widget.spec.ts
  lib/core/form/components/widgets/container/container.widget.ts
  lib/core/form/components/widgets/core/form-field.model.ts
  lib/core/form/components/widgets/core/form.model.ts
Labels: PR: partially-approved

#6253 [ADF-5279] Date range type filter selection triggers list reload
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
Labels: PR: partially-approved

#6254 [ADF-5280] [Cloud] Tasks - Created Date filter
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
Labels: PR: partially-approved

#6269 [AAE-3908] - fix clear value icon on card view text item
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
Labels: PR: partially-approved

#5907 [ACA-3619] - add task assignment filter
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-service-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.scss
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-filters/task-filters-cloud.module.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
Labels: PR: partially-approved

#6271 [AAE-3405] - Optimise attach file widget UI
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/mock/content-model.mock.ts
  lib/content-services/src/lib/search/components/search-panel/search-panel.component.html
  lib/content-services/src/lib/search/components/search-panel/search-panel.component.scss
  lib/content-services/src/lib/search/components/search-panel/search-panel.component.ts
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
Labels: PR: partially-approved

#6272 [ACA-3976]Add a new process with 2 parallel user tasks in candidatebaseapp
  e2e/resources/activiti7/candidatebaseapp.zip
  lib/testing/src/lib/process-services-cloud/resources/resources.json
Labels: PR: partially-approved

#6274 [AAE-3925] Add support for date type searchable properties in attach …
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.service.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.service.ts
  lib/content-services/src/lib/mock/content-model.mock.ts
Labels: PR: partially-approved

#6275 [AAE-3886] Cleanup the customModels when the attach file widget compo…
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
Labels: PR: partially-approved

#6276 [ACA-4089] Add new method in DatePickerCalendarPage
  lib/testing/src/lib/core/pages/material/date-picker-calendar.page.ts
Labels: PR: partially-approved

#6077 [ACA-3706] implement startedBy process filter property
  demo-shell/src/app/components/cloud/processes-cloud-demo.component.html
  demo-shell/src/app/components/cloud/processes-cloud-demo.component.ts
  e2e/process-services-cloud/config/process-list-cloud.config.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/process-filter-results.e2e.ts
  e2e/process-services-cloud/process-header-cloud.e2e.ts
  e2e/process-services-cloud/process-list-selection-cloud.e2e.ts
  lib/core/services/oauth2.service.ts
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/process-filters-cloud.module.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
Labels: PR: partially-approved

#6280 Fix the if condition on namespaces
  lib/cli/scripts/kubectl-image.ts
Labels: PR: partially-approved

#6281 [ACA-3664] Add new method in ADF to validate tasks filtering by CreatedBy filter
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
Labels: PR: partially-approved

#6279 [ACA-4049] Improve check for content on lists
  lib/testing/src/lib/process-services/pages/process-list.page.ts
  lib/testing/src/lib/process-services/pages/task-list.page.ts
Labels: PR: partially-approved

#6277 [AAE-3750] - add possibility to exclude user from selection on people…
  docs/process-services-cloud/components/people-cloud.component.md
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
Labels: PR: partially-approved

#6256 [ADF-5170] [upload] not able to upload file/folder from external content service specfic path
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog-component.interface.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.spec.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.spec.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.ts
  lib/process-services/src/lib/content-widget/attach-file-widget.component.spec.ts
  lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
Labels: PR: partially-approved

#6289 [ACA-4089] Modify setCompletedBy method to set the selected assignee
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.html
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
Labels: PR: partially-approved

#6293 [ACA-4057]Create process with random name
  lib/testing/src/lib/process-services/actions/process.util.ts
Labels: PR: partially-approved

#6288 [ACA-3870] Fix Version Compatibility Initialization
  lib/core/directives/version-compatibility.directive.ts
  lib/core/services/version-compatibility.service.spec.ts
  lib/core/services/version-compatibility.service.ts
Labels: PR: partially-approved

#6295 remove spamming of i18n warnings to console log
  lib/core/services/translate-loader.service.ts
Labels: PR: partially-approved
