Repository Alfresco/alfresco-ng2-components, pull requests merged in 2020-02, with the labels that each got.

#5429 [AAE-1594][AAE-1631] Fix not able to search for specific users, valid…
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
Labels: PR: unreviewed

#5445 [AAE-1539] People/Group - Add a formControl for the chip field
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
Labels: PR: reviewed-approved

#5447 #1256 Fix Icon alignment mismatch and the rows to have the same height.
  lib/content-services/src/lib/upload/components/file-uploading-list-row.component.scss
Labels: PR: unreviewed, next version

#5441 [ADF-5066] APS2 › Process List test need to be automated
  cspell.json
  e2e/pages/adf/demo-shell/process-services-cloud/processDetailsCloudDemoPage.ts
  e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts
  e2e/pages/adf/process-services/processListPage.ts
  e2e/process-services-cloud/process-filter-results.e2e.ts
  e2e/process-services-cloud/process-filter-task.e2e.ts
  e2e/process-services-cloud/process-list-selection-cloud.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: reviewed-approved

#5446 [AAE-1453] added e2e tests for readOnly property used in people/group cloudForm
  e2e/pages/adf/demo-shell/process-services/formDemoPage.ts
  e2e/process-services-cloud/form-field/date-widget.e2e.ts
  e2e/process-services-cloud/form-field/people-group-of-people.e2e.ts
  e2e/process-services-cloud/form-field/visibility-condition-tabs.e2e.ts
  e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
  e2e/resources/forms/people-group-formwidget-mocks.ts
  lib/testing/src/lib/core/pages/config-editor-page.ts
  lib/testing/src/lib/core/pages/public-api.ts
  lib/testing/src/lib/process-services-cloud/pages/form-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/public-api.ts
Labels: PR: reviewed-approved

#5451 AAE-1666 - updated simpleapp to test the multi-instance result collection
  e2e/resources/activiti7/simpleapp.zip
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: unreviewed

#5453 [ADF-5075] Update compatibility matrix for 3.7.0
  docs/compatibility.md
Labels: PR: reviewed-approved

#5449 [ADF-5073] Sorted column header is incorrectly read by a screen reader
  lib/core/datatable/components/datatable/datatable.component.html
  scripts/travis/e2e/content-services-e2e.sh
Labels: PR: unreviewed

#5450 [ADF-1653] [ADF-1651] - disabled download for external source and added download for same login content
  lib/process-services/src/lib/content-widget/attach-file-widget.component.html
  lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
  lib/process-services/src/lib/content-widget/attach-file-widget.components.spec.ts
Labels: PR: reviewed-approved

#5438 [ACA-2599] added always visible label to sort, i18n
  lib/core/i18n/en.json
  lib/core/sorting-picker/sorting-picker.component.html
Labels: PR: reviewed-approved

#5444 [ADF-4920] Fixed checkbox dropdown style when invalid
  lib/core/form/components/widgets/checkbox/checkbox.widget.html
  lib/core/form/components/widgets/checkbox/checkbox.widget.spec.ts
  lib/core/form/components/widgets/form.scss
Labels: PR: reviewed-approved

#5459 [ACA-2602]- Datatable - Selected state properly announced
  lib/core/datatable/components/datatable/datatable-row.component.ts
  lib/core/datatable/components/datatable/datatable.component.html
Labels: PR: reviewed-approved

#5461 Fix build scripts
  scripts/check-env/check-cs-env.js
  scripts/travis/update/trigger-travis-children.sh
Labels: PR: unreviewed

#5463 [ADF-5076] Automate tastrail case
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
  lib/process-services/src/lib/mock/task/task-list.mock.ts
  lib/process-services/src/lib/task-list/components/task-list.component.spec.ts
Labels: PR: reviewed-approved

#5464 [AAE-1179] Fix Start Task with Groups E2E tests
  e2e/process-services-cloud/start-task/start-task-group-cloud.e2e.ts
  e2e/protractor.excludes.json
Labels: PR: reviewed-approved

#5458 updated the simpleapp and candidatebase with the assignees that were …
  e2e/resources/activiti7/candidatebaseapp.zip
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#5456 [ADF-5068] APS › TaskList component › StartTask Component › Info Drawer test need to be automated
  e2e/pages/adf/process-services/taskDetailsPage.ts
  e2e/pages/adf/process-services/tasksPage.ts
  e2e/process-services/config/task.config.ts
  e2e/process-services/info-drawer.e2e.ts
Labels: PR: reviewed-approved

#5448 [ADF-5072] Permission panel shows first and last name of users
  lib/content-services/src/lib/mock/add-permission.component.mock.ts
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.spec.ts
Labels: PR: reviewed-approved

#5457 [AAE-1764] Fix testing methods checking visibility of widgets
  e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
  e2e/process-services/widgets/widget-visibility-condition.e2e.ts
  e2e/resources/forms/multiple-visibility-conditions.ts
  lib/testing/src/lib/core/pages/form/formFields.ts
  lib/testing/src/lib/core/pages/form/widgets/checkboxWidget.ts
Labels: PR: reviewed-approved, e2e

#5465 update simple app wrong name after importing
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: reviewed-approved

#5466 corrected the name in json file for candidatebaseapp
  e2e/resources/activiti7/candidatebaseapp.zip
Labels: PR: unreviewed

#5469 Updated simple app with the upload and display json process
  e2e/resources/activiti7/simpleapp.zip
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: unreviewed

#5468 [AAE-1838] Sidenav Unit test
  lib/core/layout/components/sidenav-layout/sidenav-layout.component.spec.ts
Labels: PR: unreviewed

#5500 [AAE-2034] Display disabled radio button in read-only mode
  lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.html
  lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.spec.ts
Labels: change requested

#5479 [AAE-1975] Add no results template when searching in People/Group clo…
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.scss
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.scss
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
  lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
Labels: PR: unreviewed

#5499 [AAE-2021] Automate About component
  e2e/content-services/about-content-services.component.e2e.ts
  e2e/process-services-cloud/about-process-services-cloud.component.e2e.ts
  e2e/process-services/about-process-services.e2e.ts
  lib/core/about/about-product-version/about-product-version.component.html
  lib/process-services/src/lib/content-widget/attach-file-widget.components.spec.ts
  lib/testing/src/lib/core/pages/about.page.ts
  lib/testing/src/lib/core/pages/public-api.ts
Labels: change requested

#5467 [AAE-1729] Move task-process filters methods into adf-testing, refactor dropdowns to use dropdown material testing page
  demo-shell/src/app/components/datatable/datatable.component.html
  e2e/core/settings-component.e2e.ts
  e2e/pages/adf/card-view-component.page.ts
  e2e/pages/adf/content-services.page.ts
  e2e/pages/adf/content-services/breadcrumb/bread-crumb-dropdown.page.ts
  e2e/pages/adf/demo-shell/data-table.page.ts
  e2e/pages/adf/demo-shell/process-services/process-cloud-demo.page.ts
  e2e/pages/adf/demo-shell/process-services/process-list-demo.page.ts
  e2e/pages/adf/demo-shell/process-services/task-list-demo.page.ts
  e2e/pages/adf/demo-shell/process-services/tasks-cloud-demo.page.ts
  e2e/pages/adf/notification.page.ts
  e2e/pages/adf/permissions.page.ts
  e2e/pages/adf/process-services/attach-form.page.ts
  e2e/pages/adf/process-services/dialog/start-task-dialog.page.ts
  e2e/pages/adf/process-services/start-process.page.ts
  e2e/pages/adf/process-services/task-details.page.ts
  e2e/pages/adf/process-services/tasks.page.ts
  e2e/process-services-cloud/edit-process-filters-component.e2e.ts
  e2e/process-services-cloud/edit-task-filters-component.e2e.ts
  e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/process-filter-results.e2e.ts
  e2e/process-services-cloud/process-filter-task.e2e.ts
  e2e/process-services-cloud/process-filters-cloud.e2e.ts
  e2e/process-services-cloud/process-header-cloud.e2e.ts
  e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts
  e2e/process-services-cloud/process-list-cloud-component.e2e.ts
  e2e/process-services-cloud/process-list-selection-cloud.e2e.ts
  e2e/process-services-cloud/start-process-cloud.e2e.ts
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts
  e2e/process-services-cloud/task-filters-cloud.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component-tab.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  e2e/process-services-cloud/task-header-cloud.e2e.ts
  e2e/process-services-cloud/task-list-cloud-action-menu.e2e.ts
  e2e/process-services-cloud/task-list-properties-sort.e2e.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/process-services-cloud/task-list-selection.e2e.ts
  e2e/process-services/attach-file-widget.e2e.ts
  e2e/process-services/attach-form-component.e2e.ts
  e2e/process-services/form-widgets-component.e2e.ts
  e2e/process-services/process-list-component.e2e.ts
  e2e/process-services/standalone-task.e2e.ts
  e2e/process-services/start-task-custom-app.e2e.ts
  e2e/process-services/start-task-task-app.e2e.ts
  e2e/process-services/task-details-form.e2e.ts
  e2e/search/components/search-sorting-picker.e2e.ts
  lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
  lib/testing/src/lib/content-services/pages/search/search-sorting-picker.page.ts
  lib/testing/src/lib/core/pages/form/form-fields.ts
  lib/testing/src/lib/core/pages/settings.page.ts
  lib/testing/src/lib/material/pages/dropdown.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/process-filters-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-filters-cloud-component.page.ts
  lib/testing/src/lib/process-services/pages/form-fields.page.ts
Labels: PR: unreviewed

#5509 [AAE-1797] added e2e automated tests
  e2e/content-services/document-list/document-list-actions.e2e.ts
  e2e/content-services/document-list/document-list-pagination.e2e.ts
  e2e/core/infinite-scrolling.e2e.ts
  e2e/core/pagination-empty-current-page.e2e.ts
  e2e/pages/adf/content-services.page.ts
  e2e/pages/adf/process-services/process-details.page.ts
  e2e/process-services/start-process-component.e2e.ts
  e2e/resources/apps/Start_process_attach_file.zip
  e2e/util/resources.js
  lib/testing/src/lib/core/pages/pagination.page.ts
  lib/testing/src/lib/process-services/pages/public-api.ts
  lib/testing/src/lib/process-services/pages/select-apps-dialog.page.ts
Labels: PR: unreviewed
