Repository Alfresco/alfresco-ng2-components, pull requests merged in 2020-11, with the labels that each got.

#6298 [ACA-4057] Add getProcessInstanceByName method
  lib/testing/src/lib/process-services/actions/process.util.ts
Labels: PR: partially-approved

#6296 [ACA-4057]Add method to create process with values
  e2e/resources/activiti7/subprocessapp.zip
  lib/testing/src/lib/process-services-cloud/resources/resources.json
  lib/testing/src/lib/process-services/actions/process.util.ts
Labels: PR: partially-approved

#6304 [AAE-3966] FE - Disable the upload button when the user doesn't have permissions in a folder
  docs/content-services/components/content-node-selector-panel.component.md
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
  lib/content-services/src/lib/i18n/en.json
Labels: PR: partially-approved

#6294 [ACA-4071] [ADW-Cloud]Task header takes too much to be loaded after claiming a task
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
Labels: PR: partially-approved

#6301 [AAE-3992] cleanup the code before refactoring
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-service-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  lib/process-services-cloud/tsconfig.lib.json
  lib/tsconfig.json
  lib/tsconfig.spec.json
  tsconfig.json
Labels: PR: partially-approved

#6299 [ACA-4099] Fix search query in content node selector
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/mock/search-query.mock.ts
Labels: PR: partially-approved

#6312 exported search-datetime range component
  lib/content-services/src/lib/search/public-api.ts
Labels: PR: partially-approved

#6306 [MNT-22003] - fixed check on variable for visibility service
  lib/core/form/services/widget-visibility-cloud.service.spec.ts
  lib/core/form/services/widget-visibility.service.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/models/task-variable-cloud.model.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
Labels: PR: unreviewed

#6282 Improve search filter component: hide a facet if there is no filter category
  e2e/search/search-filters.e2e.ts
  lib/content-services/src/lib/mock/search-filter-mock.ts
  lib/content-services/src/lib/search/components/search-filter/search-filter.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter/search-filter.component.ts
Labels: PR: unreviewed

#6303 [ACA-4057] Edit getProcessInstanceByName method to search the process instance directly by its name
  lib/testing/src/lib/process-services/actions/process.util.ts
Labels: PR: unreviewed, do not merge

#6318 [ACA-828] Add showTitle input in TaskCloudForm component
  docs/process-services-cloud/components/task-form-cloud.component.md
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.ts
Labels: PR: partially-approved

#6319 add missing env variables for proxy file
  demo-shell/proxy.conf.js
Labels: PR: partially-approved

#6302 [ADF-5223] Fix Amount widget styling
  e2e/process-services/widgets/amount-widget.e2e.ts
  lib/core/form/components/widgets/amount/amount.widget.html
  lib/core/form/components/widgets/amount/amount.widget.scss
  lib/core/form/components/widgets/amount/amount.widget.spec.ts
Labels: Failing tests, PR: partially-approved, PR: unreviewed

#6129 [ACA-3373] Add e2e multi item select method in DataTable component
  e2e/process-services/pages/attachment-list.page.ts
  e2e/process-services/process-attachment-list-action-menu.e2e.ts
  e2e/process-services/standalone-task.e2e.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  lib/testing/src/lib/core/utils/browser-actions.ts
Labels: PR: partially-approved

#6328 Added optional on variable models to avoid breaking changes
  lib/core/form/models/task-process-variable.model.ts
  lib/process-services-cloud/src/lib/form/models/task-variable-cloud.model.ts
Labels: PR: partially-approved

#6329 [ACS-827] - added whitelisted element and method for checking them
  lib/core/services/alfresco-api.service.ts
Labels: PR: partially-approved

#6330 AAE-3936 Tooltip card directive
  lib/core/directives/directive.module.ts
  lib/core/directives/public-api.ts
  lib/core/directives/tooltip-card/tooltip-card.component.html
  lib/core/directives/tooltip-card/tooltip-card.component.scss
  lib/core/directives/tooltip-card/tooltip-card.component.ts
  lib/core/directives/tooltip-card/tooltip-card.directive.spec.ts
  lib/core/directives/tooltip-card/tooltip-card.directive.ts
  lib/core/styles/_index.scss
Labels: PR: partially-approved

#6320 [MNT-21920] Fix Card View Integers initialization when they are set to 0
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
  lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.spec.ts
  lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
Labels: PR: unreviewed

#6305 [ACA-4124] Change name displayed for groups in Add Permission Panel Component
  demo-shell/src/app/components/error/demo-error.component.html
  e2e/content-services/permissions/permissions-component.e2e.ts
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
  lib/core/i18n/en.json
Labels: PR: partially-approved

#6332 [AAE-3936] Fix error in directive component
  lib/core/directives/directive.module.ts
Labels: PR: partially-approved

#6335 Fix clickUntilIsNotVisible by removing one return
  lib/testing/src/lib/core/utils/browser-actions.ts
Labels: PR: partially-approved

#6337 Fixed floating promise
  lib/testing/src/lib/core/utils/browser-actions.ts
Labels: PR: partially-approved

#6347 ix build
  .travis.yml
  e2e/content-services/comments/comment-component.e2e.ts
  e2e/content-services/directives/download-directive.e2e.ts
  e2e/content-services/directives/edit-folder-directive.e2e.ts
  e2e/content-services/directives/favorite-directive.e2e.ts
  e2e/content-services/directives/restore-content-directive.e2e.ts
  e2e/content-services/document-list/document-list-actions.e2e.ts
  e2e/content-services/document-list/document-list-copy-move-actions.e2e.ts
  e2e/content-services/document-list/document-list-properties.e2e.ts
  e2e/content-services/metadata/aspect-oriented-config.e2e.ts
  e2e/content-services/metadata/metadata-properties.e2e.ts
  e2e/content-services/metadata/metadata-smoke-tests.e2e.ts
  e2e/content-services/permissions/permissions-component.e2e.ts
  e2e/content-services/permissions/site-permissions.e2e.ts
  e2e/content-services/share-file/share-file.e2e.ts
  e2e/content-services/share-file/unshare-file.e2e.ts
  e2e/content-services/sso/sso-download-directive-component.e2e.ts
  e2e/content-services/version/version-actions.e2e.ts
  e2e/content-services/version/version-properties.e2e.ts
  e2e/content-services/version/version-smoke-tests.e2e.ts
  e2e/core/infinite-scrolling.e2e.ts
  e2e/core/login/login-component.e2e.ts
  e2e/core/pages/content-services.page.ts
  e2e/core/pages/navigation-bar.page.ts
  e2e/core/settings-component.e2e.ts
  e2e/core/viewer/viewer-share-content.ts
  e2e/protractor.conf.js
  e2e/protractor.excludes.json
  e2e/search/components/search-check-list.e2e.ts
  e2e/search/components/search-date-range.e2e.ts
  e2e/search/components/search-number-range.e2e.ts
  e2e/search/components/search-radio.e2e.ts
  e2e/search/components/search-slider.e2e.ts
  e2e/search/components/search-sorting-picker.e2e.ts
  e2e/search/components/search-text.e2e.ts
  e2e/search/search-component.e2e.ts
  e2e/search/search-filters.e2e.ts
  lib/cli/scripts/check-cs-env.ts
  lib/testing/src/lib/content-services/dialog/add-permissions-dialog.page.ts
  scripts/ci/job_hooks/after_e2e.sh
  scripts/ci/job_hooks/before_e2e.sh
  scripts/ci/job_hooks/before_install.sh
Labels: PR: unreviewed

#6331 [ACA-4123] Unify APS and Cloud event emitters for filters
  demo-shell/src/app/components/cloud/cloud-filters-demo.component.html
  demo-shell/src/app/components/process-service/process-service.component.html
  docs/process-services-cloud/components/process-filters-cloud.component.md
  docs/process-services-cloud/components/task-filters-cloud.component.md
  docs/process-services/components/process-filters.component.md
  docs/process-services/components/task-filters.component.md
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/mock/process-filters-cloud.mock.ts
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/base-task-filters-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/mock/task-filters-cloud.mock.ts
  lib/process-services/src/lib/mock/process/process-filters.mock.ts
  lib/process-services/src/lib/mock/process/process.service.mock.ts
  lib/process-services/src/lib/mock/public-api.ts
  lib/process-services/src/lib/mock/task/task-filters.mock.ts
  lib/process-services/src/lib/mock/task/tasklist-service.mock.ts
  lib/process-services/src/lib/process-list/components/process-filters.component.spec.ts
  lib/process-services/src/lib/process-list/components/process-filters.component.ts
  lib/process-services/src/lib/process-list/services/process-filter.service.spec.ts
  lib/process-services/src/lib/task-list/components/task-filters.component.html
  lib/process-services/src/lib/task-list/components/task-filters.component.spec.ts
  lib/process-services/src/lib/task-list/components/task-filters.component.ts
  lib/process-services/src/lib/task-list/services/task-filter.service.spec.ts
  lib/process-services/src/lib/task-list/services/tasklist.service.spec.ts
Labels: PR: unreviewed

#6348 [ADF-5284] Restore original plugin functionality
  lib/extensions/src/lib/config/extension.config.ts
  lib/extensions/src/lib/config/schema/plugin-extension.schema.json
  lib/extensions/src/lib/services/extension-loader.service.spec.ts
  lib/extensions/src/lib/services/extension-loader.service.ts
  lib/extensions/src/lib/services/extension.service.ts
Labels: PR: reviewed-approved

#6336 [DRAFT] Adding script for updating users on APS1
  scripts/ci/utils/init-apsone-env.js
Labels: PR: reviewed-changes-requested

#6351 [AAE-3638] - implement priority drodpown widget
  demo-shell/src/app.config.json
  e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts
  e2e/process-services-cloud/task-header-cloud.e2e.ts
  e2e/process-services-cloud/task-list-properties-sort.e2e.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/models/task.model.ts
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
  lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.html
  lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.scss
  lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.scss
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-header/mocks/task-details-cloud.mock.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/models/task-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
  lib/testing/src/lib/core/pages/card-view/card-view-select-item.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/start-tasks-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-header-cloud-component.page.ts
Labels: PR: partially-approved

#6355 [ACA-3957] - Replace icons on process cloud
  lib/core/assets/images/ic-process.svg
  lib/core/assets/images/save.svg
  lib/core/assets/images/task.svg
  lib/core/services/thumbnail.service.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
Labels: PR: partially-approved

#6361 Improve env check
  .travis.yml
  scripts/ci/check-env/check-cs-env.sh
  scripts/ci/check-env/check-ps-cloud-env.sh
  scripts/ci/check-env/check-ps-env.sh
  scripts/travis/e2e/content-services-e2e.sh
  scripts/travis/e2e/core-e2e.sh
  scripts/travis/e2e/process-services-cloud-e2e.sh
  scripts/travis/e2e/process-services-e2e.sh
  scripts/travis/e2e/search-e2e.sh
Labels: PR: unreviewed

#6371 [ACA-4124] Display authorityName when authorityDisplayName is missing
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
Labels: PR: partially-approved

#6370 [AAE-4127] [process-services] [APS1] Return Create Filters API response instead of the default payload
  lib/process-services/src/lib/process-list/services/process-filter.service.spec.ts
  lib/process-services/src/lib/process-list/services/process-filter.service.ts
  lib/process-services/src/lib/task-list/services/task-filter.service.spec.ts
  lib/process-services/src/lib/task-list/services/task-filter.service.ts
Labels: PR: partially-approved

#6374 [AAE-4188] Fix 3 invalid processes in simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: partially-approved

#6375 [ACA-4168] - changed to public reset pagination
  lib/content-services/src/lib/document-list/components/document-list.component.ts
Labels: PR: unreviewed

#6321 [ACA-3712] Add appVersion multi-select dropdown in edit cloud process filter
  demo-shell/src/app/components/cloud/processes-cloud-demo.component.html
  docs/process-services-cloud/components/process-list-cloud.component.md
  lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/models/application-version.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
  lib/process-services-cloud/src/lib/process/services/process-cloud.service.ts
  lib/process-services-cloud/src/public-api.ts
Labels: PR: partially-approved

#6366 [AAE-1379] - fixed form rapresentation
  lib/core/form/components/widgets/container/container.widget.spec.ts
  lib/core/form/components/widgets/container/container.widget.ts
Labels: PR: unreviewed

#6373 [AAE-4090] [ADW - Cloud] Warning message is displayed for one second in destination picker when Upload button is enabled
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
Labels: PR: unreviewed

#6386 Add upload license script
  .travis.yml
  lib/cli/README.md
  lib/cli/package-lock.json
  lib/cli/scripts/init-aps-env.ts
  scripts/ci/check-env/check-ps-env.sh
Labels: next version
