Repository Alfresco/alfresco-ng2-components, pull requests merged in 2020-12, with the labels that each got.

#6399 [ADF-5295] Fix Session not reloaded after User logs in in other tab
  lib/core/services/auth-guard.service.ts
Labels: regression

#6442 Removed the TODO placeholders from the release note.
  docs/release-notes/RelNote420.md
Labels: documentation 📄

#6469 Duplicated tutorial (because of the renaming)
  docs/user-guide/aae-extensions.md
Labels: documentation 📄

#6365 [ADF-5281][ADF] Can't go through a form with date/dateTime widgets only with Tab
  lib/core/form/components/widgets/date-time/date-time.widget.html
  lib/core/form/components/widgets/date/date.widget.html
  package-lock.json
  package.json
Labels: PR: partially-approved
