Repository Alfresco/alfresco-ng2-components, pull requests merged in 2020-06, with the labels that each got.

#5730 [ACA-3332] Add Context menu click action for process and task list and selectRow for process list
  lib/testing/src/lib/core/pages/context-menu.page.ts
  lib/testing/src/lib/core/pages/public-api.ts
  lib/testing/src/lib/process-services/pages/process-list.page.ts
  lib/testing/src/lib/process-services/pages/task-list.page.ts
Labels: PR: partially-approved

#5739 [ACA-3074] Fix preselected file loading issue
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
Labels: PR: partially-approved

#5741 [ACA-3390]Add startProcessWithApplication method on StartProcessPage
  e2e/process-services/start-process-component.e2e.ts
  e2e/process-services/stencil.e2e.ts
  e2e/process-services/task-assignee.e2e.ts
  lib/testing/src/lib/process-services/pages/start-process.page.ts
Labels: PR: partially-approved

#5743 [ADF-5153] Transclusion exposed from the DataTable to the DocumentList
  lib/content-services/src/lib/document-list/components/document-list.component.html
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.ts
Labels: PR: partially-approved

#5744 [ACA-3286] User gets error when removing the attached file
  lib/core/form/components/form-field/form-field.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/upload-cloud.widget.ts
Labels: PR: partially-approved

#5749 [ACA-3382] Expression - Fix the obj reference
  lib/extensions/src/lib/services/extension.service.ts
Labels: PR: partially-approved

#5751 [ADF-5154] Add missing API endpoints to SitesService
  lib/core/services/sites.service.ts
Labels: PR: partially-approved

#5750 [ACA-3266] Improve version upload component
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/components/files/version-manager-dialog-adapter.component.html
  demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
  docs/README.md
  docs/content-services/components/version-comparison.component.md
  docs/content-services/components/version-manager.component.md
  docs/docassets/images/version-comparison.png
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/styles/_index.scss
  lib/content-services/src/lib/version-manager/version-comparison.component.html
  lib/content-services/src/lib/version-manager/version-comparison.component.scss
  lib/content-services/src/lib/version-manager/version-comparison.component.spec.ts
  lib/content-services/src/lib/version-manager/version-comparison.component.ts
  lib/content-services/src/lib/version-manager/version-manager.component.html
  lib/content-services/src/lib/version-manager/version-manager.component.ts
  lib/content-services/src/lib/version-manager/version-manager.module.ts
Labels: PR: unreviewed

#5728 [ACA-2989]Add doubleClickRow method
  lib/testing/src/lib/core/pages/data-table/column.ts
  lib/testing/src/lib/core/pages/data-table/data-table-builder.ts
  lib/testing/src/lib/core/pages/data-table/data-table-item.ts
  lib/testing/src/lib/core/pages/data-table/date-column.ts
  lib/testing/src/lib/core/pages/data-table/text-column.ts
  lib/testing/src/lib/core/pages/snackbar.page.ts
Labels: PR: partially-approved

#5755 [ACA-2596] - fix: heading markup for bread crumbs
  lib/content-services/src/lib/breadcrumb/breadcrumb.component.html
Labels: PR: partially-approved

#5754 [ACA-2618] - fix: addition of persistent label
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
Labels: PR: unreviewed

#5757 add export missing model
  lib/testing/src/lib/core/actions/api.ts
  lib/testing/src/lib/core/models/public-api.ts
  lib/testing/src/lib/core/utils/browser-actions.ts
  lib/testing/src/lib/process-services-cloud/actions/application.ts
  lib/testing/src/lib/process-services-cloud/actions/descriptor.ts
  lib/testing/src/lib/process-services-cloud/actions/modeling-api.ts
  lib/testing/src/lib/process-services-cloud/actions/project.ts
Labels: PR: partially-approved

#5758 not use testconfig if is not present
  lib/testing/src/lib/core/actions/api.service.ts
Labels: PR: unreviewed

#5759 improve api service configuration
  lib/testing/src/lib/core/actions/api.service.ts
Labels: PR: partially-approved

#5748 [ACA-3407] New component : Filter Menu created and implemented inside the Document List
  lib/content-services/src/lib/document-list/components/document-list.component.html
  lib/content-services/src/lib/document-list/components/document-list.component.scss
  lib/content-services/src/lib/document-list/components/filter-menu/filter-menu.component.html
  lib/content-services/src/lib/document-list/components/filter-menu/filter-menu.component.ts
  lib/content-services/src/lib/document-list/document-list.module.ts
  lib/content-services/src/lib/i18n/en.json
  lib/core/assets/images/ft_ic_filter.svg
  lib/core/datatable/components/datatable/datatable.component.scss
  lib/core/services/thumbnail.service.ts
Labels: PR: partially-approved

#5761 Hide WIP filter inside document-list
  lib/content-services/src/lib/document-list/components/document-list.component.ts
Labels: PR: partially-approved

#5746 [ACA-3358] Show user friendly error templates when there are no applications/processDefinitions
  demo-shell/src/app/components/process-service/process-service.component.html
  demo-shell/src/app/components/process-service/process-service.component.ts
  docs/process-services/components/start-process.component.md
  lib/core/templates/empty-content/empty-content.component.html
  lib/core/templates/empty-content/empty-content.component.scss
  lib/core/templates/template.module.ts
  lib/process-services/src/lib/i18n/en.json
  lib/process-services/src/lib/process-list/components/start-process.component.html
  lib/process-services/src/lib/process-list/components/start-process.component.scss
  lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
  lib/process-services/src/lib/process-list/components/start-process.component.ts
  lib/testing/src/lib/process-services-cloud/pages/task-form-cloud-component.page.ts
  lib/testing/src/lib/process-services/pages/start-process.page.ts
Labels: PR: unreviewed

#5745 [ACA-3348] Add default process name pipe
  demo-shell/src/app/components/cloud/community/community-start-process-cloud.component.ts
  docs/process-services-cloud/pipes/process-name-cloud.pipe.md
  docs/process-services/pipes/process-name.pipe.md
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  e2e/process-services/process-filters-component.e2e.ts
  e2e/process-services/start-process-component.e2e.ts
  lib/process-services-cloud/src/lib/pipes/process-name-cloud.pipe.spec.ts
  lib/process-services-cloud/src/lib/pipes/process-name-cloud.pipe.ts
  lib/process-services-cloud/src/lib/pipes/process-services-cloud-pipe.module.ts
  lib/process-services-cloud/src/lib/process-services-cloud.module.ts
  lib/process-services-cloud/src/lib/process/process-cloud.module.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/models/process-instance-cloud.model.ts
  lib/process-services/src/lib/pipes/process-name.pipe.spec.ts
  lib/process-services/src/lib/pipes/process-name.pipe.ts
  lib/process-services/src/lib/pipes/process-services-pipe.module.ts
  lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
  lib/process-services/src/lib/process-list/components/start-process.component.ts
  lib/process-services/src/lib/process-list/process-list.module.ts
  lib/process-services/src/lib/process.module.ts
  lib/testing/src/lib/process-services/pages/start-process.page.ts
Labels: PR: partially-approved

#5764 [ACA-3358] Fix icon opacity
  lib/core/templates/empty-content/empty-content.component.scss
Labels: PR: partially-approved

#5747 [ACA_3292] - Add queued task as part of default task filter
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
Labels: PR: unreviewed

#5771 [ACA-3201] Fix datatable styling non-sortable with sortable columns are not a…
  lib/core/datatable/components/datatable/datatable.component.scss
Labels: PR: partially-approved

#5774 Fix start process e2e page
  lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
Labels: PR: partially-approved

#5775 [ACA-2962] Fix attach file widget shows Local source when only link is enabled
  lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
  lib/process-services/src/lib/content-widget/attach-file-widget.components.spec.ts
Labels: PR: partially-approved

#5776 Check for presence of the element before getText() in BreadcrumbPage PO.
  lib/testing/src/lib/core/pages/bread-crumb.page.ts
Labels: PR: partially-approved

#5778 [MNT-21584] fix rendering Hyperlink
  lib/core/form/components/widgets/hyperlink/hyperlink.widget.spec.ts
  lib/core/form/components/widgets/hyperlink/hyperlink.widget.ts
  lib/core/form/components/widgets/widget.component.ts
Labels: PR: partially-approved

#5760 [ACA-3109] Change order of default process filters for DW
  e2e/process-services-cloud/edit-process-filters-component.e2e.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/process-filters-cloud.e2e.ts
  e2e/process-services-cloud/process-header-cloud.e2e.ts
  e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts
  e2e/process-services-cloud/process-list-selection-cloud.e2e.ts
  e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
  e2e/process-services-cloud/start-process-cloud.e2e.ts
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
Labels: PR: partially-approved

#5765 [ACA-3329] Refactor isCompleteFormButtonDisabled method
  e2e/pages/adf/process-services/process-list.page.ts
  e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
  e2e/process-services/process-filters-component.e2e.ts
  e2e/process-services/process-instance-details.e2e.ts
  e2e/process-services/stencil.e2e.ts
  e2e/process-services/task-assignee.e2e.ts
  e2e/process-services/widgets/amount-widget.e2e.ts
  e2e/process-services/widgets/attach-folder-widget.e2e.ts
  e2e/process-services/widgets/checkbox-widget.e2e.ts
  e2e/process-services/widgets/date-time-widget.e2e.ts
  e2e/process-services/widgets/date-widget.e2e.ts
  e2e/process-services/widgets/dropdown-widget.e2e.ts
  e2e/process-services/widgets/header-widget.e2e.ts
  e2e/process-services/widgets/multi-line-widget.e2e.ts
  e2e/process-services/widgets/number-widget.e2e.ts
  e2e/process-services/widgets/radio-buttons-widget.e2e.ts
  e2e/process-services/widgets/text-widget.e2e.ts
  lib/testing/src/lib/core/pages/form/form-fields.ts
  lib/testing/src/lib/process-services/pages/form-fields.page.ts
  lib/testing/src/lib/process-services/pages/process-filters.page.ts
  lib/testing/src/lib/process-services/pages/process-list.page.ts
  lib/testing/src/lib/process-services/pages/task-filters.page.ts
Labels: PR: partially-approved

#5781 Ability to set the image of pods based on label
  lib/cli/README.md
  lib/cli/scripts/kubectl-image.ts
Labels: PR: partially-approved

#5783 Revert "Ability to set the image of pods based on label"
  lib/cli/README.md
  lib/cli/scripts/kubectl-image.ts
Labels: PR: unreviewed

#5784 [ACA-3373] Update simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: partially-approved

#5786 adf-cli k8s image - Be able to override image by label and namespace
  lib/cli/README.md
  lib/cli/scripts/kubectl-image.ts
Labels: PR: partially-approved

#5782 [ACA-3454] disable floating label for ammount
  lib/core/form/components/widgets/amount/amount.widget.html
Labels: PR: reviewed-approved

#5790 [ADF-5160] Fix CardView Key-Value Pairs Item overflowing
  lib/core/card-view/components/card-view-keyvaluepairsitem/card-view-keyvaluepairsitem.component.scss
Labels: PR: partially-approved

#5793 Add attach file forms and processes to resources file
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: partially-approved

#5792 various code quality fixes
  demo-shell/app.js
  demo-shell/src/app/components/files/files.component.ts
  docs/tutorials/working-with-data-table.md
  e2e/content-services/upload/upload-dialog.e2e.ts
  e2e/process-services/comment-component-processes.e2e.ts
  lib/cli/scripts/init-aae-env.ts
  lib/content-services/src/lib/breadcrumb/breadcrumb.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
  lib/content-services/src/lib/content-node-share/content-node-share.directive.spec.ts
  lib/content-services/src/lib/search/components/search-control.component.ts
  lib/content-services/src/lib/upload/components/base-upload/upload-base.ts
  lib/content-services/src/lib/version-manager/version-upload.component.ts
  lib/core/buttons-menu/buttons-menu.component.ts
  lib/core/comments/comments.component.ts
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/core/dialogs/edit-json/edit-json.dialog.ts
  lib/core/form/components/form-base.component.ts
  lib/core/form/components/widgets/core/content-link.model.ts
  lib/core/form/components/widgets/core/error-message.model.ts
  lib/core/form/components/widgets/core/form-field-validator.ts
  lib/core/form/components/widgets/core/form-field.model.ts
  lib/core/form/components/widgets/core/form.model.ts
  lib/core/form/components/widgets/dropdown/dropdown.widget.ts
  lib/core/form/components/widgets/dynamic-table/dynamic-table.widget.model.ts
  lib/core/form/components/widgets/widget.component.ts
  lib/core/layout/components/header/header.component.spec.ts
  lib/core/models/product-version.model.ts
  lib/core/pipes/file-size.pipe.ts
  lib/core/pipes/file-type.pipe.ts
  lib/core/services/authentication.service.ts
  lib/core/services/identity-group.service.ts
  lib/core/services/identity-user.service.ts
  lib/core/services/upload.service.ts
  lib/insights/src/lib/analytics-process/components/analytics-generator.component.ts
  lib/insights/src/lib/analytics-process/components/analytics-report-heat-map.component.ts
  lib/insights/src/lib/analytics-process/components/analytics-report-list.component.ts
  lib/insights/src/lib/analytics-process/components/widgets/widget.component.ts
  lib/insights/src/lib/diagram/models/chart/bar-chart.model.ts
  lib/insights/src/lib/diagram/models/chart/details-table-chart.model.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
  lib/process-services-cloud/src/lib/process/directives/cancel-process.directive.ts
  lib/process-services-cloud/src/lib/task/directives/claim-task-cloud.directive.ts
  lib/process-services-cloud/src/lib/task/directives/unclaim-task-cloud.directive.ts
  lib/process-services/src/lib/app-list/apps-list.component.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.ts
  lib/process-services/src/lib/form/form.component.ts
  lib/process-services/src/lib/process-list/models/process-definition.model.ts
  lib/process-services/src/lib/task-list/components/attach-form.component.ts
  lib/process-services/src/lib/task-list/components/task-audit.directive.ts
  lib/process-services/src/lib/task-list/components/task-form/claim-task.directive.ts
  lib/process-services/src/lib/task-list/components/task-form/unclaim-task.directive.ts
  lib/process-services/src/lib/task-list/models/filter.model.ts
  lib/testing/src/lib/core/pages/pagination.page.ts
Labels: PR: unreviewed

#5787 [ACA-3461] Start Process - show form for preselected process
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
Labels: PR: unreviewed

#5777 [ACA-3218] Fix attach file widget - wrong payload when link is true
  lib/core/form/services/activiti-alfresco.service.ts
  lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
  lib/process-services/src/lib/content-widget/attach-file-widget.components.spec.ts
Labels: PR: unreviewed

#5794 exclude failing test before the revert of the time modify is finalized
  e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/protractor.excludes.json
  e2e/test.config.js
  lib/testing/src/lib/core/actions/api.service.ts
  lib/testing/src/lib/core/pages/form/form-fields.ts
  lib/testing/src/lib/core/utils/browser-actions.ts
  lib/testing/src/lib/core/utils/browser-visibility.ts
  lib/testing/src/lib/core/utils/logger.ts
  lib/testing/src/lib/process-services-cloud/actions/tasks.service.ts
  scripts/travis/e2e/process-services-cloud-e2e.sh
Labels: PR: unreviewed

#5798 remove old unmaintained sub-projects
  lib/core/services/alfresco-api.service.ts
  lib/extensions/ng-package.json
  lib/process-services-cloud/src/lib/task/directives/claim-task-cloud.directive.ts
  package-lock.json
  package.json
  tools/i18n/UIStyleRules.md
  tools/i18n/cmdLi18nt.js
  tools/i18n/cmdLi18nt.ts
  tools/i18n/li18nt/.gitignore
  tools/i18n/li18nt/.vscode/launch.json
  tools/i18n/li18nt/.vscode/settings.json
  tools/i18n/li18nt/.vscode/tasks.json
  tools/i18n/li18nt/README.md
  tools/i18n/li18nt/client/.vscodeignore
  tools/i18n/li18nt/client/package-lock.json
  tools/i18n/li18nt/client/package.json
  tools/i18n/li18nt/client/src/extension.ts
  tools/i18n/li18nt/client/tsconfig.json
  tools/i18n/li18nt/package-lock.json
  tools/i18n/li18nt/package.json
  tools/i18n/li18nt/server/package-lock.json
  tools/i18n/li18nt/server/package.json
  tools/i18n/li18nt/server/src/SGStyleRules.js
  tools/i18n/li18nt/server/src/SGStyleRules.ts
  tools/i18n/li18nt/server/src/server.ts
  tools/i18n/li18nt/server/tsconfig.json
  tools/schematics/adf/.gitignore
  tools/schematics/adf/.npmignore
  tools/schematics/adf/README.md
  tools/schematics/adf/package-lock.json
  tools/schematics/adf/package.json
  tools/schematics/adf/src/adf/index.d.ts
  tools/schematics/adf/src/adf/index.js
  tools/schematics/adf/src/adf/index.js.map
  tools/schematics/adf/src/adf/index_spec.d.ts
  tools/schematics/adf/src/adf/index_spec.js
  tools/schematics/adf/src/adf/index_spec.js.map
  tools/schematics/adf/src/adf/templates/__basename__.__type__.md
  tools/schematics/adf/src/collection.json
  tools/schematics/adf/tsconfig.json
Labels: PR: unreviewed

#5799 [ADF-5161] Add query token injection for search query builder
  lib/content-services/src/lib/permission-manager/components/add-permission/search-config-permission.service.ts
  lib/content-services/src/lib/permission-manager/public-api.ts
Labels: PR: partially-approved

#5791 [ACA-3474] [Info Drawer] Error on save
  lib/core/datatable/components/datatable-cell/datatable-cell.component.spec.ts
  lib/core/datatable/components/datatable-cell/datatable-cell.component.ts
Labels: PR: partially-approved

#5780 [ACA-3448] Candidate user is able to complete a task without a form attached before claiming it
  lib/process-services/src/lib/mock/task/task-details.mock.ts
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.html
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.spec.ts
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.ts
Labels: PR: partially-approved

#5801 [ACA-3426] - removed not used color code
  lib/content-services/src/lib/search/components/search-header/search-header.component.html
Labels: PR: partially-approved

#5802 Documentation review
  docs/README.md
  docs/content-services/components/document-list.component.md
  docs/content-services/components/search-header.component.md
  docs/content-services/services/search-query-builder.service.md
  docs/core/components/datatable.component.md
  docs/core/services/card-item-types.service.md
  docs/core/services/form-rendering.service.md
  docs/core/services/sites.service.md
  docs/extensions/services/extension.service.md
  docs/process-services-cloud/components/process-list-cloud.component.md
  docs/process-services-cloud/components/task-form-cloud.component.md
  docs/process-services-cloud/components/task-list-cloud.component.md
  docs/process-services-cloud/directives/claim-task-cloud.directive.md
  docs/process-services-cloud/pipes/process-name-cloud.pipe.md
  docs/process-services-cloud/services/form-cloud.service.md
  docs/process-services-cloud/services/start-process-cloud.service.md
  docs/process-services/components/process-list.component.md
  docs/process-services/components/start-process.component.md
  docs/process-services/components/task-form.component.md
  docs/process-services/components/task-header.component.md
  docs/process-services/components/task-list.component.md
  docs/process-services/directives/claim-task.directive.md
  docs/process-services/pipes/process-name.pipe.md
  docs/process-services/services/process-filter.service.md
  docs/process-services/services/task-filter.service.md
  docs/versionIndex.md
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
  scripts/travis/update/update-children.sh
  scripts/travis/update/update-project.sh
  scripts/update-version.sh
Labels: PR: partially-approved

#5803 [ACA-3426] - reverted method renaming
  lib/content-services/src/lib/search/base-query-builder.service.ts
  lib/content-services/src/lib/search/components/search-filter/search-filter.component.spec.ts
  lib/content-services/src/lib/search/search-header-query-builder.service.spec.ts
  lib/content-services/src/lib/search/search-query-builder.service.spec.ts
Labels: PR: unreviewed

#5805 error message if log level is set with wrong name
  lib/testing/src/lib/core/utils/logger.ts
Labels: PR: partially-approved

#5804 [ACA-3426] Add translate pipe to search-header tooltip
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/search/components/search-header/search-header.component.html
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
Labels: PR: partially-approved

#5807 Update browser-actions.ts to warn instead of error
  lib/testing/src/lib/core/utils/browser-actions.ts
Labels: PR: partially-approved

#5810 Fix unknown style
  e2e/core/viewer/file-extensions/viewer-excel.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-image.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-powerpoint.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-text.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-word.component.e2e.ts
  lib/core/styles/_index.scss
  lib/core/viewer/components/unknown-format/unknown-format.component.html
  lib/core/viewer/components/unknown-format/unknown-format.component.scss
  lib/testing/src/lib/core/pages/viewer.page.ts
Labels: PR: unreviewed

#5809 [AAE-2840] Not able to complete a task with attach file widget with mappings
  lib/core/form/components/form-field/form-field.component.spec.ts
  lib/core/form/components/form-field/form-field.component.ts
  lib/core/form/components/mock/form-renderer.component.mock.ts
  lib/core/form/services/widget-visibility.service.spec.ts
  lib/core/form/services/widget-visibility.service.ts
Labels: PR: unreviewed, regression

#5812 [ADF-5163] [Regression] Fix placeholder on Form widgets
  lib/core/form/components/widgets/date-time/date-time.widget.html
  lib/core/form/components/widgets/date-time/date-time.widget.scss
  lib/core/form/components/widgets/date/date.widget.html
  lib/core/form/components/widgets/date/date.widget.scss
  lib/core/form/components/widgets/multiline-text/multiline-text.widget.html
  lib/core/form/components/widgets/multiline-text/multiline-text.widget.scss
  lib/core/form/components/widgets/number/number.widget.html
  lib/core/form/components/widgets/number/number.widget.scss
  lib/core/form/components/widgets/text/text.widget.scss
  lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.scss
Labels: PR: partially-approved

#5815 [ACA-3447] Cancel upload of new version removes existing version
  lib/core/services/upload.service.spec.ts
  lib/core/services/upload.service.ts
Labels: PR: partially-approved

#5808 Release note for ADF 3.9.0
  docs/content-services/components/version-comparison.component.md
  docs/license-info/README.md
  docs/license-info/license-info-3.9.0.md
  docs/release-notes/README.md
  docs/release-notes/RelNote390.md
  docs/release-notes/images/DocumentListFiltering.png
  docs/vulnerability/README.md
  docs/vulnerability/audit-info-3.9.0.md
  lib/cli/README.md
  lib/core/viewer/components/unknown-format/unknown-format.component.scss
  package-lock.json
  package.json
Labels: PR: unreviewed, documentation

#5816 [ADF-5167] [FORM] Task action name inconsistency
  lib/process-services/src/lib/i18n/en.json
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.html
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.spec.ts
Labels: PR: partially-approved

#5817 [ACA-3527] Add check to activeFilters update
  lib/content-services/src/lib/search/search-header-query-builder.service.spec.ts
  lib/content-services/src/lib/search/search-header-query-builder.service.ts
Labels: PR: partially-approved

#5813 [ACA-3520] - fixed providing by default of the service
  demo-shell/src/app/components/search/search-result.component.ts
  lib/content-services/src/lib/search/search.module.ts
Labels: PR: unreviewed

#5818 [ACA-3528] Fix start process feature (infinite loop, process name get…
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
Labels: PR: partially-approved

#5819 Fixed search configuration to look for facet widgets
  demo-shell/src/app.config.json
Labels: PR: partially-approved

#5820 [DO NOT MERGE] try reload search conf
  demo-shell/src/app/components/search/search-result.component.ts
  lib/testing/src/lib/core/actions/api.service.ts
  lib/testing/src/lib/core/pages/login-sso.page.ts
  lib/testing/src/lib/core/utils/local-storage.util.ts
Labels: PR: unreviewed

#5822 Fix the js-api instance and remove access to the database
  lib/cli/scripts/kubectl-clean-app.ts
Labels: PR: unreviewed

#5821 [ACA-3507] [ACA-3523] Fix Filters
  demo-shell/src/app.config.json
  docs/content-services/components/search-text.component.md
  lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.ts
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.html
  lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
  lib/content-services/src/lib/search/components/search-number-range/search-number-range.component.ts
  lib/content-services/src/lib/search/components/search-radio/search-radio.component.ts
  lib/content-services/src/lib/search/components/search-text/search-text.component.ts
  lib/content-services/src/lib/search/components/search-widget-container/search-widget-container.component.ts
  lib/content-services/src/lib/search/search-header-query-builder.service.spec.ts
  lib/content-services/src/lib/search/search-header-query-builder.service.ts
  lib/content-services/src/lib/search/search-widget.interface.ts
Labels: PR: unreviewed

#5823 adf-cli clean script - Be able to delete based on time
  lib/cli/scripts/kubectl-clean-app.ts
Labels: PR: partially-approved

#5824 [ADF-5174] Add Permisssions Dialog to adf-testing Lib
  e2e/content-services/permissions/permissions-component.e2e.ts
  e2e/content-services/permissions/site-permissions.e2e.ts
  e2e/pages/adf/permissions.page.ts
  lib/testing/src/lib/content-services/dialog/add-permissions-dialog.page.ts
  lib/testing/src/lib/content-services/dialog/public-api.ts
Labels: PR: partially-approved
