Repository Alfresco/alfresco-ng2-components, pull requests merged in 2020-05, with the labels that each got.

#5659 [AAE-2505] [PS cloud] Should not allow to start the process if is not created
  e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
Labels: PR: unreviewed

#5643 [ADF-5123] C315268 not working correctly
  e2e/process-services/attach-file-content-service.e2e.ts
  e2e/process-services/attach-folder.e2e.ts
  e2e/process-services/process-list-component.e2e.ts
  e2e/protractor.excludes.json
  lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
Labels: PR: unreviewed

#5663 release reports
  docs/license-info/README.md
  docs/license-info/license-info-3.8.0.md
  docs/upgrade-guide/README.md
  docs/upgrade-guide/upgrade37-38.md
  docs/vulnerability/README.md
  docs/vulnerability/audit-info-3.8.0.md
  package-lock.json
  package.json
Labels: PR: partially-approved

#5664 remove excluded test C260249
  e2e/protractor.excludes.json
Labels: PR: unreviewed

#5666 [ADF-5134] REGRESSION - Fix People and Group Components firing twice
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
Labels: PR: partially-approved

#5669 [ACA-3240] Information inside custom aspects when properties have default value is wrong displayed
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
Labels: PR: reviewed-approved

#5670 Update JS-API packages version 3.8.0
  demo-shell/package.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package.json
Labels: PR: partially-approved

#5674 ADF CLI fixes
  lib/cli/README.md
  lib/cli/bin/adf-cli
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/cli/scripts/artifact-from-s3.ts
  lib/cli/scripts/artifact-to-s3.ts
  lib/cli/scripts/docker-publish.ts
  lib/cli/scripts/init-aae-env.ts
  lib/cli/scripts/kubectl-clean-app.ts
  lib/cli/scripts/kubectl-delete.ts
  lib/cli/scripts/kubectl-image.ts
  lib/cli/scripts/npm-publish.ts
  lib/cli/scripts/update-commit-sha.ts
  lib/cli/scripts/update-version.ts
Labels: PR: partially-approved

#5675 [AAE-2570] prepare script to change name development to develop
  .travis.yml
  scripts/git-util/check-branch-updated.sh
  scripts/release/release.sh
  scripts/travis/build/build.sh
  scripts/travis/release/release-npm.sh
  scripts/travis/update/update-project.sh
Labels: PR: partially-approved

#5642 Deploy PR on request
  .travis.yml
  Dockerfile
  README.md
  docker/entrypoint.sh
  package-lock.json
  package.json
  scripts/travis/deploy/deploy-pr.sh
  scripts/travis/deploy/move-dist-folder.js
  scripts/travis/deploy/rancher-pr-deploy.js
Labels: PR: unreviewed, do not merge

#5672 [ADF-5131] Radio buttons display below label
  lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.scss
Labels: PR: unreviewed

#5668 [ADF-5135] Eventual Consistency Helper for e2e tests.
  lib/testing/src/lib/core/actions/identity/query.service.ts
Labels: PR: unreviewed

#5687 [ACA-3269]Move notificationPage to adf testing package
  e2e/content-services/notifications-component.e2e.ts
  e2e/pages/adf/demo-shell/notification.page.ts
  lib/testing/src/lib/core/pages/public-api.ts
  lib/testing/src/lib/core/pages/snackbar.page.ts
Labels: PR: merged

#5667 [AAE-2537] - fix mark as read notification
  lib/core/notifications/components/notification-history.component.spec.ts
  lib/core/notifications/components/notification-history.component.ts
Labels: PR: unreviewed

#5614 [ADF-5103] FE - Process/task filter - Backporting the components styles to ADF
  e2e/pages/adf/demo-shell/process-services/task-filters-demo.page.ts
  e2e/pages/adf/process-services/filters.page.ts
  e2e/pages/adf/process-services/process-filters.page.ts
  e2e/pages/adf/process-services/task-filters.page.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.scss
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.scss
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
  lib/process-services/src/lib/process-list/components/process-filters.component.html
  lib/process-services/src/lib/process-list/components/process-filters.component.scss
  lib/process-services/src/lib/process-list/components/process-filters.component.spec.ts
  lib/process-services/src/lib/process-list/components/process-filters.component.ts
  lib/process-services/src/lib/task-list/components/task-filters.component.html
  lib/process-services/src/lib/task-list/components/task-filters.component.scss
  lib/process-services/src/lib/task-list/components/task-filters.component.spec.ts
  lib/testing/src/lib/process-services-cloud/pages/process-filters-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-filters-cloud-component.page.ts
  lib/testing/src/lib/process-services/pages/filters.page.ts
  lib/testing/src/lib/process-services/pages/process-filters.page.ts
  lib/testing/src/lib/process-services/pages/task-filters.page.ts
Labels: PR: unreviewed

#5676 [ACA-3245] Fetch alfresco repo name from an API
  lib/core/app-config/app-config.service.ts
  lib/core/form/services/activiti-alfresco.service.ts
  lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
  lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
  lib/process-services/src/lib/process-list/components/start-process.component.ts
Labels: PR: reviewed-changes-requested

#5648 [AAE-2200] Upload dialog title should match selected site.
  README.md
  docs/content-services/components/content-node-selector-panel.component.md
  docs/process-services/components/process-list.component.md
  docs/process-services/components/task-list.component.md
  lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
  lib/content-services/src/lib/mock/public-api.ts
  lib/content-services/src/lib/mock/sites-dropdown.component.mock.ts
  lib/content-services/src/lib/site-dropdown/sites-dropdown.component.spec.ts
  lib/content-services/src/lib/site-dropdown/sites-dropdown.component.ts
  lib/core/form/services/activiti-alfresco.service.ts
  lib/core/services/sites.service.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.html
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.spec.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.ts
Labels: PR: reviewed-approved

#5710 [ACA-45] Drag and Drop a New Version
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/components/files/files.component.html
  demo-shell/src/app/components/files/files.component.ts
  demo-shell/src/app/components/files/version-manager-dialog-adapter.component.html
  demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
  docs/content-services/components/document-list.component.md
  docs/content-services/components/upload-button.component.md
  docs/content-services/components/upload-drag-area.component.md
  docs/content-services/components/upload-version-button.component.md
  docs/content-services/components/version-manager.component.md
  docs/core/components/datatable.component.md
  lib/content-services/src/lib/document-list/components/document-list.component.html
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/content-services/src/lib/document-list/data/share-data-row.model.ts
  lib/content-services/src/lib/document-list/data/share-datatable-adapter.ts
  lib/content-services/src/lib/upload/components/base-upload/upload-base.ts
  lib/content-services/src/lib/upload/components/upload-button.component.html
  lib/content-services/src/lib/upload/components/upload-button.component.spec.ts
  lib/content-services/src/lib/upload/components/upload-button.component.ts
  lib/content-services/src/lib/upload/components/upload-drag-area.component.spec.ts
  lib/content-services/src/lib/upload/components/upload-drag-area.component.ts
  lib/content-services/src/lib/version-manager/version-manager.component.html
  lib/content-services/src/lib/version-manager/version-manager.component.spec.ts
  lib/content-services/src/lib/version-manager/version-manager.component.ts
  lib/content-services/src/lib/version-manager/version-upload.component.html
  lib/content-services/src/lib/version-manager/version-upload.component.ts
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.ts
Labels: PR: partially-approved

#5700 [ACA-3271] START PROCESS button is inactive first time when process model is loaded
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
Labels: PR: reviewed-changes-requested

#5726 [ACA-2975] fix start process wrong response
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
Labels: PR: partially-approved

#5734 [ADF-5150] Datatable sub-component each in its own folder
  docs/README.md
  docs/core/components/empty-list.component.md
  docs/core/components/json-cell.component.md
  lib/core/datatable/components/data-cell.event.ts
  lib/core/datatable/components/data-row-action.event.ts
  lib/core/datatable/components/datatable-cell/datatable-cell.component.spec.ts
  lib/core/datatable/components/datatable-cell/datatable-cell.component.ts
  lib/core/datatable/components/datatable-row/datatable-row.component.spec.ts
  lib/core/datatable/components/datatable-row/datatable-row.component.ts
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/core/datatable/components/date-cell/date-cell.component.ts
  lib/core/datatable/components/empty-list/empty-list.component.html
  lib/core/datatable/components/empty-list/empty-list.component.scss
  lib/core/datatable/components/empty-list/empty-list.component.spec.ts
  lib/core/datatable/components/empty-list/empty-list.component.ts
  lib/core/datatable/components/filesize-cell/filesize-cell.component.ts
  lib/core/datatable/components/json-cell/json-cell.component.scss
  lib/core/datatable/components/json-cell/json-cell.component.spec.ts
  lib/core/datatable/components/json-cell/json-cell.component.ts
  lib/core/datatable/components/location-cell/location-cell.component.spec.ts
  lib/core/datatable/components/location-cell/location-cell.component.ts
  lib/core/datatable/datatable.module.ts
  lib/core/datatable/directives/drop-zone.directive.ts
  lib/core/datatable/public-api.ts
Labels: PR: partially-approved

#5736 [ACA-3359] Disable processName/ProcessDefintions drop down if no application selected.
  lib/process-services/src/lib/process-list/components/start-process.component.html
  lib/process-services/src/lib/process-list/components/start-process.component.scss
  lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
  lib/process-services/src/lib/process-list/components/start-process.component.ts
Labels: PR: partially-approved

#5735 [ACA-3286] User gets error when removing the attached file
  lib/core/form/components/form-field/form-field.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/upload-cloud.widget.ts
Labels: PR: reviewed-changes-requested

#5738 Revert "[ACA-3286] User gets error when removing the attached file"
  lib/core/form/components/form-field/form-field.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/upload-cloud.widget.ts
Labels: PR: unreviewed

#5737 [ACA-3252] Content Metadata - Use the translation key
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
Labels: PR: partially-approved

#5732 [ACA-3368] Update datatable columns when presetColumn schema changes
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/process-services/src/lib/mock/process/process-instances-list.mock.ts
  lib/process-services/src/lib/mock/task/task-list.mock.ts
  lib/process-services/src/lib/process-list/components/process-list.component.spec.ts
  lib/process-services/src/lib/process-list/components/process-list.component.ts
  lib/process-services/src/lib/task-list/components/task-list.component.spec.ts
  lib/process-services/src/lib/task-list/components/task-list.component.ts
Labels: PR: partially-approved
