Repository Alfresco/alfresco-ng2-components, pull requests merged in 2020-03, with the labels that each got.

#5527 [AAE-1949] Form Attach File Widget AAE unit test
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
Labels: PR: unreviewed

#5530 [Simple-app] Updated process-display-json process variable
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#5531 [AAE-1746]Added 3 new processed to candidatebaseapp: errorStartEventProcess, er…
  e2e/resources/activiti7/candidatebaseapp.zip
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: reviewed-approved

#5526 [AAE-2009] - Added visibility unit test for form
  lib/core/form/components/form-renderer.component.spec.ts
  lib/core/form/components/mock/form-renderer.component.mock.ts
Labels: PR: reviewed-approved

#5532 [AAE-1977] Fix file uploaded after cancelling upload
  lib/content-services/src/lib/upload/components/file-uploading-dialog.component.ts
  lib/content-services/src/lib/upload/components/file-uploading-list.component.ts
  lib/core/services/upload.service.spec.ts
  lib/core/services/upload.service.ts
Labels: PR: reviewed-approved

#5518 [AAE-1880] e2e document-list selection mode
  e2e/content-services/document-list/document-list-actions.e2e.ts
  e2e/content-services/document-list/document-list-pagination.e2e.ts
  e2e/content-services/document-list/document-list-selection.e2e.ts
  e2e/core/viewer/viewer-properties.e2e.ts
  e2e/pages/adf/content-services.page.ts
  e2e/pages/adf/process-services/process-details.page.ts
  e2e/process-services/start-process-component.e2e.ts
  lib/testing/src/lib/core/pages/viewer.page.ts
  lib/testing/src/lib/process-services/pages/select-apps-dialog.page.ts
Labels: PR: reviewed-approved

#5525 [ADF-5085] Adding possibility to search for future dates search-date-range component
  demo-shell/src/app.config.json
  docs/content-services/components/search-date-range.component.md
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.html
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.spec.ts
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.ts
Labels: PR: reviewed-approved

#5533 Updated simpleapp with new process (reset-connector-process)
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: reviewed-approved

#5535 [AAE-2107] Move e2e to Unit test
  e2e/core/card-view/card-view-component.e2e.ts
  e2e/core/datatable/data-table-component-selection.e2e.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/process-filter-results.e2e.ts
  e2e/process-services-cloud/process-filter-task.e2e.ts
  e2e/process-services-cloud/process-list-cloud-component.e2e.ts
  e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts
  e2e/process-services-cloud/task-filters-cloud.e2e.ts
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
  lib/core/card-view/components/card-view-keyvaluepairsitem/card-view-keyvaluepairsitem.component.spec.ts
  lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.spec.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/mock/process-list-service.mock.ts
  lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
Labels: PR: reviewed-approved

#5534 AAE-1951 - added extra test cases for start task and assignee
  e2e/pages/adf/demo-shell/process-services/tasks-cloud-demo.page.ts
  e2e/process-services-cloud/task-header-cloud.e2e.ts
  lib/testing/src/lib/core/pages/card-view/card-view-text-item.page.ts
  lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/start-tasks-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-header-cloud-component.page.ts
Labels: PR: reviewed-approved

#5536 remove duplicated test
  lib/core/directives/check-allowable-operation.directive.spec.ts
Labels: PR: reviewed-approved

#5537 [AAE-1895]Create card-view-boolean-item page
  e2e/pages/adf/card-view-component.page.ts
  lib/testing/src/lib/core/pages/card-view/card-view-boolean-item.page.ts
  lib/testing/src/lib/core/pages/card-view/public-api.ts
Labels: PR: reviewed-approved

#5529 [AAE-1953] Claim Reclaim Task AAE E2E
  e2e/process-services-cloud/config/task-filter.config.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/process-services-cloud/tasks-claim-release.e2e.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: reviewed-approved

#5539 [AAE-2126] Fix checkbox click testing method in datatable page
  lib/testing/src/lib/core/pages/data-table-component.page.ts
Labels: PR: reviewed-approved

#5483 [AAE-1846] [AAE-1857] automated e2e tests uploading folders
  e2e/content-services/upload/excluded-file.e2e.ts
  e2e/content-services/upload/upload-dialog.e2e.ts
  e2e/pages/adf/content-services.page.ts
  e2e/pages/adf/demo-shell/process-services/tasks-cloud-demo.page.ts
  e2e/pages/adf/dialog/share-dialog.page.ts
  e2e/pages/adf/dialog/upload-dialog.page.ts
  e2e/pages/adf/dialog/upload-toggles.page.ts
  e2e/pages/adf/process-services/dialog/app-settings-toggles.page.ts
  e2e/pages/adf/version-manager.page.ts
  e2e/util/resources.js
  lib/testing/src/lib/core/pages/login.page.ts
  lib/testing/src/lib/core/pages/public-api.ts
  lib/testing/src/lib/core/pages/viewer.page.ts
  lib/testing/src/lib/core/utils/browser-actions.ts
  lib/testing/src/lib/material/pages/public-api.ts
  lib/testing/src/lib/material/pages/toggle.page.ts
  scripts/test-e2e-lib.sh
  scripts/travis/e2e/content-services-e2e.sh
Labels: PR: reviewed-approved

#5545 [ADF-4522] Metadata value is not rolled back upon error
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
Labels: PR: reviewed-approved

#5544 [ADF-1895]Refactor date-time-picker and date-picker
  e2e/content-services/share-file/share-file.e2e.ts
  e2e/pages/adf/dialog/share-dialog.page.ts
  e2e/process-services/dynamic-table-date-picker.e2e.ts
  e2e/search/components/search-date-range.e2e.ts
  lib/testing/src/lib/content-services/pages/search/date-range-filter.page.ts
  lib/testing/src/lib/core/pages/card-view/card-view-boolean-item.page.ts
  lib/testing/src/lib/core/pages/card-view/card-view-date-item.page.ts
  lib/testing/src/lib/core/pages/card-view/public-api.ts
  lib/testing/src/lib/material/pages/date-picker-calendar.page.ts
  lib/testing/src/lib/material/pages/date-picker.page.ts
  lib/testing/src/lib/material/pages/date-time-picker-calendar.page.ts
  lib/testing/src/lib/material/pages/date-time-picker.page.ts
  lib/testing/src/lib/material/pages/public-api.ts
Labels: PR: reviewed-approved

#5542 [AAE-1923] Multilingual form unit test
  lib/process-services-cloud/karma.conf.js
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
  lib/process-services-cloud/src/lib/mock/en.json
  lib/process-services-cloud/src/lib/mock/fr.json
Labels: PR: reviewed-approved

#5439 ACA 2618 - 2619 - Share Dialog - Physical Labels
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.scss
  lib/content-services/src/lib/i18n/en.json
Labels: Accessibility, PR: reviewed-approved

#5540 [AAE-1923] Form APS E2E
  cspell.json
  e2e/actions/users.actions.ts
  e2e/pages/adf/process-services/task-details.page.ts
  e2e/process-services/dynamic-table-date-picker.e2e.ts
  e2e/process-services/stencil.e2e.ts
  e2e/process-services/task-details-form.e2e.ts
  e2e/process-services/widgets/dynamic-table-widget.e2e.ts
  e2e/process-services/widgets/people-group-widget.e2e.ts
  e2e/process-services/widgets/typeahead-widget.e2e.ts
  e2e/resources/apps/More Widgets.zip
  e2e/resources/apps/Stencil_app.zip
  e2e/resources/apps/WidgetApps.zip
  e2e/util/resources.js
  lib/core/form/components/widgets/functional-group/functional-group.widget.html
  lib/core/form/components/widgets/typeahead/typeahead.widget.html
  lib/core/form/components/widgets/typeahead/typeahead.widget.spec.ts
  lib/testing/src/lib/core/pages/form/widgets/dynamic-table-widget.page.ts
  lib/testing/src/lib/core/pages/form/widgets/group-widget.page.ts
  lib/testing/src/lib/core/pages/form/widgets/people-widget.page.ts
  lib/testing/src/lib/core/pages/form/widgets/typeahead-widget.page.ts
  lib/testing/src/lib/core/pages/form/widgets/widget.ts
Labels: PR: reviewed-approved

#5550 [ADF-4522] Metadata value is not rolled back upon error
  docs/core/services/card-view-update.service.md
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
  lib/core/card-view/components/base-card-view.ts
  lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.ts
  lib/core/card-view/components/card-view-boolitem/card-view-boolitem.component.spec.ts
  lib/core/card-view/components/card-view-boolitem/card-view-boolitem.component.ts
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
  lib/core/card-view/components/card-view-keyvaluepairsitem/card-view-keyvaluepairsitem.component.ts
  lib/core/card-view/components/card-view-mapitem/card-view-mapitem.component.ts
  lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
  lib/core/card-view/services/card-view-update.service.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
  lib/process-services/src/lib/task-list/components/task-details.component.ts
Labels: PR: reviewed-approved

#5547 AAE-1841 - added delete directive test
  demo-shell/src/app/components/files/files.component.html
  e2e/content-services/directives/delete-directive.e2e.ts
  e2e/pages/adf/content-services.page.ts
  lib/core/directives/node-delete.directive.ts
  lib/testing/src/lib/content-services/actions/permission.actions.ts
  lib/testing/src/lib/content-services/actions/public-api.ts
  lib/testing/src/lib/content-services/pages/document-list.page.ts
Labels: PR: reviewed-approved

#5553 Improve css prebuilt creation and minimize
  e2e/pages/adf/demo-shell/process-services/people-group-cloud-component.page.ts
  lib/config/bundle-scss.js
  lib/config/custom-loaders/file-loader-multi.js
  lib/config/webpack.style.js
  lib/testing/src/lib/material/pages/dropdown.page.ts
  lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
  package-lock.json
  package.json
  scripts/build/build-core.sh
Labels: PR: unreviewed

#5555 [AAE-1772]Add CardSelectItemPage PO
  lib/testing/src/lib/core/pages/card-view/card-view-select-item.page.ts
  lib/testing/src/lib/core/pages/card-view/public-api.ts
Labels: PR: reviewed-approved

#5454 [ACA-2619][ACA-2616] a11y fixes for Share Link dialog
  e2e/content-services/share-file/share-file.e2e.ts
  e2e/pages/adf/dialog/share-dialog.page.ts
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.spec.ts
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.ts
Labels: Accessibility, PR: reviewed-approved, PR: unreviewed

#5558 [ADF-5087] Document List - custom sources 'where' clause not passed
  docs/content-services/services/custom-resources.service.md
  lib/content-services/src/lib/document-list/services/custom-resources.service.ts
  lib/content-services/src/lib/document-list/services/document-list.service.ts
Labels: PR: reviewed-approved

#5546 [AAE-1579] Fixing the style of the prefix of amount widget
  lib/core/form/components/widgets/amount/amount.widget.scss
  lib/core/styles/_index.scss
Labels: PR: reviewed-approved

#5559 [ACA-2614] fix share link dialog header a11y
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
Labels: PR: reviewed-approved

#5560 [ACA-2566][ACA-2567] permissions a11y fixes
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/i18n/en.json
Labels: PR: unreviewed

#5399 [ACA-2789] - edit button a11y fixes
  lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.html
  lib/core/i18n/en.json
Labels: Accessibility, PR: reviewed-approved, PR: unreviewed

#5371 enforce types for forms cloud
  e2e/pages/adf/demo-shell/process-services/people-group-cloud-component.page.ts
  lib/process-services-cloud/src/lib/form/components/form-definition-selector-cloud.component.ts
  lib/process-services-cloud/src/lib/form/models/form-definition-selector-cloud.model.ts
  lib/process-services-cloud/src/lib/form/public-api.ts
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
  lib/process-services-cloud/src/lib/form/services/form-definition-selector-cloud.service.ts
  lib/process-services-cloud/src/lib/services/form-fields.interfaces.ts
  lib/process-services-cloud/src/lib/services/public-api.ts
Labels: PR: unreviewed

#5557 [ADF-4673] Add editable property to metadata config
  demo-shell/src/app.config.json
  docs/content-services/components/content-metadata-card.component.md
  lib/content-services/src/lib/content-metadata/interfaces/layout-oriented-config.interface.ts
  lib/content-services/src/lib/content-metadata/interfaces/property.interface.ts
  lib/content-services/src/lib/content-metadata/services/config/aspect-oriented-config.service.spec.ts
  lib/content-services/src/lib/content-metadata/services/config/aspect-oriented-config.service.ts
  lib/content-services/src/lib/content-metadata/services/config/layout-oriented-config.service.spec.ts
  lib/content-services/src/lib/content-metadata/services/config/layout-oriented-config.service.ts
  lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
  lib/core/app-config/schema.json
Labels: PR: reviewed-approved

#5551 [AAE-1725] ADF Task/Process filters - default filters should be recreated when they all get deleted
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
Labels: PR: reviewed-changes-requested

#5552 [ADF-4559] Add chips to multivalue metadata properties
  demo-shell/src/app.config.json
  docs/content-services/components/content-metadata-card.component.md
  docs/docassets/images/metadata-chips.png
  e2e/process-services-cloud/task-list-properties-sort.e2e.ts
  lib/core/app-config/schema.json
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
Labels: PR: unreviewed

#5563 calendar card item a11y fixes
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.html
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.scss
Labels: PR: reviewed-approved

#5556 [ADF-4341] Customise the property title into the InfoDrawer from configuration
  demo-shell/src/app.config.json
  docs/content-services/components/content-metadata-card.component.md
  docs/docassets/images/content-meta-data-custom-ptoperty-title.png
  lib/content-services/src/lib/content-metadata/interfaces/layout-oriented-config.interface.ts
  lib/content-services/src/lib/content-metadata/services/config/layout-oriented-config.service.spec.ts
  lib/content-services/src/lib/content-metadata/services/config/layout-oriented-config.service.ts
  lib/core/app-config/schema.json
Labels: PR: reviewed-approved

#5562 [ACA-2368] UI Issues while editing Metadata in the Preview Page #1091
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
  lib/core/viewer/components/viewer.component.spec.ts
  lib/core/viewer/components/viewer.component.ts
Labels: PR: reviewed-approved

#5565 [ADF-3726] Add copy to clipboard support to card view properties
  lib/core/card-view/card-view.module.ts
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.html
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
  lib/core/i18n/en.json
Labels: PR: reviewed-approved

#5567 [AAE-2198] Error thrown on start process with pre-selected multiple files on start form.
  lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
  lib/process-services/src/lib/process-list/components/start-process.component.ts
Labels: PR: reviewed-changes-requested

#5564 [ADF-4933] Adding keydown event on data row to simulate double click when pressing 'enter' key
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.ts
Labels: PR: reviewed-approved

#5568 [AAE-2041] [APS-1] [ADF] download process audit log not working
  lib/process-services/src/lib/process-list/components/process-audit.directive.spec.ts
  lib/process-services/src/lib/process-list/components/process-audit.directive.ts
  package-lock.json
  package.json
Labels: PR: partially-approved

#5572 [ADF-5092] Change card view label color
  lib/core/card-view/components/card-view/card-view.component.scss
Labels: PR: unreviewed

#5576 [ADF-5096] Icon on move dialog darker
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
Labels: PR: partially-approved

#5574 [ADF-5094] Changed focused chip color
  lib/content-services/src/lib/search/components/search-chip-list/search-chip-list.component.scss
  lib/content-services/src/lib/search/components/search-chip-list/search-chip-list.component.ts
  lib/content-services/src/lib/styles/_index.scss
Labels: PR: partially-approved

#5570 [ADF-5090] Change color of input button
  lib/core/login/components/login.component.html
Labels: PR: partially-approved

#5573 [ADF-5093] Change datepicker color
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.html
Labels: PR: unreviewed

#5571 [ADF-5091] Change info drawer labels color
  lib/core/info-drawer/info-drawer-layout.component.scss
Labels: PR: partially-approved

#5575 [ADF-5095] Update text color of share dialog
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.scss
  lib/content-services/src/lib/styles/_index.scss
Labels: PR: unreviewed

#5577 share link: fix regression with expiration toggle
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.ts
Labels: PR: partially-approved

#5580 Start process: Make the title optional
  demo-shell/src/app/components/process-service/process-service.component.html
  docs/process-services/components/start-process.component.md
  lib/process-services/src/lib/process-list/components/start-process.component.html
  lib/process-services/src/lib/process-list/components/start-process.component.scss
  lib/process-services/src/lib/process-list/components/start-process.component.ts
Labels: PR: unreviewed

#5579 [ACA-2956] Add event emitter when processDefinition selection changes…
  docs/process-services-cloud/components/start-process-cloud.component.md
  docs/process-services/components/start-process.component.md
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services/src/lib/process-list/components/start-process.component.html
  lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
  lib/process-services/src/lib/process-list/components/start-process.component.ts
Labels: PR: unreviewed

#5569 [AAE-2202] Not able to search for files
  demo-shell/src/app/components/content-node-selector/content-node-selector.component.html
  docs/content-services/components/content-metadata-card.component.md
  docs/content-services/components/content-node-selector-panel.component.md
  docs/content-services/services/content-node-dialog.service.md
  lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.service.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.service.ts
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog-component.interface.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.html
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.ts
Labels: PR: partially-approved

#5584 [ADF-5091] Fix undefined accent variable
  lib/core/info-drawer/info-drawer-layout.component.scss
Labels: PR: partially-approved

#5578 [ADF-3726] Enable/disable Copy to clipboard in Metadata from config
  demo-shell/src/app.config.json
  docs/content-services/components/content-metadata-card.component.md
  docs/core/components/card-view.component.md
  e2e/process-services-cloud/task-header-cloud.e2e.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
  lib/core/card-view/components/card-view-item-dispatcher/card-view-item-dispatcher.component.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
  lib/core/card-view/components/card-view/card-view.component.html
  lib/core/card-view/components/card-view/card-view.component.ts
Labels: PR: partially-approved
