Repository Alfresco/alfresco-ng2-components, pull requests merged in 2020-09, with the labels that each got.

#6090 [AAE-3338] Update simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#6085 [ACA-3441] Add method to attach file widget PO
  lib/testing/src/lib/core/pages/data-table/data-table-item.ts
  lib/testing/src/lib/core/pages/form/widgets/attach-file-widget.page.ts
  lib/testing/src/lib/process-services/pages/start-process.page.ts
Labels: PR: unreviewed

#6084 [AAE-3406] - Fix advanced search inside content-node selector
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.service.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.service.ts
Labels: PR: unreviewed

#6086 [ADF-5230] - Implement process date range filter
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.html
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.scss
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
  lib/process-services-cloud/src/lib/common/process-common.module.ts
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/process-filters-cloud.module.ts
Labels: PR: partially-approved

#6096 Remove excluded test
  e2e/content-services/directives/edit-folder-directive.e2e.ts
  e2e/content-services/document-list/document-list-pagination.e2e.ts
  e2e/core/infinite-scrolling.e2e.ts
  e2e/core/pages/content-services.page.ts
  e2e/core/pagination-empty-current-page.e2e.ts
  e2e/core/viewer/viewer-custom-toolbar-info-drawer.e2e.ts
  e2e/process-services/pages/task-details.page.ts
  e2e/process-services/people-component.e2e.ts
  e2e/process-services/process-list-component.e2e.ts
  e2e/process-services/start-task-custom-app.e2e.ts
  e2e/process-services/task-details-form.e2e.ts
  e2e/protractor.excludes.json
  e2e/resources/adf/allFileTypes/documents/text/a_cpio_file.cpio
  lib/process-services/src/lib/people/components/people-search-field/people-search-field.component.html
  lib/process-services/src/lib/people/components/people/people.component.html
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  lib/testing/src/lib/core/pages/form/form-fields.ts
  lib/testing/src/lib/core/pages/pagination.page.ts
  lib/testing/src/lib/core/pages/viewer.page.ts
  lib/testing/src/lib/core/utils/browser-actions.ts
  package-lock.json
  package.json
Labels: PR: partially-approved

#6099 [MNT-21636] - added redirection when SSO is enabled for external link
  lib/core/services/auth-guard-ecm.service.ts
Labels: PR: unreviewed

#6101 [ADF-4481] Fix Viewer peview for unsupported new versions
  lib/core/viewer/components/img-viewer.component.html
  lib/core/viewer/components/img-viewer.component.ts
  lib/core/viewer/components/media-player.component.html
  lib/core/viewer/components/media-player.component.ts
  lib/core/viewer/components/viewer.component.html
  lib/core/viewer/components/viewer.component.spec.ts
  lib/core/viewer/components/viewer.component.ts
Labels: PR: unreviewed

#6094 [AAE-3296] Add unit tests for Tooltips in Form Widgets
  lib/core/form/components/widgets/amount/amount.widget.spec.ts
  lib/core/form/components/widgets/checkbox/checkbox.widget.spec.ts
  lib/core/form/components/widgets/date-time/date-time.widget.spec.ts
  lib/core/form/components/widgets/hyperlink/hyperlink.widget.spec.ts
  lib/core/form/components/widgets/people/people.widget.spec.ts
  lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.spec.ts
  lib/core/form/components/widgets/text/text.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
Labels: PR: unreviewed

#5919 [ACA-3637] - Add dueDate range filter
  docs/process-services-cloud/components/task-list-cloud.component.md
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.html
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.spec.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.ts
  lib/process-services-cloud/src/lib/common/process-common.module.ts
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/models/date-cloud-filter.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.scss
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-filters/task-filters-cloud.module.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
Labels: PR: unreviewed

#6113 [ACA-3942] Enable assignee edit button only when userTask shared among the candidates
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
Labels: PR: partially-approved, do not merge, do not review

#6114 [MNT-21789] ADW - Disable ACS Thumbnail Generation cause ADF Upload Service to fail any file upload with 501 error
  demo-shell/src/app/components/process-service/process-attachments.component.ts
  demo-shell/src/app/components/process-service/task-attachments.component.ts
  lib/core/services/discovery-api.service.ts
  lib/core/services/upload.service.spec.ts
  lib/core/services/upload.service.ts
  lib/process-services/src/lib/task-list/services/process-upload.service.ts
  lib/process-services/src/lib/task-list/services/task-upload.service.ts
Labels: PR: partially-approved

#6102 include attach file test
  e2e/core/infinite-scrolling.e2e.ts
  e2e/core/pages/content-services.page.ts
  e2e/core/pagination-empty-current-page.e2e.ts
  e2e/process-services/attach-file-content-service.e2e.ts
  e2e/protractor.conf.js
  e2e/protractor.excludes.json
  lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  lib/testing/src/lib/core/pages/pagination.page.ts
Labels: PR: unreviewed

#6097 [ACA-3877] Add the possibility to ADF Extension to be used in compila…
  cspell.json
  lib/extensions/src/lib/config/action.extensions.ts
  lib/extensions/src/lib/config/extension.config.ts
  lib/extensions/src/lib/services/extension.service.spec.ts
  lib/extensions/src/lib/services/extension.service.ts
  lib/tsconfig.json
  tsconfig.json
Labels: PR: reviewed-approved

#6083 [Docs] cloud custom form widget examples
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/app.routes.ts
  demo-shell/src/app/components/app-layout/cloud/form-demo/cloud-form-demo.component.ts
  demo-shell/src/app/components/cloud/custom-form-components/sample-widget.component.ts
  demo-shell/src/app/components/cloud/process-cloud-layout.component.ts
Labels: PR: unreviewed

#5871 [ACA-3623] Process definition name filter in task list
  docs/process-services-cloud/components/process-list-cloud.component.md
  docs/process-services-cloud/services/start-process-cloud.service.md
  docs/process-services-cloud/services/task-cloud.service.md
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
Labels: PR: unreviewed

#6079 [AAE-3321] Select uploaded local files by default
  demo-shell/src/app/components/files/files.component.html
  demo-shell/src/app/components/files/files.component.scss
  demo-shell/src/app/components/files/files.component.ts
  docs/content-services/components/document-list.component.md
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/content-services/src/lib/document-list/data/share-datatable-adapter.spec.ts
  lib/content-services/src/lib/document-list/data/share-datatable-adapter.ts
  lib/content-services/src/lib/mock/document-list.component.mock.ts
Labels: PR: unreviewed

#6076 [ACA-3884]Attach cloud file - Ability to use the -appname- as placeholder in the destinationFolder
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
Labels: PR: partially-approved

#6130 updated outcomebuttons process
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: partially-approved

#6126 [AAE-3507] ADF - Change default destination folder alias -root- to -my-
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
Labels: PR: partially-approved

#6143 [ACA-3884] AttachFileCloud - Pass the replaced value
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
Labels: PR: partially-approved

#6144 Sanity check - Be able to pass params
  lib/cli/scripts/check-cs-env.ts
Labels: PR: unreviewed

#6137 [ADF-5237] Unexclude C362240 and C362241
  e2e/protractor.excludes.json
  lib/core/services/version-compatibility.service.spec.ts
  lib/core/services/version-compatibility.service.ts
Labels: PR: partially-approved

#5931 [ACA-3722] - rename process name sort option
  e2e/process-services-cloud/edit-process-filters-component.e2e.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.html
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
Labels: PR: partially-approved

#6148 [ACA-3973] K8s image - fetch all the namespaces and handle the missing container
  lib/cli/scripts/kubectl-image.ts
Labels: PR: partially-approved

#6142 [AAE-3514] Create file viewer widget
  lib/core/form/components/widgets/core/form-field-types.ts
  lib/core/form/components/widgets/core/form.model.spec.ts
  lib/core/form/components/widgets/core/form.model.ts
  lib/core/form/components/widgets/core/index.ts
  lib/core/form/components/widgets/core/upload-widget-content-link.model.ts
  lib/core/form/components/widgets/file-viewer/file-viewer.widget.html
  lib/core/form/components/widgets/file-viewer/file-viewer.widget.scss
  lib/core/form/components/widgets/file-viewer/file-viewer.widget.ts
  lib/core/form/components/widgets/index.ts
  lib/core/form/form-base.module.ts
  lib/core/form/services/form-rendering.service.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.scss
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
  lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
  lib/process-services-cloud/src/lib/services/form-fields.interfaces.ts
  lib/process-services-cloud/src/lib/styles/_index.scss
Labels: PR: partially-approved

#6147 [ADF-5245] Fix C297478, C297485 and C297472
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/process-services-cloud/task-list-selection.e2e.ts
  e2e/protractor.excludes.json
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
Labels: PR: partially-approved

#6149 [ADF-5241] [ADF-5243] [ADF-5244] Fix C291954, C291955, C291993 and C291995
  e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts
  e2e/process-services-cloud/start-task/start-task-group-cloud.e2e.ts
Labels: PR: unreviewed

#6128 [ACA-3637] - DueDate filter fix translation and add missing option
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
Labels: PR: unreviewed

#6131 [AAE-3469] New Service Task List in Task List Cloud Component
  demo-shell/resources/i18n/en.json
  demo-shell/src/app.config.json
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/app.routes.ts
  demo-shell/src/app/components/app-layout/app-layout.component.ts
  demo-shell/src/app/components/cloud/service-task-list-cloud-demo.component.html
  demo-shell/src/app/components/cloud/service-task-list-cloud-demo.component.ts
  docs/process-services-cloud/components/edit-task-filter-cloud.component.md
  docs/process-services-cloud/components/task-list-cloud.component.md
  lib/core/datatable/data/data-table.schema.ts
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/mock/task-filters-cloud.mock.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/mock/fake-task-response.mock.ts
  lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
  lib/process-services-cloud/src/lib/task/task-list/models/task-preset-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
Labels: PR: partially-approved, needs rebase

#6150 [ACA-3899] Viewer thumbnails cannot be accessed by keyboard
  lib/core/i18n/en.json
  lib/core/viewer/components/pdf-viewer-thumb.component.html
  lib/core/viewer/components/pdf-viewer-thumb.component.spec.ts
  lib/core/viewer/components/pdf-viewer-thumb.component.ts
  lib/core/viewer/components/pdf-viewer-thumbnails.component.html
  lib/core/viewer/components/pdf-viewer-thumbnails.component.scss
  lib/core/viewer/components/pdf-viewer-thumbnails.component.spec.ts
  lib/core/viewer/components/pdf-viewer-thumbnails.component.ts
  lib/core/viewer/components/pdf-viewer.component.html
  lib/core/viewer/components/pdf-viewer.component.ts
Labels: Accessibility, PR: partially-approved, PR: unreviewed

#5953 [ADF-3499] Make Card View Text Item reactive to user input
  lib/core/card-view/card-view.module.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
Labels: PR: unreviewed

#6154 Revert "[AAE-3469] New Service Task List in Task List Cloud Component"
  demo-shell/resources/i18n/en.json
  demo-shell/src/app.config.json
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/app.routes.ts
  demo-shell/src/app/components/app-layout/app-layout.component.ts
  demo-shell/src/app/components/cloud/service-task-list-cloud-demo.component.html
  demo-shell/src/app/components/cloud/service-task-list-cloud-demo.component.ts
  docs/process-services-cloud/components/edit-task-filter-cloud.component.md
  docs/process-services-cloud/components/task-list-cloud.component.md
  lib/core/datatable/data/data-table.schema.ts
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/mock/task-filters-cloud.mock.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/mock/fake-task-response.mock.ts
  lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
  lib/process-services-cloud/src/lib/task/task-list/models/task-preset-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
Labels: PR: unreviewed

#6155 [ACA-3973] K8s - namespaces - Replace all the occurrences
  lib/cli/scripts/kubectl-image.ts
Labels: PR: partially-approved

#6146 Test improve
  .travis.yml
  e2e/content-services/directives/favorite-directive.e2e.ts
  e2e/core/pages/login-shell.page.ts
  e2e/core/pages/notification.page.ts
  e2e/core/settings-component.e2e.ts
  e2e/process-services-cloud/task-list-properties.e2e.ts
  e2e/process-services/custom-tasks-filters.e2e.ts
  e2e/search/components/search-check-list.e2e.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  lib/testing/src/lib/core/pages/login.page.ts
  lib/testing/src/lib/core/pages/snackbar.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
Labels: PR: unreviewed

#6093 [ACA-3683] - implement started date process filter
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
  lib/process-services-cloud/src/lib/models/date-cloud-filter.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
Labels: PR: unreviewed

#6152 Update protractor.excludes.json
  e2e/protractor.excludes.json
Labels: PR: partially-approved

#6145 [ACA-3692] - Add completed date/due date/started date filter
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.html
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.spec.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.ts
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  scripts/lint.sh
Labels: PR: unreviewed

#6156 Test improve
  lib/testing/src/lib/core/pages/login.page.ts
  lib/testing/src/lib/process-services/pages/start-process.page.ts
Labels: PR: partially-approved

#6138 [ADF-5236] C246534 Failing
  e2e/process-services/attach-file-content-service.e2e.ts
  e2e/process-services/attach-folder.e2e.ts
  e2e/protractor.excludes.json
  lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
  lib/testing/src/lib/core/actions/api.service.ts
  lib/testing/src/lib/core/actions/public-api.ts
  lib/testing/src/lib/core/actions/search.service.ts
Labels: PR: unreviewed

#6078 [MNT-21705] - fixed column display for fields
  docs/process-services/components/form.component.md
  lib/core/form/components/form-renderer.component.spec.ts
  lib/core/form/components/widgets/container/container.widget.html
  lib/core/form/components/widgets/container/container.widget.scss
  lib/core/form/components/widgets/container/container.widget.spec.ts
  lib/core/form/components/widgets/container/container.widget.ts
  lib/core/form/components/widgets/core/form.model.ts
  lib/core/form/services/form.service.ts
  lib/process-services/src/lib/form/form.component.ts
Labels: PR: partially-approved

#6157 [ACA-3977] FE - Integrate new user assign API
  docs/process-services-cloud/services/task-cloud.service.md
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
Labels: PR: partially-approved

#5924 [ACA-3643] - add completedBy filter on tasks
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-filters/task-filters-cloud.module.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
Labels: PR: unreviewed

#6098 [ACA-3312] Add user-filter util class
  lib/testing/src/lib/process-services/actions/public-api.ts
  lib/testing/src/lib/process-services/actions/user-filters.util.ts
  lib/testing/src/lib/process-services/pages/filters.page.ts
  lib/testing/src/lib/process-services/pages/process-filters.page.ts
  lib/testing/src/lib/process-services/pages/process-list.page.ts
  lib/testing/src/lib/process-services/pages/task-filters.page.ts
Labels: PR: unreviewed

#6092 [ADF-5219] Refactor Document list Filters
  demo-shell/src/app/components/files/files.component.html
  demo-shell/src/app/components/files/files.component.ts
  demo-shell/src/app/components/files/filtered-search.component.html
  demo-shell/src/app/components/files/filtered-search.component.ts
  docs/content-services/components/document-list.component.md
  docs/content-services/components/search-header.component.md
  docs/docassets/images/header-filters.png
  docs/upgrade-guide/upgrade40-41.md
  lib/content-services/src/lib/breadcrumb/dropdown-breadcrumb.component.spec.ts
  lib/content-services/src/lib/document-list/components/document-list.component.html
  lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/content-services/src/lib/document-list/components/filter-header/filter-header.component.html
  lib/content-services/src/lib/document-list/components/filter-header/filter-header.component.spec.ts
  lib/content-services/src/lib/document-list/components/filter-header/filter-header.component.ts
  lib/content-services/src/lib/document-list/document-list.module.ts
  lib/content-services/src/lib/search/base-query-builder.service.ts
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.html
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.scss
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.html
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
  lib/content-services/src/lib/search/filter-search.interface.ts
  lib/content-services/src/lib/search/public-api.ts
  lib/content-services/src/lib/search/search-filter-query-builder.service.spec.ts
  lib/content-services/src/lib/search/search-filter-query-builder.service.ts
  lib/content-services/src/lib/search/search.module.ts
  lib/content-services/src/lib/styles/_index.scss
  lib/core/datatable/datatable.module.ts
  lib/core/datatable/public-api.ts
Labels: PR: partially-approved

#6159 [ACA-3960] FE - Users that are part of a candidate group should not be able to see 'Assignee' property as editable when on that user task candidate group was set as assignment
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
Labels: PR: unreviewed, do not merge

#6158 [AAE-3493] Update the documentation to provide the proper guidance on custom forms widgets for APA and APS developers
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/components/app-layout/cloud/form-demo/cloud-form-demo.component.ts
  demo-shell/src/app/components/cloud/custom-form-components/custom-editor.component.ts
  demo-shell/src/app/components/cloud/process-cloud-layout.component.ts
  docs/docassets/images/aae-form-widget.png
  docs/docassets/images/aae-form-with-widget.png
  docs/docassets/images/aae-resolved-widget.png
  docs/docassets/images/aae-simple-form.png
  docs/docassets/images/aae-simple-override-form.png
  docs/docassets/images/aae-unresolved-widget.png
  docs/user-guide/aae-extensions.md
  docs/user-guide/aps-extensions.md
  docs/user-guide/extensibility.md
Labels: PR: partially-approved

#6164 [ACA-3903] DocumentList - header filters are missing aria-labels
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.html
Labels: PR: partially-approved

#6165 [ACA-3689] Update customize filter locator
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
Labels: PR: partially-approved

#6166 [ADF-5219] Fix Production Build
  docs/upgrade-guide/upgrade40-41.md
  lib/content-services/src/lib/document-list/components/filter-header/filter-header.component.spec.ts
  lib/content-services/src/lib/document-list/components/filter-header/filter-header.component.ts
  lib/content-services/src/lib/document-list/public-api.ts
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.ts
  lib/content-services/src/lib/search/public-api.ts
  lib/content-services/src/lib/search/search-header-query-builder.service.spec.ts
  lib/content-services/src/lib/search/search-header-query-builder.service.ts
Labels: PR: partially-approved

#6153 Ole tutorial updates
  PREREQUISITES.md
  README.md
  docs/abn-tree.yml
  docs/tutorials/README.md
  docs/tutorials/activiti-7-and-adf.md
  docs/tutorials/basic-theming.md
  docs/tutorials/creating-javascript-app-using-alfresco-js-api.md
  docs/tutorials/creating-the-app-using-yeoman.md
  docs/tutorials/creating-your-first-adf-application.md
  docs/tutorials/customising-login.md
  docs/tutorials/preparing-environment.md
  docs/tutorials/using-components.md
  docs/tutorials/working-with-nodes-api-service.md
  docs/user-guide/summary.json
Labels: PR: partially-approved

#6160 [AAE-3410] NodeSelector - Use user alias (-my-) name as default for upload of type Alfresco Content only
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
Labels: PR: partially-approved

#6167 Test improve 2
  .travis.yml
  e2e/content-services/directives/edit-folder-directive.e2e.ts
  e2e/content-services/directives/favorite-directive.e2e.ts
  e2e/content-services/version/version-properties.e2e.ts
  e2e/core/pages/navigation-bar.page.ts
  e2e/lite-server-proxy.js
  e2e/process-services/custom-tasks-filters.e2e.ts
  e2e/process-services/pages/task-list-demo.page.ts
  e2e/protractor.conf.js
  lib/content-services/src/lib/permission-manager/services/node-permission.service.ts
  package-lock.json
  package.json
Labels: PR: unreviewed

#6173 [AAE-3469] Expose ServiceTaskListCloudComponent in public api
  lib/process-services-cloud/src/lib/task/task-filters/public-api.ts
Labels: PR: unreviewed

#6175 Expose ServiceTaskFilterCloudService in public API
  lib/process-services-cloud/src/lib/task/task-filters/public-api.ts
Labels: PR: unreviewed

#6174 [AAE-3651] FE - Export DateCloudFilterType from process-services-cloud lib
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/public-api.ts
Labels: PR: partially-approved

#6177 Added switch to be able to check the form behaviour
  demo-shell/src/app/components/form/form.component.html
  demo-shell/src/app/components/form/form.component.ts
  demo-shell/src/app/services/in-memory-form.service.ts
Labels: PR: partially-approved

#6180 Fix broken e2e tests because of the lack of thrown error
  lib/testing/src/lib/core/pages/data-table-component.page.ts
Labels: PR: partially-approved

#6181 fix rxjs imports
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
  lib/core/dialogs/download-zip/download-zip.dialog.spec.ts
  lib/core/login/components/login.component.spec.ts
Labels: PR: partially-approved

#6182 Update candidatebaseapp for variable mapping in tasks to work
  e2e/resources/activiti7/candidatebaseapp.zip
Labels: PR: partially-approved

#6184 [ADF-5260] Fix Service task list initialization in DemoShell
  demo-shell/src/app/components/cloud/service-task-list-cloud-demo.component.html
  demo-shell/src/app/components/cloud/service-task-list-cloud-demo.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/service-task-filter-cloud.service.ts
  lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.ts
Labels: PR: partially-approved

#6141 [ADF-4481] e2e test for uploading an unsupported file
  e2e/core/viewer/viewer-content-services-component.e2e.ts
Labels: PR: partially-approved

#6185 [ACA-3626] Cloud Task - completed date filter
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
Labels: PR: partially-approved

#6176 [ACA-3689] Update edit-process-filter-cloud-component PO
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
Labels: PR: partially-approved

#6191 LOC-258_Localised UI files for ADF 4.1 in 16 languages
  demo-shell/resources/i18n/ar.json
  demo-shell/resources/i18n/cs.json
  demo-shell/resources/i18n/da.json
  demo-shell/resources/i18n/de.json
  demo-shell/resources/i18n/fr.json
  demo-shell/resources/i18n/it.json
  demo-shell/resources/i18n/ja.json
  demo-shell/resources/i18n/nb.json
  demo-shell/resources/i18n/nl.json
  demo-shell/resources/i18n/pl.json
  demo-shell/resources/i18n/sv.json
  demo-shell/resources/i18n/zh-CN.json
  lib/content-services/src/lib/i18n/fr.json
  lib/core/i18n/ar.json
  lib/core/i18n/cs.json
  lib/core/i18n/da.json
  lib/core/i18n/de.json
  lib/core/i18n/es.json
  lib/core/i18n/fi.json
  lib/core/i18n/fr.json
  lib/core/i18n/it.json
  lib/core/i18n/ja.json
  lib/core/i18n/nb.json
  lib/core/i18n/nl.json
  lib/core/i18n/pl.json
  lib/core/i18n/pt-BR.json
  lib/core/i18n/ru.json
  lib/core/i18n/sv.json
  lib/core/i18n/zh-CN.json
  lib/insights/src/lib/i18n/nl.json
  lib/process-services-cloud/src/lib/i18n/ar.json
  lib/process-services-cloud/src/lib/i18n/cs.json
  lib/process-services-cloud/src/lib/i18n/da.json
  lib/process-services-cloud/src/lib/i18n/de.json
  lib/process-services-cloud/src/lib/i18n/es.json
  lib/process-services-cloud/src/lib/i18n/fi.json
  lib/process-services-cloud/src/lib/i18n/fr.json
  lib/process-services-cloud/src/lib/i18n/it.json
  lib/process-services-cloud/src/lib/i18n/ja.json
  lib/process-services-cloud/src/lib/i18n/nb.json
  lib/process-services-cloud/src/lib/i18n/nl.json
  lib/process-services-cloud/src/lib/i18n/pl.json
  lib/process-services-cloud/src/lib/i18n/pt-BR.json
  lib/process-services-cloud/src/lib/i18n/ru.json
  lib/process-services-cloud/src/lib/i18n/sv.json
  lib/process-services-cloud/src/lib/i18n/zh-CN.json
  lib/process-services/src/lib/i18n/it.json
  lib/process-services/src/lib/i18n/nl.json
Labels: PR: partially-approved

#6190 [ACA-3957] Added correct Icon for save-as button in task filter and p…
  lib/core/assets/images/save-as.svg
  lib/core/services/thumbnail.service.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
Labels: PR: partially-approved
