Repository Alfresco/alfresco-ng2-components, pull requests merged in 2020-04, with the labels that each got.

#5585 fix shared link dialog regressions
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.ts
Labels: PR: partially-approved

#5583 [AAE-2200] Fix upload dialog title
  lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
  lib/content-services/src/lib/i18n/en.json
Labels: PR: partially-approved

#5586 [ADF-5101] Change empty folder text display colors
  lib/content-services/src/lib/document-list/components/document-list.component.scss
Labels: PR: partially-approved

#5587 share link: add time debouncing
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.spec.ts
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.ts
Labels: PR: unreviewed

#5589 [ADF-4264] Fixed the breadcrumb when changing to custom site in node selector
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/core/datatable/components/datatable/datatable.component.scss
Labels: PR: partially-approved

#5590 [ADF-5102] Added indeterminate state for 'select all' in datatable
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.ts
Labels: PR: partially-approved

#5591 [ADF-1881] Consolidate NodeService and NodesApiService
  docs/core/services/node.service.md
  docs/core/services/nodes-api.service.md
  lib/core/form/services/node.service.spec.ts
  lib/core/form/services/node.service.ts
  lib/core/models/node-metadata.model.ts
  lib/core/models/public-api.ts
  lib/core/services/nodes-api.service.spec.ts
  lib/core/services/nodes-api.service.ts
Labels: PR: partially-approved

#5595 [ADF-5104] Change color of location text
  lib/content-services/src/lib/content-node-selector/name-location-cell/name-location-cell.component.scss
Labels: PR: partially-approved

#5597 [ADF-5105] Force color of header button of upload dialog
  lib/content-services/src/lib/upload/components/file-uploading-dialog.component.scss
Labels: PR: partially-approved

#5598 Ability to check if loggedIn based on provider
  lib/core/services/authentication.service.spec.ts
  lib/core/services/authentication.service.ts
  lib/extensions/src/lib/config/navbar.extensions.ts
  lib/extensions/src/lib/config/schema/plugin-extension.schema.json
Labels: PR: partially-approved

#5594 [AAE-2200] Add dynamic title to attach-file-widget-dialog
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.html
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.spec.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.ts
  lib/process-services/src/lib/i18n/en.json
Labels: PR: partially-approved

#5593 [ACA-2983] Changed the labels from the inputs name and type to always floating
  lib/process-services/src/lib/process-list/components/start-process.component.html
  lib/process-services/src/lib/process-list/components/start-process.component.scss
  lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
  lib/process-services/src/lib/process-list/components/start-process.component.ts
  lib/process-services/src/lib/styles/_index.scss
Labels: PR: unreviewed

#5600 Review Documentation and tools doc
  docs/README.md
  docs/content-services/components/content-metadata-card.component.md
  docs/content-services/components/content-node-selector-panel.component.md
  docs/content-services/services/custom-resources.service.md
  docs/content-services/services/document-actions.service.md
  docs/content-services/services/folder-actions.service.md
  docs/core/components/card-view.component.md
  docs/core/components/icon.component.md
  docs/core/components/toolbar.component.md
  docs/core/components/user-info.component.md
  docs/core/services/authentication.service.md
  docs/core/services/upload.service.md
  docs/process-services-cloud/components/form-cloud.component.md
  docs/process-services-cloud/components/group-cloud.component.md
  docs/process-services-cloud/components/people-cloud.component.md
  docs/process-services-cloud/components/start-process-cloud.component.md
  docs/process-services-cloud/services/local-preference-cloud.service.md
  docs/process-services-cloud/services/start-process-cloud.service.md
  docs/process-services/components/start-process.component.md
  docs/roadmap.md
  docs/tutorials/README.md
  docs/versionIndex.md
  lib/content-services/src/lib/document-list/services/custom-resources.service.ts
  lib/process-services-cloud/src/lib/services/local-preference-cloud.service.ts
  lib/process-services/src/lib/process-list/components/start-process.component.ts
  package-lock.json
  package.json
  tools/doc/ReviewCheckerGuide.md
  tools/doc/docProcessor.js
  tools/doc/doctool.config.json
  tools/doc/reviewChecker.js
  tools/doc/reviewChecker.ts
  tools/doc/sourceInfoClasses.js
  tools/doc/sourceInfoClasses.ts
  tools/doc/tools/fileChecker.js
  tools/doc/tools/fileChecker.ts
  tools/doc/tools/linkFixer.js
  tools/doc/tools/linkFixer.ts
  tools/doc/tools/tsInfo.js
  tools/doc/tools/tsInfo.ts
  tools/doc/tools/versionIndex.js
  tools/doc/tsconfig.json
Labels: PR: unreviewed

#5596 [ACA-3000][ACA-2999] FE - Provide way to show ContextMenu on Task/Process list
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/components/process-service/process-service.component.html
  demo-shell/src/app/components/process-service/process-service.component.ts
  docs/docassets/images/process-instance-list-context-menu.png
  docs/docassets/images/task-list-context-menu.png
  docs/process-services/components/process-list.component.md
  docs/process-services/components/task-list.component.md
  lib/process-services/src/lib/process-list/components/process-list.component.html
  lib/process-services/src/lib/process-list/components/process-list.component.spec.ts
  lib/process-services/src/lib/process-list/components/process-list.component.ts
  lib/process-services/src/lib/task-list/components/task-list.component.html
  lib/process-services/src/lib/task-list/components/task-list.component.spec.ts
  lib/process-services/src/lib/task-list/components/task-list.component.ts
Labels: PR: partially-approved

#5604 [#5561] Translate notification action value
  lib/core/notifications/services/notification.service.spec.ts
  lib/core/notifications/services/notification.service.ts
Labels: PR: partially-approved

#5605 [ACA-2493] Fix disabled create folder button color
  lib/content-services/src/lib/dialogs/folder.dialog.scss
Labels: PR: partially-approved

#5609 [ACA-2476] Fix color contrast in mat-calendar and mat-datetimepicker-calendar
  lib/core/styles/_index.scss
  lib/core/styles/_mixins.scss
Labels: PR: unreviewed

#5606 [AAE-1929] Attach Folder APS1 E2E
  e2e/process-services/attach-folder.e2e.ts
  e2e/resources/apps/WidgetApps.zip
  e2e/util/resources.js
  lib/testing/src/lib/core/actions/APS/integration.service.ts
  lib/testing/src/lib/core/actions/APS/public-api.ts
  lib/testing/src/lib/core/pages/form/widgets/attach-folder-widget.page.ts
  lib/testing/src/lib/core/pages/form/widgets/widget.ts
Labels: PR: partially-approved

#5612 Fix people-group-cloud-filter-component.e2e.ts
  e2e/process-services-cloud/people-group-cloud-component.e2e.ts
Labels: PR: partially-approved

#5613 [ADF-5114] Change dialog action button color
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-dialog.component.scss
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.scss
Labels: PR: partially-approved

#5617 [ACA-2523] Change comment colors
  lib/core/comments/comment-list.component.scss
Labels: PR: partially-approved

#5615 [ACA-2520] Opacity of tab label of info drawer set to 1
  lib/core/info-drawer/info-drawer-layout.component.scss
Labels: PR: partially-approved

#5610 [ACA-2948] Add API to fetch the bpm properties
  lib/core/mock/alfresco-api.service.mock.ts
  lib/core/services/alfresco-api.service.ts
  lib/core/services/discovery-api.service.spec.ts
  lib/core/services/discovery-api.service.ts
  lib/core/services/user-preferences.service.ts
  package-lock.json
  package.json
Labels: PR: partially-approved

#5622 [ACA-2734] Fix API - Return an error in case the response isn't a json
  lib/core/services/discovery-api.service.ts
Labels: PR: partially-approved

#5620 [ADF-5116] Make ADF's pipeline GREEN again
  e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
  e2e/process-services-cloud/process-filter-results.e2e.ts
  e2e/process-services-cloud/process-filters-cloud.e2e.ts
  e2e/process-services-cloud/process-header-cloud.e2e.ts
  e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts
  e2e/process-services-cloud/process-list-selection-cloud.e2e.ts
  e2e/process-services-cloud/start-process-cloud.e2e.ts
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  e2e/protractor.excludes.json
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
Labels: PR: unreviewed

#5543 [AAE-1948] Form Attach File cloud widget E2E
  e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
  lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
  lib/testing/src/lib/process-services-cloud/resources/resources.ts
Labels: PR: unreviewed, needs rebase

#5621 [ACA-2577] Change color of dropdown-breadcrumb current folder
  lib/content-services/src/lib/breadcrumb/dropdown-breadcrumb.component.scss
Labels: PR: unreviewed, needs rebase

#5618 [ACA-2556] Change checking and welcome colors in login button
  lib/core/login/components/login.component.scss
Labels: PR: partially-approved, needs rebase

#5616 [AAE-2321] Should not be able to start a process with space as name (Process Services)
  lib/process-services/src/lib/i18n/en.json
  lib/process-services/src/lib/process-list/components/start-process.component.html
  lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
  lib/process-services/src/lib/process-list/components/start-process.component.ts
Labels: PR: partially-approved

#5624 Fix E2E run
  e2e/content-services/directives/delete-directive.e2e.ts
  e2e/process-services-cloud/task-header-cloud.e2e.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
  e2e/protractor.excludes.json
  e2e/protractor/save-remote.js
  e2e/test.config.js
  lib/testing/src/lib/core/pages/card-view/card-view-text-item.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-header-cloud-component.page.ts
  package-lock.json
  package.json
  protractor.conf.ts
  scripts/test-e2e-lib.sh
  scripts/travis/e2e/content-services-e2e.sh
  scripts/travis/e2e/process-services-cloud-e2e.sh
Labels: PR: unreviewed

#5603 [ACA-3020] Start process on process cloud updated the labels (always floating)
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.scss
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/styles/_index.scss
Labels: PR: unreviewed, needs rebase

#5626 better retry strategy for query service e2e
  e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/process-filter-results.e2e.ts
  e2e/process-services-cloud/process-filters-cloud.e2e.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
  e2e/protractor.excludes.json
  e2e/protractor/override-jasmine.js
  lib/testing/src/lib/core/actions/identity/query.service.ts
  protractor.conf.ts
Labels: PR: partially-approved

#5619 [ACA-3080] Remove selecting first filter by default when no defaults …
  demo-shell/src/app/components/cloud/cloud-filters-demo.component.ts
  demo-shell/src/app/components/cloud/processes-cloud-demo.component.ts
  demo-shell/src/app/components/cloud/tasks-cloud-demo.component.ts
  docs/process-services-cloud/components/process-filters-cloud.component.md
  docs/process-services-cloud/components/task-filters-cloud.component.md
  docs/process-services/components/process-filters.component.md
  docs/process-services/components/task-filters.component.md
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
  lib/process-services/src/lib/process-list/components/process-filters.component.spec.ts
  lib/process-services/src/lib/process-list/components/process-filters.component.ts
  lib/process-services/src/lib/task-list/components/task-filters.component.spec.ts
  lib/process-services/src/lib/task-list/components/task-filters.component.ts
Labels: PR: unreviewed

#5601 [ADF-5106] allow to redefine form widgets (APS 1.x and cloud)
  lib/core/form/components/form-base.component.ts
  lib/process-services-cloud/src/lib/form/components/cloud-form-rendering.service.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.ts
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
  lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.ts
  lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts
  lib/process-services-cloud/src/lib/form/public-api.ts
  lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
  lib/process-services/src/lib/content-widget/attach-folder-widget.component.ts
  lib/process-services/src/lib/form/form.component.spec.ts
  lib/process-services/src/lib/form/form.component.ts
  lib/process-services/src/lib/form/process-form-rendering.service.ts
  lib/process-services/src/lib/form/public-api.ts
  lib/process-services/src/lib/form/start-form.component.ts
Labels: PR: unreviewed

#5627 [ACA-2523] Update comment text colors
  lib/core/comments/comment-list.component.scss
Labels: PR: partially-approved

#5623 [AAE-1936] Attach File E2E APS1
  e2e/process-services/attach-file-content-service.e2e.ts
  e2e/process-services/attach-file-widget.e2e.ts
  e2e/process-services/attach-folder.e2e.ts
  e2e/process-services/widgets/attach-file-widget.e2e.ts
  e2e/resources/apps/WidgetApps.zip
  e2e/test.config.js
  e2e/util/resources.js
  lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
  lib/testing/src/lib/core/actions/APS/integration.service.ts
  lib/testing/src/lib/core/pages/form/widgets/attach-file-widget.page.ts
  lib/testing/src/lib/process-services/pages/external-node-selector-dialog.page.ts
  lib/testing/src/lib/process-services/pages/public-api.ts
  lib/testing/src/lib/test.configuration.ts
Labels: PR: partially-approved

#5611 [ACA-30333]FE - [Process-services] Create ADF task form.
  demo-shell/src/app/components/process-service/process-service.component.html
  docs/process-services/components/task-form.component.md
  e2e/pages/adf/process-services/attach-form.page.ts
  e2e/pages/adf/process-services/task-details.page.ts
  e2e/process-services/attach-folder.e2e.ts
  e2e/process-services/attach-form-component.e2e.ts
  e2e/process-services/standalone-task.e2e.ts
  e2e/process-services/task-details-form.e2e.ts
  lib/process-services/src/lib/i18n/en.json
  lib/process-services/src/lib/mock/task/task-details.mock.ts
  lib/process-services/src/lib/styles/_index.scss
  lib/process-services/src/lib/task-list/components/attach-form.component.html
  lib/process-services/src/lib/task-list/components/attach-form.component.scss
  lib/process-services/src/lib/task-list/components/attach-form.component.spec.ts
  lib/process-services/src/lib/task-list/components/no-task-detail-template.directive.spec.ts
  lib/process-services/src/lib/task-list/components/task-details.component.html
  lib/process-services/src/lib/task-list/components/task-details.component.spec.ts
  lib/process-services/src/lib/task-list/components/task-details.component.ts
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.html
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.scss
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.spec.ts
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.ts
  lib/process-services/src/lib/task-list/public-api.ts
  lib/process-services/src/lib/task-list/task-list.module.ts
  lib/testing/src/lib/core/pages/form/form-fields.ts
  lib/testing/src/lib/process-services/pages/form-fields.page.ts
Labels: PR: unreviewed

#5630 [ACA-3170]Task/Process Add the sticky header feature
  docs/process-services/components/process-list.component.md
  docs/process-services/components/task-list.component.md
  lib/process-services/src/lib/process-list/components/process-list.component.html
  lib/process-services/src/lib/process-list/components/process-list.component.ts
  lib/process-services/src/lib/task-list/components/task-list.component.html
  lib/process-services/src/lib/task-list/components/task-list.component.ts
Labels: PR: partially-approved

#5631 [ACA-3174] Add custom icons for processes and tasks
  lib/core/assets/images/dynamic_feed-24px.svg
  lib/core/assets/images/ic-process.svg
  lib/core/services/thumbnail.service.ts
Labels: PR: partially-approved

#5628 [ADF-5118] Enable E2E
  e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
  e2e/process-services-cloud/process-custom-filters.e2e.ts
  e2e/process-services-cloud/process-header-cloud.e2e.ts
  e2e/process-services-cloud/process-list-selection-cloud.e2e.ts
  e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  e2e/process-services-cloud/tasks-custom-filters.e2e.ts
  e2e/protractor.excludes.json
  lib/testing/src/lib/core/actions/identity/group-identity.service.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/process-header-cloud-component.page.ts
Labels: PR: unreviewed, do not merge

#5629 [ACA-3023]Refactor APS1 PO and ACS API calls of ADF testing package
  e2e/content-services/comments/comment-component.e2e.ts
  e2e/content-services/directives/delete-directive.e2e.ts
  e2e/content-services/directives/download-directive.e2e.ts
  e2e/content-services/directives/edit-folder-directive.e2e.ts
  e2e/content-services/directives/favorite-directive.e2e.ts
  e2e/content-services/directives/restore-content-directive.e2e.ts
  e2e/content-services/document-list/document-list-actions.e2e.ts
  e2e/content-services/document-list/document-list-component.e2e.ts
  e2e/content-services/document-list/document-list-copy-move-actions.e2e.ts
  e2e/content-services/document-list/document-list-gallery.e2e.ts
  e2e/content-services/document-list/document-list-thumbnails-tooltips.e2e.ts
  e2e/content-services/lock-file.e2e.ts
  e2e/content-services/metadata/aspect-oriented-config.e2e.ts
  e2e/content-services/metadata/metadata-permissions.e2e.ts
  e2e/content-services/metadata/metadata-properties.e2e.ts
  e2e/content-services/metadata/metadata-smoke-tests.e2e.ts
  e2e/content-services/permissions/permissions-component.e2e.ts
  e2e/content-services/permissions/site-permissions.e2e.ts
  e2e/content-services/share-file/share-file.e2e.ts
  e2e/content-services/share-file/unshare-file.e2e.ts
  e2e/content-services/social/social.component.e2e.ts
  e2e/content-services/sso/sso-download-directive-component.e2e.ts
  e2e/content-services/upload/uploader-component.e2e.ts
  e2e/content-services/version/version-actions.e2e.ts
  e2e/content-services/version/version-permissions.e2e.ts
  e2e/content-services/version/version-properties.e2e.ts
  e2e/content-services/version/version-smoke-tests.e2e.ts
  e2e/core/pagination-empty-current-page.e2e.ts
  e2e/core/viewer/file-extensions/viewer-archive.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-excel.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-image.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-powerpoint.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-text.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-word.component.e2e.ts
  e2e/core/viewer/info-drawer.component.e2e.ts
  e2e/core/viewer/viewer-content-services-component.e2e.ts
  e2e/core/viewer/viewer-custom-toolbar-info-drawer.e2e.ts
  e2e/core/viewer/viewer-extension.e2e.ts
  e2e/core/viewer/viewer-properties.e2e.ts
  e2e/core/viewer/viewer-share-content.ts
  e2e/models/ACS/file.model.ts
  e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
  e2e/process-services-cloud/start-task-form-cloud.e2e.ts
  e2e/process-services/attach-file-content-service.e2e.ts
  e2e/process-services/attach-file-widget.e2e.ts
  e2e/process-services/widgets/attach-file-widget.e2e.ts
  e2e/search/components/search-number-range.e2e.ts
  e2e/search/components/search-slider.e2e.ts
  e2e/search/components/search-sorting-picker.e2e.ts
  e2e/search/search-filters.e2e.ts
  e2e/search/search-multiselect.e2e.ts
  e2e/search/search-page-component.e2e.ts
  e2e/util/resources.js
  lib/testing/src/lib/content-services/actions/upload.actions.ts
  lib/testing/src/lib/process-services-cloud/pages/form/widget/attach-file-widget-cloud.page.ts
  lib/testing/src/lib/process-services/pages/start-process.page.ts
Labels: PR: partially-approved

#5635 [ACA-2523] Fix text color of comment user icon
  lib/core/comments/comment-list.component.scss
Labels: PR: partially-approved

#5634 [ADF-5120] Fix initialization error of PS cloud Services
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
  lib/process-services-cloud/src/lib/form/services/form-definition-selector-cloud.service.ts
  lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
  lib/process-services-cloud/src/lib/process/services/process-cloud.service.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
  lib/process-services-cloud/src/lib/services/base-cloud.service.ts
  lib/process-services-cloud/src/lib/services/user-preference-cloud.service.ts
  lib/process-services-cloud/src/lib/task/services/start-task-cloud.service.ts
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
  lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
Labels: PR: partially-approved

#5632 add slower type method for user picker
  e2e/content-services/directives/create-folder-directive.e2e.ts
  e2e/content-services/document-list/document-list-component.e2e.ts
  e2e/content-services/document-list/document-list-permissions.e2e.ts
  e2e/content-services/metadata/metadata-smoke-tests.e2e.ts
  e2e/pages/adf/content-services.page.ts
  e2e/process-services-cloud/process-filter-results.e2e.ts
  e2e/process-services-cloud/process-header-cloud.e2e.ts
  e2e/process-services-cloud/task-header-cloud.e2e.ts
  e2e/protractor.excludes.json
  lib/testing/src/lib/content-services/actions/upload.actions.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  lib/testing/src/lib/core/pages/form/widgets/date-time-widget.page.ts
  lib/testing/src/lib/core/utils/browser-actions.ts
  lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-header-cloud-component.page.ts
Labels: PR: unreviewed

#5633 [ACA-1894] - added the possibility to filter whenever is possible by …
  demo-shell/src/app.config.json
  docs/core/services/upload.service.md
  lib/core/app-config/schema.json
  lib/core/services/upload.service.spec.ts
  lib/core/services/upload.service.ts
Labels: PR: unreviewed

#5602 [DW-1669] [ADF-5107]- Added new api call for creating and starting a process in…
  e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
  e2e/process-services-cloud/start-process-cloud.e2e.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
  lib/process-services/src/lib/process-list/components/process-filters.component.spec.ts
Labels: PR: unreviewed

#5637 [MNT-21469] TreeView component has events on icon only
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/tree-view/components/tree-view.component.html
  lib/content-services/src/lib/tree-view/components/tree-view.component.scss
  lib/content-services/src/lib/tree-view/components/tree-view.component.spec.ts
Labels: PR: partially-approved

#5641 [ACA-1894] - fixed missing behaviour for drag&drop
  lib/core/services/upload.service.spec.ts
  lib/core/services/upload.service.ts
Labels: PR: partially-approved

#5639 [AAE-2321] Should not be able to start a process with space(s) in the beginning/end of process name (Process Services Cloud)
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
Labels: PR: partially-approved, needs rebase

#5581 [AAE-2020] Add release version filter for process instances
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-list/mock/process-list-service.mock.ts
  lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
Labels: PR: unreviewed

#5645 [AAE-2456] - Added a new function for generate lowercase and number strings
  lib/testing/src/lib/core/utils/string.util.ts
Labels: PR: partially-approved

#5646 [ADF-5129][ADF-5130] Fix Lock in Gallery view and Lock Dialog
  demo-shell/src/app/components/files/files.component.scss
  lib/content-services/src/lib/dialogs/node-lock.dialog.html
  lib/content-services/src/lib/document-list/components/document-list.component.scss
  lib/core/datatable/components/datatable/datatable.component.scss
Labels: PR: partially-approved

#5649 [ADF-5132] Review UI strings
  lib/content-services/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services/src/lib/i18n/en.json
Labels: PR: partially-approved

#5644 documentation update
  docs/README.md
  docs/core/services/discovery-api.service.md
  docs/core/services/upload.service.md
  docs/process-services-cloud/components/process-filters-cloud.component.md
  docs/process-services-cloud/components/process-list-cloud.component.md
  docs/process-services-cloud/components/task-filters-cloud.component.md
  docs/process-services-cloud/services/start-process-cloud.service.md
  docs/process-services/components/process-filters.component.md
  docs/process-services/components/process-list.component.md
  docs/process-services/components/task-filters.component.md
  docs/process-services/components/task-form.component.md
  docs/process-services/components/task-list.component.md
  docs/versionIndex.md
  scripts/travis/update/update-children.sh
  scripts/travis/update/update-project.sh
Labels: PR: unreviewed

#5650 [ACA-3040]Modify some methods of start-process PO
  e2e/process-services/comment-component-processes.e2e.ts
  e2e/process-services/custom-process-filters-sorting.e2e.ts
  e2e/process-services/custom-tasks-filters.e2e.ts
  e2e/process-services/process-attachment-list-action-menu.e2e.ts
  e2e/process-services/start-process-component.e2e.ts
  lib/testing/src/lib/core/actions/APS/models.service.ts
  lib/testing/src/lib/core/actions/APS/process.util.ts
  lib/testing/src/lib/process-services/pages/start-process.page.ts
Labels: PR: partially-approved

#5651 [DW-1530] - created extra method for process definition key set on fi…
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
Labels: PR: unreviewed

#5653 [AAE-000] fix the start process failing in APW
  lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
Labels: PR: unreviewed

#5652 [PRODDEL-3086] Release note in draft for 3.8.0.
  docs/abn-tree.yml
  docs/release-notes/README.md
  docs/release-notes/RelNote380.md
  docs/roadmap.md
Labels: PR: partially-approved, documentation

#5654 APS11
  e2e/process-services/attach-folder.e2e.ts
  lib/testing/src/lib/core/actions/APS/integration.service.ts
Labels: PR: unreviewed

#5656 [ACA-3232] Fix console error expression has changed after it has…
  lib/process-services/src/lib/process-list/components/start-process.component.html
  lib/process-services/src/lib/process-list/components/start-process.component.ts
Labels: PR: partially-approved

#5657 [AAE-2487] Fix Checkbox Widget bug
  lib/core/form/components/widgets/checkbox/checkbox.widget.html
  lib/core/form/components/widgets/checkbox/checkbox.widget.spec.ts
  lib/core/form/components/widgets/checkbox/checkbox.widget.ts
Labels: PR: partially-approved

#5655 [ADF-5122] Unexclude C309674 test
  e2e/protractor.excludes.json
  scripts/affected-libs.sh
Labels: PR: partially-approved

#5660 [ACA-3229] - fixed error on start process cloud when all the value a…
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
Labels: PR: unreviewed
