Repository Alfresco/alfresco-ng2-components, pull requests merged in 2020-07, with the labels that each got.

#5825 AAE-2972 Use BrowserActions in login page
  lib/testing/src/lib/core/pages/login-sso.page.ts
Labels: PR: partially-approved

#5826 adf-cli k8s-clean-app - Add more logs and default interval
  lib/cli/scripts/kubectl-clean-app.ts
Labels: PR: partially-approved

#5830 [AAE-2972] Add password visibility to login sso page
  lib/testing/src/lib/core/pages/login-sso.page.ts
Labels: PR: unreviewed

#5832 [ACA-3548] Convert Start Process manual cases to unit tests
  lib/process-services/src/lib/mock/process/start-process.component.mock.ts
  lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
  lib/process-services/src/lib/process-list/components/start-process.component.ts
Labels: PR: partially-approved

#5835 cleanup dependencies and fix versions
  demo-shell/src/polyfills.ts
  lib/content-services/karma.conf.js
  lib/core/karma.conf.js
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/karma.conf.js
  lib/process-services-cloud/package.json
  lib/process-services/karma.conf.js
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#5836 [ADF-5175] - perform the search when at least one filter is active
  lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
Labels: PR: unreviewed

#5837 [ACA-3546] Update simpleapp for DW Cloud e2e tests
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#5838 adf-cli - return the project release
  lib/cli/scripts/init-aae-env.ts
  scripts/build/build-cli.sh
Labels: PR: partially-approved

#5839 Travis: Fix the path for the docker image
  .travis.yml
  Dockerfile
Labels: PR: partially-approved

#5840 [ADF-5177] Search-header execute when enter is pressed
  lib/content-services/src/lib/search/components/search-header/search-header.component.html
  lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
Labels: PR: unreviewed

#5829 [ACA-3529] Custom filter doesn't work properly when Direction is set to ASC
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
Labels: PR: partially-approved

#5841 [ADF-5176] - fixed apply when no value is given
  lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.spec.ts
  lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.ts
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
  lib/content-services/src/lib/search/components/search-number-range/search-number-range.component.ts
  lib/content-services/src/lib/search/components/search-radio/search-radio.component.ts
  lib/content-services/src/lib/search/components/search-slider/search-slider.component.ts
  lib/content-services/src/lib/search/components/search-text/search-text.component.ts
  lib/content-services/src/lib/search/components/search-widget-container/search-widget-container.component.ts
  lib/content-services/src/lib/search/search-widget.interface.ts
Labels: PR: partially-approved

#5843 [ADF-5178] - add translation for filters
  demo-shell/src/app.config.json
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/search/components/search-header/search-header.component.html
  lib/content-services/src/lib/search/components/search-text/search-text.component.html
Labels: PR: partially-approved

#5848 [ACA-3614] Add a way to not show info drawer header
  docs/core/components/info-drawer-layout.component.md
  docs/core/components/info-drawer.component.md
  lib/core/info-drawer/info-drawer-layout.component.html
  lib/core/info-drawer/info-drawer-layout.component.ts
  lib/core/info-drawer/info-drawer.component.html
  lib/core/info-drawer/info-drawer.component.spec.ts
  lib/core/info-drawer/info-drawer.component.ts
Labels: PR: partially-approved

#5847 use the tag and not id because does not exist
  lib/testing/src/lib/core/pages/login-sso.page.ts
Labels: PR: partially-approved

#5846 [ACA-3373] Add resources for Process Cloud e2e tests
  lib/testing/src/lib/process-services-cloud/resources/resources.json
Labels: PR: partially-approved

#5852 update simpleapp
  e2e/resources/activiti7/simpleapp.zip
  lib/testing/src/lib/process-services-cloud/resources/resources.json
Labels: PR: partially-approved

#5853 fixed simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#5857 Update the adf deps before install
  scripts/travis/build/build.sh
Labels: PR: partially-approved

#5859 [#5858] Fix elements of tags
  docs/insights/components/analytics-report-list.component.md
Labels: PR: partially-approved

#5861 [#5860] Fix end tag.
  docs/process-services/components/process-list.component.md
Labels: PR: partially-approved

#5833 [MNT-21595] Content - Expose a group service for content
  lib/content-services/src/lib/group/index.ts
  lib/content-services/src/lib/group/public-api.ts
  lib/content-services/src/lib/group/services/group.service.ts
  lib/content-services/src/lib/permission-manager/services/node-permission.service.ts
  lib/content-services/src/public-api.ts
  lib/core/services/alfresco-api.service.ts
  scripts/smart-build.sh
  scripts/travis/build/build.sh
Labels: PR: partially-approved

#5864 Update start-form.component documentation
  docs/core/components/start-form.component.md
  lib/process-services/src/lib/form/start-form.component.ts
Labels: PR: unreviewed

#5854 [ACA-3596] process-header change assignee property key to createdBy
  docs/process-services/components/process-instance-header.component.md
  lib/core/app-config/schema.json
  lib/process-services/src/lib/process-list/components/process-instance-header.component.spec.ts
  lib/process-services/src/lib/process-list/components/process-instance-header.component.ts
Labels: PR: partially-approved

#5849 [ADF-5179] - added folders for size filters
  demo-shell/src/app.config.json
Labels: PR: unreviewed, needs rebase

#5855 [ACA-3613] Inconsistent role value between library views
  lib/content-services/src/lib/document-list/components/library-role-column/library-role-column.component.spec.ts
  lib/content-services/src/lib/document-list/components/library-role-column/library-role-column.component.ts
  lib/content-services/src/lib/i18n/en.json
Labels: PR: unreviewed

#5868 [ADF-5180] Add keyboard accessibility for filters
  lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.html
  lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.spec.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.html
  lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
Labels: PR: partially-approved

#5872 [dev-crisj-ACA-3611]Refactor createUser method
  lib/testing/src/lib/core/actions/users.actions.ts
Labels: PR: unreviewed

#5877 [ADF-5063] Add translate pipe to attach file/folder widget titles
  lib/process-services/src/lib/content-widget/attach-file-widget.component.html
  lib/process-services/src/lib/content-widget/attach-folder-widget.component.html
Labels: PR: partially-approved

#5879 upgrade 3rd party dependencies
  demo-shell/src/polyfills.ts
  package-lock.json
  package.json
  tslint.json
Labels: PR: unreviewed

#5878 [AAE-3073] Fix error due to formatSorting() in APW
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
Labels: PR: unreviewed

#5875 [ADF-5177] Pressing enter close filter menu
  lib/content-services/src/lib/search/components/search-header/search-header.component.html
  lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
Labels: PR: partially-approved

#5869 [ADF-5175] Fix clear button removing multiple filter
  lib/content-services/src/lib/search/search-header-query-builder.service.ts
Labels: PR: partially-approved

#5863 [ACA-3184][ACA-3185] Create Task Util class
  lib/testing/src/lib/core/pages/form/form-fields.ts
  lib/testing/src/lib/process-services/actions/public-api.ts
  lib/testing/src/lib/process-services/actions/task.util.ts
Labels: PR: partially-approved

#5876 [ACA-3739] Can't upload a new version
  lib/content-services/src/lib/upload/components/upload-button.component.ts
Labels: PR: reviewed-changes-requested

#5882 [ACA-3499] Card View Textitem update on change
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
Labels: PR: partially-approved

#5881 fix pagination issues
  lib/core/pagination/pagination.component.spec.ts
  lib/core/pagination/pagination.component.ts
Labels: PR: partially-approved

#5884 Optimize tests and upgrade Nx workspace
  angular.json
  decorate-angular-cli.js
  lib/process-services-cloud/src/lib/pipes/process-name-cloud.pipe.spec.ts
  lib/process-services-cloud/src/lib/process/directives/cancel-process.directive.spec.ts
  lib/process-services-cloud/src/lib/process/directives/cancel-process.directive.ts
  lib/process-services-cloud/src/lib/process/mock/process-details.mock.ts
  lib/process-services-cloud/src/lib/process/process-filters/mock/process-filters.cloud.mock.ts
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.ts
  lib/process-services-cloud/src/lib/process/services/process-cloud.service.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
  lib/process-services-cloud/src/lib/process/start-process/models/process-instance-cloud.model.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
  package-lock.json
  package.json
Labels: PR: partially-approved

#5886 Revert "[ACA-3499] Card View Textitem update on change"
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
Labels: PR: unreviewed

#5889 move scripts check env in cli
  lib/cli/README.md
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/cli/scripts/check-cs-env.ts
  lib/cli/scripts/check-ps-env.ts
  lib/cli/scripts/logger.ts
  scripts/check-env/delete-all-apps.js
  scripts/travis/build/build.sh
  scripts/travis/e2e/content-services-e2e.sh
  scripts/travis/e2e/core-e2e.sh
  scripts/travis/e2e/insights-e2e.sh
  scripts/travis/e2e/process-services-cloud-e2e.sh
  scripts/travis/e2e/process-services-e2e.sh
  scripts/travis/e2e/search-e2e.sh
Labels: PR: unreviewed

#5885 [ACA-3506] - Filter are kept when reloaded
  demo-shell/src/app.config.json
  demo-shell/src/app/components/files/files.component.html
  demo-shell/src/app/components/files/files.component.ts
  demo-shell/src/app/components/files/filtered-search.component.html
  demo-shell/src/app/components/files/filtered-search.component.ts
  docs/content-services/components/search-check-list.component.md
  docs/content-services/components/search-text.component.md
  lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.html
  lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.ts
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.html
  lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
  lib/content-services/src/lib/search/components/search-header/search-header.component.ts
  lib/content-services/src/lib/search/components/search-number-range/search-number-range.component.ts
  lib/content-services/src/lib/search/components/search-radio/search-radio.component.spec.ts
  lib/content-services/src/lib/search/components/search-radio/search-radio.component.ts
  lib/content-services/src/lib/search/components/search-slider/search-slider.component.ts
  lib/content-services/src/lib/search/components/search-text/search-text.component.ts
  lib/content-services/src/lib/search/components/search-widget-container/search-widget-container.component.ts
  lib/content-services/src/lib/search/search-header-query-builder.service.spec.ts
  lib/content-services/src/lib/search/search-header-query-builder.service.ts
  lib/content-services/src/lib/search/search-widget.interface.ts
  scripts/travis/build/build.sh
  scripts/travis/e2e/content-services-e2e.sh
  scripts/travis/e2e/core-e2e.sh
  scripts/travis/e2e/insights-e2e.sh
  scripts/travis/e2e/process-services-cloud-e2e.sh
  scripts/travis/e2e/process-services-e2e.sh
  scripts/travis/e2e/search-e2e.sh
  scripts/travis/release/release-npm.sh
  scripts/travis/unit-test/content.sh
  scripts/travis/unit-test/core-extension.sh
  scripts/travis/unit-test/process.sh
Labels: PR: unreviewed

#5891 [ADF-1960] automated C315180, C310200 and C313200
  e2e/process-services-cloud/task-form-cloud-component-tab.e2e.ts
  e2e/process-services-cloud/task-form-cloud-component.e2e.ts
  e2e/protractor.conf.js
  scripts/travis/e2e/content-services-e2e.sh
  scripts/travis/e2e/core-e2e.sh
  scripts/travis/e2e/process-services-cloud-e2e.sh
  scripts/travis/e2e/process-services-e2e.sh
  scripts/travis/e2e/search-e2e.sh
Labels: PR: partially-approved

#5890 [AAE-3114] Ability to restrict search to a root folder
  docs/content-services/components/content-node-selector-panel.component.md
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
Labels: PR: partially-approved

#5892 [ADF-3484] - Metadata drop-down list option for properties constrained by a list of values
  demo-shell/src/app/components/files/files.component.ts
  lib/content-services/src/lib/content-metadata/services/content-metadata.service.ts
  lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.spec.ts
  lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
  lib/content-services/src/lib/document-list/services/document-list.service.ts
  lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.html
  lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.ts
  lib/core/card-view/interfaces/card-view-item-properties.interface.ts
  package-lock.json
  package.json
Labels: PR: partially-approved

#5893 [ACA-3492] ADF - Expose new Groups Endpoints
  .travis.yml
  docs/core/services/sites.service.md
  lib/core/pipes/user-initial.pipe.ts
  lib/core/services/sites.service.ts
  lib/testing/src/lib/content-services/pages/document-list.page.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  package-lock.json
  package.json
  scripts/travis/unit-test/content.sh
  scripts/travis/unit-test/core-extension.sh
  scripts/travis/unit-test/process-cloud.sh
  scripts/travis/unit-test/process.sh
Labels: PR: unreviewed

#5899 [ACA-3672] - added server order for document -list
  demo-shell/src/app.config.json
  demo-shell/src/app/components/files/files.component.html
  demo-shell/src/app/components/files/files.component.ts
  docs/content-services/components/content-action.component.md
  docs/content-services/components/content-node-selector-panel.component.md
  docs/content-services/components/document-list.component.md
  docs/content-services/components/like.component.md
  docs/content-services/components/rating.component.md
  docs/content-services/components/search-header.component.md
  docs/content-services/components/tag-actions.component.md
  docs/content-services/components/tag-list.component.md
  docs/content-services/components/tag-node-list.component.md
  docs/content-services/components/upload-button.component.md
  docs/content-services/components/upload-drag-area.component.md
  docs/content-services/components/upload-version-button.component.md
  docs/content-services/components/webscript.component.md
  docs/content-services/services/document-list.service.md
  docs/core/components/data-column.component.md
  docs/core/components/datatable.component.md
  docs/core/components/form-field.component.md
  docs/core/components/info-drawer-layout.component.md
  docs/core/components/info-drawer.component.md
  docs/core/components/pagination.component.md
  docs/core/components/start-form.component.md
  docs/core/components/viewer.component.md
  docs/core/directives/version-compatibility.directive.md
  docs/core/services/form.service.md
  docs/core/services/sites.service.md
  docs/core/widgets/content.widget.md
  docs/insights/components/analytics-generator.component.md
  docs/insights/components/analytics-report-list.component.md
  docs/insights/components/analytics.component.md
  docs/insights/components/diagram.component.md
  docs/process-services-cloud/components/edit-task-filter-cloud.component.md
  docs/process-services-cloud/components/group-cloud.component.md
  docs/process-services-cloud/components/people-cloud.component.md
  docs/process-services-cloud/services/start-process-cloud.service.md
  docs/process-services-cloud/services/task-cloud.service.md
  docs/process-services/components/people-search.component.md
  docs/process-services/components/people.component.md
  docs/process-services/components/process-attachment-list.component.md
  docs/process-services/components/process-list.component.md
  docs/process-services/components/start-process.component.md
  docs/process-services/components/task-attachment-list.component.md
  docs/process-services/components/task-list.component.md
  docs/process-services/services/tasklist.service.md
  lib/content-services/src/lib/breadcrumb/breadcrumb.component.spec.ts
  lib/content-services/src/lib/breadcrumb/dropdown-breadcrumb.component.spec.ts
  lib/content-services/src/lib/document-list/components/document-list.component.html
  lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/content-services/src/lib/document-list/services/document-list.service.ts
  lib/core/data-column/data-column.component.ts
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/core/datatable/data/data-column.model.ts
  lib/core/datatable/data/object-datacolumn.model.ts
Labels: PR: partially-approved

#5905 Update package.json
  package.json
Labels: PR: partially-approved

#5906 [ACA-3765] [ADF] move reusable versioning logic
  lib/core/directives/version-compatibility.directive.ts
  lib/core/services/version-compatibility.service.spec.ts
  lib/core/services/version-compatibility.service.ts
Labels: PR: partially-approved

#5904 [AAE-3115] Content node selector - Ability to select multiple files
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/components/cloud/start-process-cloud-demo.component.ts
  docs/content-services/components/content-node-selector-panel.component.md
  docs/content-services/components/document-list.component.md
  lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
  lib/process-services-cloud/src/lib/process-services-cloud.module.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
Labels: PR: unreviewed

#5909 Use travis chrome version
  scripts/test-e2e-lib.sh
Labels: PR: partially-approved

#5910 [ADF-5201] Metadata - Update node pass 'definition' field
  lib/core/services/nodes-api.service.ts
Labels: PR: partially-approved

#5897 [ACA-3751] Disable save & delete buttons for default task filters
  e2e/process-services-cloud/edit-task-filters-component.e2e.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
Labels: PR: partially-approved

#5896 [ACA-3678] Disable save & delete buttons for default process filters
  e2e/process-services-cloud/edit-process-filters-component.e2e.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
Labels: PR: unreviewed

#5913 [ACA-100] View a previous version
  demo-shell/src/app/app.routes.ts
  demo-shell/src/app/components/file-view/file-view.component.html
  demo-shell/src/app/components/file-view/file-view.component.ts
  demo-shell/src/app/components/files/version-manager-dialog-adapter.component.html
  demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
  demo-shell/src/app/services/preview.service.ts
  docs/content-services/components/version-list.component.md
  docs/content-services/components/version-manager.component.md
  docs/core/components/viewer.component.md
  docs/core/directives/node-download.directive.md
  e2e/content-services/version/version-actions.e2e.ts
  e2e/core/pages/version-manager.page.ts
  e2e/core/viewer/viewer-custom-toolbar-info-drawer.e2e.ts
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/version-manager/version-list.component.html
  lib/content-services/src/lib/version-manager/version-list.component.spec.ts
  lib/content-services/src/lib/version-manager/version-list.component.ts
  lib/content-services/src/lib/version-manager/version-manager.component.html
  lib/content-services/src/lib/version-manager/version-manager.component.spec.ts
  lib/content-services/src/lib/version-manager/version-manager.component.ts
  lib/core/directives/node-download.directive.spec.ts
  lib/core/directives/node-download.directive.ts
  lib/core/viewer/components/viewer.component.html
  lib/core/viewer/components/viewer.component.ts
  lib/core/viewer/services/view-util.service.ts
  lib/testing/src/lib/core/pages/viewer.page.ts
Labels: PR: partially-approved

#5883 [ACA-3107] add possibility to hide task name from the sidenav
  docs/process-services-cloud/components/task-header-cloud.component.md
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.scss
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
Labels: PR: unreviewed

#5916 [AAE-3162] [ADF-APS1] Local storage option of attach file widget is not displayed
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.ts
Labels: PR: unreviewed

#5918 Put folder on top by default
  demo-shell/src/app/components/files/files.component.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
Labels: PR: partially-approved

#5920 [ACA-3645] add missing task list translation key
  lib/process-services-cloud/src/lib/i18n/en.json
Labels: PR: partially-approved

#5915 [ACA-100] FIX - View a previous version
  e2e/protractor.excludes.json
  lib/core/viewer/components/viewer.component.ts
  lib/core/viewer/services/view-util.service.ts
Labels: PR: unreviewed

#5921 [AAE-3115] Make selectionMode optioanl in ContentNodeSelectorComponentData
  lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
Labels: PR: partially-approved

#5922 [ADF-5204] Metadata - Error message still appears after exiting Edit form
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
Labels: PR: unreviewed

#5894 [ACA-3590]Created process-instance-header, info-drawer and task-header POs
  e2e/process-services/pages/process-details.page.ts
  e2e/process-services/process-instance-details.e2e.ts
  e2e/process-services/start-process-component.e2e.ts
  e2e/protractor.excludes.json
  lib/testing/src/lib/core/pages/card-view/card-view-date-item.page.ts
  lib/testing/src/lib/core/pages/card-view/card-view-text-item.page.ts
  lib/testing/src/lib/core/pages/data-table/column.ts
  lib/testing/src/lib/core/pages/data-table/data-table-item.ts
  lib/testing/src/lib/core/pages/info-drawer.page.ts
  lib/testing/src/lib/core/pages/material/tabs.page.ts
  lib/testing/src/lib/core/pages/public-api.ts
  lib/testing/src/lib/process-services/pages/process-instance-header.page.ts
  lib/testing/src/lib/process-services/pages/public-api.ts
  lib/testing/src/lib/process-services/pages/task-header.page.ts
  scripts/test-e2e-lib.sh
Labels: PR: partially-approved

#5912 [AAE-3113] Node selector - Be able to restrict the breadcrums to a specific root
  docs/content-services/components/content-node-selector-panel.component.md
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
Labels: PR: unreviewed

#5923 [ACA-3745] Folder - update metadata default copies the name in the title field
  lib/content-services/src/lib/dialogs/folder.dialog.html
  lib/content-services/src/lib/dialogs/folder.dialog.spec.ts
  lib/content-services/src/lib/dialogs/folder.dialog.ts
  lib/core/i18n/en.json
Labels: PR: partially-approved

#5927 Minor cosmetic fix filter
  lib/content-services/src/lib/search/components/search-header/search-header.component.scss
  package.json
Labels: PR: partially-approved

#5870 [ACA-3687] Implement Process definition name filter dropdown in Process List
  demo-shell/src/app/components/cloud/processes-cloud-demo.component.html
  docs/process-services-cloud/components/process-list-cloud.component.md
  docs/process-services-cloud/components/start-process-cloud.component.md
  docs/process-services-cloud/pipes/process-name-cloud.pipe.md
  docs/process-services-cloud/services/process-cloud.service.md
  docs/process-services-cloud/services/start-process-cloud.service.md
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/models/process-definition-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
  lib/process-services-cloud/src/lib/process/services/process-cloud.service.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
  lib/process-services-cloud/src/lib/process/start-process/public-api.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
  lib/process-services-cloud/src/public-api.ts
  tools/doc/docProcessor.js
Labels: PR: partially-approved

#5926 [ADF-5209] When viewing a previous version, the title is not displayed correctly.
  lib/core/viewer/components/viewer.component.spec.ts
  lib/core/viewer/components/viewer.component.ts
Labels: PR: partially-approved

#5925 fix drop effect
  lib/content-services/src/lib/upload/directives/file-draggable.directive.spec.ts
  lib/content-services/src/lib/upload/directives/file-draggable.directive.ts
Labels: PR: unreviewed

#5929 [ACA-3731] E2E test to validate Save, Save as and Delete buttons availability on custom filters
  e2e/process-services-cloud/edit-task-filters-component.e2e.ts
Labels: PR: partially-approved

#5935 [ACA-3687] Implement Process definition name filter dropdown in Process List
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
Labels: PR: unreviewed

#5933 remove unused ID and fix the duplicate warning
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
Labels: PR: partially-approved

#5934 [AAE-612] Support for Form Outcome Visibility Conditions
  lib/core/form/components/widgets/core/form-outcome.model.spec.ts
  lib/core/form/components/widgets/core/form-outcome.model.ts
  lib/core/form/components/widgets/core/tab.model.spec.ts
  lib/core/form/services/widget-visibility-cloud.service.spec.ts
  lib/core/form/services/widget-visibility.service.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.html
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
Labels: PR: partially-approved

#5901 [AAE-3110] Move upload button inside the node selector dialog
  demo-shell/src/app/components/files/files.component.ts
  docs/content-services/components/content-node-selector-panel.component.md
  docs/process-services-cloud/services/form-cloud.service.md
  e2e/protractor.excludes.json
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.module.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/upload/components/upload-button.component.html
  lib/core/form/components/widgets/core/form-field-file-source.ts
  lib/core/form/components/widgets/core/form.model.ts
  lib/core/i18n/en.json
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/upload-cloud.widget.ts
  lib/process-services-cloud/src/lib/form/models/task-variable-cloud.model.ts
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
  lib/process-services-cloud/src/lib/form/services/process-cloud-content.service.ts
  lib/process-services-cloud/src/lib/i18n/en.json
Labels: Missing documentation, PR: partially-approved, PR: unreviewed

#5850 [ACA-3551] Show vs View button for attach widget.
  lib/core/i18n/en.json
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
  lib/process-services/src/lib/content-widget/attach-file-widget.component.html
  lib/process-services/src/lib/content-widget/attach-file-widget.component.spec.ts
Labels: PR: unreviewed

#5930 [ACA-3795] E2E test to validate Delete Save and Save as actions should be displayed and enabled when clicking on custom filter header
  e2e/process-services-cloud/edit-process-filters-component.e2e.ts
Labels: PR: partially-approved

#5941 Updated simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: partially-approved

#5942 Improve smart runner
  .gitignore
  e2e/protractor.conf.js
Labels: PR: unreviewed
