Repository Alfresco/alfresco-ng2-components, pull requests merged in 2021-12, with the labels that each got.

#7383 Update branch for JS-API PR#4011
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7404 <adf-context-menu-holder> removed from adf document list
  docs/content-services/components/document-list.component.md
Labels: PR: reviewed-approved

#7401 [AAE-5964] Storybook stories for DateRangeFilter component
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.stories.ts
  lib/process-services-cloud/src/lib/common/mock/date-range-filter.mock.ts
Labels: PR: partially-approved

#7402 Update branch for JS-API PR#4024
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7413 [ADF-5228] Remove duplicate E2E of Unit
  e2e/core/datatable/data-table-component.e2e.ts
Labels: PR: partially-approved

#7424 Retrieve jwt user info from id token
  lib/core/services/identity-user.service.spec.ts
  lib/core/services/identity-user.service.ts
  lib/core/services/jwt-helper.service.ts
Labels: PR: partially-approved

#7423 Update branch for JS-API PR#4046
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7425 [AAE-6742] Create E2Es for dropdown search capability
  e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts
  e2e/resources/activiti7/simpleapp.zip
  lib/testing/src/lib/protractor/core/pages/form/widgets/dropdown-widget.page.ts
  lib/testing/src/lib/protractor/process-services-cloud/resources/resources.ts
Labels: PR: partially-approved

#7412 AAE-6757 Improving e2e tests relating to modeling-ee. Part one - improve flaky tests, ProcessModelerComponent
  lib/testing/src/lib/protractor/core/pages/card-view/card-view-text-item.page.ts
Labels: PR: unreviewed
