Repository Alfresco/alfresco-ng2-components, pull requests merged in 2021-09, with the labels that each got.

#7229 [AAE-5727] Add 'today' and 'now' as default values for date and datetime widgets
  lib/core/form/components/widgets/core/form-field.model.spec.ts
  lib/core/form/components/widgets/core/form-field.model.ts
Labels: PR: partially-approved

#7231 Update candidatebaseapp to remove start event referencing unexistent form
  e2e/resources/activiti7/candidatebaseapp.zip
Labels: PR: partially-approved

#7230 [ACA-3669] Incorrect Version Number Displayed
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/version-manager/version-manager.component.html
  lib/content-services/src/lib/version-manager/version-upload.component.html
  lib/content-services/src/lib/version-manager/version-upload.component.spec.ts
  lib/content-services/src/lib/version-manager/version-upload.component.ts
Labels: PR: partially-approved

#7234 LOC-323 - Updated UI for ADF 4.6 in 16 languages
  lib/content-services/src/lib/i18n/zh-CN.json
  lib/process-services-cloud/src/lib/i18n/ar.json
  lib/process-services-cloud/src/lib/i18n/cs.json
  lib/process-services-cloud/src/lib/i18n/da.json
  lib/process-services-cloud/src/lib/i18n/de.json
  lib/process-services-cloud/src/lib/i18n/es.json
  lib/process-services-cloud/src/lib/i18n/fi.json
  lib/process-services-cloud/src/lib/i18n/fr.json
  lib/process-services-cloud/src/lib/i18n/it.json
  lib/process-services-cloud/src/lib/i18n/ja.json
  lib/process-services-cloud/src/lib/i18n/nb.json
  lib/process-services-cloud/src/lib/i18n/nl.json
  lib/process-services-cloud/src/lib/i18n/pl.json
  lib/process-services-cloud/src/lib/i18n/pt-BR.json
  lib/process-services-cloud/src/lib/i18n/ru.json
  lib/process-services-cloud/src/lib/i18n/sv.json
  lib/process-services-cloud/src/lib/i18n/zh-CN.json
Labels: PR: partially-approved

#7241 [ACA-4310] - Show the breadcrumb even for invalid selections in searc…
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
Labels: PR: partially-approved

#7246 Update documentation extension viewer
  docs/core/components/viewer.component.md
Labels: PR: unreviewed

#7245 [ADF-5462] - fixed logout redirect on other tabs
  lib/core/services/auth-guard.service.ts
Labels: PR: partially-approved

#7262 [AAE-5843] - Add e2e method to check the visibility of the upload fro…
  e2e/resources/activiti7/simpleapp.zip
  lib/testing/src/lib/protractor/content-services/dialog/content-node-selector-dialog.page.ts
Labels: PR: partially-approved

#7225 [ADF-5173] - improved fix for closing pdfjs worker error
  .gitignore
  lib/core/viewer/components/pdf-viewer.component.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.ts
  lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
Labels: PR: unreviewed, PR: partially-approved

#7224 [AAE-5612] FE - [ADF] Destination picker it's not displaying my files folder if the destination Folder path type of string/folder variable is set to a folder part of trash
  lib/core/form/components/widgets/core/index.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
  lib/process-services-cloud/src/lib/form/mocks/attach-file-cloud-widget.mock.ts
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.spec.ts
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
Labels: PR: unreviewed

#7255 [ADF-5464] [form]Mandatory field validations are not applied once content removed
  lib/core/form/components/widgets/functional-group/functional-group.widget.html
  lib/core/form/components/widgets/functional-group/functional-group.widget.spec.ts
  lib/core/form/components/widgets/functional-group/functional-group.widget.ts
  lib/core/form/components/widgets/people/people.widget.html
  lib/core/form/components/widgets/people/people.widget.spec.ts
  lib/core/form/components/widgets/people/people.widget.ts
Labels: PR: partially-approved
