Repository Alfresco/alfresco-ng2-components, pull requests merged in 2021-06, with the labels that each got.

#7059 [ADF-5148] ContentService.hasPermissions() should check inhertied permission
  lib/core/services/content.service.spec.ts
  lib/core/services/content.service.ts
Labels: PR: unreviewed

#7049 [AAE-4974] FE - Remove scroll bar from empty "Upload from your device" list
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
Labels: PR: unreviewed

#7070 [AAE-5280] Better error handling for user task
  demo-shell/src/app/components/cloud/community/community-task-details-cloud.component.html
  demo-shell/src/app/components/cloud/community/community-task-details-cloud.component.ts
  demo-shell/src/app/components/cloud/task-details-cloud-demo.component.html
  demo-shell/src/app/components/cloud/task-details-cloud-demo.component.ts
  lib/process-services-cloud/src/lib/task/directives/claim-task-cloud.directive.spec.ts
  lib/process-services-cloud/src/lib/task/directives/complete-task.directive.spec.ts
  lib/process-services-cloud/src/lib/task/directives/unclaim-task-cloud.directive.spec.ts
  lib/process-services-cloud/src/lib/task/directives/unclaim-task-cloud.directive.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html
Labels: PR: partially-approved

#7055 [AAE-5208] Add pagination info to listPeople function in PeopleContentService
  docs/core/services/people-content.service.md
  lib/core/services/people-content.service.spec.ts
  lib/core/services/people-content.service.ts
Labels: PR: partially-approved

#7080 Update branch for JS-API PR#3558
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#7066 [ACA-4464] Add user/groups - should not be able to select the same user multiple times
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.spec.ts
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.ts
Labels: PR: partially-approved

#7089 [ACA-4474]Add checkWidgetsAreVisible method
  lib/testing/src/lib/core/pages/form/form-fields.ts
  lib/testing/src/lib/core/pages/form/widgets/attach-file-widget.page.ts
Labels: PR: partially-approved

#7087 [ADF-5369] HTTP 500 response in adf-upload-button is emitted as a success event
  demo-shell/src/app/components/files/files.component.ts
  lib/content-services/src/lib/mock/upload.service.mock.ts
  lib/content-services/src/lib/upload/components/base-upload/upload-base.ts
  lib/content-services/src/lib/upload/components/upload-button.component.spec.ts
  lib/content-services/src/lib/upload/components/upload-drag-area.component.spec.ts
  lib/content-services/src/lib/upload/components/upload-files.event.ts
  lib/core/services/upload.service.spec.ts
  lib/core/services/upload.service.ts
Labels: PR: partially-approved

#7097 [ACA-4474]Add isStartProcessButtonEnabled method
  e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
  e2e/process-services-cloud/start-task/start-process-cloud.e2e.ts
  e2e/process-services-cloud/start-task/start-task-form-cloud.e2e.ts
  e2e/process-services/process/start-process-component.e2e.ts
  e2e/protractor.excludes.json
  lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
  lib/testing/src/lib/process-services/pages/start-process.page.ts
Labels: PR: unreviewed

#7068 [AAE-2617] To get access to datatable component from process-list component
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
Labels: PR: unreviewed

#7100 [ADF-5421]Include test back
  e2e/protractor.excludes.json
Labels: PR: partially-approved

#7093 Update branch for JS-API PR#3583
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7088 [ACA-3611] Create test folder for E2E precondition files
  lib/cli/resources/content/e2e_favorite_file.jpg
  lib/cli/resources/content/e2e_lock.png
  lib/cli/resources/content/e2e_second_lock.png
  lib/cli/resources/content/e2e_share_file.jpg
  lib/cli/resources/content/e2e_share_profile_pic.jpg
  lib/cli/resources/content/e2e_share_profile_pic.png
  lib/cli/resources/content/e2e_to_be_deleted.png
  lib/cli/scripts/init-acs-env.ts
  lib/cli/scripts/resources.ts
Labels: PR: unreviewed, do not merge 🙅🏻‍♂️

#7114 Expose shared library as subdirectory
  lib/testing/shared/package.json
Labels: PR: unreviewed

#7117 [AAE-5362] Add option to make actions button visible only on hover
  docs/core/components/datatable.component.md
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
  lib/content-services/src/lib/site-dropdown/sites-dropdown.component.spec.ts
  lib/core/comments/comments.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.scss
  lib/core/datatable/components/datatable/datatable.component.ts
Labels: PR: partially-approved

#7119 [AAE-5392] - Add find people api call
  docs/core/services/people-content.service.md
  lib/core/services/people-content.service.spec.ts
  lib/core/services/people-content.service.ts
Labels: PR: partially-approved

#7121 Revert "[AAE-5392] - Add find people api call"
  docs/core/services/people-content.service.md
  lib/core/services/people-content.service.spec.ts
  lib/core/services/people-content.service.ts
Labels: PR: partially-approved

#7111 Update branch for JS-API PR#3612
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7113 [ACA-4436] - added option for select item to display None
  lib/content-services/src/lib/content-metadata/services/content-type-property.service.ts
  lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.ts
  lib/core/card-view/components/card-view/card-view.component.html
  lib/core/card-view/components/card-view/card-view.component.spec.ts
  lib/core/card-view/interfaces/card-view-selectitem-properties.interface.ts
  lib/core/card-view/models/card-view-selectitem.model.spec.ts
  lib/core/card-view/models/card-view-selectitem.model.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
Labels: PR: unreviewed

#7130 4.5.0 Release note
  docs/README.md
  docs/license-info/README.md
  docs/license-info/license-info-4.5.0.md
  docs/release-notes/README.md
  docs/release-notes/RelNote450.md
  docs/upgrade-guide/README.md
  docs/upgrade-guide/upgrade44-45.md
  docs/versionIndex.md
  docs/vulnerability/README.md
  docs/vulnerability/audit-info-4.5.0.md
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
Labels: PR: partially-approved

#7129 Update branch for JS-API PR#3648
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#7131 [ACA-4479][ACA-4480] - Enable Save button when the form is invalid
  e2e/process-services-cloud/form-field/people-group-of-people.e2e.ts
  e2e/process-services/widgets/date-time-widget.e2e.ts
  lib/core/form/components/form-base.component.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services/src/lib/form/form.component.spec.ts
Labels: PR: partially-approved

#7134 [ACA-4450] - fix disable complete button on invalid datetime
  lib/core/form/components/widgets/core/form-field-validator.spec.ts
  lib/core/form/components/widgets/core/form-field-validator.ts
Labels: PR: partially-approved

#7132 Update protractor.excludes.json
  e2e/protractor.excludes.json
Labels: PR: reviewed-approved

#7135 [ACA-4455] Fix horizontal scroller sometimes showing up on datatable
  lib/core/datatable/components/datatable/datatable.component.scss
Labels: PR: partially-approved
