Repository Alfresco/alfresco-ng2-components, pull requests merged in 2021-04, with the labels that each got.

#6897 [AAE-4924]Add method for createProcess with variables
  e2e/protractor.excludes.json
  lib/testing/src/lib/process-services-cloud/actions/process.services.ts
Labels: PR: partially-approved

#6887 [ACA-3652] Add Assignment custom filter in task filter cloud component page
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
Labels: PR: partially-approved

#6890 improved language picker
  demo-shell/src/app.config.json
  lib/core/i18n/en.json
  lib/core/language-menu/language-menu.component.html
  lib/core/language-menu/language-menu.component.spec.ts
  lib/core/language-menu/language-menu.component.ts
  lib/core/language-menu/language-menu.module.ts
  lib/core/language-menu/language-picker.component.ts
  lib/core/language-menu/public-api.ts
  lib/core/services/language.service.ts
  lib/core/services/public-api.ts
  lib/core/services/user-preferences.service.ts
Labels: PR: partially-approved

#6901 Run dependabot on sunday
  .github/dependabot.yml
Labels: PR: unreviewed

#6894 [ADF-5374]Fix flaky filters tests
  e2e/process-services-cloud/process/process-custom-filters.e2e.ts
  e2e/process-services-cloud/process/process-filter-results.e2e.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
Labels: PR: partially-approved

#6889 [ADF-5212] fix button filter color in high contrast
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.scss
Labels: PR: partially-approved

#6876 Update branch for JS-API PR#3342
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#6905 Docker publish - Remove the pathProject as mandatory
  lib/cli/scripts/docker-publish.ts
Labels: PR: unreviewed

#6879 [ACA-3957] Added correct Icons and left nav, process config layout an…
  lib/core/assets/images/dynamic_feed-24px.svg
  lib/core/assets/images/ic-process.svg
  lib/core/assets/images/save-as.svg
  lib/core/assets/images/save.svg
  lib/core/assets/images/task.svg
Labels: PR: partially-approved

#6904 [ADF-5156] Name column fixes
  demo-shell/src/app.config.json
  demo-shell/src/app/components/document-list/extension-presets/name-column/name-column.component.ts
  demo-shell/src/app/components/files/files.component.html
  docs/content-services/components/document-list.component.md
  lib/content-services/src/lib/document-list/components/name-column/name-column.component.spec.ts
  lib/content-services/src/lib/document-list/components/name-column/name-column.component.ts
Labels: PR: partially-approved

#6872 [ACA-4358][ACA-4359] [APA] Floating label added for the process and t…
  angular.json
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.html
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-service-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.spec.ts
Labels: PR: partially-approved

#6891 [ACA-3619] - change assignment placeholder
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.html
Labels: PR: partially-approved

#6862 [AAE-4841] - Fix content node selector current selection is lost after uploading files
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/content-services/src/lib/document-list/data/share-data-row.model.ts
  lib/content-services/src/lib/document-list/data/share-datatable-adapter.spec.ts
  lib/content-services/src/lib/document-list/data/share-datatable-adapter.ts
  lib/content-services/src/lib/mock/document-library.model.mock.ts
  lib/content-services/src/lib/mock/document-list.component.mock.ts
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/core/datatable/data/data-row.model.ts
Labels: PR: partially-approved

#6807 [ACA-4202] - forcing firefox to ignore cache when document version ha…
  lib/core/viewer/components/pdf-viewer.component.ts
  lib/core/viewer/components/viewer.component.html
  lib/core/viewer/components/viewer.component.ts
Labels: PR: partially-approved

#6910 Update branch for JS-API PR#3366
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#6907 docker command: Create 2 different actions publish and link
  lib/cli/README.md
  lib/cli/scripts/docker-publish.ts
  lib/cli/scripts/docker.ts
  scripts/travis/release/release-docker.sh
Labels: PR: partially-approved

#6906 [ADF-5363] - when aspects has no name we will show the id instead
  lib/content-services/src/lib/aspect-list/aspect-list.component.html
  lib/content-services/src/lib/aspect-list/aspect-list.component.spec.ts
  lib/content-services/src/lib/aspect-list/aspect-list.component.ts
Labels: PR: partially-approved

#6916 [AAE-4483] Add empty list drag and drop template in upload from local…
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
Labels: PR: partially-approved

#6915 add enableFractions in form values on number widget
  lib/core/form/components/widgets/core/form-field.model.ts
Labels: PR: unreviewed

#6909 [ADF-5362] - showing in the confirm dialog only the propery of the cu…
  lib/content-services/src/lib/content-type/content-type-dialog.component.html
  lib/content-services/src/lib/content-type/content-type-dialog.component.spec.ts
  lib/content-services/src/lib/content-type/content-type-dialog.component.ts
Labels: PR: partially-approved

#6914 [AAE-4966] Extensible app config
  lib/content-services/src/lib/aspect-list/aspect-list.service.spec.ts
  lib/content-services/src/lib/document-list/services/custom-resources.service.spec.ts
  lib/content-services/src/lib/document-list/services/document-actions.service.spec.ts
  lib/content-services/src/lib/document-list/services/document-list.service.spec.ts
  lib/content-services/src/lib/document-list/services/folder-actions.service.spec.ts
  lib/content-services/src/lib/search/components/search-sorting-picker/search-sorting-picker.component.spec.ts
  lib/content-services/src/lib/search/search-header-query-builder.service.spec.ts
  lib/content-services/src/lib/search/search-query-builder.service.spec.ts
  lib/core/app-config/app-config.service.spec.ts
  lib/core/app-config/app-config.service.ts
  lib/core/app-config/debug-app-config.service.ts
  lib/core/datatable/components/datatable-cell/datatable-cell.component.spec.ts
  lib/core/directives/library-membership.directive.spec.ts
  lib/core/directives/node-favorite.directive.spec.ts
  lib/core/mock/alfresco-api.service.mock.ts
  lib/core/mock/app-config.service.mock.ts
  lib/core/mock/search.service.mock.ts
  lib/core/pipes/decimal-number.pipe.spec.ts
  lib/core/pipes/localized-date.pipe.spec.ts
  lib/core/pipes/time-ago.pipe.spec.ts
  lib/core/services/nodes-api.service.spec.ts
  lib/core/services/user-preferences.service.spec.ts
  lib/core/testing/core.testing.module.ts
  lib/core/viewer/components/media-player.component.spec.ts
  lib/core/viewer/components/viewer.component.spec.ts
  lib/extensions/src/lib/config/extension.config.ts
  lib/extensions/src/lib/config/schema/plugin-extension.schema.json
  lib/extensions/src/lib/services/extension.service.ts
  lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/form/services/form-definition-selector-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/services/notification-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/services/user-preference-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/services/service-task-list-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/testing/process-service-cloud.testing.module.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.spec.ts
  lib/process-services/src/lib/process-list/services/process-filter.service.spec.ts
  lib/process-services/src/lib/process-list/services/process-filter.service.ts
  lib/process-services/src/lib/process-list/services/process.service.spec.ts
  lib/process-services/src/lib/task-list/services/task-filter.service.spec.ts
  lib/process-services/src/lib/task-list/services/tasklist.service.spec.ts
  lib/process-services/src/lib/testing/process.testing.module.ts
Labels: PR: partially-approved

#6925 [ADF-5372] - fixed wrong result pipe
  lib/core/pipes/file-size.pipe.spec.ts
  lib/core/pipes/file-size.pipe.ts
Labels: PR: unreviewed

#6922 [ADF-5362] - Content type properties should be showed when content type is changed.
  e2e/content-services/metadata/metadata-smoke-tests.e2e.ts
  e2e/core/pages/metadata-view.page.ts
  e2e/core/viewer/viewer-content-services-component.e2e.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
  lib/content-services/src/lib/content-metadata/services/basic-properties.service.ts
  lib/content-services/src/lib/content-metadata/services/content-metadata.service.spec.ts
  lib/content-services/src/lib/content-metadata/services/content-metadata.service.ts
  lib/content-services/src/lib/content-metadata/services/content-type-property.service.spec.ts
  lib/content-services/src/lib/content-metadata/services/content-type-property.service.ts
  lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.spec.ts
  lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
Labels: PR: partially-approved

#6881 [AAE-4428] Add selected file counter to attach file widget
  docs/content-services/directives/node-counter.directive.md
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.module.ts
  lib/content-services/src/lib/directives/content-directive.module.ts
  lib/content-services/src/lib/directives/node-counter.directive.spec.ts
  lib/content-services/src/lib/directives/node-counter.directive.ts
  lib/content-services/src/lib/i18n/en.json
Labels: PR: partially-approved

#6926 Revert "[ADF-5346] DocumentList - header is not scrollable when the width of the browser is small"
  lib/core/datatable/components/datatable/datatable.component.scss
Labels: PR: partially-approved

#6927 Run develop only once a day
  .travis.yml
Labels: PR: partially-approved

#6923 [ADF-5370] - fixed style for container dimension
  lib/core/form/components/widgets/container/container.widget.scss
Labels: PR: partially-approved

#6930 [AAE-4879] Update tooltip card to receive custom HTML
  lib/core/directives/tooltip-card/tooltip-card.component.html
  lib/core/directives/tooltip-card/tooltip-card.component.scss
  lib/core/directives/tooltip-card/tooltip-card.component.ts
  lib/core/directives/tooltip-card/tooltip-card.directive.spec.ts
  lib/core/directives/tooltip-card/tooltip-card.directive.ts
Labels: PR: partially-approved

#6928 [MNT-22207] - resetting query fragment when clicking Reset all button…
  lib/content-services/src/lib/search/components/search-filter/search-filter.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter/search-filter.component.ts
Labels: PR: partially-approved

#6939 [AAE-4879] Detach tooltip card when directive is destroyed
  lib/core/directives/tooltip-card/tooltip-card.directive.spec.ts
  lib/core/directives/tooltip-card/tooltip-card.directive.ts
Labels: PR: partially-approved

#6886 [ACA-3700] - add suspended date filter
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
Labels: PR: unreviewed

#6929 [ADF-5225] smoke test
  e2e/protractor.conf.js
  lib/testing/src/lib/core/actions/api.service.ts
Labels: PR: unreviewed

#6931 [AAE-4995] Expand ADF PeopleContentService to create new person
  docs/core/services/people-content.service.md
  lib/core/mock/ecm-user.service.mock.ts
  lib/core/services/people-content.service.spec.ts
  lib/core/services/people-content.service.ts
Labels: PR: partially-approved

#6938 [AAE-4863] Fixed the async and done warning due to new version of Karma
  lib/core/testing/setup-test-bed.ts
Labels: PR: partially-approved

#6940 [ACA-3700] - fix suspended data filter not preserving data
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
Labels: PR: partially-approved

#6943 Improve checkFilesAreAttachedToWidget() method
  e2e/protractor.excludes.json
  lib/testing/src/lib/core/pages/form/widgets/attach-file-widget.page.ts
Labels: PR: unreviewed

#6942 [AAE-4985] - Make SSO Role Service accept a content admin role that is not part of the JWT token
  docs/core/services/auth-guard-sso-role.service.md
  e2e/protractor.excludes.json
  lib/core/mock/ecm-user.service.mock.ts
  lib/core/services/auth-guard-sso-role.service.spec.ts
  lib/core/services/auth-guard-sso-role.service.ts
  lib/core/services/people-content.service.spec.ts
  lib/core/services/people-content.service.ts
Labels: PR: partially-approved

#6949 Run all e2e for cron jobs
  scripts/travis/e2e/e2e.sh
Labels: PR: partially-approved

#6948 [ACA-4361] should be able to change permission if search service is down
  lib/content-services/src/lib/permission-manager/services/node-permission.service.spec.ts
  lib/content-services/src/lib/permission-manager/services/node-permission.service.ts
Labels: PR: partially-approved, do not merge 🙅🏻‍♂️

#6950 Fix content unit tests executing twice
  scripts/travis/unit-test/content.sh
Labels: PR: partially-approved

#6951 improve travis ci
  .travis.yml
  scripts/travis/release/deprecate-develop-build.sh
  scripts/travis/update/pr-creator.js
Labels: PR: partially-approved

#6952 [ADF-5362] - enabiling properties refresh on ADW/ACA
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
Labels: PR: partially-approved

#6954 [E2E] Log demo shell not starting
  e2e/protractor.conf.js
Labels: PR: reviewed-approved

#6956 rename env variable
  e2e/test.config.js
Labels: PR: partially-approved

#6953 Travis Ci only remove e2e on develop merge
  .travis.yml
Labels: PR: partially-approved

#6957 Abn content fixes
  docs/content-services/components/document-list.component.md
  docs/core/services/auth-guard-sso-role.service.md
  docs/core/services/process-content.service.md
Labels: PR: reviewed-approved

#6962 Fix e2e protractor
  e2e/protractor.conf.js
  nx.json
Labels: PR: partially-approved

#6947 [AAE-5021] Add listPeople method to PeopleContentService
  docs/core/services/people-content.service.md
  lib/content-services/src/lib/permission-manager/components/user-name-column/user-name-column.component.ts
  lib/content-services/src/lib/permission-manager/models/member.model.ts
  lib/content-services/src/lib/permission-manager/services/node-permission.service.ts
  lib/core/mock/ecm-user.service.mock.ts
  lib/core/models/comment.model.ts
  lib/core/models/ecm-user.model.ts
  lib/core/services/people-content.service.spec.ts
  lib/core/services/people-content.service.ts
  lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
Labels: PR: unreviewed

#6960 More documentation syntax fixes
  docs/core/services/process-content.service.md
Labels: PR: reviewed-approved

#6963 [ACS-1526] Fail on Draft and unapproved PRs
  .travis.yml
  scripts/ci/job_hooks/before_install.sh
  scripts/ci/jobs/dbpci-build-guard-check
  scripts/ci/partials/_ci-flags-parser.sh
Labels: PR: partially-approved

#6864 [ADF-5366] initialize discovery and version compatibility service for oauth based session
  e2e/content-services/components/permissions-component.e2e.ts
  e2e/content-services/components/site-permissions.e2e.ts
  e2e/content-services/metadata/metadata-content-type.e2e.ts
  e2e/core/pages/metadata-view.page.ts
  e2e/protractor.conf.js
  e2e/protractor.excludes.json
  lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.html
  lib/core/directives/node-download.directive.spec.ts
  lib/core/services/authentication.service.ts
  lib/core/services/discovery-api.service.spec.ts
  lib/core/services/discovery-api.service.ts
  lib/core/services/external-alfresco-api.service.ts
  lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/form/services/form-definition-selector-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/services/notification-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/services/user-preference-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/services/service-task-list-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.spec.ts
  lib/testing/src/lib/content-services/actions/model.actions.ts
  lib/testing/src/lib/content-services/dialog/add-permissions-dialog.page.ts
Labels: PR: partially-approved
