Repository Alfresco/alfresco-ng2-components, pull requests merged in 2021-03, with the labels that each got.

#6761 ADF 4.3 Release Note in draft.
  docs/abn-tree.yml
  docs/release-notes/README.md
  docs/release-notes/RelNote410.md
  docs/release-notes/RelNote420.md
  docs/release-notes/RelNote430.md
Labels: documentation 📄

#6779 Added extra checks for fixing the e2e
  e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
Labels: PR: partially-approved

#6775 Update branch for JS-API PR#3264
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#6773 [AAE-4749] process filter notification fixes
  e2e/protractor.excludes.json
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
Labels: PR: unreviewed

#6780 [ACA-4322] Logout - Avoid the redirect in case SSO auth
  lib/core/directives/logout.directive.spec.ts
  lib/core/directives/logout.directive.ts
Labels: PR: partially-approved

#6774 [ADF-5353] WS Token refresh
  demo-shell/src/app.config.json
  e2e/protractor.excludes.json
  lib/process-services-cloud/src/lib/services/notification-cloud.service.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
Labels: PR: partially-approved

#6777 [ADF-5354] Content node selector is not working properly for read-only folders
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
Labels: PR: unreviewed

#6785 [ACA-4198] fix appVersion init for multiple versions
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
Labels: PR: unreviewed

#6787 Update branch for JS-API PR#3278
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#6795 Revert "[MNT-22063] - fix form cloud layout"
  lib/core/form/components/widgets/container/container.widget.scss
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.scss
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.scss
Labels: PR: partially-approved

#6792 [ADF-5357] - Convert process name manual tests to unit tests
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
Labels: PR: unreviewed

#6798 Update ADW+APS1 e2e-Application.zip
  lib/cli/resources/e2e-Application.zip
Labels: PR: partially-approved

#6793 4.3.0
  demo-shell/package.json
  docs/license-info/README.md
  docs/license-info/license-info-4.3.0.md
  docs/vulnerability/README.md
  docs/vulnerability/audit-info-4.3.0.md
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/package-lock.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  scripts/release.sh
Labels: PR: partially-approved

#6801 Revert "[ADF-5354] Content node selector is not working properly for read-only folders"
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
Labels: PR: partially-approved

#6804 Move the upstream to a lower level
  .travis.yml
Labels: PR: partially-approved

#6805 [ACA-4344] - increase debounce time on process filters
  .travis.yml
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  scripts/ci/job_hooks/after_e2e.sh
  scripts/ci/job_hooks/before_e2e.sh
  scripts/ci/job_hooks/before_install.sh
Labels: PR: unreviewed

#6784 [ADF-5355] - Fix attach button visibility when using external source
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.html
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.spec.ts
  lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.ts
Labels: PR: unreviewed

#6815 [ADF-5358] - fixed duplicated type on reopening viewer
  lib/content-services/src/lib/content-metadata/services/content-type-property.service.ts
Labels: PR: partially-approved

#6823 Add some more info on the refresh token timeout
  docs/core/components/login.component.md
  lib/core/app-config/schema.json
  lib/core/models/oauth-config.model.ts
Labels: PR: unreviewed

#6799 [ADF-5318] E2E Content Change type
  e2e/content-services/metadata/metadata-content-type.e2e.ts
  e2e/core/pages/metadata-view.page.ts
  lib/content-services/src/lib/content-type/content-type-dialog.component.html
  lib/content-services/src/lib/content-type/content-type-dialog.component.spec.ts
  lib/testing/src/lib/content-services/actions/model.actions.ts
  lib/testing/src/lib/content-services/actions/public-api.ts
Labels: PR: partially-approved

#6800 [ADF-5359] Improve response time for filter counters
  lib/process-services-cloud/src/lib/task/task-filters/components/base-task-filters-cloud.component.scss
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
Labels: PR: partially-approved

#6778 [ACA-4307] Move Process task JSON mapping e2e process and task names to ADF resource file
  lib/testing/src/lib/core/pages/form/widgets/display-value-widget.page.ts
  lib/testing/src/lib/process-services-cloud/resources/resources.json
Labels: PR: partially-approved

#6382 [ACA-4096] - Add getProcessFilters method in testing for APS - filters util
  lib/testing/src/lib/process-services/actions/user-filters.util.ts
Labels: PR: partially-approved

#6834 additional API docs for the TestElement
  lib/testing/src/lib/core/test-element.ts
Labels: PR: partially-approved

#6837 Validate config improvements
  lib/core/app-config/schema.json
  package.json
  scripts/lint.sh
Labels: PR: unreviewed

#6838 [ACA-4350] Add widgets to inputform for SIMPLE_APP
  lib/testing/src/lib/process-services-cloud/resources/resources.json
Labels: PR: partially-approved

#6806 [ACA-4306] Testing - Add form widget ids in the SIMPLEAPP resources file
  lib/testing/src/lib/process-services-cloud/resources/resources.json
  scripts/ci/job_hooks/before_install.sh
  scripts/git-util/check-branch-updated.sh
  scripts/travis/e2e/content-services-e2e.sh
  scripts/travis/e2e/core-e2e.sh
  scripts/travis/e2e/insights-e2e.sh
  scripts/travis/e2e/process-services-cloud-e2e.sh
  scripts/travis/e2e/process-services-e2e.sh
  scripts/travis/e2e/search-e2e.sh
  scripts/travis/unit-test/content.sh
  scripts/travis/unit-test/core-extension.sh
  scripts/travis/unit-test/process-cloud.sh
  scripts/travis/unit-test/process.sh
Labels: PR: partially-approved

#6840 [AAE-4751] Modify Delete method
  lib/testing/src/lib/process-services-cloud/actions/descriptor.ts
Labels: PR: partially-approved

#6846 Fix affect
  .travis.yml
  e2e/protractor.conf.js
  scripts/test-e2e-lib.sh
  scripts/travis/e2e/content-services-e2e.sh
  scripts/travis/e2e/core-e2e.sh
  scripts/travis/e2e/e2e.sh
  scripts/travis/e2e/insights-e2e.sh
  scripts/travis/e2e/process-services-cloud-e2e.sh
  scripts/travis/e2e/process-services-e2e.sh
  scripts/travis/e2e/search-e2e.sh
Labels: PR: partially-approved

#6738 [AAE-4697] Restrict content node selector breadcrumb when destination folder path is wrong
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
  lib/process-services-cloud/src/lib/form/mocks/attach-file-cloud-widget.mock.ts
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
Labels: PR: unreviewed

#6852 [MNT-22236] update e2e to reflect permission i18n support
  e2e/content-services/components/comment-component.e2e.ts
  e2e/content-services/components/lock-file.e2e.ts
  e2e/content-services/components/site-permissions.e2e.ts
  e2e/content-services/components/unshare-file.e2e.ts
  e2e/content-services/directives/create-library-directive.e2e.ts
  e2e/content-services/directives/delete-directive.e2e.ts
  e2e/content-services/document-list/document-list-copy-move-actions.e2e.ts
  e2e/content-services/document-list/document-list-permissions.e2e.ts
  e2e/content-services/metadata/metadata-permissions.e2e.ts
  e2e/content-services/upload/user-permission.e2e.ts
  e2e/content-services/upload/version-permissions.e2e.ts
  e2e/core/viewer/file-extensions/viewer-archive.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-excel.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-image.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-powerpoint.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-text.component.e2e.ts
  e2e/core/viewer/file-extensions/viewer-word.component.e2e.ts
  e2e/core/viewer/viewer-share-content.ts
  e2e/search/search-multiselect.e2e.ts
  e2e/util/constants.js
Labels: PR: unreviewed

#6854 [ACA-4337]Move APW tests: claim/release standalone task, json widget
  e2e/process-services-cloud/form-field/json-widget.e2e.ts
  e2e/process-services-cloud/task-list/tasks-claim-release.e2e.ts
  lib/testing/src/lib/core/pages/form/widgets/json-widget.page.ts
  lib/testing/src/lib/core/pages/form/widgets/widget.ts
Labels: PR: unreviewed

#6851 [AAE-4823] Add resources used in e2e tests in ADW
  lib/testing/src/lib/process-services-cloud/resources/resources.json
Labels: PR: unreviewed

#6856 [MNT-22236] UI strings fully updated in 16 languages
  demo-shell/resources/i18n/ar.json
  demo-shell/resources/i18n/cs.json
  demo-shell/resources/i18n/da.json
  demo-shell/resources/i18n/de.json
  demo-shell/resources/i18n/es.json
  demo-shell/resources/i18n/fi.json
  demo-shell/resources/i18n/fr.json
  demo-shell/resources/i18n/it.json
  demo-shell/resources/i18n/ja.json
  demo-shell/resources/i18n/nb.json
  demo-shell/resources/i18n/nl.json
  demo-shell/resources/i18n/pl.json
  demo-shell/resources/i18n/pt-BR.json
  demo-shell/resources/i18n/ru.json
  demo-shell/resources/i18n/sv.json
  demo-shell/resources/i18n/zh-CN.json
  lib/core/i18n/ar.json
  lib/core/i18n/cs.json
  lib/core/i18n/da.json
  lib/core/i18n/de.json
  lib/core/i18n/es.json
  lib/core/i18n/fi.json
  lib/core/i18n/fr.json
  lib/core/i18n/it.json
  lib/core/i18n/ja.json
  lib/core/i18n/nb.json
  lib/core/i18n/nl.json
  lib/core/i18n/pl.json
  lib/core/i18n/pt-BR.json
  lib/core/i18n/ru.json
  lib/core/i18n/sv.json
  lib/core/i18n/zh-CN.json
  lib/process-services-cloud/src/lib/i18n/ar.json
  lib/process-services-cloud/src/lib/i18n/cs.json
  lib/process-services-cloud/src/lib/i18n/da.json
  lib/process-services-cloud/src/lib/i18n/de.json
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/i18n/es.json
  lib/process-services-cloud/src/lib/i18n/fi.json
  lib/process-services-cloud/src/lib/i18n/fr.json
  lib/process-services-cloud/src/lib/i18n/it.json
  lib/process-services-cloud/src/lib/i18n/ja.json
  lib/process-services-cloud/src/lib/i18n/nb.json
  lib/process-services-cloud/src/lib/i18n/nl.json
  lib/process-services-cloud/src/lib/i18n/pl.json
  lib/process-services-cloud/src/lib/i18n/pt-BR.json
  lib/process-services-cloud/src/lib/i18n/ru.json
  lib/process-services-cloud/src/lib/i18n/sv.json
  lib/process-services-cloud/src/lib/i18n/zh-CN.json
Labels: PR: unreviewed

#6850 [AAE-4017] Change label: attach file retrieve metadata
  lib/process-services-cloud/src/lib/i18n/en.json
Labels: PR: partially-approved

#6853 [AAE-4817] E2E - Add process/form wdget ids in the CANDIDATEBASEAPP resources file
  lib/testing/src/lib/process-services-cloud/resources/resources.json
Labels: PR: partially-approved

#6861 migrate library directives from ACA
  lib/core/directives/directive.module.ts
  lib/core/directives/library-favorite.directive.spec.ts
  lib/core/directives/library-favorite.directive.ts
  lib/core/directives/library-membership.directive.spec.ts
  lib/core/directives/library-membership.directive.ts
  lib/core/directives/public-api.ts
Labels: PR: unreviewed

#6847 update js-api
  demo-shell/src/polyfills.ts
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#6863 [AAE-4817] Add reusble method in ProcessListCloudComponent page object
  lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-form-cloud-component.page.ts
Labels: PR: partially-approved

#6845 [MNT-22298] - Added check for ACS version
  lib/content-services/src/lib/content-metadata/services/content-type-property.service.spec.ts
  lib/content-services/src/lib/content-metadata/services/content-type-property.service.ts
Labels: PR: partially-approved

#6873 [ACA-4370] Refresh filter counter on filter click
  lib/process-services-cloud/src/lib/services/notification-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/services/notification-cloud.service.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
Labels: PR: partially-approved

#6874 [ADF-5225] smoke test suite
  e2e/protractor.conf.js
Labels: PR: unreviewed

#6865 [AAE-4824] Add more widgets to resources and cloud related methods
  lib/testing/src/lib/core/utils/string.util.ts
  lib/testing/src/lib/process-services-cloud/pages/task-form-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/resources/resources.json
Labels: PR: unreviewed

#6875 [AAE-4842] Extensibility: support replacing values on merge
  lib/extensions/src/lib/config/extension-utils.spec.ts
  lib/extensions/src/lib/config/extension-utils.ts
Labels: PR: partially-approved

#6860 [ACA-4220] - preselect initator values by username
  demo-shell/src/app/components/cloud/processes-cloud-demo.component.html
  demo-shell/src/app/components/cloud/processes-cloud-demo.component.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
Labels: PR: partially-approved

#6866 [ACA-4324]MovAdd details about tasks in resource files
  lib/testing/src/lib/process-services-cloud/resources/resources.json
Labels: PR: partially-approved

#6882 Update wrong methods
  lib/testing/src/lib/core/utils/string.util.ts
Labels: PR: partially-approved
