Repository Alfresco/alfresco-ng2-components, pull requests merged in 2021-01, with the labels that each got.

#6460 [AAE-3472] e2e service task
  e2e/core/pages/navigation-bar.page.ts
  e2e/process-services-cloud/pages/service-task-list.page.ts
  e2e/process-services-cloud/service-task-list-cloud-component.e2e.ts
  e2e/protractor.excludes.json
  e2e/test.config.js
  e2e/util/constants.js
Labels: PR: reviewed-changes-requested

#6473 [ACA-3975]Add process definitions to simpleapp
  e2e/resources/activiti7/simpleapp.zip
  lib/testing/src/lib/core/pages/card-view/card-view-text-item.page.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  lib/testing/src/lib/process-services-cloud/resources/resources.json
Labels: PR: unreviewed

#6545 Getting started tutorial on ADF.
  docs/abn-tree.yml
  docs/getting-started.md
Labels: documentation 📄
