Repository Alfresco/alfresco-ng2-components, pull requests merged in 2021-05, with the labels that each got.

#6958 [ADF-5378] ADF Previewer: Image Rotate + Save
  angular.json
  docs/core/components/viewer.component.md
  e2e/core/viewer/viewer-content-services-component.e2e.ts
  lib/core/i18n/en.json
  lib/core/package.json
  lib/core/viewer/components/img-viewer.component.html
  lib/core/viewer/components/img-viewer.component.scss
  lib/core/viewer/components/img-viewer.component.spec.ts
  lib/core/viewer/components/img-viewer.component.ts
  lib/core/viewer/components/viewer.component.html
  lib/core/viewer/components/viewer.component.scss
  lib/core/viewer/components/viewer.component.spec.ts
  lib/core/viewer/components/viewer.component.ts
  package-lock.json
  package.json
Labels: PR: partially-approved

#6967 [ADF-5371] fix swsdp in breadcrumb
  lib/content-services/src/lib/i18n/en.json
Labels: PR: partially-approved

#6959 [ACA-4389] [APS1] Convert some of process services extension E2E steps to unit-tests
  lib/process-services/src/lib/task-list/components/task-filters.component.spec.ts
  lib/process-services/src/lib/task-list/components/task-form/task-form.component.spec.ts
Labels: PR: partially-approved

#6968 [AAE-4973] - fixed start process button enabling when default process…
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
Labels: PR: partially-approved

#6974 [ACA-4361] Review permission list
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-dialog.component.html
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-dialog.component.scss
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.scss
  lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.html
  lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.scss
  lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.ts
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.scss
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.service.ts
  lib/content-services/src/lib/permission-manager/components/user-icon-column/user-icon-column.component.scss
  lib/content-services/src/lib/permission-manager/components/user-icon-column/user-icon-column.component.spec.ts
  lib/content-services/src/lib/permission-manager/components/user-icon-column/user-icon-column.component.ts
  lib/content-services/src/lib/permission-manager/components/user-role-column/user-role-column.component.ts
Labels: PR: partially-approved

#6924 [ADF-5379] Add a way to disable WS notifications
  demo-shell/src/app.config.json
  demo-shell/src/app/services/app-notifications.service.ts
  docs/docassets/images/update-filter-bubble.png
  docs/process-services-cloud/components/task-filters-cloud.component.md
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
Labels: PR: unreviewed

#6975 CropperJS dependency from styles to assets
  angular.json
  lib/core/viewer/components/viewer.component.scss
Labels: PR: partially-approved

#6977 [ADF-5377] Viewer: Image Crop
  lib/core/i18n/en.json
  lib/core/viewer/components/img-viewer.component.html
  lib/core/viewer/components/img-viewer.component.spec.ts
  lib/core/viewer/components/img-viewer.component.ts
Labels: PR: partially-approved

#6964 Update branch for JS-API PR#3405
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#6986 [ACA-4361] Fix data column conflict
  lib/core/data-column/data-column-header.component.ts
  lib/core/datatable/data/object-datacolumn.model.ts
Labels: PR: partially-approved

#6991 Update branch for JS-API PR#3450
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#6992 [ADF-5393] auto update node version when media management actions are…
  demo-shell/src/app/components/app-layout/app-layout.component.html
  demo-shell/src/app/components/app-layout/app-layout.component.scss
  demo-shell/src/app/components/files/files.component.html
  docs/core/components/viewer.component.md
  lib/core/viewer/components/img-viewer.component.ts
  lib/core/viewer/components/viewer.component.html
  lib/core/viewer/components/viewer.component.spec.ts
  lib/core/viewer/components/viewer.component.ts
Labels: PR: unreviewed

#6980 [ADF-5390] [ADF-5391] Add multivalue cardview for Date, Datetime, Integers and Decimal properties.
  demo-shell/src/app/components/card-view/card-view.component.ts
  e2e/core/pages/metadata-view.page.ts
  e2e/process-services/pages/task-details.page.ts
  lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.html
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.scss
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
  lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
  lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
  lib/core/card-view/interfaces/card-view-item-properties.interface.ts
  lib/core/card-view/models/card-view-baseitem.model.ts
  lib/core/card-view/models/card-view-dateitem.model.ts
  lib/core/card-view/models/card-view-floatitem.model.ts
  lib/core/card-view/models/card-view-intitem.model.ts
  lib/core/card-view/models/card-view-textitem.model.ts
  lib/core/card-view/validators/card-view-item-float.validator.ts
  lib/core/card-view/validators/card-view-item-int.validator.ts
  lib/core/pipes/decimal-number.pipe.ts
  lib/core/pipes/multi-value.pipe.spec.ts
  lib/core/pipes/multi-value.pipe.ts
  lib/testing/src/lib/process-services-cloud/pages/task-header-cloud-component.page.ts
Labels: PR: unreviewed

#6993 audit npm fix
  package-lock.json
  package.json
Labels: PR: unreviewed

#7007 [ADF-5393] add missing event on image viewer
  lib/core/viewer/components/viewer.component.html
Labels: PR: partially-approved

#7004 [ACA-4407] unit test for data table custom header
  lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.scss
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.scss
  lib/core/datatable/components/datatable/datatable.component.spec.ts
Labels: PR: partially-approved

#6999 Update branch for JS-API PR#3476
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#6966 [ACS-1525] Only run scan environment on cron
  lib/cli/README.md
  scripts/ci/job_hooks/after_e2e.sh
  scripts/ci/job_hooks/before_e2e.sh
Labels: PR: reviewed-approved

#7005 Start Process Cloud - Use the cloud key for validate error
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
Labels: PR: partially-approved

#7013 [AAE-5128] [APA] Drag and Drop template is broken on Upload from your…
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
Labels: PR: partially-approved

#7014 LOC-300 Updated UI files in 16 languages
  demo-shell/resources/i18n/cs.json
  demo-shell/resources/i18n/fr.json
  demo-shell/resources/i18n/it.json
  demo-shell/resources/i18n/nl.json
  demo-shell/resources/i18n/pt-BR.json
  demo-shell/resources/i18n/ru.json
  lib/content-services/src/lib/i18n/ar.json
  lib/content-services/src/lib/i18n/cs.json
  lib/content-services/src/lib/i18n/da.json
  lib/content-services/src/lib/i18n/de.json
  lib/content-services/src/lib/i18n/es.json
  lib/content-services/src/lib/i18n/fi.json
  lib/content-services/src/lib/i18n/fr.json
  lib/content-services/src/lib/i18n/it.json
  lib/content-services/src/lib/i18n/ja.json
  lib/content-services/src/lib/i18n/nb.json
  lib/content-services/src/lib/i18n/nl.json
  lib/content-services/src/lib/i18n/pl.json
  lib/content-services/src/lib/i18n/pt-BR.json
  lib/content-services/src/lib/i18n/ru.json
  lib/content-services/src/lib/i18n/sv.json
  lib/content-services/src/lib/i18n/zh-CN.json
  lib/core/i18n/ar.json
  lib/core/i18n/cs.json
  lib/core/i18n/da.json
  lib/core/i18n/de.json
  lib/core/i18n/es.json
  lib/core/i18n/fi.json
  lib/core/i18n/fr.json
  lib/core/i18n/it.json
  lib/core/i18n/ja.json
  lib/core/i18n/nb.json
  lib/core/i18n/nl.json
  lib/core/i18n/pl.json
  lib/core/i18n/pt-BR.json
  lib/core/i18n/ru.json
  lib/core/i18n/sv.json
  lib/core/i18n/zh-CN.json
  lib/process-services-cloud/src/lib/i18n/ar.json
  lib/process-services-cloud/src/lib/i18n/cs.json
  lib/process-services-cloud/src/lib/i18n/da.json
  lib/process-services-cloud/src/lib/i18n/de.json
  lib/process-services-cloud/src/lib/i18n/es.json
  lib/process-services-cloud/src/lib/i18n/fi.json
  lib/process-services-cloud/src/lib/i18n/fr.json
  lib/process-services-cloud/src/lib/i18n/it.json
  lib/process-services-cloud/src/lib/i18n/ja.json
  lib/process-services-cloud/src/lib/i18n/nb.json
  lib/process-services-cloud/src/lib/i18n/nl.json
  lib/process-services-cloud/src/lib/i18n/pl.json
  lib/process-services-cloud/src/lib/i18n/pt-BR.json
  lib/process-services-cloud/src/lib/i18n/ru.json
  lib/process-services-cloud/src/lib/i18n/sv.json
  lib/process-services-cloud/src/lib/i18n/zh-CN.json
Labels: PR: partially-approved

#7010 [AAE-5139] User name style and Discovery service initialization fix
  e2e/content-services/metadata/metadata-content-type.e2e.ts
  e2e/protractor.excludes.json
  lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.html
  lib/content-services/src/lib/permission-manager/components/user-icon-column/user-icon-column.component.scss
  lib/content-services/src/lib/permission-manager/components/user-icon-column/user-icon-column.component.ts
  lib/content-services/src/lib/permission-manager/components/user-name-column/user-name-column.component.scss
  lib/content-services/src/lib/permission-manager/components/user-name-column/user-name-column.component.ts
  lib/content-services/src/lib/styles/_index.scss
  lib/core/directives/node-download.directive.spec.ts
  lib/core/mock/search.service.mock.ts
  lib/core/services/authentication.service.ts
  lib/core/services/discovery-api.service.spec.ts
  lib/core/services/discovery-api.service.ts
  lib/core/services/nodes-api.service.spec.ts
  lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/form/services/form-definition-selector-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/services/notification-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/services/user-preference-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/services/service-task-list-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.spec.ts
  package-lock.json
  package.json
Labels: PR: partially-approved

#7011 [AAE-5124] Show counter only when attaching files
  docs/content-services/components/content-node-selector-panel.component.md
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
Labels: PR: partially-approved

#7017 [ACA-4325] - disable upload button on upload new file version begin
  lib/content-services/src/lib/version-manager/version-upload.component.spec.ts
  lib/content-services/src/lib/version-manager/version-upload.component.ts
Labels: PR: partially-approved

#7019 Update branch for JS-API PR#3494
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7029 update docs on the extension value replace
  docs/user-guide/app-extensions.md
Labels: PR: reviewed-approved

#7027 [AAE-5146] Viewer - Reset button is in fact Full Screen button in ADW
  lib/core/viewer/components/img-viewer.component.spec.ts
  lib/core/viewer/components/img-viewer.component.ts
Labels: PR: partially-approved

#7020 [ACA-3700] - fix suspened date start date
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
Labels: PR: partially-approved

#7021 [ACA-2864] Site Managers are not able to disable inherit permissions …
  lib/content-services/src/lib/mock/permission-list.component.mock.ts
  lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.html
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.spec.ts
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.ts
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.service.spec.ts
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.service.ts
  lib/content-services/src/lib/permission-manager/models/permission.model.ts
Labels: PR: unreviewed

#7026 [ADF-5379] change notification history service storage variable
  lib/core/notifications/components/notification-history.component.spec.ts
  lib/core/notifications/components/notification-history.component.ts
Labels: PR: unreviewed

#7028 Fixing header style as now it's not aligned anymore
  lib/core/form/components/form-renderer.component.scss
Labels: PR: partially-approved

#7024 [ACA-4423] VIEWER - when closing the upload dialog the filename changes to "Unknown"
  lib/core/viewer/components/viewer.component.spec.ts
  lib/core/viewer/components/viewer.component.ts
Labels: PR: partially-approved

#7022 [ACA-4422] Resolved - Edit Aspects Dialog should close when pressing ESC
  lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.spec.ts
  lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.ts
Labels: PR: partially-approved

#7018 [ACA-4409] Resolved - More button is displayed on Destination Picker …
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
Labels: PR: unreviewed

#7023 [AAE-4009] Fix horizontal scroll issue for pdf-viewer
  lib/core/viewer/components/pdf-viewer.component.spec.ts
  lib/core/viewer/components/pdf-viewer.component.ts
Labels: PR: partially-approved

#7037 [ADF-5397] Resolved - selection count should show at the end
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
Labels: PR: unreviewed

#7035 [ACA-4421] [Edit Aspects] Apply button should be disabled by default
  lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.html
  lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.spec.ts
  lib/content-services/src/lib/aspect-list/aspect-list.component.spec.ts
  lib/content-services/src/lib/aspect-list/aspect-list.component.ts
Labels: PR: partially-approved

#7038 [ADF-5398] Form fix style
  lib/core/form/components/widgets/container/container.widget.scss
Labels: PR: partially-approved

#7036 LOC-300 Second commit of updated UI files in 16 languages
  demo-shell/resources/i18n/pt-BR.json
  lib/content-services/src/lib/i18n/ar.json
  lib/content-services/src/lib/i18n/cs.json
  lib/content-services/src/lib/i18n/da.json
  lib/content-services/src/lib/i18n/de.json
  lib/content-services/src/lib/i18n/es.json
  lib/content-services/src/lib/i18n/fi.json
  lib/content-services/src/lib/i18n/fr.json
  lib/content-services/src/lib/i18n/it.json
  lib/content-services/src/lib/i18n/ja.json
  lib/content-services/src/lib/i18n/nb.json
  lib/content-services/src/lib/i18n/nl.json
  lib/content-services/src/lib/i18n/pl.json
  lib/content-services/src/lib/i18n/pt-BR.json
  lib/content-services/src/lib/i18n/ru.json
  lib/content-services/src/lib/i18n/sv.json
  lib/content-services/src/lib/i18n/zh-CN.json
  lib/core/i18n/ar.json
  lib/core/i18n/cs.json
  lib/core/i18n/da.json
  lib/core/i18n/de.json
  lib/core/i18n/es.json
  lib/core/i18n/fi.json
  lib/core/i18n/fr.json
  lib/core/i18n/it.json
  lib/core/i18n/ja.json
  lib/core/i18n/nb.json
  lib/core/i18n/nl.json
  lib/core/i18n/pl.json
  lib/core/i18n/pt-BR.json
  lib/core/i18n/ru.json
  lib/core/i18n/sv.json
  lib/core/i18n/zh-CN.json
Labels: PR: partially-approved

#7040 [ADF-5399] Viewer- Editing a property by pressing the letter "r" inside the info drawer in the image viewer unexpectedly rotates the image
  lib/core/info-drawer/info-drawer.component.ts
  lib/core/viewer/components/viewer-sidebar.component.ts
Labels: PR: partially-approved

#7043 [ACA-4445] - disabled edit aspect button on content card for ACS vers…
  lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.html
  lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.spec.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.ts
Labels: PR: partially-approved

#7050 [ACA-4458]Add expand cloud custom filter method
  e2e/process-services-cloud/task-list/edit-process-filters-component.e2e.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
Labels: PR: partially-approved

#7048 Fix some build scripts
  .travis.yml
  scripts/npm-move-tag.sh
  scripts/travis/build/build-libs.sh
  scripts/travis/release/release-npm.sh
Labels: PR: partially-approved

#7041 [MNT-22418] Update activiti-alfresco.service.ts to make it work with records
  lib/core/form/services/activiti-alfresco.service.ts
Labels: PR: partially-approved

#7042 [ADF-5400] PDF viewer - The document page from the thumbnail pane is not highlighted
  lib/core/viewer/components/pdf-viewer-thumbnails.component.scss
Labels: PR: partially-approved

#7044 [ADF-5387] - Fix dropdown tests, remove call to external API
  e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts
  e2e/process-services-cloud/process/process-header-cloud.e2e.ts
  e2e/process-services-cloud/task-list/task-form-cloud-component.e2e.ts
  e2e/process-services-cloud/task-list/task-list-properties.e2e.ts
  e2e/process-services-cloud/task-list/tasks-custom-filters.e2e.ts
  e2e/protractor.excludes.json
  e2e/resources/activiti7/simpleapp.zip
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
  lib/testing/src/lib/process-services-cloud/resources/resources.json
Labels: PR: unreviewed

#7045 [DW-1608] Added username tag in the ID of the dropdown in deploy appl…
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
Labels: PR: partially-approved

#7046 [ACA-4454] The create library button should get disabled after being …
  lib/content-services/src/lib/dialogs/library/library.dialog.html
  lib/content-services/src/lib/dialogs/library/library.dialog.spec.ts
  lib/content-services/src/lib/dialogs/library/library.dialog.ts
  lib/core/services/sites.service.ts
Labels: PR: partially-approved

#7057 [MNT-22418] - disabling action for physical records
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/mocks/attach-file-cloud-widget.mock.ts
  lib/process-services/src/lib/content-widget/attach-file-widget.component.html
  lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
Labels: PR: partially-approved

#7039 [AAE-5145] Add enum for content node selector actions
  lib/content-services/src/lib/content-node-selector/content-node-dialog.service.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
  lib/content-services/src/lib/document-list/models/node-action.enum.ts
  lib/content-services/src/lib/document-list/public-api.ts
  lib/content-services/src/lib/document-list/services/node-actions.service.ts
  lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
Labels: PR: unreviewed

#7051 e2e: Improve cloud custom filters
  e2e/process-services-cloud/process/process-filter-results.e2e.ts
  e2e/process-services-cloud/process/process-task-attach-content-file-cloud.e2e.ts
  e2e/process-services-cloud/start-task/start-task-form-cloud.e2e.ts
  e2e/process-services-cloud/task-list/edit-process-filters-component.e2e.ts
  e2e/process-services-cloud/task-list/edit-task-filters-component.e2e.ts
  e2e/process-services-cloud/task-list/task-form-cloud-component.e2e.ts
  e2e/process-services-cloud/task-list/tasks-claim-release.e2e.ts
  e2e/protractor.excludes.json
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
Labels: PR: unreviewed

#7058 Remove e2e already covered by unit test
  e2e/core/header-component.e2e.ts
  e2e/core/icons-component.e2e.ts
  e2e/core/login/login-component.e2e.ts
  e2e/protractor.excludes.json
Labels: PR: unreviewed

#7060 [MNT-22030] ADW Previewer does not wrap long lines and there are no scroll-bars
  lib/core/viewer/components/txt-viewer.component.scss
Labels: PR: partially-approved

#7067 disable w3c due getValue problem
  e2e/content-services/components/tag-component.e2e.ts
  e2e/content-services/directives/create-folder-directive.e2e.ts
  e2e/content-services/directives/delete-directive.e2e.ts
  e2e/content-services/directives/edit-folder-directive.e2e.ts
  e2e/content-services/pages/permissions.page.ts
  e2e/content-services/pages/social.page.ts
  e2e/content-services/pages/tag.page.ts
  e2e/content-services/pages/tree-view.page.ts
  e2e/core/pages/card-view-component.page.ts
  e2e/core/pages/content-services.page.ts
  e2e/core/pages/data-table.page.ts
  e2e/core/pages/dialog/folder-dialog.page.ts
  e2e/core/pages/dialog/share-dialog.page.ts
  e2e/core/pages/login-shell.page.ts
  e2e/core/pages/metadata-view.page.ts
  e2e/process-services-cloud/pages/people-group-cloud-component.page.ts
  e2e/process-services/pages/dialog/create-checklist-dialog.page.ts
  e2e/process-services/pages/dialog/start-task-dialog.page.ts
  e2e/process-services/pages/task-details.page.ts
  e2e/process-services/pages/task-list-demo.page.ts
  e2e/protractor.conf.js
  e2e/search/components/search-date-range.e2e.ts
  e2e/search/components/search-number-range.e2e.ts
  e2e/search/components/search-slider.e2e.ts
  lib/testing/src/lib/content-services/pages/search/date-range-filter.page.ts
  lib/testing/src/lib/content-services/pages/search/number-range-filter.page.ts
  lib/testing/src/lib/content-services/pages/search/search-categories.page.ts
  lib/testing/src/lib/content-services/pages/search/search-slider.page.ts
  lib/testing/src/lib/core/dialog/edit-json-dialog.ts
  lib/testing/src/lib/core/pages/data-table-component.page.ts
  lib/testing/src/lib/core/pages/form/form-fields.ts
  lib/testing/src/lib/core/pages/form/widgets/attach-file-widget.page.ts
  lib/testing/src/lib/core/pages/form/widgets/checkbox-widget.page.ts
  lib/testing/src/lib/core/pages/form/widgets/dynamic-table-widget.page.ts
  lib/testing/src/lib/core/pages/form/widgets/hyperlink-widget.page.ts
  lib/testing/src/lib/core/pages/material/checkbox.page.ts
  lib/testing/src/lib/core/pages/material/date-picker-calendar.page.ts
  lib/testing/src/lib/core/pages/material/tabs.page.ts
  lib/testing/src/lib/core/pages/material/toggle.page.ts
  lib/testing/src/lib/core/pages/settings.page.ts
  lib/testing/src/lib/core/pages/viewer.page.ts
  lib/testing/src/lib/core/test-element.ts
  lib/testing/src/lib/core/utils/browser-actions.ts
  lib/testing/src/lib/core/utils/browser-visibility.ts
  lib/testing/src/lib/process-services-cloud/pages/dialog/edit-process-filter-dialog.page.ts
  lib/testing/src/lib/process-services-cloud/pages/dialog/edit-task-filter-dialog.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/form/widget/attach-file-widget-cloud.page.ts
  lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
  lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
  lib/testing/src/lib/process-services/pages/start-process.page.ts
  package-lock.json
Labels: PR: unreviewed
