Repository Alfresco/alfresco-ng2-components, pull requests merged in 2021-08, with the labels that each got.

#7172 [MNT-22334] ADW - User information not displayed when Kerberos is in use
  lib/core/services/authentication.service.spec.ts
  lib/core/services/authentication.service.ts
Labels: PR: unreviewed

#7193 [AAE-5529] Include sorting params in the PeopleContentQueryRequestModel
  lib/core/services/people-content.service.spec.ts
  lib/core/services/people-content.service.ts
Labels: PR: partially-approved

#7198 [ADF-5429] Improve search for testability
  lib/content-services/src/lib/search/components/search-sorting-picker/search-sorting-picker.component.spec.ts
  lib/content-services/src/lib/search/services/base-query-builder.service.ts
  lib/content-services/src/lib/search/services/search-header-query-builder.service.spec.ts
  lib/content-services/src/lib/search/services/search-query-builder.service.spec.ts
Labels: PR: unreviewed

#7202 [AAE-5163] Landing page title tooltip is displayed correctly
  lib/core/templates/empty-content/empty-content.component.html
Labels: PR: partially-approved

#7183 Update branch for JS-API PR#3711
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#7120 add missing api to extensions interface
  lib/extensions/src/lib/config/action.extensions.ts
Labels: PR: partially-approved

#7209 Update branch for JS-API PR#3781
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7208 [ADF-5460] Add placeholder to SearchTextInputComponent
  docs/core/components/search-text-input.component.md
  lib/core/search-text/search-text-input.component.html
  lib/core/search-text/search-text-input.component.ts
Labels: PR: partially-approved

#7216 Update update-project.sh
  scripts/travis/update/update-project.sh
Labels: PR: partially-approved

#7215 Update branch for JS-API PR#3793
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7222 [AAE-5414] - SSO Auth Guard - Add the concept of excluded roles
  docs/core/services/auth-guard-sso-role.service.md
  lib/core/services/auth-guard-sso-role.service.spec.ts
  lib/core/services/auth-guard-sso-role.service.ts
Labels: PR: partially-approved

#7221 Update branch for JS-API PR#3805
  lib/cli/package-lock.json
  tools/doc/package-lock.json
Labels: PR: unreviewed

#7223 [AAE-5718] change ngOnInit to ngAfterViewInit in Login component docs…
  docs/core/components/login.component.md
Labels: PR: reviewed-approved
