Repository Alfresco/alfresco-ng2-components, pull requests merged in 2022-01, with the labels that each got.

#7433 Update branch for JS-API PR#4054
  lib/cli/package-lock.json
  tools/doc/package-lock.json
Labels: PR: partially-approved

#7439 [AAE-6310] Add a category in process definition model
  lib/process-services-cloud/src/lib/models/process-definition-cloud.model.ts
Labels: PR: partially-approved

#7442 [AAE-6954] remove depend on from the general render
  lib/core/form/components/widgets/date-time/date-time.widget.scss
  lib/core/i18n/en.json
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.scss
Labels: PR: partially-approved

#7444 [AAE-5715] support hint labels for search input
  lib/core/search-text/search-text-input.component.html
  lib/core/search-text/search-text-input.component.ts
Labels: PR: partially-approved

#7438 Update branch for JS-API PR#4064
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#7443 AAE-6861 - Add runtimeBundleVersion property to the Model
  e2e/protractor.excludes.json
  lib/process-services-cloud/src/lib/app/models/application-instance.model.ts
Labels: PR: unreviewed

#7445 [adf-cli] - Expose property for custom dockerfile name
  lib/cli/scripts/docker.ts
Labels: PR: partially-approved

#7446 [ACA-3744] correct copy icon for share dialog
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
Labels: PR: partially-approved

#7456 [AAE-7035] Being able to load a dynamic file location
  lib/cli/scripts/init-aae-env.ts
  lib/cli/scripts/resources.ts
Labels: PR: reviewed-changes-requested

#7458 [ACA-4554] drag and drop fixes and unit tests
  lib/content-services/src/lib/upload/directives/file-draggable.directive.spec.ts
  lib/content-services/src/lib/upload/directives/file-draggable.directive.ts
Labels: PR: unreviewed

#7455 ADF-5467 re-enable test
  e2e/protractor.excludes.json
Labels: do not merge 🙅🏻‍♂️, PR: unreviewed, PR: reviewed-changes-requested, PR: draft, PR: partially-approved

#7462 [AAE-7062] Fixed failing e2e tests
  e2e/process-services-cloud/task-list/task-list-properties.e2e.ts
Labels: PR: reviewed-approved

#7459 LOC-350 - fix All UI files localized in 16 languages for ADF 4.8 release
  demo-shell/resources/i18n/ar.json
  demo-shell/resources/i18n/cs.json
  demo-shell/resources/i18n/da.json
  demo-shell/resources/i18n/de.json
  demo-shell/resources/i18n/es.json
  demo-shell/resources/i18n/fi.json
  demo-shell/resources/i18n/fr.json
  demo-shell/resources/i18n/it.json
  demo-shell/resources/i18n/ja.json
  demo-shell/resources/i18n/nb.json
  demo-shell/resources/i18n/nl.json
  demo-shell/resources/i18n/pl.json
  demo-shell/resources/i18n/pt-BR.json
  demo-shell/resources/i18n/ru.json
  demo-shell/resources/i18n/sv.json
  demo-shell/resources/i18n/zh-CN.json
  lib/core/i18n/ar.json
  lib/core/i18n/cs.json
  lib/core/i18n/da.json
  lib/core/i18n/de.json
  lib/core/i18n/es.json
  lib/core/i18n/fi.json
  lib/core/i18n/fr.json
  lib/core/i18n/it.json
  lib/core/i18n/ja.json
  lib/core/i18n/nb.json
  lib/core/i18n/nl.json
  lib/core/i18n/pl.json
  lib/core/i18n/pt-BR.json
  lib/core/i18n/ru.json
  lib/core/i18n/sv.json
  lib/core/i18n/zh-CN.json
  lib/process-services-cloud/src/lib/i18n/zh-CN.json
Labels: PR: partially-approved

#7457 [AAE-6310] Fix for attaching files
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
Labels: PR: unreviewed

#7463 [AAE-7010] - Fix nested linked dropdowns are not reset
  lib/core/form/components/widgets/core/form-field.model.spec.ts
  lib/core/form/components/widgets/core/form-field.model.ts
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
Labels: PR: partially-approved

#7470 Improve a datatable e2e method
  lib/testing/src/lib/protractor/core/pages/data-table/data-table-item.ts
Labels: PR: partially-approved

#7471 Bump 4.8.0
  demo-shell/package.json
  docs/content-services/components/content-metadata-card.component.md
  docs/core/components/search-text-input.component.md
  docs/core/components/viewer.component.md
  docs/core/services/discovery-api.service.md
  docs/core/services/identity-user.service.md
  docs/core/services/jwt-helper.service.md
  docs/core/services/people-content.service.md
  docs/core/services/upload.service.md
  docs/license-info/README.md
  docs/license-info/license-info-4.8.0.md
  docs/process-services-cloud/services/form-cloud.service.md
  docs/release-notes/README.md
  docs/release-notes/RelNote480.md
  docs/vulnerability/README.md
  docs/vulnerability/audit-info-4.8.0.md
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/package-lock.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved
