Repository Alfresco/alfresco-ng2-components, pull requests merged in 2022-09, with the labels that each got.

#7799 [AAE-10472] upgrade apollo libraries to Angular 14 compatible versions
  lib/process-services-cloud/src/lib/process-services-cloud.module.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.spec.ts
  package-lock.json
  package.json
Labels: PR: unreviewed

#7803 [AAE-10377] Fix the rich text editor widget is not opening
  lib/core/src/lib/form/components/widgets/display-rich-text/display-rich-text.widget.ts
  lib/core/src/lib/rich-text-editor/editorjs-config.ts
Labels: PR: partially-approved

#7805 rename the schame appconfig
  lib/core/ng-package.json
  lib/core/src/lib/app-config/app.config.schema.json
Labels: PR: partially-approved

#7813 [ACA-4609] Fix regression checkbox list shown horizontally
  lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.scss
Labels: PR: unreviewed

#7815 [AAE-10555] Set mat-checkbox display to block in order to takes up the…
  lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.scss
Labels: PR: partially-approved

#7817 Release 5.0.0
  demo-shell/package.json
  docs/license-info/README.md
  docs/license-info/license-info-5.0.0.md
  docs/release-notes/RelNote500.md
  docs/vulnerability/README.md
  docs/vulnerability/audit-info-5.0.0.md
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#7780 [AAE-10252] Storybook Update existing Stories to adhere to conventions
  e2e-playwright/page-object/index.ts
  e2e-playwright/page-object/stories/base.storie.ts
  e2e-playwright/page-object/stories/base.stories.ts
  e2e-playwright/process-services-cloud/specs/groups-cloud.e2e.ts
  e2e-playwright/process-services-cloud/specs/people-cloud.e2e.ts
  lib/content-services/.storybook/preview.js
  lib/content-services/src/lib/social/like.component.html
  lib/content-services/src/lib/social/like.component.stories.ts
  lib/core/.storybook/preview.js
  lib/core/src/lib/about/about.component.stories.ts
  lib/core/src/lib/comments/comment-list.component.stories.ts
  lib/core/src/lib/comments/comments.component.stories.ts
  lib/core/src/lib/icon/icon.component.stories.ts
  lib/core/src/lib/info-drawer/info-drawer.component.stories.ts
  lib/core/src/lib/language-menu/language-menu.component.stories.ts
  lib/core/src/lib/language-menu/language-picker.component.stories.ts
  lib/core/src/lib/templates/empty-content/empty-content.component.stories.ts
  lib/core/src/lib/templates/error-content/error-content.component.stories.ts
  lib/core/src/lib/toolbar/toolbar.component.stories.ts
  lib/process-services-cloud/.storybook/preview.js
  lib/process-services-cloud/src/lib/app/components/app-details-cloud.component.stories.ts
  lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.stories.ts
  lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.stories.ts
  lib/process-services-cloud/src/lib/form/components/form-definition-selector-cloud.component.stories.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.stories.ts
  lib/process-services-cloud/src/lib/people/components/people-cloud.component.stories.ts
  lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.stories.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.stories.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.stories.ts
  lib/stories/.storybook/preview.js
Labels: PR: unreviewed

#7797 [AAE-10468] e2es Task List fixes
  .travis.yml
  e2e/protractor.conf.js
  e2e/protractor.excludes.json
  lib/testing/src/lib/protractor/core/pages/material/dropdown.page.ts
Labels: PR: partially-approved

#7819 Release notes for ADF 5
  docs/release-notes/RelNote500.md
Labels: PR: reviewed-approved

#7743 Update branch for JS-API PR#239
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7787 [AAE-10311] - Fix deprecation warning about dates in cloud unit tests
  lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.ts
  lib/process-services-cloud/src/lib/models/date-format-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/public-api.ts
Labels: PR: partially-approved

#7825 Update branch for JS-API PR#316
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7826 Update branch for JS-API PR#317
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7831 [AAE-10316] - Fix moment js deprecation warnings in core
  lib/core/src/lib/form/components/widgets/date-time/date-time.widget.spec.ts
  lib/core/src/lib/form/components/widgets/date/date.widget.spec.ts
Labels: PR: partially-approved

#7830 [AAE-6991] Stories for datatable component
  lib/core/src/lib/datatable/components/datatable/datatable.component.stories.ts
Labels: PR: unreviewed

#7828 Update branch for JS-API PR#321
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#7827 Fix update-project github user
  scripts/travis/update/update-project.sh
Labels: PR: partially-approved

#7829 [AAE-10474] review why xit and console log is allowed to be committed
  .eslintrc.json
  .husky/pre-commit
  lib/cli/.eslintrc.json
  lib/core/src/lib/pagination/pagination.component.spec.ts
  lib/core/src/lib/rich-text-editor/rich-text-editor.component.ts
  lib/testing/.eslintrc.json
  package.json
Labels: PR: unreviewed

#7775 [AAE-10282] Storybook DataColumn Component
  lib/core/src/lib/data-column/data-column.component.stories.ts
  lib/core/src/lib/mock/data-column.mock.ts
Labels: PR: unreviewed

#7842 [AAE-10454] Stories for search-text-input component
  lib/core/src/lib/search-text/search-text-input.component.stories.ts
Labels: PR: partially-approved

#7833 [ACS-3537] - Fix accessibility issues in ACA personal files
  lib/content-services/src/lib/breadcrumb/breadcrumb.component.html
  lib/content-services/src/lib/permission-manager/components/user-icon-column/user-icon-column.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.html
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.spec.ts
  lib/core/src/lib/datatable/components/datatable-cell/datatable-cell.component.spec.ts
  lib/core/src/lib/datatable/components/datatable-cell/datatable-cell.component.ts
  lib/core/src/lib/datatable/components/date-cell/date-cell.component.ts
  lib/core/src/lib/datatable/components/filesize-cell/filesize-cell.component.ts
  lib/core/src/lib/i18n/en.json
  lib/core/src/lib/notifications/components/notification-history.component.html
  lib/core/src/lib/pipes/user-initial.pipe.spec.ts
  lib/core/src/lib/pipes/user-initial.pipe.ts
  lib/core/src/lib/userinfo/components/user-info.component.html
  lib/core/src/lib/userinfo/components/user-info.component.spec.ts
  lib/testing/src/lib/protractor/core/pages/user-info.page.ts
Labels: PR: partially-approved

#7848 [AAE-10452] Stories for pagination component
  lib/core/src/lib/pagination/pagination.component.stories.ts
Labels: PR: partially-approved

#7845 ACS-3544 Fix accessibility issues in ACA trashcan
  lib/content-services/src/lib/document-list/components/document-list.component.html
  lib/content-services/src/lib/i18n/en.json
  lib/core/src/lib/datatable/components/datatable/datatable.component.html
  lib/core/src/lib/i18n/en.json
Labels: PR: partially-approved

#7847 [AAE-10281] Stories for components in Layout module in ADF Core
  lib/core/src/lib/layout/components/header/header.component.stories.ts
  lib/core/src/lib/layout/components/sidebar-action/sidebar-action-menu.component.ts
  lib/core/src/lib/layout/components/sidebar-action/sidebar-action.component.stories.ts
  lib/core/src/lib/layout/components/sidenav-layout/sidenav-layout.component.stories.ts
  lib/core/src/lib/layout/components/sidenav-layout/sidenav-layout.component.ts
Labels: PR: unreviewed

#7846 [AAE-10453] Stories for rich-text-editor component
  lib/core/src/lib/rich-text-editor/mocks/rich-text-editor.mock.ts
  lib/core/src/lib/rich-text-editor/rich-text-editor.component.stories.ts
Labels: PR: partially-approved

#7849 Update README.md with link to Rel Note 5.0.0
  docs/release-notes/README.md
Labels: PR: reviewed-approved

#7852 [AAE-10706] Selector login fix
  lib/testing/src/lib/protractor/core/pages/login.page.ts
Labels: PR: partially-approved

#7822 [AAE-10446] Storybook CardView module
  lib/core/src/lib/card-view/components/card-view-arrayitem/card-view-arrayitem.component.stories.ts
  lib/core/src/lib/card-view/components/card-view-boolitem/card-view-boolitem.component.stories.ts
  lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.stories.ts
  lib/core/src/lib/card-view/components/card-view-keyvaluepairsitem/card-view-keyvaluepairsitem.component.stories.ts
  lib/core/src/lib/card-view/components/card-view-keyvaluepairsitem/card-view-keyvaluepairsitem.component.ts
  lib/core/src/lib/card-view/components/card-view-mapitem/card-view-mapitem.component.stories.ts
  lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.stories.ts
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.stories.ts
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.ts
  lib/core/src/lib/card-view/components/card-view/card-view.component.stories.ts
  lib/core/src/lib/card-view/mock/card-view-content.mock.ts
Labels: PR: partially-approved

#7850 [AAE-10317] - Fix APS unit tests warning "Test has no expectations"
  lib/process-services/src/lib/attachment/process-attachment-list.component.spec.ts
  lib/process-services/src/lib/attachment/task-attachment-list.component.spec.ts
  lib/process-services/src/lib/form/form.component.spec.ts
  lib/process-services/src/lib/form/start-form.component.mock.ts
  lib/process-services/src/lib/form/start-form.component.spec.ts
  lib/process-services/src/lib/mock/process/process-attachments.mock.ts
  lib/process-services/src/lib/mock/task/task-attachments.mock.ts
  lib/process-services/src/lib/people/components/people-search/people-search.component.spec.ts
  lib/process-services/src/lib/people/components/people/people.component.spec.ts
  lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
  lib/process-services/src/lib/process-list/services/process.service.spec.ts
  lib/process-services/src/lib/task-list/components/task-details.component.spec.ts
  lib/process-services/src/lib/task-list/services/tasklist.service.spec.ts
Labels: PR: unreviewed

#7853 ACA-4615 Restrict Edit Profile functionality to ECM users only
  lib/core/src/lib/userinfo/components/user-info.component.html
Labels: PR: partially-approved

#7844 [AAE-10643] Form validation should fail for dropdown required field and default value
  lib/core/src/lib/form/components/widgets/core/form-field-validator.spec.ts
  lib/core/src/lib/form/components/widgets/core/form-field-validator.ts
Labels: PR: partially-approved

#7814 [AAE-10457] Storybook User Info module
  lib/core/src/lib/userinfo/components/mocks/authentication.service.mock.ts
  lib/core/src/lib/userinfo/components/mocks/user.service.mock.ts
  lib/core/src/lib/userinfo/components/user-info.component.stories.ts
  lib/core/src/lib/userinfo/userinfo.module.ts
Labels: PR: unreviewed

#7854 [AAE-10707] - test e2e.sh fix
  scripts/travis/e2e/e2e.sh
Labels: PR: unreviewed

#7731 [AAE-10102] Storybook stories for Buttons Menu component
  e2e/protractor.excludes.json
  lib/core/src/lib/buttons-menu/buttons-menu.component.stories.ts
  lib/core/src/lib/buttons-menu/buttons-menu.module.ts
Labels: PR: unreviewed

#7859 [AAE-6153] Enable correct sorting while data are numbers
  lib/core/src/lib/datatable/data/object-datatable-adapter.spec.ts
  lib/core/src/lib/datatable/data/object-datatable-adapter.ts
Labels: PR: unreviewed

#7862 [AAE-10668] - Fix [object Object] for License entitlements in Admin App's About page
  lib/core/src/lib/about/about-license-list/about-license-list.component.html
  lib/core/src/lib/about/about-license-list/about-license-list.component.scss
  lib/core/src/lib/about/about-license-list/about-license-list.component.ts
  lib/core/src/lib/about/about.component.ts
  lib/core/src/lib/utils/object-utils.spec.ts
  lib/core/src/lib/utils/object-utils.ts
  lib/core/src/lib/utils/public-api.ts
  lib/core/src/lib/utils/string-utils.spec.ts
  lib/core/src/lib/utils/string-utils.ts
Labels: PR: unreviewed

#7871 fix cron run for e2e
  scripts/travis/affected-contains.sh
  scripts/travis/e2e/e2e.sh
Labels: PR: partially-approved

#7834 Update branch for JS-API PR#323
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7873 AAE-2824: Managed to trigger executeOutcome when clicking on custom outcome buttons
  lib/core/src/lib/form/components/form-base.component.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.ts
  lib/process-services/src/lib/form/form.component.spec.ts
Labels: PR: partially-approved

#7840 [AAE-10320] Fix Content Service unit tests - 'has no expectations'
  lib/content-services/src/lib/content-metadata/services/content-metadata.service.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/directives/node-counter.directive.spec.ts
  lib/content-services/src/lib/document-list/services/document-list.service.spec.ts
  lib/content-services/src/lib/document-list/services/node-actions.service.spec.ts
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-dialog.component.spec.ts
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.spec.ts
  lib/content-services/src/lib/search/components/search-control.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter-chips/search-filter-menu-card/search-filter-menu-card.component.spec.ts
  lib/content-services/src/lib/search/services/search-query-builder.service.spec.ts
  lib/content-services/src/lib/upload/components/base-upload/upload-base.spec.ts
  lib/content-services/src/lib/upload/components/upload-drag-area.component.spec.ts
  lib/content-services/src/lib/version-manager/version-upload.component.spec.ts
Labels: PR: unreviewed
