Repository Alfresco/alfresco-ng2-components, pull requests merged in 2022-12, with the labels that each got.

#8022 Update branch for JS-API PR#446
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#8021 [AAE-11480] - Fix required error is displayed for a non required drop…
  lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
  lib/core/src/lib/form/components/widgets/core/form-field.model.ts
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
Labels: PR: partially-approved

#8033 [AAE-11664] Release 6.0.0-A.1
  demo-shell/package.json
  docs/license-info/README.md
  docs/license-info/license-info-6.0.0-A.1.md
  docs/release-notes/README.md
  docs/release-notes/RelNote-6.0.0-A.1.md
  docs/vulnerability/README.md
  docs/vulnerability/audit-info-6.0.0-A.1.md
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  scripts/travis/release/release-npm.sh
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#8037 [ACS-3553] Fix process page accessibility from csv(880320,880281)
  lib/process-services/src/lib/content-widget/attach-file-widget.component.html
  lib/process-services/src/lib/process-list/components/start-process.component.html
Labels: PR: partially-approved

#8040 [AAE-11418] Add missing rules prop to NavBar interfaces
  lib/extensions/src/lib/config/navbar.extensions.ts
Labels: PR: partially-approved

#8035 [AAE-11653] Automate part of ADF Form Widgets
  lib/core/src/lib/form/components/form-renderer.component.spec.ts
  lib/core/src/lib/form/components/mock/form-renderer.component.mock.ts
  lib/core/src/lib/form/components/widgets/amount/amount.widget.spec.ts
  lib/core/src/lib/form/components/widgets/date/date.widget.spec.ts
Labels: PR: partially-approved

#8042 Update branch for JS-API PR#467
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#8041 AAE-11739 removed unnecessary api call when cancelling not started pr…
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
Labels: PR: unreviewed

#8034 [ACS-3757] returning focus to element from which they were opened
  docs/content-services/services/new-version-uploader.dialog.service.md
  lib/content-services/src/lib/aspect-list/services/dialog-aspect-list.service.spec.ts
  lib/content-services/src/lib/aspect-list/services/dialog-aspect-list.service.ts
  lib/content-services/src/lib/aspect-list/services/node-aspect.service.spec.ts
  lib/content-services/src/lib/aspect-list/services/node-aspect.service.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.spec.ts
  lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.ts
  lib/core/src/lib/datatable/components/datatable/datatable.component.html
  lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
  lib/core/src/lib/datatable/components/datatable/datatable.component.ts
  lib/core/src/lib/datatable/data/data-row.model.ts
Labels: PR: partially-approved

#8043 [AAE-11695] add breaking changes notes
  docs/upgrade-guide/upgrade50-60.md
Labels: PR: reviewed-approved

#8039 [ADF-5508] Fix half hidden checkmark icon
  lib/core/src/lib/datatable/components/datatable/datatable.component.scss
Labels: PR: partially-approved

#8044 [AAE-11763] cleanup ADF root package config
  package-lock.json
  package.json
Labels: PR: unreviewed

#8046 [AAE-10775] remove js-api dependency for pagination
  docs/upgrade-guide/upgrade50-60.md
  lib/core/src/lib/models/pagination.model.ts
  lib/core/src/lib/pagination/infinite-pagination.component.spec.ts
  lib/core/src/lib/pagination/infinite-pagination.component.ts
  lib/core/src/lib/pagination/pagination.component.spec.ts
Labels: PR: unreviewed

#8049 Update branch for JS-API PR#476
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8050 [AAE-7986] Migrate ADF from Travis to Github actions
  .editorconfig
  .github/actions/before-install/action.yml
  .github/actions/download-build-artifacts/action.yml
  .github/actions/e2e/action.yml
  .github/actions/get-latest-tag-sha/action.yml
  .github/actions/setup/action.yml
  .github/actions/travis-env-var-facade/action.yml
  .github/actions/upload-build-artifacts/action.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  e2e/protractor/save-remote.js
  lib/cli/scripts/docker.ts
  lib/cli/scripts/npm-publish.ts
  scripts/ci/job_hooks/after_e2e.sh
  scripts/ci/job_hooks/before_e2e.sh
  scripts/ci/job_hooks/before_install.sh
  scripts/ci/partials/_ci-flags-parser.sh
  scripts/travis/affected-contains.sh
  scripts/travis/e2e/e2e.sh
  scripts/travis/release/docker-tag.sh
  scripts/travis/release/release-demoshell-docker.sh
  scripts/travis/release/release-npm.sh
  scripts/travis/release/release-storybook-docker.sh
Labels: PR: partially-approved

#8053 Update branch for JS-API PR#477
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8051 [AAE-10774] move host settings to demo shell
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/components/settings/host-settings.component.html
  demo-shell/src/app/components/settings/host-settings.component.scss
  demo-shell/src/app/components/settings/host-settings.component.ts
  demo-shell/src/app/components/settings/settings.component.html
  demo-shell/src/app/components/settings/settings.module.ts
  lib/core/src/lib/core.module.ts
  lib/core/src/lib/i18n/ar.json
  lib/core/src/lib/i18n/cs.json
  lib/core/src/lib/i18n/da.json
  lib/core/src/lib/i18n/de.json
  lib/core/src/lib/i18n/en.json
  lib/core/src/lib/i18n/es.json
  lib/core/src/lib/i18n/fi.json
  lib/core/src/lib/i18n/fr.json
  lib/core/src/lib/i18n/it.json
  lib/core/src/lib/i18n/ja.json
  lib/core/src/lib/i18n/nb.json
  lib/core/src/lib/i18n/nl.json
  lib/core/src/lib/i18n/pl.json
  lib/core/src/lib/i18n/pt-BR.json
  lib/core/src/lib/i18n/ru.json
  lib/core/src/lib/i18n/sv.json
  lib/core/src/lib/i18n/zh-CN.json
  lib/core/src/lib/settings/host-settings.module.ts
  lib/core/src/lib/settings/index.ts
  lib/core/src/lib/settings/public-api.ts
  lib/core/src/public-api.ts
Labels: PR: partially-approved

#8055 [AAE-11822] fix/build-demoshell
  .github/workflows/pull-request.yml
Labels: PR: partially-approved

#8054 AAE-11714 changed max-width for cropped image
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
Labels: PR: unreviewed

#8059 [AAE-11843]-fix-before_install_script
  scripts/ci/job_hooks/before_install.sh
Labels: PR: unreviewed

#8048 [AAE-10776] NodeNameTooltipPipe moved in content service pkg
  docs/core/pipes/node-name-tooltip.pipe.md
  docs/upgrade-guide/upgrade50-60.md
  lib/content-services/src/lib/content.module.ts
  lib/content-services/src/lib/document-list/document-list.module.ts
  lib/content-services/src/lib/pipes/content-pipe.module.ts
  lib/content-services/src/lib/pipes/index.ts
  lib/content-services/src/lib/pipes/node-name-tooltip.pipe.spec.ts
  lib/content-services/src/lib/pipes/node-name-tooltip.pipe.ts
  lib/content-services/src/lib/pipes/public-api.ts
  lib/content-services/src/public-api.ts
  lib/core/src/lib/pipes/pipe.module.ts
  lib/core/src/lib/pipes/public-api.ts
Labels: PR: unreviewed

#8068 [AAE-11727] add suggested karma test explorer plugin
  .vscode/extensions.json
Labels: PR: partially-approved

#8056 Update branch for JS-API PR#478
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#8065 fixed release
  .github/workflows/release.yml
Labels: PR: partially-approved

#8067 [AAE-11588] Send Process Variables as a post body in admin process instances
  lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
  lib/process-services-cloud/src/lib/services/base-cloud.service.ts
Labels: PR: partially-approved

#8071 [AAE-10319] unit test fixes for content-services lib
  lib/content-services/karma.conf.js
  lib/content-services/src/lib/social/rating.component.spec.ts
  lib/content-services/src/lib/testing/content.testing.module.ts
  lib/content-services/src/lib/version-manager/version-list.component.spec.ts
  lib/content-services/src/lib/version-manager/version-list.component.ts
Labels: PR: partially-approved

#8052 [AAE-11740] replaced api for starting process
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
Labels: PR: unreviewed

#8072 [AAE-10315] fix karma 404 for images and certain errors in the Core unit tests
  lib/core/src/lib/directives/tooltip-card/tooltip-card.directive.spec.ts
  lib/core/src/lib/login/components/login.component.spec.ts
  lib/core/src/lib/login/components/login.component.ts
  lib/core/src/lib/userinfo/components/user-info.component.spec.ts
Labels: PR: partially-approved

#8074 [AAE-11274] remove unnecessary var export
  scripts/test-e2e-lib.sh
Labels: PR: unreviewed

#8069 Update branch for JS-API PR#484
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8077 [AAE-11486] move NodeUdpdate in nodeapiservice
  demo-shell/src/app/components/document-list/extension-presets/name-column/name-column.component.ts
  docs/upgrade-guide/upgrade50-60.md
  lib/content-services/src/lib/aspect-list/services/node-aspect.service.spec.ts
  lib/content-services/src/lib/aspect-list/services/node-aspect.service.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
  lib/content-services/src/lib/document-list/components/library-name-column/library-name-column.component.ts
  lib/content-services/src/lib/document-list/components/library-role-column/library-role-column.component.ts
  lib/content-services/src/lib/document-list/components/library-status-column/library-status-column.component.ts
  lib/content-services/src/lib/document-list/components/name-column/name-column.component.ts
  lib/content-services/src/lib/version-manager/version-manager.component.spec.ts
  lib/content-services/src/lib/version-manager/version-manager.component.ts
  lib/core/src/lib/datatable/components/datatable-cell/datatable-cell.component.ts
  lib/core/src/lib/datatable/components/date-cell/date-cell.component.ts
  lib/core/src/lib/datatable/components/filesize-cell/filesize-cell.component.ts
  lib/core/src/lib/datatable/components/json-cell/json-cell.component.ts
  lib/core/src/lib/datatable/components/location-cell/location-cell.component.ts
  lib/core/src/lib/services/alfresco-api.service.ts
  lib/core/src/lib/services/nodes-api.service.ts
  lib/core/src/lib/viewer/components/viewer.component.spec.ts
  lib/core/src/lib/viewer/components/viewer.component.ts
Labels: PR: unreviewed
