Repository Alfresco/alfresco-ng2-components, pull requests merged in 2022-05, with the labels that each got.

#7616 Added font awesome to icons model map
  e2e/process-services/form/apps-section.e2e.ts
  lib/process-services/src/lib/app-list/icon.model.ts
Labels: PR: unreviewed

#7580 [AAE-7817] Show hide columns on datatable
  demo-shell/src/app/components/datatable/datatable.component.html
  demo-shell/src/app/components/datatable/datatable.component.ts
  docs/core/components/data-column.component.md
  docs/core/components/datatable.component.md
  lib/core/datatable/components/columns-selector/columns-selector.component.html
  lib/core/datatable/components/columns-selector/columns-selector.component.scss
  lib/core/datatable/components/columns-selector/columns-selector.component.spec.ts
  lib/core/datatable/components/columns-selector/columns-selector.component.ts
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.spec.ts
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/core/datatable/data/data-column.model.ts
  lib/core/datatable/data/data-table.schema.ts
  lib/core/datatable/data/object-datacolumn.model.ts
  lib/core/datatable/datatable.module.ts
  lib/core/datatable/directives/main-data-table-action-template.directive.spec.ts
  lib/core/datatable/directives/main-data-table-action-template.directive.ts
  lib/core/datatable/public-api.ts
  lib/core/i18n/en.json
  lib/core/pipes/filter-out-every-object-by-prop.pipe.spec.ts
  lib/core/pipes/filter-out-every-object-by-prop.pipe.ts
  lib/core/pipes/filter-string.pipe.spec.ts
  lib/core/pipes/filter-string.pipe.ts
  lib/core/pipes/pipe.module.ts
  lib/core/pipes/public-api.ts
Labels: PR: unreviewed

#7625 Update branch for JS-API PR#9
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#7607 [AAE-8659] fix eslint configuration for rxjs
  .eslintrc.json
  .vscode/settings.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#7609 [MNT-22924] Fix slow search results loading, limit number of pages
  lib/core/pagination/pagination.component.html
  lib/core/pagination/pagination.component.spec.ts
  lib/core/pagination/pagination.component.ts
Labels: PR: unreviewed

#7611 Add eslint ban rule
  .eslintrc.json
  lib/core/form/components/widgets/widget.component.spec.ts
  package-lock.json
  package.json
Labels: PR: unreviewed

#7610 [AAE-8648] Fix deprecated copy to clipboard api
  lib/core/clipboard/clipboard.service.spec.ts
  lib/core/clipboard/clipboard.service.ts
Labels: PR: unreviewed

#7633 Added missing top-level export for MainMenuDataTableTemplateDirective
  lib/core/datatable/public-api.ts
Labels: PR: partially-approved

#7628 [AAE-8764] Enable left labels in text, number and dropdown cloud widget
  lib/core/form/components/form-renderer.component.scss
  lib/core/form/components/widgets/core/form-field.model.ts
  lib/core/form/components/widgets/form.theme.scss
  lib/core/form/components/widgets/number/number.widget.html
  lib/core/form/components/widgets/number/number.widget.spec.ts
  lib/core/form/components/widgets/text/text.widget.html
  lib/core/form/components/widgets/text/text.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
Labels: PR: partially-approved

#7629 Update branch for JS-API PR#126
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7637 [AAE-7077] Reset people content service cache on logout
  lib/core/services/people-content.service.spec.ts
  lib/core/services/people-content.service.ts
Labels: PR: partially-approved

#7612 [AAE-7817] Add columns selector for processes and tasks tasks
  demo-shell/src/app/components/datatable/datatable.component.html
  lib/core/datatable/components/columns-selector/columns-selector.component.spec.ts
  lib/core/datatable/components/columns-selector/columns-selector.component.ts
  lib/core/datatable/components/datatable/datatable.component.html
  lib/core/datatable/components/datatable/datatable.component.ts
  lib/core/datatable/data/data-table.schema.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-preferences.ts
  lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-preset.model.ts
  lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/models/task-preset-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-list/models/tasks-cloud-preferences.ts
Labels: PR: unreviewed

#7639 [AAE-8652] OAuth - use default profile email as scope
  demo-shell/src/app.config.json
Labels: PR: partially-approved

#7648 test: remove flaky file upload e2e test
  e2e/process-services/form/attach-file-content-service.e2e.ts
Labels: PR: unreviewed

#7647 Revert "[AAE-8713] feat: create api registry with factories support (…
  lib/core/api/api-client.factory.ts
  lib/core/api/api-clients.service.spec.ts
  lib/core/api/api-clients.service.ts
  lib/core/api/api.module.ts
  lib/core/api/clients/activiti/activiti-client.module.ts
  lib/core/api/clients/alfresco-js-clients.module.ts
  lib/core/api/clients/discovery/discovery-client.module.ts
  lib/core/api/clients/index.ts
  lib/core/api/index.ts
  lib/core/api/legacy-api-client.factory.ts
  lib/core/api/types.ts
  lib/core/core.module.ts
  lib/core/index.ts
  lib/core/services/discovery-api.service.ts
Labels: PR: unreviewed

#7650 [MNT-22844] fix small viewport attach file
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
Labels: PR: reviewed-approved
