Repository Alfresco/alfresco-ng2-components, pull requests merged in 2022-08, with the labels that each got.

#7717 [AAE-9348] Fix validate for people and group widgets
  lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.ts
  lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts
Labels: PR: unreviewed

#7722 [AAE-8561] [Modeling] The 'value' of string var in destinat…
  lib/core/form/components/widgets/core/form.model.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/upload-cloud.widget.ts
  lib/process-services-cloud/src/lib/form/mocks/attach-file-cloud-widget.mock.ts
Labels: PR: partially-approved

#7699 Update branch for JS-API PR#198
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7740 [AAE-9219] replay errored service task part 2
  lib/process-services-cloud/src/lib/task/task-list/services/service-task-list-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/services/service-task-list-cloud.service.ts
Labels: PR: partially-approved

#7741 [AAE-10125] Storybook stories for Comments component
  lib/core/comments/comment-list.component.stories.ts
  lib/core/comments/comments.component.stories.ts
  lib/core/comments/comments.module.ts
  lib/core/mock/comment-content-service.mock.ts
  lib/core/mock/comment-content.mock.ts
  lib/core/mock/comment-process-service.mock.ts
  lib/core/mock/comment-process.mock.ts
  lib/core/services/comment-content.service.interface.ts
  lib/core/services/comment-content.service.spec.ts
  lib/core/services/comment-content.service.ts
  lib/core/services/comment-process.service.interface.ts
  lib/core/services/comment-process.service.spec.ts
  lib/core/services/comment-process.service.ts
Labels: PR: unreviewed

#7747 [AAE-10149] Material Overlay - Use flexibleConnectedTo and remove deprecated
  lib/core/context-menu/context-menu-overlay.service.ts
Labels: PR: partially-approved

#7749 Update js api to latest
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#7753 check-bundle ng13
  scripts/travis/build/npm-check-bundles.sh
Labels: PR: partially-approved

#7754 Fix angular 13 migration
  .travis.yml
  scripts/next_version.sh
  scripts/travis/release/deprecate-develop-build.sh
  scripts/update-version.sh
Labels: PR: unreviewed

#7755 5.0.0-angular.13.1
  demo-shell/package.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  scripts/travis/release/release-docker.sh
Labels: PR: unreviewed

#7758 [AAE-10270] adf-cli - kube-clean script : Add the missing options
  lib/cli/scripts/kubectl-clean-app.ts
Labels: PR: partially-approved

#7759 [AAE-10278] restore correct simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: partially-approved

#7762 Release of 5.0.0-angular.13.2
  demo-shell/package.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#7744 [AAE-10089] Process variables values are not shown for old tasks and …
  lib/process-services-cloud/src/lib/mock/process-instance-variable.mock.ts
  lib/process-services-cloud/src/lib/models/process-instance-variable.model.ts
  lib/process-services-cloud/src/lib/services/variable-mapper.sevice.spec.ts
  lib/process-services-cloud/src/lib/services/variable-mapper.sevice.ts
Labels: PR: unreviewed

#7765 [AAE-10105] Update Storybook to 6.5.10v
  .storybook/alfrescoTheme.js
  .storybook/main.js
  .travis.yml
  angular.json
  demo-shell/src/assets/storybook-logo.png
  e2e-playwright/playwright.config.ts
  e2e-playwright/utils/timeouts.ts
  lib/content-services/.storybook/main.js
  lib/core/.storybook/main.js
  lib/process-services-cloud/.storybook/main.js
  lib/stories/.storybook/main.js
  package-lock.json
  package.json
  scripts/travis/storybook-testing/storybook-test.sh
Labels: PR: unreviewed

#7770 [AAE-10292] Fix opening two dialogs for card view array items
  lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.html
  lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.scss
  lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.spec.ts
Labels: PR: unreviewed

#7760 [AAE-10261] SmartRunner fix
  .travis.yml
  scripts/ci/job_hooks/after_e2e.sh
  scripts/ci/job_hooks/before_e2e.sh
  scripts/ci/job_hooks/before_install.sh
  scripts/ci/utils/artifact-from-s3.sh
  scripts/ci/utils/artifact-to-s3.sh
Labels: PR: partially-approved

#7739 ACA-4600 Added edit profile link
  lib/core/i18n/en.json
  lib/core/userinfo/components/user-info.component.html
Labels: PR: unreviewed

#7772 [AAE-10347] Remove playwright travis job duplication
  .travis.yml
Labels: PR: unreviewed

#7745 [AAE-10202] Storybook EmptyContent component
  lib/core/templates/empty-content/empty-content.component.stories.ts
Labels: PR: unreviewed

#7757 [AAE-10220] Storybook stories for Info Drawer component
  lib/core/comments/comment-list.component.stories.ts
  lib/core/comments/comments.component.stories.ts
  lib/core/info-drawer/info-drawer.component.stories.ts
  lib/core/info-drawer/info-drawer.module.ts
  lib/core/info-drawer/mock/info-drawer.mock.ts
Labels: PR: unreviewed

#7761 [AAE-10214] Storybook ErrorContent Component
  lib/core/templates/error-content/error-content.component.stories.ts
  lib/core/templates/template.module.ts
Labels: PR: unreviewed

#7774 Fix incorrect import in card view array
  lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.spec.ts
Labels: PR: unreviewed

#7781 change wrong licence header dates
  lib/core/comments/comment-list.component.stories.ts
  lib/core/comments/comments.component.stories.ts
  lib/core/icon/icon.component.stories.ts
  lib/core/info-drawer/info-drawer.component.stories.ts
  lib/core/language-menu/language-menu.component.stories.ts
  lib/core/language-menu/language-picker.component.stories.ts
  lib/core/mock/comment-content-service.mock.ts
  lib/core/mock/comment-content.mock.ts
  lib/core/mock/comment-process-service.mock.ts
  lib/core/mock/comment-process.mock.ts
  lib/core/mock/language.service.mock.ts
  lib/core/services/comment-process.service.interface.ts
  lib/core/services/language.service.interface.ts
  lib/core/services/language.service.ts
  lib/core/templates/empty-content/empty-content.component.stories.ts
  lib/core/templates/error-content/error-content.component.stories.ts
  lib/core/templates/template.module.ts
Labels: PR: unreviewed

#7785 [AAE-10460] fix storybook config
  angular.json
Labels: PR: partially-approved

#7750 [AAE-10219] Add css to align according to alignment property in RadioField
  angular.json
  lib/core/src/lib/form/components/widgets/core/form-field.model.ts
  lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.scss
  nx.json
Labels: PR: unreviewed

#7784 [AAE-9186] Filter tasks by assignee
  angular.json
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.html
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.scss
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/mock/edit-task-filter-cloud.mock.ts
  lib/process-services-cloud/src/lib/task/task-filters/mock/task-filters-cloud.mock.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  scripts/build/build-all-lib.sh
  scripts/build/build-cli.sh
  scripts/build/build-core.sh
  scripts/build/build-testing.sh
Labels: do not merge 🙅🏻‍♂️, PR: unreviewed, PR: partially-approved

#7791 Run e2e only when lib affected
  .travis.yml
  nx.json
  scripts/travis/affected-contains.sh
Labels: PR: partially-approved

#7788 [AAE-10472] Upgrade and deprecate libs
  e2e/content-services/document-list/document-list-gallery.e2e.ts
  e2e/protractor.excludes.json
  e2e/resources/forms/checkbox-visibility-condition.ts
  e2e/resources/forms/custom-date-form.ts
  e2e/resources/forms/display-value-visibility-conditions.ts
  e2e/resources/forms/people-group-formwidget-mocks.ts
  e2e/resources/forms/tab-visibility-conditions.ts
  e2e/tslint.json
  lib/cli/bin/adf-cli
  lib/core/src/lib/viewer/services/rendering-queue.services.ts
  lib/core/src/lib/viewer/services/view-util.service.ts
  lib/tslint.json
  package-lock.json
  package.json
  tools/doc/remarkGraphQl.js
  tools/doc/remarkGraphQl.ts
  tools/doc/reviewChecker.js
  tools/doc/reviewChecker.ts
  tools/doc/tools/fileChecker.js
  tools/doc/tools/fileChecker.ts
  tools/doc/tools/gqIndex.js
  tools/doc/tools/gqIndex.ts
  tools/doc/tools/linkFixer.js
  tools/doc/tools/linkFixer.ts
  tools/doc/tools/tsInfo.js
  tools/doc/tools/tsInfo.ts
  tslint.json
Labels: PR: unreviewed

#7779 [AAE-9464] - Fetch profile picture from ACS only in case of ECM
  lib/core/src/lib/userinfo/components/user-info.component.spec.ts
  lib/core/src/lib/userinfo/components/user-info.component.ts
Labels: PR: partially-approved

#7796 Update datatable.component.md
  docs/core/components/datatable.component.md
Labels: PR: unreviewed

#7793 Fix assignment type translations
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.html
Labels: PR: unreviewed

#7801 Short circuit e2e in case lib not affected
  .travis.yml
  scripts/build/build-all-lib.sh
  scripts/travis/affected-contains.sh
  scripts/travis/e2e/e2e.sh
Labels: PR: unreviewed

#7802 app config schema - Not anymore used
  scripts/travis/build/npm-check-bundles.sh
Labels: PR: partially-approved
