Repository Alfresco/alfresco-ng2-components, pull requests merged in 2022-11, with the labels that each got.

#7933 [AAE-11255] adf-cli - Get rid of the build-testing and call copydist when needed
  angular.json
  scripts/build/build-all-lib.sh
  scripts/build/build-testing.sh
  scripts/ci/job_hooks/before_e2e.sh
  scripts/ci/job_hooks/install.sh
Labels: PR: unreviewed

#7934 [AAE-11217] - Make init-aps script not rely on email domain
  lib/cli/scripts/init-aps-env.ts
Labels: PR: unreviewed

#7937 Adf-cli - Move the cli bundle under dist/libs/cli
  angular.json
  lib/cli/package.json
  lib/cli/tsconfig.json
Labels: PR: partially-approved

#7936 [AAE-11126] About Component - Deprecate commit sha
  lib/core/src/lib/about/about.component.html
  lib/core/src/lib/about/about.component.ts
Labels: PR: partially-approved

#7900 AAE-10842: Modified properties viewer widget to handle file input
  lib/process-services-cloud/src/lib/form/components/widgets/properties-viewer/properties-viewer.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/properties-viewer/properties-viewer.widget.ts
Labels: PR: unreviewed

#7940 Move check bundle after release npm
  .travis.yml
Labels: PR: unreviewed

#7931 [ACA-4622] Remove additional close button, unify buttons style
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/new-version-uploader/new-version-uploader.dialog.html
  lib/content-services/src/lib/upload/components/upload-button.component.html
Labels: PR: unreviewed

#7926 [AAE-7666] Add error message when REST API fails for radio buttons
  lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.scss
  lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.ts
Labels: PR: unreviewed

#7923 ACS-3545 a 11 y aca metadata sidebar
  e2e/core/pages/comments.page.ts
  e2e/process-services/pages/process-details.page.ts
  e2e/process-services/pages/task-details.page.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.scss
  lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.html
  lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.html
  lib/core/src/lib/comments/comment-list.component.html
  lib/core/src/lib/comments/comment-list.component.spec.ts
  lib/core/src/lib/comments/comments.component.html
  lib/core/src/lib/comments/comments.component.scss
  lib/core/src/lib/comments/comments.component.spec.ts
  lib/core/src/lib/i18n/en.json
  lib/process-services/src/lib/process-comments/process-comments.component.spec.ts
  lib/testing/src/lib/protractor/core/pages/card-view/card-view-date-item.page.ts
  lib/testing/src/lib/protractor/process-services/pages/start-process.page.ts
Labels: PR: unreviewed

#7945 Pipeline - Split the build from release
  .travis.yml
  scripts/travis/release/release-demoshell-docker.sh
  scripts/travis/release/release-storybook-docker.sh
Labels: PR: unreviewed

#7943 [AAE-11279] Pipeline - Build libs and apps in the same stage and avoid install
  .travis.yml
  demo-shell/src/index.html
Labels: PR: partially-approved

#7944 [AAE-11275] - e2e protractor - remove sleep step
  lib/testing/src/lib/protractor/process-services/pages/start-process.page.ts
Labels: PR: partially-approved

#7920 Update branch for JS-API PR#388
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#7946 [AAE-11284] Remove unused scripts. Yeah!!
  scripts/build/build-all-lib.sh
  scripts/build/build-core.sh
  scripts/travis/build/build-libs.sh
Labels: PR: partially-approved

#7950 Use npm bin/nx
  .travis.yml
  demo-shell/src/index.html
Labels: PR: partially-approved

#7948 Update branch for JS-API PR#402
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7951 Run release only on merge and upstream on cron
  .travis.yml
Labels: PR: partially-approved

#7964 Update branch for JS-API PR#409
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#7916 ACS-3640 a 11 y aca 881740 snackbar messages disappear without option to adjust timing
  demo-shell/src/app/components/cloud/community/community-start-process-cloud.component.ts
  demo-shell/src/app/components/cloud/community/community-start-task-cloud.component.ts
  demo-shell/src/app/components/file-view/file-view.component.ts
  demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
  docs/README.md
  docs/core/components/snackbar-content.component.md
  docs/core/services/notification.service.md
  docs/versionIndex.md
  e2e/core/pages/notification.page.ts
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.spec.ts
  lib/content-services/src/lib/upload/components/upload-drag-area.component.ts
  lib/core/src/lib/core.module.ts
  lib/core/src/lib/i18n/en.json
  lib/core/src/lib/notifications/components/notification-history.component.spec.ts
  lib/core/src/lib/notifications/services/notification.service.spec.ts
  lib/core/src/lib/notifications/services/notification.service.ts
  lib/core/src/lib/snackbar-content/index.ts
  lib/core/src/lib/snackbar-content/public-api.ts
  lib/core/src/lib/snackbar-content/snack-bar-data.ts
  lib/core/src/lib/snackbar-content/snackbar-content.component.html
  lib/core/src/lib/snackbar-content/snackbar-content.component.scss
  lib/core/src/lib/snackbar-content/snackbar-content.component.spec.ts
  lib/core/src/lib/snackbar-content/snackbar-content.component.ts
  lib/core/src/lib/snackbar-content/snackbar-content.module.ts
  lib/core/src/public-api.ts
  lib/testing/src/lib/protractor/core/pages/snackbar.page.ts
Labels: Accessibility, next version ➡️, PR: unreviewed, PR: reviewed-changes-requested, PR: draft, PR: partially-approved

#7966 Update branch for JS-API PR#411
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#7962 [AAE-10912] Added destinationFolderPath to simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#7968 [AAE-11319] start process loading spinner
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.scss
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
Labels: PR: unreviewed

#7965 [ACS-3888] Correct role for new version dialog
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
  lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.ts
Labels: PR: unreviewed

#7977 Revert "ACS-3640 a 11 y aca 881740 snackbar messages disappear withou…
  demo-shell/src/app/components/cloud/community/community-start-process-cloud.component.ts
  demo-shell/src/app/components/cloud/community/community-start-task-cloud.component.ts
  demo-shell/src/app/components/file-view/file-view.component.ts
  demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
  docs/README.md
  docs/core/components/snackbar-content.component.md
  docs/core/services/notification.service.md
  docs/versionIndex.md
  e2e/core/pages/notification.page.ts
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.spec.ts
  lib/content-services/src/lib/upload/components/upload-drag-area.component.ts
  lib/core/src/lib/core.module.ts
  lib/core/src/lib/i18n/en.json
  lib/core/src/lib/notifications/components/notification-history.component.spec.ts
  lib/core/src/lib/notifications/services/notification.service.spec.ts
  lib/core/src/lib/notifications/services/notification.service.ts
  lib/core/src/lib/snackbar-content/index.ts
  lib/core/src/lib/snackbar-content/public-api.ts
  lib/core/src/lib/snackbar-content/snack-bar-data.ts
  lib/core/src/lib/snackbar-content/snackbar-content.component.html
  lib/core/src/lib/snackbar-content/snackbar-content.component.scss
  lib/core/src/lib/snackbar-content/snackbar-content.component.spec.ts
  lib/core/src/lib/snackbar-content/snackbar-content.component.ts
  lib/core/src/lib/snackbar-content/snackbar-content.module.ts
  lib/core/src/public-api.ts
  lib/testing/src/lib/protractor/core/pages/snackbar.page.ts
Labels: PR: partially-approved

#7974 Update branch for JS-API PR#418
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#7949 [ACS-3863] Edit aspect dialog accessibility issues
  lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.html
  lib/content-services/src/lib/aspect-list/aspect-list.component.html
  lib/content-services/src/lib/aspect-list/services/dialog-aspect-list.service.ts
Labels: PR: unreviewed

#7985 Update branch for JS-API PR#420
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#7939 [ACS-3548] Accessibility issues
  e2e/process-services/pages/task-details.page.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
  lib/content-services/src/lib/search/components/search.component.html
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/src/lib/comments/comments.component.html
  lib/core/src/lib/datatable/components/datatable/datatable.component.html
Labels: PR: unreviewed

#7981 [ACS-3731] move/copy dialog and content overlaps other than 320px issue fixed
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
Labels: PR: unreviewed

#7980 [ACS-3781] 878751 function cannot be performed by keyboard alone hiding the user groups
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
  lib/content-services/src/lib/permission-manager/components/pop-over.directive.spec.ts
  lib/content-services/src/lib/permission-manager/components/pop-over.directive.ts
Labels: PR: unreviewed

#7991 Update branch for JS-API PR#423
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#7997 [ACS-4036] Revert folder color change
  lib/core/src/lib/assets/images/ft_ic_folder.svg
Labels: PR: partially-approved

#7987 [ACS-3658] Fix duplicated ids
  lib/core/src/lib/icon/icon.component.html
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
  lib/process-services/src/lib/content-widget/attach-file-widget.component.html
  lib/testing/src/lib/protractor/core/pages/form/widgets/attach-file-widget.page.ts
Labels: PR: unreviewed

#7989 [AAE-11385] Switched ids for attach-file-variables form
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#8001 [ACS-4051] 880283, 880284, 880285 Critical CSV issues buttons must have discernible text fixed
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/file-properties-table-cloud.component.html
  lib/process-services/src/lib/content-widget/attach-file-widget.component.html
  lib/process-services/src/lib/i18n/en.json
Labels: PR: partially-approved

#7993 Update branch for JS-API PR#424
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#8003 [AAE-11437] Remove snackbar duplications
  e2e/content-services/components/permissions-component.e2e.ts
  e2e/content-services/components/site-permissions.e2e.ts
  e2e/core/notifications-component.e2e.ts
  e2e/core/pages/notification.page.ts
  lib/testing/src/lib/protractor/core/pages/snackbar.page.ts
Labels: PR: partially-approved

#8006 [ACS-3758] Focus modal first focusable element after opening
  lib/content-services/src/lib/dialogs/dialog.module.ts
  lib/content-services/src/lib/dialogs/folder.dialog.html
  lib/content-services/src/lib/dialogs/library/library.dialog.html
Labels: PR: unreviewed

#8011 [ACS-3791] Renaming labels for uploader screen
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/upload/components/file-uploading-dialog.component.html
  lib/content-services/src/lib/upload/components/file-uploading-list-row.component.html
  lib/content-services/src/lib/upload/components/file-uploading-list-row.component.spec.ts
Labels: PR: partially-approved

#8007 [ACS-4051] CSV issues 880196 Function cannot be performed by keyboard alone addressed
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
Labels: PR: partially-approved

#7979 [ACS-3731] content reflow issue fixed to fit the viewport at 400% zoom sub task ACS-3889
  lib/content-services/src/lib/dialogs/folder.dialog.scss
Labels: PR: partially-approved

#8016 [ACS-4087] Restore missing close button for manage version dialog
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/new-version-uploader/new-version-uploader.dialog.html
Labels: PR: unreviewed

#8005 [ACS-4050]critical issues from csv 880282, 880449, 880280
  lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.html
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
  lib/process-services/src/lib/process-list/components/start-process.component.html
Labels: PR: partially-approved

#8017 [ACS-3553] Fix process page accessibility from csv(880320,880281)
  lib/process-services/src/lib/content-widget/attach-file-widget.component.html
  lib/process-services/src/lib/process-list/components/start-process.component.html
Labels: PR: partially-approved

#8018 Revert "[ACS-3553] Fix process page accessibility from csv(880320,880281)"
  lib/process-services/src/lib/content-widget/attach-file-widget.component.html
  lib/process-services/src/lib/process-list/components/start-process.component.html
Labels: PR: partially-approved

#8010 Update branch for JS-API PR#438
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/core/src/lib/services/authentication.service.spec.ts
  lib/core/src/lib/services/authentication.service.ts
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: unreviewed

#8019 [AAE-11501] Fix simpleapp dropdown option ids after changing validation
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: partially-approved

#8020 Update branch for JS-API PR#445
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved
