Repository Alfresco/alfresco-ng2-components, pull requests merged in 2022-07, with the labels that each got.

#7693 [AAE-9190] - ATTACH FILE: view file content directly by clicking
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/file-properties-table-cloud.component.html
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/file-properties-table-cloud.component.scss
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/file-properties-table-cloud.component.spec.ts
Labels: PR: unreviewed

#7697 [AAE-9112] Included a output event on change of language
  lib/core/language-menu/language-menu.component.spec.ts
  lib/core/language-menu/language-menu.component.ts
Labels: PR: unreviewed

#7698 [AAE-9370] Add manageruser to default apps
  .nxignore
  lib/cli/scripts/resources.ts
Labels: PR: unreviewed

#7692 Update branch for JS-API PR#194
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#7694 [AAE-9310] Add missing initial on task assignment dialog
  lib/core/models/general-user.model.ts
  lib/core/models/public-api.ts
  lib/core/pipes/full-name.pipe.ts
  lib/core/pipes/user-initial.pipe.spec.ts
  lib/core/pipes/user-initial.pipe.ts
  lib/core/userinfo/components/user-info.component.spec.ts
Labels: PR: unreviewed, PR: partially-approved

#7701 [AAE-7865] Configuration of columns in Task and Process Lists in ADW e2e
  lib/core/datatable/components/columns-selector/columns-selector.component.html
  lib/testing/src/lib/protractor/core/pages/data-table-component.page.ts
  lib/testing/src/lib/protractor/core/pages/data-table/columns-selector.ts
  lib/testing/src/lib/protractor/core/pages/data-table/public-api.ts
  lib/testing/src/lib/protractor/process-services-cloud/pages/process-list-cloud-component.page.ts
  lib/testing/src/lib/protractor/process-services-cloud/pages/task-list-cloud-component.page.ts
  lib/testing/src/lib/protractor/process-services-cloud/resources/resources.ts
Labels: do not merge 🙅🏻‍♂️, PR: unreviewed, PR: partially-approved

#7705 [AAE-9462] Being able to add contributors of the current upstream
  .travis.yml
  scripts/travis/update/pr-creator.js
  scripts/travis/update/update-project.sh
Labels: PR: reviewed-approved

#7706 [AAE-9461] Change variable process definition id
  lib/process-services-cloud/src/lib/models/data-column-custom-data.ts
  lib/process-services-cloud/src/lib/models/filter-cloud-model.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-list/datatable/process-list-datatable-adapter.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
  lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
  lib/process-services-cloud/src/lib/services/variable-mapper.sevice.spec.ts
  lib/process-services-cloud/src/lib/services/variable-mapper.sevice.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/datatable/task-list-datatable-adapter.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
Labels: do not merge 🙅🏻‍♂️, PR: partially-approved

#7510 master patch
  .travis.yml
  scripts/travis/release/release-docker.sh
  scripts/travis/release/release-npm.sh
Labels: PR: partially-approved

#7708 [AAE-9311] Use new micro service ingress for people/group
  lib/core/services/user-access.service.spec.ts
  lib/core/services/user-access.service.ts
  lib/process-services-cloud/src/lib/group/services/identity-group.service.ts
  lib/process-services-cloud/src/lib/people/services/identity-user.service.ts
Labels: PR: unreviewed

#7713 [AAE-7865] Added second process with displayable variables
  e2e/resources/activiti7/simpleapp.zip
  lib/testing/src/lib/protractor/process-services-cloud/resources/resources.ts
Labels: PR: partially-approved

#7711 [AAE-9200] - Be able to customise task/process list and header date f…
  docs/core/components/datatable.component.md
  docs/process-services-cloud/components/process-header-cloud.component.md
  docs/process-services-cloud/components/task-header-cloud.component.md
  e2e/process-services-cloud/pages/process-details-cloud-demo.page.ts
  e2e/process-services-cloud/process/process-custom-filters.e2e.ts
  e2e/process-services-cloud/start-task/start-task-form-cloud.e2e.ts
  e2e/process-services-cloud/task-list/task-header-cloud.e2e.ts
  e2e/process-services-cloud/task-list/task-list-properties-sort.e2e.ts
  lib/core/datatable/components/date-cell/date-cell.component.spec.ts
  lib/core/datatable/components/date-cell/date-cell.component.ts
  lib/core/karma.conf.js
  lib/process-services-cloud/karma.conf.js
  lib/process-services-cloud/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/process/mock/process-instance-details-cloud.mock.ts
  lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-header/mocks/task-details-cloud.mock.ts
  lib/testing/src/lib/protractor/process-services-cloud/pages/process-list-cloud-component.page.ts
  lib/testing/src/lib/protractor/process-services-cloud/pages/task-list-cloud-component.page.ts
Labels: PR: unreviewed

#7720 [AAE-9463] Check if minDateRangeValue and maxDateRangeValue are inte…
  lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.ts
Labels: PR: unreviewed

#7723 [AAE-10065] - Fix can't debug unit tests on ADF
  angular.json
Labels: PR: partially-approved

#7718 [AAE-6919] add a display text form control
  demo-shell/resources/i18n/en.json
  demo-shell/src/app/app.routes.ts
  demo-shell/src/app/components/app-layout/app-layout.component.ts
  demo-shell/src/app/components/rich-text-editor/rich-text-editor.component.html
  demo-shell/src/app/components/rich-text-editor/rich-text-editor.component.scss
  demo-shell/src/app/components/rich-text-editor/rich-text-editor.component.ts
  demo-shell/src/app/components/rich-text-editor/rich-text-editor.module.ts
  docs/README.md
  docs/core/components/form-field.component.md
  docs/core/components/rich-text-editor.md
  docs/core/services/form-rendering.service.md
  docs/user-guide/extensibility.md
  lib/core/core.module.ts
  lib/core/form/components/widgets/display-rich-text/display-rich-text.widget.html
  lib/core/form/components/widgets/display-rich-text/display-rich-text.widget.scss
  lib/core/form/components/widgets/display-rich-text/display-rich-text.widget.spec.ts
  lib/core/form/components/widgets/display-rich-text/display-rich-text.widget.ts
  lib/core/form/components/widgets/index.ts
  lib/core/form/services/form-rendering.service.spec.ts
  lib/core/form/services/form-rendering.service.ts
  lib/core/index.ts
  lib/core/mock/form/demo-form.mock.ts
  lib/core/rich-text-editor/editorjs-config.ts
  lib/core/rich-text-editor/index.ts
  lib/core/rich-text-editor/public-api.ts
  lib/core/rich-text-editor/rich-text-editor.component.html
  lib/core/rich-text-editor/rich-text-editor.component.scss
  lib/core/rich-text-editor/rich-text-editor.component.spec.ts
  lib/core/rich-text-editor/rich-text-editor.component.ts
  lib/core/rich-text-editor/rich-text-editor.module.ts
  package-lock.json
  package.json
Labels: PR: unreviewed

#7725 [AAE-10077] ADF's cron job, make it smarter by avoiding publishing on NPM and triggering the PR upstream
  scripts/travis/build/build-libs.sh
  scripts/travis/update/adf-same-commit-verify.js
  scripts/travis/update/update-project.sh
Labels: PR: partially-approved

#7727 [AAE-10091] Add adf-core missing dependencies
  lib/core/ng-package.json
  lib/core/package.json
Labels: PR: partially-approved

#7730 [AAE-9169] adf-cli - Change the doc and add clientId input
  lib/cli/README.md
  lib/cli/scripts/check-plugin-env.ts
  lib/cli/scripts/init-acs-env.ts
  lib/cli/scripts/init-aps-env.ts
  lib/cli/scripts/plugins/check-env.ts
  lib/cli/scripts/scan-env.ts
Labels: PR: partially-approved

#7728 [AAE-10104] Storybook stories for Icon component
  lib/core/icon/icon.component.stories.ts
Labels: PR: unreviewed
