Repository Alfresco/alfresco-ng2-components, pull requests merged in 2023-02, with the labels that each got.

#8213 [ACS-4307] Label is not persistent as placeholder is being used as the only visual label for a text field
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.html
Labels: PR: partially-approved

#8220 Revert "[ACS-4307] Label is not persistent as placeholder is being used as the only visual label for a text field"
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.html
Labels: PR: partially-approved

#8156 [ACS-4364] Move tree component and categories service to ADF
  cspell.json
  docs/content-services/components/tree.component.md
  docs/content-services/services/category-tree-datasource.service.md
  docs/content-services/services/category.service.md
  docs/docassets/images/tree.png
  lib/content-services/src/lib/category/index.ts
  lib/content-services/src/lib/category/mock/category-mock.service.ts
  lib/content-services/src/lib/category/models/category-node.interface.ts
  lib/content-services/src/lib/category/public-api.ts
  lib/content-services/src/lib/category/services/category-tree-datasource.service.spec.ts
  lib/content-services/src/lib/category/services/category-tree-datasource.service.ts
  lib/content-services/src/lib/category/services/category.service.spec.ts
  lib/content-services/src/lib/category/services/category.service.ts
  lib/content-services/src/lib/content.module.ts
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/tree/components/tree.component.html
  lib/content-services/src/lib/tree/components/tree.component.scss
  lib/content-services/src/lib/tree/components/tree.component.spec.ts
  lib/content-services/src/lib/tree/components/tree.component.ts
  lib/content-services/src/lib/tree/index.ts
  lib/content-services/src/lib/tree/mock/tree-node.mock.ts
  lib/content-services/src/lib/tree/mock/tree-service.service.mock.ts
  lib/content-services/src/lib/tree/models/tree-node.interface.ts
  lib/content-services/src/lib/tree/models/tree-response.interface.ts
  lib/content-services/src/lib/tree/public-api.ts
  lib/content-services/src/lib/tree/services/tree.service.spec.ts
  lib/content-services/src/lib/tree/services/tree.service.ts
  lib/content-services/src/lib/tree/tree.module.ts
  lib/content-services/src/public-api.ts
Labels: PR: unreviewed

#8221 [ACS-4307] Label is not persistent as placeholder is being used as the only visual label for a text field
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.html
Labels: PR: partially-approved

#8224 Revert "[ACS-4051] Copy to clipboard button is now accessible through the keyboard enter earlier which was only accessible through mouse click"
  lib/core/src/lib/clipboard/clipboard.directive.spec.ts
  lib/core/src/lib/clipboard/clipboard.directive.ts
Labels: PR: partially-approved

#8223 [ACS-4296] changes required after removing tags service from apps
  docs/content-services/services/tag.service.md
  lib/content-services/src/lib/tag/services/tag.service.spec.ts
  lib/content-services/src/lib/tag/services/tag.service.ts
Labels: PR: partially-approved

#8227 Fix alfresco-apps upstream build 260285240: export search-text-input.…
  lib/content-services/src/lib/search-text/public-api.ts
Labels: PR: partially-approved

#8225 [ACS-4051] Copy to clipboard button is now accessible through the keyboard enter earlier which was only accessible through mouse click
  lib/core/src/lib/clipboard/clipboard.directive.spec.ts
  lib/core/src/lib/clipboard/clipboard.directive.ts
Labels: PR: partially-approved

#8215 Update branch for JS-API PR#565
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8192 [ACS-4274] Add role heading and aria level in header template
  lib/core/src/lib/layout/components/header/header.component.html
Labels: PR: partially-approved

#8229 [AAE-12532] remove pipelines from travis.yml
  .travis.yml
  README.md
Labels: PR: partially-approved

#8230 devel: schedule check
  .github/workflows/pull-request.yml
Labels: PR: unreviewed

#8226 [AAE-12249] add description field
  demo-shell/src/app.config.json
  lib/process-services-cloud/src/lib/i18n/en.json
Labels: PR: partially-approved

#8181 [ADF-5514] Fix red dot still present after filter being cleared
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.ts
Labels: PR: partially-approved

#8244 Fix cli compilation
  .mergify.yml
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/cli/tsconfig.json
Labels: PR: partially-approved

#8160 AAE-12139 disabled start process btn when clicked and api call in pro…
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
Labels: PR: unreviewed, PR: partially-approved

#8241 [AAE-12558] Fix load content-services translation resources
  lib/process-services-cloud/src/lib/form/form-cloud.module.ts
  lib/process-services/src/lib/form/form.module.ts
Labels: PR: unreviewed

#8240 [ACS-4296] adding mapping in tags service
  lib/content-services/src/lib/tag/services/tag.service.spec.ts
  lib/content-services/src/lib/tag/services/tag.service.ts
Labels: PR: unreviewed

#8172 AAE-12192 - adding upload artifacts action
  .github/actions/e2e/action.yml
  .github/workflows/pull-request.yml
Labels: PR: unreviewed

#8216 [ACS-4254] Delete permissions button is now keyboard interact-able
  lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.html
  lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.ts
Labels: PR: partially-approved

#8243 [AAE-12260] - fixing form field mapping
  lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
  lib/core/src/lib/form/components/widgets/core/form-field.model.ts
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
  lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.ts
Labels: PR: unreviewed

#8252 Update dependabot.yml
  .github/dependabot.yml
Labels: PR: partially-approved

#8250 Update branch for JS-API PR#620
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
Labels: PR: partially-approved

#8201 [ACS-4322] content overlap issue fixed at 400% zoom and close button which was earlier not visible at 400% zoom is visible now.
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.scss
Labels: approved, PR: unreviewed

#8247 [ACS-4124] Display only as much tags as fits container in tag node list
  docs/content-services/components/tag-node-list.component.md
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/tag/tag-node-list.component.html
  lib/content-services/src/lib/tag/tag-node-list.component.scss
  lib/content-services/src/lib/tag/tag-node-list.component.spec.ts
  lib/content-services/src/lib/tag/tag-node-list.component.ts
  lib/extensions/src/lib/components/dynamic-column/dynamic-column.component.ts
Labels: PR: unreviewed

#8222 [ACS-4252] Resolved accessibility issues around inherited permissions popover
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
  lib/content-services/src/lib/permission-manager/components/pop-over.directive.spec.ts
  lib/content-services/src/lib/permission-manager/components/pop-over.directive.ts
Labels: PR: partially-approved

#8256 [ACS-3742] extra cfg support for shell navbar
  lib/core/shell/src/lib/components/shell/shell.component.html
  lib/core/shell/src/lib/components/shell/shell.component.ts
  lib/core/shell/src/lib/services/shell-app.service.ts
Labels: PR: partially-approved

#8263 [dependabot issue] Use one bucket variable
  .github/actions/e2e/action.yml
  .github/actions/upload-cache-and-artifacts/action.yml
  .github/workflows/git-tag.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: PR: partially-approved

#8168 [ACS-4257] - Resolved a11y issue around jumping focus
  lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip/search-facet-chip.component.html
  lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip/search-facet-chip.component.ts
  lib/content-services/src/lib/search/components/search-filter-chips/search-widget-chip/search-widget-chip.component.html
  lib/content-services/src/lib/search/components/search-filter-chips/search-widget-chip/search-widget-chip.component.ts
Labels: PR: unreviewed

#8269 Update branch for JS-API PR#643
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
Labels: PR: unreviewed

#8267 [AAE-12134] unit test: Should be able to set number of columns for He…
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
Labels: PR: unreviewed

#8187 [AAE-10779] User info component refactor
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/components/app-layout/app-layout.component.html
  demo-shell/src/app/components/app-layout/user-info/user-info.component.html
  demo-shell/src/app/components/app-layout/user-info/user-info.component.ts
  docs/content-services/components/content-user-info.component.md
  docs/core/components/identity-user-info.component.md
  docs/process-services/components/process-user-info.component.md
  docs/upgrade-guide/upgrade50-60.md
  lib/content-services/src/lib/content-user-info/content-user-info.component.html
  lib/content-services/src/lib/content-user-info/content-user-info.component.scss
  lib/content-services/src/lib/content-user-info/content-user-info.component.spec.ts
  lib/content-services/src/lib/content-user-info/content-user-info.component.ts
  lib/content-services/src/lib/content-user-info/content-user-info.module.ts
  lib/content-services/src/lib/content-user-info/index.ts
  lib/content-services/src/lib/content-user-info/public-api.ts
  lib/content-services/src/lib/content.module.ts
  lib/content-services/src/public-api.ts
  lib/core/src/lib/common/index.ts
  lib/core/src/lib/common/models/user-info-mode.enum.ts
  lib/core/src/lib/core.module.ts
  lib/core/src/lib/identity-user-info/identity-user-info.component.html
  lib/core/src/lib/identity-user-info/identity-user-info.component.scss
  lib/core/src/lib/identity-user-info/identity-user-info.component.spec.ts
  lib/core/src/lib/identity-user-info/identity-user-info.component.stories.ts
  lib/core/src/lib/identity-user-info/identity-user-info.component.ts
  lib/core/src/lib/identity-user-info/identity-user-info.module.ts
  lib/core/src/lib/identity-user-info/index.ts
  lib/core/src/lib/identity-user-info/public-api.ts
  lib/core/src/lib/userinfo/components/mocks/authentication.service.mock.ts
  lib/core/src/lib/userinfo/components/mocks/user.service.mock.ts
  lib/core/src/lib/userinfo/components/user-info.component.html
  lib/core/src/lib/userinfo/components/user-info.component.spec.ts
  lib/core/src/lib/userinfo/components/user-info.component.stories.ts
  lib/core/src/public-api.ts
  lib/process-services/src/lib/process-user-info/index.ts
  lib/process-services/src/lib/process-user-info/process-user-info.component.html
  lib/process-services/src/lib/process-user-info/process-user-info.component.scss
  lib/process-services/src/lib/process-user-info/process-user-info.component.spec.ts
  lib/process-services/src/lib/process-user-info/process-user-info.component.ts
  lib/process-services/src/lib/process-user-info/process-user-info.module.ts
  lib/process-services/src/lib/process-user-info/public-api.ts
  lib/process-services/src/lib/process.module.ts
  lib/process-services/src/public-api.ts
Labels: do not merge 🙅🏻‍♂️, PR: unreviewed, PR: partially-approved, breaking change

#8273 [AAE-12662] Get rid of multiplicity of "more than one element found for locator" warnings in tests caused by redundant click
  lib/testing/src/lib/protractor/core/pages/material/date-picker.page.ts
Labels: PR: partially-approved

#8274 [ACS-4634] Add ADF and JS API upstream to applications repo
  scripts/travis/update/update-project.sh
Labels: PR: unreviewed

#8268 [AAE-12668] refactored typography for themes
  demo-shell/src/custom-style-dev.scss
  lib/core/src/lib/styles/_index.scss
  lib/core/src/lib/styles/prebuilt/adf-blue-orange.scss
  lib/core/src/lib/styles/prebuilt/adf-blue-purple.scss
  lib/core/src/lib/styles/prebuilt/adf-cyan-orange.scss
  lib/core/src/lib/styles/prebuilt/adf-cyan-purple.scss
  lib/core/src/lib/styles/prebuilt/adf-green-orange.scss
  lib/core/src/lib/styles/prebuilt/adf-green-purple.scss
  lib/core/src/lib/styles/prebuilt/adf-indigo-pink.scss
  lib/core/src/lib/styles/prebuilt/adf-pink-bluegrey.scss
  lib/core/src/lib/styles/prebuilt/adf-purple-green.scss
Labels: PR: unreviewed

#8280 Being able to upstream alfresco-apps or alfresco-applications
  .github/actions/travis-env-var-facade/action.yml
  .github/workflows/adf_alpha.yml
  scripts/travis/update/update-project.sh
Labels: PR: partially-approved

#8277 AAE-12716 updated the typography documentation
  docs/user-guide/theming.md
  docs/user-guide/typography.md
Labels: PR: unreviewed

#8282 AAE-12721 - when a PR is closed the part of the pipeline is still triggered
  .github/workflows/release.yml
Labels: PR: partially-approved

#8141 [AAE-10594] Run unit tests in headless mode
  demo-shell/karma.conf.js
  lib/content-services/karma.conf.js
  lib/core/karma.conf.js
  lib/core/src/lib/clipboard/clipboard.service.spec.ts
  lib/extensions/karma.conf.js
  lib/insights/karma.conf.js
  lib/process-services-cloud/karma.conf.js
  lib/process-services/karma.conf.js
  lib/testing/karma.conf.js
Labels: PR: partially-approved

#8275 AAE-12274: Added support for column resizing to process and task lists
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts
Labels: PR: unreviewed

#8298 trigger upstream daily for hxp monorepo
  .github/workflows/adf_alpha.yml
  .github/workflows/cron.yml
Labels: PR: unreviewed

#8296 AAE-12578 added fn to save col width with preferences
  lib/core/src/lib/datatable/components/datatable/datatable.component.html
  lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
  lib/core/src/lib/datatable/components/datatable/datatable.component.ts
  lib/core/src/lib/datatable/data/data-table.schema.ts
  lib/core/src/lib/datatable/data/object-datacolumn.model.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.html
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-preferences.ts
  lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/models/tasks-cloud-preferences.ts
Labels: PR: partially-approved

#8279 [ACS-4565] add search for categories tree in admin cc
  docs/content-services/services/category-tree-datasource.service.md
  docs/content-services/services/category.service.md
  docs/core/services/search.service.md
  lib/content-services/src/lib/category/mock/category-mock.service.ts
  lib/content-services/src/lib/category/services/category-tree-datasource.service.spec.ts
  lib/content-services/src/lib/category/services/category-tree-datasource.service.ts
  lib/content-services/src/lib/category/services/category.service.spec.ts
  lib/content-services/src/lib/category/services/category.service.ts
  lib/content-services/src/lib/tree/components/tree.component.spec.ts
  lib/content-services/src/lib/tree/components/tree.component.ts
  lib/content-services/src/lib/tree/services/tree.service.ts
Labels: PR: partially-approved, A/N BDU

#8191 [ACS-4326] Content was overlapping with other contents and some elements were missing when we zoom at 400% or 320px equivalent which is fixed
  lib/content-services/src/lib/upload/components/file-uploading-dialog.component.scss
Labels: PR: unreviewed, PR: partially-approved, A/N BDU

#8276 Update branch for JS-API PR#644
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
Labels: PR: unreviewed

#8299 AAE-12767-concurrency-group
  .github/workflows/adf_alpha.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: PR: partially-approved

#8297 Fixed error on custom style and added doc for BC
  demo-shell/src/custom-style-dev.scss
  docs/upgrade-guide/upgrade50-60.md
Labels: PR: partially-approved

#8306 AAE-12767 - fix concurrency: only on PR workflow
  .github/workflows/adf_alpha.yml
  .github/workflows/release.yml
Labels: PR: reviewed-approved

#8278 [ACS-4281] removed heading role from breadcrumbs.
  lib/content-services/src/lib/breadcrumb/breadcrumb.component.html
Labels: PR: partially-approved, A/N BDU

#8300 Cron - Separate cron e2e from upstream and for different repo
  .github/workflows/adf_alpha.yml
  .github/workflows/cron-e2e.yml
  .github/workflows/cron-upstream.yml
  scripts/travis/update/update-project.sh
Labels: PR: unreviewed

#8309 Updated datatable component docs
  docs/core/components/datatable.component.md
Labels: PR: reviewed-approved

#8313 [AAE-12831] ADF Publish the adf pkgs on gh registry
  .github/workflows/release.yml
  lib/cli/scripts/npm-publish.ts
  scripts/travis/release/release-npm.sh
Labels: PR: partially-approved

#8314 publish on gh first
  lib/cli/scripts/npm-publish.ts
  scripts/travis/release/release-npm.sh
Labels: PR: unreviewed

#8126 [ACS-4331] Add deleteTag method to tag service
  docs/content-services/services/tag.service.md
  lib/content-services/src/lib/tag/services/tag.service.spec.ts
  lib/content-services/src/lib/tag/services/tag.service.ts
Labels: PR: unreviewed, A/N BDU

#8286 [ACS-4571] Move SecurityControlsService to ADF Content Lib
  docs/content-services/services/security-controls.service.md
  lib/content-services/src/lib/content.module.ts
  lib/content-services/src/lib/security/index.ts
  lib/content-services/src/lib/security/public-api.ts
  lib/content-services/src/lib/security/services/mock/security-authorities.mock.ts
  lib/content-services/src/lib/security/services/mock/security-groups.mock.ts
  lib/content-services/src/lib/security/services/mock/security-marks.mock.ts
  lib/content-services/src/lib/security/services/models/security-controls-group-info-response.interface.ts
  lib/content-services/src/lib/security/services/models/security-controls-group-list-response.interface.ts
  lib/content-services/src/lib/security/services/models/security-controls-group-response.interface.ts
  lib/content-services/src/lib/security/services/models/security-controls-mark-response.interface.ts
  lib/content-services/src/lib/security/services/security-controls-groups-marks-security.service.spec.ts
  lib/content-services/src/lib/security/services/security-controls-groups-marks-security.service.ts
  lib/content-services/src/lib/security/services/security-controls-service.module.ts
  lib/content-services/src/public-api.ts
Labels: PR: unreviewed, A/N BDU

#8307 [ACS-4670] Removed View 0 More tags button when chip takes more than on…
  lib/content-services/src/lib/tag/tag-node-list.component.spec.ts
  lib/content-services/src/lib/tag/tag-node-list.component.ts
Labels: PR: partially-approved, A/N BDU

#8270 [ACS-4294] Added title to clear button and changed its icon type to clear from close
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/search/components/search-facet-field/search-facet-field.component.html
Labels: PR: unreviewed, A/N BDU

#8237 [ACS-4290] Changed filter icon to generic filter icon instead of the custom icon
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.html
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.scss
  lib/core/src/lib/assets/images/ft_ic_filter.svg
  lib/core/src/lib/common/services/thumbnail.service.ts
Labels: PR: unreviewed, A/N BDU

#8264 [ACS-4270] [ACS-4301] Content or functionality was lost due to overlapping content when the page is adjusted to an equivalent width of 320px or 400% zoom
  lib/core/src/lib/datatable/components/datatable/datatable.component.scss
Labels: PR: partially-approved, A/N BDU

#8323 AAE-12860-build errors on cron
  .github/actions/download-node-modules-and-artifacts/action.yml
  .github/actions/setup/action.yml
  .github/actions/upload-node-modules-and-artifacts/action.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: PR: unreviewed

#8326 Regenerate adf-cli package lock with lock file version 1
  lib/cli/package-lock.json
Labels: PR: partially-approved

#8312 AAE-11918A - remove travis env var
  .dockerignore
  .github/actions/before-install/action.yml
  .github/actions/e2e/action.yml
  .github/actions/npm-check-bundle/action.yml
  .github/actions/set-npm-tag/action.yml
  .github/actions/setup/action.yml
  .github/actions/travis-env-var-facade/action.yml
  .github/workflows/adf_alpha.yml
  .github/workflows/cron-e2e.yml
  .github/workflows/git-tag.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  .travis.yml
  e2e/protractor.conf.js
  e2e/protractor/save-remote.js
  lib/cli/.npmignore
  lib/content-services/.npmignore
  lib/core/.npmignore
  lib/insights/.npmignore
  lib/process-services/.npmignore
  scripts/ci/job_hooks/before_install.sh
  scripts/ci/job_hooks/install.sh
  scripts/github/affected-contains.sh
  scripts/github/build/bumpversion.sh
  scripts/github/build/npm-check-bundles.sh
  scripts/github/e2e/e2e.sh
  scripts/github/release/deprecate-develop-build.sh
  scripts/github/release/docker-tag.sh
  scripts/github/release/git-tag.sh
  scripts/github/release/release-demoshell-docker.sh
  scripts/github/release/release-npm.sh
  scripts/github/release/release-storybook-docker.sh
  scripts/github/storybook-testing/storybook-test.sh
  scripts/github/update/adf-same-commit-verify.js
  scripts/github/update/pr-creator.js
  scripts/github/update/update-project.sh
  tools/tslint-rules/.npmignore
Labels: PR: unreviewed
