Repository Alfresco/alfresco-ng2-components, pull requests merged in 2023-05, with the labels that each got.

#8522 [ACS-5147] Fixed typo
  lib/content-services/src/lib/i18n/en.json
Labels: PR: partially-approved, A/N BDU

#8506 [HXOR-200] Standardize dry run flags as dry-run-flag: ${{ inputs.dry-run-flag }}
  .github/workflows/release.yml
Labels: PR: partially-approved

#8526 [AAE-14166] - fixing dependencies for editorjs
  lib/process-services-cloud/package-lock.json
  lib/process-services-cloud/package.json
Labels: PR: partially-approved

#8528 [ACS-5143] Tree component expand/collapse fix
  lib/content-services/src/lib/tree/components/tree.component.html
  lib/content-services/src/lib/tree/components/tree.component.spec.ts
  lib/content-services/src/lib/tree/components/tree.component.ts
  lib/content-services/src/lib/tree/services/tree.service.spec.ts
  lib/content-services/src/lib/tree/services/tree.service.ts
Labels: PR: unreviewed

#8521 GH Auto: Upstream dependencies JS-API:6.1.0-899
  package-lock.json
  package.json
Labels: PR: partially-approved

#8532 [AAE-14166] - fixing script for version
  scripts/next_version.sh
Labels: PR: unreviewed

#8531 [ADF-5509] Migrate to Node 18
  .github/actions/setup/action.yml
  .github/workflows/adf_alpha.yml
  .github/workflows/git-tag.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  .github/workflows/upstream-js.yml
  .nvmrc
  NX
  angular.json
  e2e/protractor.excludes.json
  migrations.json
  package-lock.json
  package.json
  scripts/github/e2e/e2e.sh
Labels: PR: unreviewed

#8535 [ACS-5148] Corrected first tag position and removed extra scrollbar whe…
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.scss
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.scss
Labels: PR: partially-approved

#8533 GH Auto: Upstream dependencies JS-API:6.1.0-907
  package-lock.json
  package.json
Labels: PR: partially-approved

#8539 [ADF-5509] fix core dependency on datetimepicker
  lib/core/package.json
Labels: PR: partially-approved

#8541 [AAE-14184] App key as parameter when fetching roles
  cspell.json
  lib/core/src/lib/auth/services/user-access.service.spec.ts
  lib/core/src/lib/auth/services/user-access.service.ts
Labels: PR: unreviewed

#8501 [AAE-13971] changed color to accent contrast
  lib/process-services-cloud/src/lib/task/task-filters/components/base-task-filters-cloud.component.scss
Labels: PR: partially-approved

#8512 [AAE-12763] Unit test - C588832 Should not be able to upload a file …
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
Labels: PR: unreviewed, PR: partially-approved

#8542 GH Auto: Upstream dependencies JS-API:6.1.0-912
  package-lock.json
  package.json
Labels: PR: partially-approved

#8487 [AAE-11270] replaced error message with shorter version
  e2e-playwright/process-services-cloud/specs/groups-cloud.e2e.ts
  lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
  lib/process-services-cloud/src/lib/i18n/en.json
Labels: PR: unreviewed

#8550 [ACS-5155] tags message about required field displayed after discarding changes
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts
Labels: PR: partially-approved, A/N BDU

#8549 GH Auto: Upstream dependencies JS-API:6.1.0-922
  package-lock.json
  package.json
Labels: PR: unreviewed

#8489 [AAE-13661] Modify init-aae-env file to accept env parameter
  lib/cli/scripts/init-aae-env.ts
Labels: PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved

#8543 cleanup ADF readme
  BROWSER-SUPPORT.md
  INTRODUCTION.md
  PREREQUISITES.md
  README.md
Labels: PR: unreviewed

#8534 [ACS-5137] Fixed navigation between images
  lib/core/src/lib/viewer/components/img-viewer.component.spec.ts
  lib/core/src/lib/viewer/components/img-viewer.component.ts
  lib/core/src/lib/viewer/components/mock/adf-viewer-container-more-actions.component.mock.ts
  lib/core/src/lib/viewer/components/mock/adf-viewer-container-open-with.component.mock.ts
  lib/core/src/lib/viewer/components/mock/adf-viewer-container-sidebar.component.mock.ts
  lib/core/src/lib/viewer/components/mock/adf-viewer-container-toolbar-actions.component.mock.ts
  lib/core/src/lib/viewer/components/mock/adf-viewer-container-toolbar.component.mock.ts
  lib/core/src/lib/viewer/components/viewer-render.component.html
  lib/core/src/lib/viewer/components/viewer-render.component.spec.ts
  lib/core/src/lib/viewer/components/viewer-render.component.ts
  lib/core/src/lib/viewer/components/viewer.component.html
  lib/core/src/lib/viewer/components/viewer.component.spec.ts
Labels: A/N BDU

#8563 [ACS-5171] Facets section - UI changes
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip/search-facet-chip.component.html
  lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.scss
  lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter-chips/search-widget-chip/search-widget-chip.component.html
Labels: A/N BDU

#8525 Update datatable.component.md documentation
  docs/core/components/datatable.component.md
Labels: PR: unreviewed

#8570 [ADF-5542] Update JS-API and ADF libs versions to use caret
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
Labels: A/N BDU

#8287 [ADF-5517] Add unit test to test clicking anywhere on a row in a datatable
  lib/core/src/lib/datatable/components/datatable/datatable.component.html
  lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
  lib/core/src/lib/datatable/components/datatable/datatable.component.ts
  lib/process-services/src/lib/task-list/components/task-list.component.spec.ts
Labels: PR: unreviewed, A/N BDU

#8587 [ADF-5540] Enable C277288 e2e
  e2e/protractor.excludes.json
Labels: A/N BDU

#8516 [ADF-5532] ADF Upgrade guide(upgrade411-50.md)
  docs/upgrade-guide/README.md
  docs/upgrade-guide/upgrade411-50.md
Labels: PR: unreviewed

#8609 [AAE-14759] Fixed image viewer when going to full screen mode
  lib/core/src/lib/viewer/components/img-viewer.component.spec.ts
  lib/core/src/lib/viewer/components/img-viewer.component.ts
Labels: next version ➡️
