Repository Alfresco/alfresco-ng2-components, pull requests merged in 2023-07, with the labels that each got.

#8671 [ACS-5314] Data table row should be clickable anywhere
  lib/core/src/lib/datatable/components/datatable/datatable.component.html
  lib/core/src/lib/datatable/components/datatable/datatable.component.scss
  lib/testing/src/lib/protractor/core/pages/data-table-component.page.ts
Labels: A/N BDU

#8733 [ACS-5406] Removed some importants
  lib/process-services/src/lib/process-list/components/process-filters.component.scss
  lib/process-services/src/lib/task-list/components/task-filters.component.scss
Labels: A/N BDU

#8707 [ACS-5399] Fix incomplete multi-character sanitization
  e2e/content-services/components/comment-component.e2e.ts
  lib/core/src/lib/comments/comments.component.spec.ts
  lib/core/src/lib/comments/comments.component.ts
  lib/core/src/lib/common/services/highlight-transform.service.ts
Labels: A/N BDU, security

#8732 [ACS-5145] Align header row with data rows.
  lib/core/src/lib/datatable/components/datatable/datatable.component.html
  lib/core/src/lib/datatable/components/datatable/datatable.component.scss
Labels: A/N BDU

#8755 [ACS-5571] Add deprecated attribute to Webscript component
  demo-shell/src/app/components/webscript/webscript.component.ts
  demo-shell/src/app/components/webscript/webscript.module.ts
  lib/content-services/src/lib/webscript/webscript.component.ts
  lib/content-services/src/lib/webscript/webscript.module.ts
Labels: next version ➡️, A/N BDU

#8756 [ACS-5572] Add deprecated attribute to Like and Rating components
  demo-shell/src/app/components/social/social.component.ts
  demo-shell/src/app/components/social/social.module.ts
  lib/content-services/src/lib/social/like.component.ts
  lib/content-services/src/lib/social/rating.component.ts
  lib/content-services/src/lib/social/social.module.ts
Labels: next version ➡️, A/N BDU

#8763 [ACS-5629] enhanced way of providing translations
  demo-shell/src/app/app.module.ts
  docs/core/services/translation.service.md
  lib/content-services/src/lib/content.module.ts
  lib/core/src/lib/testing/core.story.module.ts
  lib/core/src/lib/translation/translation.service.spec.ts
  lib/core/src/lib/translation/translation.service.ts
  lib/insights/src/lib/insights.module.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process-services-cloud.module.ts
  lib/process-services-cloud/src/lib/testing/process-services-cloud-story.module.ts
  lib/process-services/src/lib/process.module.ts
Labels: A/N BDU

#8764 [ACS-5266] Advanced Search - New component for Category facet
  docs/content-services/components/search-chip-autocomplete-input.component.md
  docs/content-services/components/search-filter-autocomplete-chips.component.md
  docs/content-services/pipes/is-included.pipe.md
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/material.module.ts
  lib/content-services/src/lib/pipes/is-included.pipe.spec.ts
  lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.html
  lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.scss
  lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.spec.ts
  lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.ts
  lib/content-services/src/lib/search/components/search-filter-autocomplete-chips/search-filter-autocomplete-chips.component.html
  lib/content-services/src/lib/search/components/search-filter-autocomplete-chips/search-filter-autocomplete-chips.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter-autocomplete-chips/search-filter-autocomplete-chips.component.ts
  lib/content-services/src/lib/search/components/search-properties/search-properties.component.html
  lib/content-services/src/lib/search/components/search-properties/search-properties.component.spec.ts
  lib/content-services/src/lib/search/components/search-properties/search-properties.component.ts
  lib/content-services/src/lib/search/models/autocomplete-option.interface.ts
  lib/content-services/src/lib/search/models/search-widget-settings.interface.ts
Labels: A/N BDU

#8772 [ACS-5687] info drawer layout fix for header
  lib/core/src/lib/info-drawer/info-drawer-layout.component.scss
Labels: A/N BDU

#8775 [ACS-5179] Add search facet tabbed component for creator and modifier
  docs/content-services/components/search-facet-chip-tabbed.md
  docs/docassets/images/search-facet-chip-tabbed.png
  docs/versionIndex.md
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.ts
  lib/content-services/src/lib/search/components/search-facet-field/search-facet-field.component.spec.ts
  lib/content-services/src/lib/search/components/search-facet-field/search-facet-field.component.ts
  lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-chip-tabbed.component.html
  lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-chip-tabbed.component.scss
  lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-chip-tabbed.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-chip-tabbed.component.ts
  lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.html
  lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.scss
  lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.ts
  lib/content-services/src/lib/search/components/search-filter/search-filter.component.spec.ts
  lib/content-services/src/lib/search/models/tabbed-facet-field.interface.ts
  lib/content-services/src/lib/search/public-api.ts
  lib/content-services/src/lib/search/search.module.ts
  lib/content-services/src/lib/search/services/base-query-builder.service.ts
  lib/content-services/src/lib/search/services/search-facet-filters.service.spec.ts
  lib/content-services/src/lib/search/services/search-facet-filters.service.ts
  lib/content-services/src/lib/search/services/search-query-builder.service.spec.ts
Labels: A/N BDU

#8783 flags for tags and categories in metadata
  lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.html
  lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.ts
Labels: A/N BDU

#8785 [ACA-4712] changes required to disallow using important for styles in aca
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
  lib/content-services/src/lib/document-list/components/document-list.component.scss
Labels: A/N BDU

#8721 [ACS-5400] Fix incomplete string escaping
  lib/cli/scripts/changelog.ts
Labels: A/N BDU, security

#8787 [ACS-5703] Comment List code and styles cleanup
  e2e/content-services/components/comment-component.e2e.ts
  e2e/protractor.excludes.json
  lib/content-services/src/lib/node-comments/mocks/node-comments.mock.ts
  lib/core/karma.conf.js
  lib/core/src/lib/comments/comment-list/comment-list.component.html
  lib/core/src/lib/comments/comment-list/comment-list.component.scss
  lib/core/src/lib/comments/comment-list/comment-list.component.spec.ts
  lib/core/src/lib/comments/comment-list/comment-list.component.ts
  lib/core/src/lib/comments/comment-list/mocks/comment-list.service.mock.ts
  lib/core/src/lib/comments/comments.component.html
  lib/core/src/lib/comments/comments.component.scss
  lib/core/src/lib/comments/comments.component.spec.ts
  lib/core/src/lib/comments/comments.component.ts
  lib/core/src/lib/comments/interfaces/index.ts
  lib/core/src/lib/comments/interfaces/public-api.ts
  lib/core/src/lib/comments/mocks/comments.service.mock.ts
  lib/core/src/lib/comments/mocks/comments.service.stories.mock.ts
  lib/core/src/lib/comments/mocks/comments.stories.mock.ts
  lib/core/src/lib/comments/public-api.ts
  lib/core/src/lib/i18n/en.json
  lib/core/src/lib/models/comment.model.ts
Labels: A/N BDU, security
