Repository Alfresco/alfresco-ng2-components, pull requests merged in 2023-01, with the labels that each got.

#8087 [AE-11486] move app process service in process-service
  docs/README.md
  docs/core/services/apps-process.service.md
  docs/upgrade-guide/upgrade50-60.md
  lib/core/src/lib/mock/public-api.ts
  lib/core/src/lib/services/public-api.ts
  lib/process-services/src/lib/app-list/apps-list.component.spec.ts
  lib/process-services/src/lib/app-list/apps-list.component.ts
  lib/process-services/src/lib/app-list/mocks/apps-service.mock.ts
  lib/process-services/src/lib/app-list/public-api.ts
  lib/process-services/src/lib/app-list/select-apps-dialog.component.spec.ts
  lib/process-services/src/lib/app-list/select-apps-dialog.component.ts
  lib/process-services/src/lib/app-list/services/apps-process.service.spec.ts
  lib/process-services/src/lib/app-list/services/apps-process.service.ts
  lib/process-services/src/lib/process-list/components/process-filters.component.spec.ts
  lib/process-services/src/lib/process-list/components/process-filters.component.ts
  lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
  lib/process-services/src/lib/process-list/components/start-process.component.ts
  lib/process-services/src/lib/task-list/components/task-filters.component.spec.ts
  lib/process-services/src/lib/task-list/components/task-filters.component.ts
Labels: PR: partially-approved

#8086 [AE-11486] move search service in alfresco content
  demo-shell/src/app/components/search/search-extended.component.ts
  demo-shell/src/app/components/search/search-filter-chips.component.ts
  demo-shell/src/app/components/search/search-result.component.ts
  docs/core/interfaces/search-configuration.interface.md
  docs/core/services/search-configuration.service.md
  docs/core/services/search.service.md
  docs/release-notes/RelNote230.md
  docs/upgrade-guide/upgrade50-60.md
  lib/content-services/src/lib/document-list/components/filter-header/filter-header.component.spec.ts
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.spec.ts
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.ts
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.spec.ts
  lib/content-services/src/lib/permission-manager/services/node-permission.service.spec.ts
  lib/content-services/src/lib/permission-manager/services/node-permission.service.ts
  lib/content-services/src/lib/search/components/search-control.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.spec.ts
  lib/content-services/src/lib/search/components/search-filter/search-filter.component.spec.ts
  lib/content-services/src/lib/search/components/search.component.spec.ts
  lib/content-services/src/lib/search/components/search.component.ts
  lib/content-services/src/lib/search/mocks/search.service.mock.ts
  lib/content-services/src/lib/search/public-api.ts
  lib/content-services/src/lib/search/services/search-configuration.service.ts
  lib/content-services/src/lib/search/services/search-facet-filters.service.ts
  lib/content-services/src/lib/search/services/search.service.spec.ts
  lib/content-services/src/lib/search/services/search.service.ts
  lib/core/src/lib/auth/index.ts
  lib/core/src/lib/auth/interface/authentication.interface.ts
  lib/core/src/lib/interface/public-api.ts
  lib/core/src/lib/mock/public-api.ts
  lib/core/src/lib/search-text/interfaces/search-configuration.interface.ts
  lib/core/src/lib/search-text/public-api.ts
  lib/core/src/lib/search-text/search-trigger.directive.ts
  lib/core/src/lib/services/public-api.ts
  lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget-dialog.component.ts
Labels: PR: unreviewed

#8078 Update branch for JS-API PR#493
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#8093 [AAE-11882] demoshell fix; pipeline bugfix
  .github/actions/download-build-artifacts/action.yml
  .github/actions/download-cache-and-artifacts/action.yml
  .github/actions/e2e/action.yml
  .github/actions/enable-dryrun/action.yml
  .github/actions/npm-check-bundle/action.yml
  .github/actions/setup-chrome/action.yml
  .github/actions/setup/action.yml
  .github/actions/travis-env-var-facade/action.yml
  .github/actions/upload-build-artifacts/action.yml
  .github/actions/upload-cache-and-artifacts/action.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: PR: unreviewed

#8045 [AAE-10769] remove alfresco deps from datatable
  demo-shell/src/app/components/files/files.component.ts
  docs/README.md
  docs/core/components/data-column.component.md
  docs/core/services/datatable.service.md
  docs/upgrade-guide/upgrade50-60.md
  docs/versionIndex.md
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/core/src/lib/core.module.ts
  lib/core/src/lib/datatable/components/datatable-cell/datatable-cell.component.ts
  lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
  lib/core/src/lib/datatable/components/datatable/datatable.component.ts
  lib/core/src/lib/datatable/components/date-cell/date-cell.component.ts
  lib/core/src/lib/datatable/components/filesize-cell/filesize-cell.component.ts
  lib/core/src/lib/datatable/components/json-cell/json-cell.component.ts
  lib/core/src/lib/datatable/components/location-cell/location-cell.component.ts
  lib/core/src/lib/datatable/data-column/data-column-header.component.ts
  lib/core/src/lib/datatable/data-column/data-column-list.component.ts
  lib/core/src/lib/datatable/data-column/data-column.component.spec.ts
  lib/core/src/lib/datatable/data-column/data-column.component.stories.ts
  lib/core/src/lib/datatable/data-column/data-column.component.ts
  lib/core/src/lib/datatable/data-column/data-column.module.ts
  lib/core/src/lib/datatable/data-column/index.ts
  lib/core/src/lib/datatable/data-column/public-api.ts
  lib/core/src/lib/datatable/data/data-row-update.model.ts
  lib/core/src/lib/datatable/data/data-table.schema.ts
  lib/core/src/lib/datatable/datatable.module.ts
  lib/core/src/lib/datatable/public-api.ts
  lib/core/src/lib/datatable/services/datatable.service.ts
  lib/core/src/lib/form/form-base.module.ts
  lib/core/src/public-api.ts
Labels: PR: reviewed-approved

#8066 [AAE-10994] Added task-executor forms and process to simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: partially-approved

#8096 [AAE-11913] Fix name of simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: partially-approved

#8095 Update branch for JS-API PR#511
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8097 added npm registry secrets
  .github/workflows/release.yml
Labels: PR: partially-approved

#8089 [AE-11486] move lock and favorite
  docs/README.md
  docs/content-services/interfaces/base-card-view-content-update.interface.md
  docs/content-services/services/card-view-content-update.service.md
  docs/content-services/services/sites.service.md
  docs/core/services/app-config.service.md
  docs/core/services/favorites-api.service.md
  docs/upgrade-guide/upgrade50-60.md
  lib/content-services/src/lib/aspect-list/services/node-aspect.service.spec.ts
  lib/content-services/src/lib/aspect-list/services/node-aspect.service.ts
  lib/content-services/src/lib/common/index.ts
  lib/content-services/src/lib/common/public-api.ts
  lib/content-services/src/lib/common/services/card-view-content-update.service.spec.ts
  lib/content-services/src/lib/common/services/card-view-content-update.service.ts
  lib/content-services/src/lib/common/services/favorites-api.service.ts
  lib/content-services/src/lib/common/services/sites.service.spec.ts
  lib/content-services/src/lib/common/services/sites.service.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-dialog.service.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component-search.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
  lib/content-services/src/lib/dialogs/library/library.dialog.spec.ts
  lib/content-services/src/lib/dialogs/library/library.dialog.ts
  lib/content-services/src/lib/directives/library-membership.directive.spec.ts
  lib/content-services/src/lib/directives/library-membership.directive.ts
  lib/content-services/src/lib/document-list/components/document-list.component.ts
  lib/content-services/src/lib/document-list/public-api.ts
  lib/content-services/src/lib/document-list/services/lock.service.spec.ts
  lib/content-services/src/lib/document-list/services/lock.service.ts
  lib/content-services/src/lib/services/public-api.ts
  lib/content-services/src/lib/site-dropdown/sites-dropdown.component.spec.ts
  lib/content-services/src/lib/site-dropdown/sites-dropdown.component.ts
  lib/content-services/src/public-api.ts
  lib/core/src/lib/app-config/app-config.service.ts
  lib/core/src/lib/auth/index.ts
  lib/core/src/lib/auth/interfaces/openid-configuration.interface.ts
  lib/core/src/lib/auth/public-api.ts
  lib/core/src/lib/services/alfresco-api.service.ts
  lib/core/src/lib/services/public-api.ts
Labels: PR: unreviewed

#8098 AAE-11910 - add a workflow_dispatch to execute manually adf tests from gha GUI
  .github/workflows/adf_alpha.yml
Labels: PR: reviewed-approved

#8092 [AE-11486] remove unused comment services and improve doc
  docs/upgrade-guide/upgrade50-60.md
  lib/core/src/lib/comments/comment-list.component.stories.ts
  lib/core/src/lib/comments/mocks/comments.stories.mock.ts
  lib/core/src/lib/mock/comment-content-service.mock.ts
  lib/core/src/lib/mock/comment-content.mock.ts
  lib/core/src/lib/mock/comment-process.mock.ts
  lib/core/src/lib/mock/public-api.ts
  lib/core/src/lib/services/comment-content.service.spec.ts
  lib/core/src/lib/services/comment-content.service.ts
  lib/core/src/lib/services/comment-process.service.spec.ts
  lib/core/src/lib/services/public-api.ts
  lib/process-services/src/lib/process-comments/interfaces/comment-process.service.interface.ts
  lib/process-services/src/lib/process-comments/mock/comment-process-service.mock.ts
  lib/process-services/src/lib/process-comments/mock/comment-process.mock.ts
  lib/process-services/src/lib/process-comments/process-comments.component.spec.ts
  lib/process-services/src/lib/process-comments/process-comments.component.ts
  lib/process-services/src/lib/process-comments/public-api.ts
  lib/process-services/src/lib/process-comments/services/comment-process.service.ts
  lib/process-services/src/lib/process-list/components/process-instance-details.component.spec.ts
  lib/process-services/src/lib/task-list/components/task-details.component.spec.ts
Labels: PR: reviewed-approved

#8099 [AAE-11919] export identity-group.service
  lib/core/src/lib/auth/interfaces/identity-group.interface.ts
  lib/core/src/lib/auth/interfaces/identity-user.service.interface.ts
  lib/core/src/lib/auth/mock/identity-group.mock.ts
  lib/core/src/lib/auth/mock/identity-group.service.mock.ts
  lib/core/src/lib/auth/mock/identity-user.service.mock.ts
  lib/core/src/lib/auth/public-api.ts
  lib/core/src/lib/auth/services/identity-group.service.ts
  lib/core/src/lib/auth/services/identity-user.service.ts
  lib/process-services-cloud/src/lib/people/mock/jwt-helper.service.spec.ts
  lib/process-services-cloud/src/lib/people/services/identity-user.service.spec.ts
Labels: PR: unreviewed

#8103 Update branch for JS-API PR#514
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#8101 [#7902] Fix to enable cmaps with pdfjs
  lib/core/src/lib/viewer/components/pdf-viewer.component.ts
Labels: PR: partially-approved

#8100 AAE-11910 - setup cron pipe to trigger alpha_adf and add a workflow_dispatch to execute manually adf tests
  .github/workflows/adf_alpha.yml
  .github/workflows/cron.yml
Labels: PR: reviewed-approved

#8105 AAE-11910 - cron schedule fix
  .github/workflows/adf_alpha.yml
  .github/workflows/cron.yml
Labels: PR: reviewed-approved

#8090 AAE-11810 added conditional class to indicate validation error
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
Labels: PR: partially-approved

#8106 Update branch for JS-API PR#517
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8114 [AAE-11708] Use perl regexp instead of reverse grep in changelog
  lib/cli/scripts/changelog.ts
Labels: PR: partially-approved

#8116 [AAE-11817]-bugfix-on-gh-action-envvar
  .github/actions/before-install/action.yml
  .github/actions/e2e/action.yml
  .github/actions/setup/action.yml
  .github/actions/travis-env-var-facade/action.yml
  .github/workflows/release.yml
Labels: PR: partially-approved

#8117 Update branch for JS-API PR#524
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8120 [AAE-11817]-release-fix
  .github/actions/before-install/action.yml
Labels: PR: partially-approved

#8113 AAE-11940 - fix alpha adf test in cron workflow
  .github/workflows/adf_alpha.yml
  .github/workflows/cron.yml
  scripts/travis/update/update-project.sh
Labels: PR: unreviewed

#8121 [AAE-11817]-release fix if condition
  .github/actions/before-install/action.yml
Labels: PR: partially-approved

#8104 [ACA-4647] Fix for e2e
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
  lib/process-services-cloud/src/lib/process/start-process/models/process-instance-cloud.model.ts
Labels: PR: unreviewed

#8123 Update branch for JS-API PR#525
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8127 [AAE-12054] publish on npm alpha tag
  scripts/travis/release/release-npm.sh
Labels: PR: unreviewed

#8122 AAE-11940 - npm err fix in trigger-adf workflow
  .github/workflows/adf_alpha.yml
  .github/workflows/pull-request.yml
Labels: PR: reviewed-approved

#8129 Update branch for JS-API PR#527
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8128 [AAE-11992] Fix processInstanceId filter empty
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/mock/edit-task-filter-cloud.mock.ts
Labels: PR: partially-approved

#8130 [AAE-12057] unit tests fix
  .github/workflows/pull-request.yml
Labels: PR: partially-approved

#8124 AAE-12037 git-tag stage
  .github/workflows/git-tag.yml
  scripts/travis/release/git-tag.sh
Labels: PR: unreviewed

#8140 [AAE-11992] pass only the processInstanceId as Input instead of the e…
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/mock/edit-task-filter-cloud.mock.ts
Labels: PR: partially-approved

#8139 [AAE-1274] CI opt - Build only core/content/process storybook
  .github/workflows/pull-request.yml
  angular.json
Labels: PR: partially-approved

#8136 [AAE-12057] unit tests: force e2e only after build-libs, lint, unit-tests
  .github/workflows/pull-request.yml
Labels: PR: partially-approved

#8142 Update branch for JS-API PR#528
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8119 [ACS-4051] Copy to clipboard button is now accessible through the keyboard enter earlier which was only accessible through mouse click
  lib/core/src/lib/clipboard/clipboard.directive.spec.ts
  lib/core/src/lib/clipboard/clipboard.directive.ts
Labels: PR: partially-approved

#8147 [AAE-12123] env var interpolation bugfix
  .github/actions/travis-env-var-facade/action.yml
Labels: PR: partially-approved

#8143 [ACS-4118] create a tag from tags list
  docs/content-services/services/tag.service.md
  lib/content-services/src/lib/tag/services/tag.service.spec.ts
  lib/content-services/src/lib/tag/services/tag.service.ts
  package-lock.json
  package.json
Labels: next version ➡️, PR: unreviewed, PR: partially-approved

#8145 AAE-12046 - add pre-condition on approval
  .github/workflows/adf_alpha.yml
  .github/workflows/pull-request.yml
Labels: PR: unreviewed

#8132 [AAE-12057] add description to unit tests
  .github/workflows/pull-request.yml
Labels: PR: unreviewed

#8154 AAE-12123
  .github/actions/npm-check-bundle/action.yml
  .github/actions/travis-env-var-facade/action.yml
  .github/actions/travis-event-type-load/action.yml
  .github/workflows/release.yml
Labels: PR: unreviewed

#8159 Revert "[ACS-4051] Copy to clipboard button is now accessible through the keyboard enter earlier which was only accessible through mouse click"
  lib/core/src/lib/clipboard/clipboard.directive.spec.ts
  lib/core/src/lib/clipboard/clipboard.directive.ts
Labels: PR: merged

#8155 enable e2e: C260040
  .github/workflows/pull-request.yml
  e2e/content-services/upload/version-actions.e2e.ts
  e2e/protractor.excludes.json
Labels: e2e, PR: unreviewed, PR: partially-approved

#8148 Update branch for JS-API PR#532
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#8157 [AAE-12124] Use a function to remove js files
  angular.json
  lib/config/index.js
  lib/config/webpack.style.js
Labels: PR: partially-approved

#8169 [ACA-4650] Use NodeCommentsService for ADF_COMMENTS_SERVICE
  lib/content-services/src/lib/node-comments/node-comments.component.ts
  lib/content-services/src/lib/node-comments/node-comments.module.ts
  lib/process-services/src/lib/task-comments/task-comments.component.ts
  lib/process-services/src/lib/task-comments/task-comments.module.ts
Labels: PR: partially-approved

#8173 [AAE-12135] Added process ui to subprocess app
  e2e/resources/activiti7/subprocessapp.zip
Labels: PR: partially-approved

#8177 LOC-405 - Updated string in process-services-cloud in 16 languages fo…
  lib/process-services-cloud/src/lib/i18n/ar.json
  lib/process-services-cloud/src/lib/i18n/cs.json
  lib/process-services-cloud/src/lib/i18n/da.json
  lib/process-services-cloud/src/lib/i18n/de.json
  lib/process-services-cloud/src/lib/i18n/es.json
  lib/process-services-cloud/src/lib/i18n/fi.json
  lib/process-services-cloud/src/lib/i18n/fr.json
  lib/process-services-cloud/src/lib/i18n/it.json
  lib/process-services-cloud/src/lib/i18n/ja.json
  lib/process-services-cloud/src/lib/i18n/nb.json
  lib/process-services-cloud/src/lib/i18n/nl.json
  lib/process-services-cloud/src/lib/i18n/pl.json
  lib/process-services-cloud/src/lib/i18n/pt-BR.json
  lib/process-services-cloud/src/lib/i18n/ru.json
  lib/process-services-cloud/src/lib/i18n/sv.json
  lib/process-services-cloud/src/lib/i18n/zh-CN.json
Labels: PR: partially-approved

#8179 Release 6.0.0-A.2
  demo-shell/package.json
  docs/license-info/README.md
  docs/license-info/license-info-6.0.0-A.2.md
  docs/release-notes/README.md
  docs/release-notes/RelNote-6.0.0-A.2.md
  docs/vulnerability/README.md
  docs/vulnerability/audit-info-6.0.0-A.2.md
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package.json
Labels: PR: partially-approved

#8186 AAE-12304
  .github/workflows/git-tag.yml
Labels: PR: partially-approved

#8184 [ACS-4413] Upgrade CodeQL analysis to v2
  .github/workflows/codeql-analysis.yml
Labels: PR: partially-approved

#8175 Update branch for JS-API PR#540
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#8170 [ACS-4253] - Added aria-label to form element
  lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
Labels: PR: partially-approved

#8174 AAE-12239: Managed to populate processInstanceId in service tasks filters
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-service-task-filter-cloud.component.ts
Labels: next version ➡️, PR: unreviewed, PR: partially-approved

#8131 AAE-12063 removed startCreatedProcess with relevant unit tests
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
Labels: next version ➡️, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved

#8176 [ACS-4242] Visible label/form field are not associated
  lib/core/src/lib/viewer/components/pdf-viewer.component.html
Labels: PR: partially-approved

#8158 [AAE-12127] Test: The aspect added in config is displayed even if inc…
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
  lib/content-services/src/lib/content-metadata/services/content-metadata.service.spec.ts
Labels: PR: unreviewed

#8133 AAE-10979: Added support to display html icon for mht file format
  e2e/protractor.excludes.json
  lib/core/src/lib/services/thumbnail.service.spec.ts
  lib/core/src/lib/services/thumbnail.service.ts
Labels: bug, PR: unreviewed, PR: partially-approved

#8166 [AAE-8306] - Managed to disable complete/claim/release buttons on first click
  lib/core/src/lib/form/components/form-base.component.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/directives/claim-task-cloud.directive.spec.ts
  lib/process-services-cloud/src/lib/task/directives/claim-task-cloud.directive.ts
  lib/process-services-cloud/src/lib/task/directives/complete-task.directive.spec.ts
  lib/process-services-cloud/src/lib/task/directives/complete-task.directive.ts
  lib/process-services-cloud/src/lib/task/directives/unclaim-task-cloud.directive.spec.ts
  lib/process-services-cloud/src/lib/task/directives/unclaim-task-cloud.directive.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.spec.ts
Labels: PR: unreviewed, PR: partially-approved

#8178 [AAE-11708] Fix changelog author filtering programatically
  lib/cli/scripts/changelog.ts
Labels: PR: partially-approved

#8183 [ACS-4263] Add 'aria-pressed' attribute for reset button on content viewer page
  lib/core/src/lib/viewer/components/pdf-viewer.component.html
Labels: PR: draft, PR: partially-approved

#8198 [AAE-11700] add process to simpleapp
  e2e/resources/activiti7/simpleapp.zip
Labels: PR: unreviewed

#8199 [ACS-4282] [ACS-4271] [ACS-4298] [ACS-4327] [ACS-4328] Exclue snackbar from screen reader
  lib/core/src/lib/snackbar-content/snackbar-content.component.html
Labels: PR: partially-approved

#8200 [ACS-4411] updateTag method added to tags service
  docs/content-services/services/tag.service.md
  lib/content-services/src/lib/tag/services/tag.service.spec.ts
  lib/content-services/src/lib/tag/services/tag.service.ts
Labels: PR: partially-approved

#8202 fix the private access to the service variables
  lib/content-services/src/lib/aspect-list/services/aspect-list.service.ts
  lib/content-services/src/lib/aspect-list/services/dialog-aspect-list.service.ts
  lib/content-services/src/lib/audit/audit.service.ts
  lib/content-services/src/lib/common/services/favorites-api.service.ts
  lib/content-services/src/lib/content-metadata/services/property-descriptors.service.ts
  lib/content-services/src/lib/content-type/content-type.service.ts
  lib/content-services/src/lib/group/services/group.service.ts
  lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.ts
  lib/content-services/src/lib/permission-manager/services/node-permission.service.ts
  lib/content-services/src/lib/search/services/base-query-builder.service.ts
  lib/content-services/src/lib/search/services/search-configuration.service.ts
  lib/content-services/src/lib/social/services/rating.service.ts
  lib/content-services/src/lib/tag/services/tag.service.spec.ts
  lib/content-services/src/lib/tag/services/tag.service.ts
  lib/core/src/lib/services/content.service.ts
  lib/core/src/lib/services/deleted-nodes-api.service.ts
  lib/core/src/lib/services/discovery-api.service.ts
  lib/core/src/lib/services/ecm-user.service.ts
  lib/core/src/lib/services/nodes-api.service.ts
  lib/core/src/lib/services/people-process.service.ts
  lib/core/src/lib/services/thumbnail.service.ts
  lib/core/src/lib/viewer/services/view-util.service.ts
  lib/insights/src/lib/diagram/services/diagrams.service.ts
  lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
  lib/process-services-cloud/src/lib/form/services/process-cloud-content.service.ts
  lib/process-services/src/lib/app-list/services/apps-process.service.ts
  lib/process-services/src/lib/form/services/activiti-alfresco.service.ts
  lib/process-services/src/lib/form/services/ecm-model.service.ts
  lib/process-services/src/lib/form/services/editor.service.ts
  lib/process-services/src/lib/form/services/model.service.ts
  lib/process-services/src/lib/form/services/process-content.service.ts
  lib/process-services/src/lib/form/services/process-definition.service.ts
  lib/process-services/src/lib/form/services/task-form.service.ts
  lib/process-services/src/lib/form/services/task.service.ts
  lib/process-services/src/lib/process-comments/services/comment-process.service.ts
  lib/process-services/src/lib/task-list/services/process-upload.service.ts
  lib/process-services/src/lib/task-list/services/task-upload.service.ts
Labels: PR: unreviewed

#8197 AAE-12357: update unit test name
  .github/workflows/pull-request.yml
Labels: PR: partially-approved

#8190 Update branch for JS-API PR#552
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8210 AAE-12412 - dependabot actor check
  .github/workflows/pull-request.yml
Labels: PR: partially-approved

#8214 [AAE-12412] alfresco-build user whitelisted
  .github/workflows/pull-request.yml
Labels: PR: partially-approved

#8167 [AAE-12146] Update getFeature typings
  lib/extensions/src/lib/services/extension.service.spec.ts
  lib/extensions/src/lib/services/extension.service.ts
Labels: PR: unreviewed

#8165 [ACS-4051] Copy to clipboard button is now accessible through the keyboard enter earlier which was only accessible through mouse click
  lib/core/src/lib/clipboard/clipboard.directive.spec.ts
  lib/core/src/lib/clipboard/clipboard.directive.ts
Labels: PR: partially-approved

#8146 [AAE-11654] Fix default option being selectable when parent dropdown …
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
Labels: PR: unreviewed, PR: partially-approved
