Repository Alfresco/alfresco-ng2-components, pull requests merged in 2023-03, with the labels that each got.

#8333 fix release npm
  scripts/github/release/release-npm.sh
Labels: PR: reviewed-approved

#8337 [HXOR-164] pr check job
  .github/workflows/pull-request.yml
Labels: PR: unreviewed

#8317 [AAE-12870] use gh action to publish
  .github/workflows/release.yml
  angular.json
  scripts/github/release/release-npm.sh
Labels: PR: unreviewed, PR: partially-approved

#8342 Use as default prod
  .github/workflows/release.yml
  angular.json
Labels: PR: partially-approved

#8343 Use the right path for testing
  angular.json
Labels: PR: partially-approved

#8345 [AAE-13016] Can't resolve 'angular-oauth2-oidc' after merge OIDC PR
  lib/core/ng-package.json
  lib/core/package.json
Labels: PR: partially-approved

#8338 AAE-12589 - fixing ci:force flag
  .github/actions/before-install/action.yml
  .github/workflows/pull-request.yml
Labels: PR: partially-approved

#8347 [AAE-12888] moved label inside field for easier styling
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
Labels: PR: partially-approved

#8348 Fix for ADF -> APPS upstream
  .github/workflows/adf_alpha.yml
  scripts/github/update/update-project.sh
Labels: PR: unreviewed

#8350 [AAE-11707] Fix wrong paths in adf-core
  lib/core/src/lib/datatable/data-column/data-column.module.ts
  lib/core/src/lib/datatable/datatable.module.ts
  lib/core/tsconfig.lib.json
Labels: PR: unreviewed

#8352 Dev alepore 12511 fix bc wrong auth url
  lib/core/src/lib/api-factories/alfresco-api-v2-loader.service.ts
  lib/core/src/lib/services/alfresco-api.service.ts
Labels: PR: partially-approved

#8358 AAE-12589 fix cron e2e schedule avoiding ci:force flag checker
  .github/workflows/pull-request.yml
Labels: PR: partially-approved

#8329 AAE-11622 - remove unused scripts from pipeline
  scripts/ci/check-env/check-cs-env.sh
  scripts/ci/check-env/check-external-cs-env.sh
  scripts/ci/check-env/check-ps-cloud-env.sh
  scripts/ci/check-env/check-ps-env.sh
  scripts/ci/job_hooks/after_e2e.sh
  scripts/ci/job_hooks/before_e2e.sh
  scripts/ci/job_hooks/before_install.sh
  scripts/ci/job_hooks/install.sh
  scripts/ci/jobs/dbpci-before-playwright
  scripts/ci/jobs/dbpci-build-guard-check
  scripts/ci/partials/_ci-flags-parser.sh
  scripts/ci/utils/artifact-from-s3.sh
  scripts/ci/utils/artifact-to-s3.sh
  scripts/github/build/bumpversion.sh
  scripts/github/storybook-testing/storybook-test.sh
  scripts/github/update/adf-same-commit-verify.js
  scripts/npm-move-tag.sh
  scripts/pre-publish.js
  scripts/release.sh
  scripts/update-version.sh
Labels: PR: reviewed-approved

#8362 Fix ci force for dependabot check
  .github/workflows/pull-request.yml
Labels: PR: unreviewed

#8361 Use PAT to publish pkgs
  .github/workflows/release.yml
Labels: PR: partially-approved

#8367 chmod change permission
  scripts/github/build/bumpversion.sh
  scripts/update-version.sh
Labels: PR: reviewed-approved

#8335 [HXOR-158] release wont start if pr closed but not approved
  .github/workflows/release.yml
Labels: PR: partially-approved

#8369 repository-dispatch custom event to monorepo
  .github/workflows/package_dispatch.yml
Labels: PR: partially-approved

#8370 change event name
  .github/workflows/package_dispatch.yml
Labels: PR: unreviewed

#8371 registry_package change payload
  .github/workflows/package_dispatch.yml
Labels: PR: unreviewed

#8372 dispatch package event - change payload values
  .github/workflows/package_dispatch.yml
Labels: PR: unreviewed

#8374 change context
  .github/workflows/package_dispatch.yml
Labels: PR: unreviewed

#8375 dispatch event - remove await
  .github/workflows/package_dispatch.yml
Labels: PR: unreviewed

#8377 dispatch event - Use escape to read var
  .github/workflows/package_dispatch.yml
Labels: PR: unreviewed

#8378 dispatch event - use v6
  .github/workflows/package_dispatch.yml
Labels: PR: unreviewed

#8380 dispatch event - attempt with await
  .github/workflows/package_dispatch.yml
Labels: PR: unreviewed

#8368 [ACS-4106] changed place of mat-error tag & style change
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
Labels: PR: partially-approved

#8385 dispatch event - use PAT
  .github/workflows/package_dispatch.yml
Labels: PR: unreviewed

#8389 Update branch for JS-API PR#326
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8405 HXOR-193 in the pull-request flow, branch name in the flag parser should be managed better
  .github/workflows/pull-request.yml
Labels: PR: reviewed-approved

#8404 [AAE-12242] Fix code coverage
  .github/workflows/pull-request.yml
  angular.json
  lib/content-services/karma.conf.js
  lib/core/karma.conf.js
  lib/extensions/karma.conf.js
  lib/insights/karma.conf.js
  lib/process-services-cloud/karma.conf.js
  lib/process-services/karma.conf.js
Labels: PR: unreviewed

#8407 [AAE-12784] elements get typography from theme
  demo-shell/src/app/components/logout/logout.component.html
  demo-shell/src/app/components/logout/logout.component.scss
Labels: PR: partially-approved

#8409 HXOR-241 - finalize job needs to be improved by adding a setup check
  .github/workflows/pull-request.yml
Labels: PR: reviewed-approved

#8408 [AAE-13063] replaced custom color with theme related
  demo-shell/src/app/components/datatable/datatable.component.scss
  demo-shell/src/app/components/files/files.component.scss
  demo-shell/src/app/components/log/log.component.css
  demo-shell/src/app/components/process-list-demo/process-list-demo.component.scss
  demo-shell/src/app/components/task-list-demo/task-list-demo.component.scss
  lib/insights/src/lib/analytics-process/components/widgets/dropdown/dropdown.widget.scss
Labels: PR: partially-approved

#8412 [HXCS-1310] fix e2e notification
  lib/testing/src/lib/protractor/core/pages/snackbar.page.ts
Labels: PR: partially-approved

#8413 [HXCS-1322] fix e2e NotificaionComponent demo
  demo-shell/src/app/components/notifications/notifications.component.ts
  e2e/core/notifications-component.e2e.ts
  lib/core/src/lib/snackbar-content/snackbar-content.component.html
Labels: PR: unreviewed

#8402 [ACS-4128] Undo functionality added for input in Perform Actions after selecting an action and it works after destnation folder change in Create/Edit a rule in Manage Rules
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.ts
Labels: PR: unreviewed

#8411 HXOR-196 - get pr number change
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: PR: unreviewed

#8414 Update branch for JS-API PR#756
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  tools/doc/package-lock.json
  tools/doc/package.json
Labels: PR: partially-approved

#8418 [AAE-13060] documented css global variables
  docs/user-guide/theming.md
Labels: PR: unreviewed

#8211 [ACS-4295] Label is not persistent as placeholder is being used as the only visual label for a text field
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/site-dropdown/sites-dropdown.component.html
  lib/content-services/src/lib/site-dropdown/sites-dropdown.component.spec.ts
Labels: PR: unreviewed, A/N BDU

#8422 [AAE-10309] - Joy to the world the unit tests are fixed!
  .vscode/tasks.json
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-definition-selector-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/file-viewer/file-viewer.widget.spec.ts
  lib/process-services-cloud/src/lib/form/mocks/attach-file-cloud-widget.mock.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/services/user-preference-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-service-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-list/services/service-task-list-cloud.service.spec.ts
Labels: PR: unreviewed

#8430 [ACA-4654] Sign in button isn't centred as expected
  lib/core/src/lib/login/components/login.component.scss
Labels: PR: partially-approved

#8427 HXOR-99 [ci:force] commits on adf is not working properly
  .github/workflows/pull-request.yml
Labels: PR: reviewed-approved
