Repository Alfresco/alfresco-ng2-components, pull requests merged in 2023-04, with the labels that each got.

#8425 [AAE-12318] Adjustments for HxP Attach-File widget
  lib/core/src/lib/form/components/widgets/core/form.model.ts
  lib/core/src/lib/form/components/widgets/core/upload-widget-content-link.model.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
Labels: PR: unreviewed

#8431 Remove the ability to run upstream from adf [do not merge]
  .github/workflows/cron-upstream.yml
  scripts/github/update/update-project.sh
Labels: do not merge 🙅🏻‍♂️, PR: unreviewed, PR: partially-approved

#8444 [ACS-4523] Add strings to translate
  lib/content-services/src/lib/i18n/en.json
Labels: PR: partially-approved

#8360 [AAE-12288] Enable Environment Id filtering support
  docs/process-services-cloud/components/edit-process-filter-cloud.component.md
  docs/process-services-cloud/components/edit-task-filter-cloud.component.md
  docs/process-services-cloud/services/apps-process-cloud.service.md
  lib/process-services-cloud/src/lib/app/mock/app-model.mock.ts
  lib/process-services-cloud/src/lib/app/models/application-instance.model.ts
  lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts
  lib/process-services-cloud/src/lib/common/index.ts
  lib/process-services-cloud/src/lib/common/interface/environment.interface.ts
  lib/process-services-cloud/src/lib/common/interface/index.ts
  lib/process-services-cloud/src/lib/common/interface/public-api.ts
  lib/process-services-cloud/src/lib/common/mock/environment.mock.ts
  lib/process-services-cloud/src/lib/common/public-api.ts
  lib/process-services-cloud/src/lib/models/filter-cloud-model.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
  lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
  lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-service-task-filter-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/mock/edit-task-filter-cloud.mock.ts
  lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
  lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-list/models/service-task-cloud.model.ts
  lib/process-services-cloud/src/public-api.ts
Labels: PR: partially-approved

#8447 [AAE-12288] Fix bc
  lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
Labels: PR: partially-approved

#8448 [AAE-13200] - Fix GH workflow e2e not affected when testing lib is modified
  .github/actions/e2e/action.yml
  .github/workflows/pull-request.yml
  scripts/github/affected-contains.sh
  scripts/github/e2e/e2e.sh
Labels: PR: partially-approved

#8450 [AAE-12782] Custom theme creation
  lib/core/custom-theme/material-theme.scss
  lib/core/custom-theme/theme/custom-background-color.scss
  lib/core/custom-theme/theme/custom-palette-creator.scss
  lib/core/custom-theme/theme/custom-text-color.scss
  lib/core/custom-theme/theme/custom-theme-palettes.scss
  lib/core/custom-theme/theme/theme-configuration.scss.tpl
  lib/core/custom-theme/theme/theme-data.scss
  lib/core/custom-theme/theme/typography.scss
  lib/core/custom-theme/variables/font-family.scss
  lib/core/ng-package.json
  stylelint-config.json
Labels: PR: unreviewed

#8461 Add connector regression app
  e2e/resources/activiti7/connector-regression.zip
Labels: PR: partially-approved

#8460 [AAE-13093] - Fix demoshell and storybook publishing not working
  .github/workflows/release.yml
Labels: PR: partially-approved

#8462 [AAE-13093] - Fix invalid node version for release workflow
  .github/workflows/release.yml
Labels: PR: partially-approved

#8463 [AAE-13093] - Fix yml file indentation, use npm cache
  .github/workflows/release.yml
Labels: PR: partially-approved

#8464 [AAE-13093] - Use node v16 for publish docker
  .github/workflows/release.yml
Labels: PR: partially-approved

#8428 [ACA-4676][ACA-4678] Added Non Responsive Preview Dialog to viewer component
  demo-shell/src/app.config.json
  demo-shell/src/app/components/files/files.component.html
  demo-shell/src/app/components/files/files.component.ts
  docs/core/components/viewer.component.md
  lib/core/src/lib/i18n/en.json
  lib/core/src/lib/viewer/components/download-prompt-dialog/download-prompt-dialog.component.html
  lib/core/src/lib/viewer/components/download-prompt-dialog/download-prompt-dialog.component.spec.ts
  lib/core/src/lib/viewer/components/download-prompt-dialog/download-prompt-dialog.component.ts
  lib/core/src/lib/viewer/components/viewer.component.spec.ts
  lib/core/src/lib/viewer/components/viewer.component.ts
  lib/core/src/lib/viewer/models/download-prompt.actions.ts
  lib/core/src/lib/viewer/public-api.ts
  lib/core/src/lib/viewer/viewer.module.ts
Labels: PR: unreviewed, A/N BDU

#8465 [AAE-13093] - Set node version of dockerfile to 16.20
  .github/workflows/release.yml
  Dockerfile
Labels: PR: partially-approved

#8452 [AAE-12782] Custom theme - add custom color for app-bar
  lib/core/custom-theme/theme/custom-background-color.scss
Labels: PR: unreviewed

#8419 Dispatch Event- Retry 3 times in case of failing
  .github/workflows/package_dispatch.yml
Labels: PR: partially-approved

#8466 AAE-13608 - Use the gh run id as image suffix
  scripts/next_version.sh
Labels: PR: unreviewed, PR: reviewed-approved

#8475 AAE-11622 - add release script
  release.sh
Labels: PR: reviewed-approved

#8474 [AAE-13141] fix: remove faulty interceptor with caused CORS issues
  lib/core/src/lib/core.module.ts
Labels: PR: partially-approved

#8482 [AAE-13775] Upstream Js API
  .github/workflows/upstream-js.yml
  scripts/github/update/latest-version-of.js
  scripts/github/update/useme-to-test-restokit.js
Labels: PR: unreviewed

#8484 [AAE-13775] Upstream js - fix issue
  .github/workflows/upstream-js.yml
  scripts/github/update/check-pr-already-exist.js
  scripts/github/update/latest-version-of.js
Labels: PR: unreviewed

#8486 GH Auto: Upstream dependencies JS-API:5.5.0-796
  package-lock.json
  package.json
Labels: PR: partially-approved

#8481 Generate docs
  docs/README.md
  docs/content-services/components/content-user-info.component.md
  docs/content-services/components/document-list.component.md
  docs/content-services/components/node-comments.component.md
  docs/content-services/components/search-chip-list.component.md
  docs/content-services/components/tags-creator.component.md
  docs/content-services/services/audit.service.md
  docs/content-services/services/category.service.md
  docs/content-services/services/tag.service.md
  docs/core/components/identity-user-info.component.md
  docs/core/components/viewer.component.md
  docs/core/services/notification.service.md
  docs/core/services/people-process.service.md
  docs/process-services-cloud/components/edit-process-filter-cloud.component.md
  docs/process-services-cloud/components/edit-task-filter-cloud.component.md
  docs/process-services-cloud/components/process-list-cloud.component.md
  docs/process-services-cloud/components/task-list-cloud.component.md
  docs/process-services-cloud/services/apps-process-cloud.service.md
  docs/process-services/components/process-user-info.component.md
  docs/process-services/components/task-comments.component.md
  lib/content-services/src/lib/audit/audit.service.ts
  lib/content-services/src/lib/content-user-info/content-user-info.component.ts
  lib/content-services/src/lib/search/components/search-chip-list/search-chip-list.component.ts
  lib/content-services/src/lib/tag/services/tag.service.ts
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
  lib/process-services/src/lib/process-user-info/process-user-info.component.ts
  lib/process-services/src/lib/task-comments/task-comments.component.ts
  tools/doc/package-lock.json
Labels: PR: partially-approved

#8483 [ACA-4589] Remove requirement for update permission on node to open manage versions dialog
  lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.spec.ts
  lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.ts
Labels: PR: partially-approved

#8490 LOC-411 - PRODDEL-6965 - Updated UI files in 16 languages for ADF 6.0…
  demo-shell/resources/i18n/ar.json
  demo-shell/resources/i18n/cs.json
  demo-shell/resources/i18n/da.json
  demo-shell/resources/i18n/de.json
  demo-shell/resources/i18n/es.json
  demo-shell/resources/i18n/fi.json
  demo-shell/resources/i18n/fr.json
  demo-shell/resources/i18n/it.json
  demo-shell/resources/i18n/ja.json
  demo-shell/resources/i18n/nb.json
  demo-shell/resources/i18n/nl.json
  demo-shell/resources/i18n/pl.json
  demo-shell/resources/i18n/pt-BR.json
  demo-shell/resources/i18n/ru.json
  demo-shell/resources/i18n/sv.json
  demo-shell/resources/i18n/zh-CN.json
  lib/content-services/src/lib/i18n/ar.json
  lib/content-services/src/lib/i18n/cs.json
  lib/content-services/src/lib/i18n/da.json
  lib/content-services/src/lib/i18n/de.json
  lib/content-services/src/lib/i18n/es.json
  lib/content-services/src/lib/i18n/fi.json
  lib/content-services/src/lib/i18n/fr.json
  lib/content-services/src/lib/i18n/it.json
  lib/content-services/src/lib/i18n/ja.json
  lib/content-services/src/lib/i18n/nb.json
  lib/content-services/src/lib/i18n/nl.json
  lib/content-services/src/lib/i18n/pl.json
  lib/content-services/src/lib/i18n/pt-BR.json
  lib/content-services/src/lib/i18n/ru.json
  lib/content-services/src/lib/i18n/sv.json
  lib/content-services/src/lib/i18n/zh-CN.json
  lib/core/src/lib/i18n/ar.json
  lib/core/src/lib/i18n/cs.json
  lib/core/src/lib/i18n/da.json
  lib/core/src/lib/i18n/de.json
  lib/core/src/lib/i18n/es.json
  lib/core/src/lib/i18n/fi.json
  lib/core/src/lib/i18n/fr.json
  lib/core/src/lib/i18n/it.json
  lib/core/src/lib/i18n/ja.json
  lib/core/src/lib/i18n/nb.json
  lib/core/src/lib/i18n/nl.json
  lib/core/src/lib/i18n/pl.json
  lib/core/src/lib/i18n/pt-BR.json
  lib/core/src/lib/i18n/ru.json
  lib/core/src/lib/i18n/sv.json
  lib/core/src/lib/i18n/zh-CN.json
  lib/process-services-cloud/src/lib/i18n/es.json
  lib/process-services-cloud/src/lib/i18n/ja.json
  lib/process-services-cloud/src/lib/i18n/zh-CN.json
  lib/process-services/src/lib/i18n/ja.json
  lib/process-services/src/lib/i18n/zh-CN.json
Labels: PR: partially-approved

#8492 fix tag
  scripts/github/update/latest-version-of.js
Labels: PR: unreviewed

#8495 Release 6.0.0-A.4
  demo-shell/package.json
  docs/license-info/README.md
  docs/license-info/license-info-6.0.0-A.4.md
  docs/release-notes/README.md
  docs/release-notes/RelNote-6.0.0-A.4.md
  docs/vulnerability/README.md
  docs/vulnerability/audit-info-6.0.0-A.4.md
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
  scripts/release.sh
Labels: PR: partially-approved

#8496 AAE-13893 - add condition for master release
  .github/workflows/release.yml
Labels: PR: partially-approved

#8453 [ACS-5021] Fixed displaying label above existing tags list
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.html
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts
Labels: next version ➡️, PR: partially-approved, A/N BDU

#8467 [ACA-4677] Added download functionality on DownloadPromptDialog
  docs/core/components/viewer.component.md
  lib/content-services/src/lib/viewer/components/alfresco-viewer.component.html
  lib/content-services/src/lib/viewer/components/alfresco-viewer.component.spec.ts
  lib/content-services/src/lib/viewer/components/alfresco-viewer.component.ts
  lib/core/src/lib/viewer/components/viewer.component.spec.ts
  lib/core/src/lib/viewer/components/viewer.component.ts
Labels: PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved, A/N BDU

#8493 GH Auto: Upstream dependencies JS-API:5.6.0-809
  package-lock.json
  package.json
Labels: PR: partially-approved

#8470 [ACS-4788] Add support for the Categories facet
  docs/content-services/services/category.service.md
  lib/content-services/src/lib/category/services/category.service.spec.ts
  lib/content-services/src/lib/category/services/category.service.ts
  lib/content-services/src/lib/search/services/search-facet-filters.service.spec.ts
  lib/content-services/src/lib/search/services/search-facet-filters.service.ts
Labels: PR: partially-approved, A/N BDU

#8497 [AAE-13884] Remove duplicated test C315169
  e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
Labels: PR: partially-approved

#8494 [ACS-4662] Allow to see category children after search
  lib/content-services/src/lib/category/mock/category-mock.service.ts
  lib/content-services/src/lib/category/services/category-tree-datasource.service.spec.ts
  lib/content-services/src/lib/category/services/category-tree-datasource.service.ts
Labels: PR: partially-approved, A/N BDU

#8505 [ACS-4523] Fix translation and label
  lib/content-services/src/lib/category/categories-management/categories-management.component.html
  lib/content-services/src/lib/category/categories-management/categories-management.component.ts
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.html
Labels: PR: partially-approved

#8500 GH Auto: Upstream dependencies JS-API:5.6.0-847
  package-lock.json
  package.json
Labels: PR: partially-approved

#8508 Stop PR in case of forbidden label
  .github/workflows/pull-request.yml
  scripts/github/update/check-issue-has-label.js
Labels: PR: unreviewed

#8507 [AAE-13433] Update app for BE UAT and move processes from simpleapp to be uat default one
  e2e/resources/activiti7/uat-be-default-app.zip
Labels: PR: unreviewed

#8510 LOC-436 - Additional UI strings to be updated after last committ. Als…
  demo-shell/resources/i18n/ru.json
  demo-shell/resources/i18n/zh-CN.json
  lib/content-services/src/lib/i18n/ar.json
  lib/content-services/src/lib/i18n/cs.json
  lib/content-services/src/lib/i18n/da.json
  lib/content-services/src/lib/i18n/de.json
  lib/content-services/src/lib/i18n/es.json
  lib/content-services/src/lib/i18n/fi.json
  lib/content-services/src/lib/i18n/fr.json
  lib/content-services/src/lib/i18n/it.json
  lib/content-services/src/lib/i18n/ja.json
  lib/content-services/src/lib/i18n/nb.json
  lib/content-services/src/lib/i18n/nl.json
  lib/content-services/src/lib/i18n/pl.json
  lib/content-services/src/lib/i18n/pt-BR.json
  lib/content-services/src/lib/i18n/ru.json
  lib/content-services/src/lib/i18n/sv.json
  lib/content-services/src/lib/i18n/zh-CN.json
  lib/process-services-cloud/src/lib/i18n/es.json
  lib/process-services-cloud/src/lib/i18n/pl.json
  lib/process-services/src/lib/i18n/es.json
  lib/process-services/src/lib/i18n/zh-CN.json
Labels: PR: partially-approved

#8509 GH Auto: Upstream dependencies JS-API:5.6.0-870
  package-lock.json
  package.json
Labels: PR: partially-approved

#8511 GH Auto: Upstream dependencies JS-API:5.6.0-875
  package-lock.json
  package.json
Labels: PR: unreviewed

#8514 refine upgrade to 6.0.0 guide
  docs/upgrade-guide/upgrade50-60.md
Labels: PR: unreviewed

#8520 [ACS-5065] Release 6.0.0
  demo-shell/package.json
  docs/license-info/README.md
  docs/license-info/license-info-6.0.0.md
  docs/release-notes/README.md
  docs/release-notes/RelNote-6.0.0.md
  docs/vulnerability/README.md
  docs/vulnerability/audit-info-6.0.0.md
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/ng-package.json
  lib/core/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/process-services-cloud/ng-package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  lib/testing/package.json
  package-lock.json
  package.json
Labels: PR: partially-approved

#8519 [ACS-5135] Tree component emit pagination only when top-level entries…
  lib/content-services/src/lib/tree/components/tree.component.spec.ts
  lib/content-services/src/lib/tree/components/tree.component.ts
Labels: PR: partially-approved
