Repository Alfresco/alfresco-ng2-components, pull requests merged in 2024-05, with the labels that each got.

#9658 AAE-21937 Fix context menu list component
  lib/core/src/lib/context-menu/context-menu-list.component.html
Labels: angular

#9676 AAE-22037 Set static value for form variables in start event form
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
Labels: bug

#9687 [ACS-7768] unify inputs and selects across the app
  lib/content-services/src/lib/category/categories-management/categories-management.component.html
  lib/content-services/src/lib/category/categories-management/categories-management.component.scss
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.scss
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
  lib/content-services/src/lib/content-node-share/content-node-share.dialog.scss
  lib/content-services/src/lib/dialogs/folder.dialog.html
  lib/content-services/src/lib/dialogs/library/library.dialog.html
  lib/content-services/src/lib/i18n/en.json
  lib/content-services/src/lib/material.module.ts
  lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
  lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.scss
  lib/content-services/src/lib/permission-manager/components/user-role-column/user-role-column.component.ts
  lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.html
  lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.scss
  lib/content-services/src/lib/search/components/search-date-range-tabbed/search-date-range/search-date-range.component.html
  lib/content-services/src/lib/search/components/search-date-range-tabbed/search-date-range/search-date-range.component.scss
  lib/content-services/src/lib/search/components/search-filter-chips/search-widget-chip/search-widget-chip.component.ts
  lib/content-services/src/lib/search/components/search-input/search-input.component.html
  lib/content-services/src/lib/search/components/search-logical-filter/search-logical-filter.component.html
  lib/content-services/src/lib/search/components/search-logical-filter/search-logical-filter.component.scss
  lib/content-services/src/lib/search/components/search-properties/search-properties.component.html
  lib/content-services/src/lib/search/components/search-properties/search-properties.component.scss
  lib/content-services/src/lib/search/components/search-text/search-text.component.html
  lib/content-services/src/lib/search/components/search-text/search-text.component.scss
  lib/content-services/src/lib/site-dropdown/sites-dropdown.component.html
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.html
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.scss
  lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.html
  lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.scss
  lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.html
  lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.scss
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
  lib/core/src/lib/card-view/components/card-view/card-view.component.scss
  lib/core/src/lib/comments/comments.component.scss
  lib/core/src/lib/login/components/login/login.component.scss
  lib/core/src/lib/styles/_components-variables.scss
  lib/core/src/lib/styles/_mat-selectors.scss
  lib/core/src/lib/styles/_reference-variables.scss
  lib/core/src/lib/styles/_typography.scss
  lib/core/src/lib/styles/material.theme.scss
Labels: A/N BDU, angular

#9689 AAE-22635 Auto upstream for hxp
  .github/workflows/release.yml
Labels: hxp-upstream

#9706 AAE-21952 Fix Radio buttons widget not displayed properly when labels…
  lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.scss
Labels: hxp-upstream

#9713 [ACS-7999] Fix inputs for edit and create folder
  lib/content-services/src/lib/dialogs/folder.dialog.html
  lib/content-services/src/lib/dialogs/folder.dialog.scss
  lib/core/src/lib/styles/_mat-selectors.scss
Labels: A/N BDU, angular

#9719 AAE-22612 Update process services cloud package json
  lib/process-services-cloud/package-lock.json
  lib/process-services-cloud/package.json
Labels: hxp-upstream

#9722 [ACS-8021] Inputs for comments
  lib/core/src/lib/comments/comments.component.html
  lib/core/src/lib/comments/comments.component.scss
Labels: angular
