Repository Alfresco/alfresco-ng2-components, pull requests merged in 2024-06, with the labels that each got.

#9772 [ACS-8104] Fix buttons alignment
  lib/core/src/lib/dialogs/dialog/dialog.component.html
Labels: A/N BDU

#9783 [ACS-8066] fix unit tests
  lib/content-services/src/lib/site-dropdown/sites-dropdown.component.spec.ts
Labels: A/N BDU, angular

#9803 [ACS-8157] Used mat chip set instead of mat chip listbox for dynamic ch…
  lib/core/src/lib/dynamic-chip-list/dynamic-chip-list.component.html
Labels: A/N BDU, angular

#9798 [ACS-7980][ACC] - Delete tag
  lib/core/src/lib/dialogs/confirm-dialog/confirm.dialog.html
  lib/core/src/lib/dialogs/confirm-dialog/confirm.dialog.scss
  lib/core/src/lib/dialogs/confirm-dialog/confirm.dialog.ts
Labels: angular

#9793 [ACS-7979] Fixed UI for create tags dialog
  lib/content-services/src/lib/category/categories-management/categories-management.component.html
  lib/content-services/src/lib/category/categories-management/categories-management.component.scss
  lib/content-services/src/lib/category/categories-management/categories-management.component.ts
  lib/content-services/src/lib/tag/tag.module.ts
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.html
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.scss
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts
Labels: angular

#9808 [ACS-8158] Fixed spacing of tags in ACA
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.scss
  lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
  lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
Labels: angular

#9809 [ACS-8191] Added missing mat selectors for ACA. Updated mat selector name
  lib/content-services/src/lib/search/components/search-properties/search-properties.component.scss
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
  lib/core/src/lib/form/components/inplace-form-input/inplace-form-input.component.scss
  lib/core/src/lib/form/components/widgets/form.theme.scss
  lib/core/src/lib/search-text/search-text-input.component.scss
  lib/core/src/lib/styles/_mat-selectors.scss
Labels: angular

#9810 [ACS-8196][ACC] pagination icon misplaced
  lib/core/src/lib/pagination/pagination.component.scss
Labels: angular

#9830 [ACS-8230] Fixed UI for snackbars with long text content and action buttons
  lib/core/src/lib/snackbar-content/snackbar-content.component.scss
Labels: angular

#9804 AAE-23134 Fix overlapping external property widgets when key is too long
  lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.scss
Labels: hxp-upstream

#9835 AAE-23115 Display key of the user attribute in external property preview
  lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.spec.ts
Labels: hxp-upstream

#9816 [MNT-24351] Add missing array validation to card-view
  lib/core/src/lib/card-view/validators/card-view-item-length.valiator.ts
  lib/core/src/lib/card-view/validators/card-view-item-length.validator.spec.ts
  lib/core/src/lib/card-view/validators/card-view-item-match.valiator.ts
  lib/core/src/lib/card-view/validators/card-view-item-match.validator.spec.ts
  lib/core/src/lib/card-view/validators/card-view-item-minmax.valiator.ts
  lib/core/src/lib/card-view/validators/card-view-item-minmax.validator.spec.ts
  lib/core/src/lib/card-view/validators/card-view-item-only-positive-int.validator.spec.ts
Labels: A/N BDU

#9850 Updated update-to-newest-webdriver.sh to be compatible with linux
  scripts/webdriver-update-newest/update-to-newest-webdriver.sh
Labels: possible breaking change

#9845 ACS-8254 [ADF] Add functionality to pass data on confirmation in DialogComponent
  docs/core/dialogs/dialog.md
  docs/core/interfaces/dialog.interface.md
  docs/core/models/dialog.model.md
  lib/core/src/lib/dialogs/dialog/dialog-data.interface.ts
  lib/core/src/lib/dialogs/dialog/dialog.component.spec.ts
  lib/core/src/lib/dialogs/dialog/dialog.component.ts
Labels: A/N BDU

#9865 AAE-23379 Fix - Required empty attach file field allows user to submi…
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-form/mocks/task-form-cloud.mock.ts
Labels: hxp-upstream

#9874 AAE-23379 Fix - required attach file allows to start process
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
Labels: hxp-upstream

#9876 AAE-23494 Fix - Required Date field still allows user to submit form
  lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
  lib/core/src/lib/form/components/widgets/core/form-field.model.ts
Labels: hxp-upstream
