Repository Alfresco/alfresco-ng2-components, pull requests merged in 2024-04, with the labels that each got.

#9518 [ACS-6644] review search documentation and examples for adf
  docs/content-services/components/search-check-list.component.md
  docs/content-services/components/search-datetime-range.component.md
  docs/content-services/components/search-logical-filter.component.md
  docs/content-services/components/search-number-range.component.md
  docs/content-services/components/search-radio.component.md
  docs/content-services/components/search-slider.component.md
  docs/content-services/components/search-text.component.md
  docs/content-services/interfaces/search-widget.interface.md
  docs/content-services/services/search-query-builder.service.md
  docs/user-guide/search-configuration-guide.md
Labels: documentation 📄, A/N BDU

#9530 [ACS-6721] [ACA] Aspects dialog does not display butons on smaller screens
  lib/content-services/src/lib/aspect-list/aspect-list.component.scss
Labels: A/N BDU

#9539 [MNT-24028] edit aspects dialog counter bug
  docs/content-services/components/aspect-list-dialog.component.md
  docs/content-services/components/aspect-list.component.md
  lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.html
  lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.ts
  lib/content-services/src/lib/aspect-list/aspect-list.component.spec.ts
  lib/content-services/src/lib/aspect-list/aspect-list.component.ts
Labels: A/N BDU

#8758 [ACS-5572] Remove unused Social components
  docs/README.md
  docs/content-services/components/like.component.md
  docs/content-services/components/rating.component.md
  docs/content-services/services/rating.service.md
  lib/content-services/src/lib/content.module.ts
  lib/content-services/src/lib/social/index.ts
  lib/content-services/src/lib/social/like.component.html
  lib/content-services/src/lib/social/like.component.scss
  lib/content-services/src/lib/social/like.component.spec.ts
  lib/content-services/src/lib/social/like.component.stories.ts
  lib/content-services/src/lib/social/like.component.ts
  lib/content-services/src/lib/social/mock/rating-response.mock.ts
  lib/content-services/src/lib/social/mock/rating.service.mock.ts
  lib/content-services/src/lib/social/public-api.ts
  lib/content-services/src/lib/social/rating.component.html
  lib/content-services/src/lib/social/rating.component.scss
  lib/content-services/src/lib/social/rating.component.spec.ts
  lib/content-services/src/lib/social/rating.component.ts
  lib/content-services/src/lib/social/services/rating.service.interface.ts
  lib/content-services/src/lib/social/services/rating.service.spec.ts
  lib/content-services/src/lib/social/services/rating.service.ts
  lib/content-services/src/lib/social/social.module.ts
  lib/content-services/src/public-api.ts
Labels: A/N BDU

#9574 [ACS-7575] Create library dialog fixes
  lib/content-services/src/lib/dialogs/library/library.dialog.html
  lib/content-services/src/lib/dialogs/library/library.dialog.scss
Labels: angular

#9575 [ACS-7534] Create/edit folder dialog fixes
  lib/content-services/src/lib/dialogs/folder.dialog.html
  lib/content-services/src/lib/dialogs/folder.dialog.scss
  lib/content-services/src/lib/dialogs/folder.dialog.ts
Labels: angular

#9576 [ACS-7555] column filters
  lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.scss
  lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.scss
  lib/content-services/src/lib/search/components/search-text/search-text.component.html
  lib/content-services/src/lib/search/components/search-text/search-text.component.scss
  lib/core/src/lib/styles/_mat-selectors.scss
Labels: A/N BDU, angular

#9582 [ACS-7577] [ADF] Remove Folder Directives from Content Services lib
  demo-shell/src/app/app.module.ts
  demo-shell/src/app/components/files/files.component.html
  demo-shell/src/app/components/files/files.component.ts
  demo-shell/src/app/folder-directive/folder-create.directive.md
  demo-shell/src/app/folder-directive/folder-create.directive.spec.ts
  demo-shell/src/app/folder-directive/folder-create.directive.ts
  demo-shell/src/app/folder-directive/folder-directive.module.ts
  demo-shell/src/app/folder-directive/index.ts
  docs/README.md
  docs/content-services/directives/folder-edit.directive.md
  e2e/content-services/document-list/document-list-pagination.e2e.ts
  lib/content-services/src/lib/content.module.ts
  lib/content-services/src/lib/folder-directive/folder-edit.directive.spec.ts
  lib/content-services/src/lib/folder-directive/folder-edit.directive.ts
  lib/content-services/src/lib/folder-directive/public-api.ts
  lib/content-services/src/public-api.ts
Labels: A/N BDU

#9607 [ACS-7572] link rules dialog fixes
  lib/content-services/src/lib/breadcrumb/dropdown-breadcrumb.component.html
  lib/content-services/src/lib/breadcrumb/dropdown-breadcrumb.component.scss
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
  lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
  lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
  lib/content-services/src/lib/site-dropdown/sites-dropdown.component.html
  lib/core/src/lib/styles/_mat-selectors.scss
Labels: angular

#9608 Bump formidable and superagent in js-api and adf-cli
  lib/cli/package-lock.json
  lib/core/package.json
  lib/js-api/package.json
Labels: dependencies

#9632 [ACS-7560] undo deletion notification
  lib/core/src/lib/snackbar-content/snackbar-content.component.scss
  lib/core/src/lib/styles/_mat-selectors.scss
  lib/core/src/lib/styles/material.theme.scss
Labels: A/N BDU, angular
