Repository Alfresco/alfresco-ng2-components, pull requests merged in 2024-08, with the labels that each got.

#10017 [ACS-8452] Fixed UI for folder select input fields in create/edit rules
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
  lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
Labels: angular

#9999 [ACS-8247] Fixed empty context menu for DataTable row
  lib/core/src/lib/datatable/components/datatable/datatable.component.html
  lib/core/src/lib/datatable/components/datatable/datatable.component.scss
  lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
  lib/core/src/lib/datatable/components/datatable/datatable.component.ts
Labels: A/N BDU

#10014 [ACS-8447] Align pagination buttons
  lib/core/src/lib/pagination/pagination.component.scss
Labels: angular

#10063 [ACS-8371] Fix viewer toolbar page selector
  lib/core/src/lib/viewer/components/pdf-viewer/pdf-viewer.component.scss
Labels: angular

#10054 [ACS-8555] Name filter clear icon now no longer gets cut off
  lib/content-services/src/lib/search/components/search-text/search-text.component.html
  lib/content-services/src/lib/search/components/search-text/search-text.component.scss
Labels: angular

#10090 Core Pipes backwards compatibility
  lib/core/src/lib/pipes/pipe.module.ts
Labels: hxp-upstream

#10109 Core pipes backward compatibility v2
  lib/core/src/lib/core.module.ts
  lib/core/src/lib/pipes/pipe.module.ts
Labels: hxp-upstream
