Repository Alfresco/alfresco-ng2-components, pull requests merged in 2024-09, with the labels that each got.

#10110 AAE-25268 Added output for updated filter
  lib/process-services-cloud/src/lib/task/task-filters/components/base-task-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
  lib/process-services-cloud/src/lib/task/task-filters/mock/task-filters-cloud.mock.ts
Labels: do not merge 🙅🏻‍♂️

#10133 AAE-25190 Retrieve start process cloud customisation
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
  lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
Labels: New Feature

#10196 [ACS-8745] handle row selection in process list
  docs/process-services/components/process-list.component.md
  lib/process-services/src/lib/process-list/components/process-list/process-list.component.html
  lib/process-services/src/lib/process-list/components/process-list/process-list.component.spec.ts
  lib/process-services/src/lib/process-list/components/process-list/process-list.component.ts
Labels: A/N BDU

#10112 [ACS-8602] [Legal Hold] The tabs names in "Manage Legal Holds" window are not matching the design
  lib/core/src/lib/dialogs/dialog/dialog.component.html
  lib/core/src/lib/dialogs/dialog/dialog.component.scss
Labels: Legal Holds

#10228 AAE-26043 Use text alignment set in rich text editor
  lib/process-services-cloud/src/lib/form/components/widgets/display-rich-text/display-rich-text.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/display-rich-text/display-rich-text.widget.ts
Labels: bug

#10230 [ACS-8806] refactor process comments
  docs/process-services/components/process-comments.component.md
  lib/process-services/src/lib/process-comments/process-comments.component.html
  lib/process-services/src/lib/process-comments/process-comments.component.scss
  lib/process-services/src/lib/process-comments/process-comments.component.spec.ts
  lib/process-services/src/lib/process-comments/process-comments.component.ts
Labels: A/N BDU

#10247 [ACS-8823] Viewer - do not show non responsive dialog if blobFile was provided
  lib/core/src/lib/viewer/components/viewer.component.spec.ts
  lib/core/src/lib/viewer/components/viewer.component.ts
Labels: A/N BDU
