Repository Alfresco/alfresco-ng2-components, pull requests merged in 2025-03, with the labels that each got.

#10687 [ACS-9225] serious a11y testing side bar elements must meet minimum color contrast ratio thresholds
  lib/core/src/lib/styles/_components-variables.scss
  lib/core/src/lib/styles/_reference-variables.scss
  lib/process-services/src/lib/process-list/components/process-filters/process-filters.component.scss
  lib/process-services/src/lib/task-list/components/task-filters/task-filters.component.scss
Labels: A/N BDU

#10690 Move @storybook under dev-dependencies
  package-lock.json
  package.json
Labels: dependencies, A/N BDU

#10696 [MNT-24909] Check if property constraint is handled by validators available in ADF
  lib/core/src/lib/card-view/models/card-view-baseitem.model.spec.ts
  lib/core/src/lib/card-view/models/card-view-baseitem.model.ts
Labels: A/N BDU

#10708 [ACS-9371] Migrate docs from docs.alfresco to support.hyland
  ALFRESCOCORS.md
  docs/content-services/components/alfresco-viewer.component.md
  docs/content-services/components/search-number-range.component.md
  docs/content-services/dialogs/library.dialog.md
  docs/content-services/services/tag.service.md
  docs/core/components/start-form.component.md
  docs/core/services/renditions.service.md
  docs/release-notes/RelNote161.md
  docs/release-notes/RelNote170.md
  docs/release-notes/RelNote180.md
  docs/release-notes/RelNote190.md
  docs/release-notes/RelNote200.md
  docs/release-notes/RelNote210.md
  docs/release-notes/RelNote220.md
  docs/release-notes/RelNote230.md
  docs/release-notes/RelNote240.md
  docs/release-notes/RelNote250.md
  docs/release-notes/RelNote260.md
  docs/release-notes/RelNote300.md
  docs/release-notes/RelNote310.md
  docs/release-notes/RelNote320.md
  docs/release-notes/RelNote321.md
  docs/release-notes/RelNote330.md
  docs/release-notes/RelNote340.md
  docs/release-notes/RelNote350.md
  docs/release-notes/RelNote360.md
  docs/release-notes/RelNote370.md
  docs/release-notes/RelNote380.md
  docs/release-notes/RelNote390.md
  docs/release-notes/RelNote400.md
  docs/release-notes/RelNote410.md
  docs/release-notes/RelNote420.md
  docs/release-notes/RelNote430.md
  docs/release-notes/RelNote440.md
  docs/release-notes/RelNote450.md
  docs/user-guide/search-configuration-guide.md
  lib/js-api/src/api/search-rest-api/docs/SearchApi.md
Labels: A/N BDU

#10725 Release 7.0.0
  docs/license-info/README.md
  docs/license-info/license-info-7.0.0.md
  docs/release-notes/README.md
  docs/release-notes/RelNote-7.0.0.md
  docs/vulnerability/README.md
  docs/vulnerability/audit-info-7.0.0.md
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/eslint-angular/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/js-api/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  package-lock.json
  package.json
Labels: A/N BDU

#10726 Post-release version bump
  lib/cli/package-lock.json
  lib/cli/package.json
  lib/content-services/package.json
  lib/core/package.json
  lib/eslint-angular/package.json
  lib/extensions/package.json
  lib/insights/package.json
  lib/js-api/package.json
  lib/process-services-cloud/package.json
  lib/process-services/package.json
  package-lock.json
  package.json
Labels: A/N BDU

#10714 [ACS-9398] Add snackbar notifications for favorite node directive
  lib/content-services/src/lib/directives/library-favorite.directive.spec.ts
  lib/content-services/src/lib/directives/library-favorite.directive.ts
  lib/content-services/src/lib/directives/node-favorite.directive.spec.ts
  lib/content-services/src/lib/directives/node-favorite.directive.ts
  lib/content-services/src/lib/i18n/en.json
Labels: A/N BDU

#10691 [ACS-9375] Transparent background for hovered spinner
  lib/core/src/lib/datatable/components/datatable/datatable.component.html
  lib/core/src/lib/datatable/components/datatable/datatable.component.scss
Labels: A/N BDU

#10715 [ACS-5190] document name text alignement and long name trim issue
  lib/core/src/lib/viewer/components/viewer.component.html
  lib/core/src/lib/viewer/components/viewer.component.scss
  lib/core/src/lib/viewer/components/viewer.component.spec.ts
  lib/core/src/lib/viewer/components/viewer.component.ts
Labels: A/N BDU

#10744 AAE-33007 Display empty data table without error
  lib/core/src/lib/i18n/en.json
  lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table-adapter.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table-adapter.widget.ts
  lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.html
  lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.ts
  lib/process-services-cloud/src/lib/form/components/widgets/data-table/helpers/data-table-path-parser.helper.spec.ts
  lib/process-services-cloud/src/lib/form/components/widgets/data-table/helpers/data-table-path-parser.helper.ts
  lib/process-services-cloud/src/lib/form/components/widgets/data-table/mocks/data-table-widget.mock.ts
Labels: hxp-upstream
